### ISSUE TITLE
행정구역에 관한 문의 드립니다.

### ISSUE THREAD

**Issue by aaronbyun** [navermaps/maps.js#1]
https://navermaps.github.io/maps.js/docs/data/region09.json

이렇게 서울시 전체에 관한 geojson 데이터는 제공하는 것으로 보이는데, 
각 구(강남구, 서초구 등등)에 관해서도 제공하는지 문의드립니다.

감사합니다.

**Comment by boxersb** [comment]
@aaronbyun 안녕하세요?

예제에서 활용한 행정구역 geojson 데이터는 데이터 스냅샷이라 정식 서비스 용도는 아닙니다.
현재는 각 행정구역별 데이터를 서비스할 수 있는 API가 없는데요..
앞으로 공개할 수 있도록 노력하겠습니다~

해당 데이터는 국가공간정보 통합 포털( http://openapi.nsdi.go.kr/nsdi/eios/OpenapiList.do?gubun=S ) 에서 사용할 수 있는 api 또는 파일 데이터가 있는지 검토해보시고, 지도 API와 매시업해서 사용하셔도 될것 같습니다..

감사합니다~

**Comment by boxersb** [comment]
이슈 close 하겠습니다..
