### ISSUE TITLE
How to set view port on naver map

### ISSUE THREAD

**Issue by dkchittimilla** [navermaps/maps.js#10]
Hi,

In my code I have naver map and dynamically based on a search condition we are adding the map points. Now I want to zoom and show the map only where the points were added. Currently user need to zoom out the map to find out the map points.

In my code firstly I am creating a map with below code

mapObj = new naver.maps.Map('navermap', {
                        center: new naver.maps.LatLng(37.3595704, 127.105399),
                        zoom: 5
                    });

I want to change the center based on my map points which will be generated dynamically based on search.

Thanks in advance.

**Comment by junthus** [comment]
Hi @dkchittimilla


To simply place a new point at the center of the map , you can use the `setCenter` and `setZoom`
```js
// get coordinates by the search first,

var pointToAdd = new naver.maps.LatLng(/*y, x*/);

mapObj.setCenter(pointToAdd);
mapObj.setZoom(/*desired zoom level(-1~14 when default map)*/); // if you need to change zoom level
```

You can also do this if you need animations. (instead of above)
```js
mapObj.morph(pointToAdd, desired_zoom_level); //setCenter + setZoom
//or
mapObj.panTo(pointToAdd) //setCenter
```

Or... 
To show several or all of the results on one screen at once, use the `naver.map.LatLngBounds.bounds` and `fitBounds`. `naver.map.LatLngBounds.bounds` returns the boundary that contains all of the coordinates .
```js
// get coordinates by the search first,

var pointToAdd1 = new naver.maps.LatLng(/*y, x*/),
    pointToAdd2 = new naver.maps.LatLng(/*y, x*/),
    ...
    pointToAddN = new naver.maps.LatLng(/*y, x*/);

var bounds = naver.map.LatLngBounds.bounds(pointToAdd1, pointToAdd2 /*, ... */, pointToAddN);

mapObj.fitBounds(bounds);
```

Of course, this also can be animated.  (instead of `fitBounds`)
```js
mapObj.panToBounds(pointsBounds);
```

I hope this helps.

**Comment by dkchittimilla** [comment]
Hi Junthus,

I tried below code

 var bounds = naver.maps.Map.LatLngBounds.bounds(navermarkers[0]);
                    mapObj.fitBounds(bounds);

**navermarkers** is my array which contains some set of markers. When I try to execute this code, it is throwing below error.
 
**Uncaught TypeError: Cannot read property 'bounds' of undefined**

Please suggest.

**Comment by junthus** [comment]
Hi Hi @dkchittimilla again

Our namespace is `naver.maps`, All classes are here. So `naver.maps.LatLngBounds.bounds` is the right path. And `bounds` function needs to 2 arguments at least which are `Coords`, not marker instance.

try this. 
```js
var bounds = naver.maps.LatLngBounds.bounds(navermarkers[0].getPosition(), navermarkers[1].getPosition()/*, more positions are available */);

mapObj.fitBounds(bounds);
```

If it intended using a single coordinate,`naver.maps.LatLngBounds.bounds` will be wrong. Use `mapObj.setCenter(navermarker[0].getPosition())` instead.
