### ISSUE TITLE
IE5 환경에서는 fromLatLngToTM128를 사용할 수 없나요?

### ISSUE THREAD

**Issue by yoonheeoh** [navermaps/maps.js#100]
정의되지 않음 또는 null 참조인 ‘fromLatLngToTM128’ 속성을 가져올 수 없습니다
라는 에러가 발생합니다..

**Comment by boxersb** [comment]
@yoonheeoh 지도 API v3는 IE8 이상을 지원합니다. IE5는 지원 대상이 아닙니다.
