### ISSUE TITLE
줌인/줌아웃 문제

### ISSUE THREAD

**Issue by davidshimjs** [navermaps/maps.js#101]
줌이 안된다는 CS가 많아서 확인 중인데, Mobile Safari로 네이버 지도 사이트를 열어서 수평 각도로 pinch to zoom out/in을 해보면 80% 정도의 확률로 동작하지 않습니다. (이를테면 양쪽 끝에서 화면 중앙으로 수평하게 touchmove를 수행하는 경우)

아무래도 각도 계산에 오류가 있는 것 같습니다.

**Comment by davidshimjs** [comment]
Android도 동일하게 발생합니다. 꽤 심각합니다 ㅠㅠ

**Comment by junthus** [comment]
@davidshimjs님 안녕하세요. 
해당 내용 패치하여 26일 배포될 예정입니다. 배포가 연기되는 바람에 알려드리는게 늦었네요 ㅜㅜ
언제나 이슈 제보 감사드립니다. 즐거운 주말 보내세요 ^^

**Comment by davidshimjs** [comment]
@junthus 이미 배포 예정에 있었군요~! 다행입니다 👍 즐거운 하루 되세요~!

**Comment by junthus** [comment]
@davidshimjs 배포가 또 변경되었네요 ;; 25일 (수) 배포 예정입니다.

**Comment by davidshimjs** [comment]
@junthus 더 빨라졌네요!! 👍 👍 👍

**Comment by junthus** [comment]
@davidshimjs 님 ~
해당 패치 반영되었습니다. 테스트 해 보시고 이슈 클로징 부탁드려요 ~~

**Comment by davidshimjs** [comment]
@junthus 확인해봤는데 정상적으로 작동합니다. 감사합니다~!
