### ISSUE TITLE
phonegap에서 네이버지도를 넣고 싶은데 가능할까요?

### ISSUE THREAD

**Issue by kimsungtaek1** [navermaps/maps.js#102]
네이버 지도 open api 인증이 실패하였습니다.
clientId와 웹 서비스 url을 확인해주시기 바랍니다.

라고 뜨네요.. clientId는 제대로 기입했거든요.

**Comment by junthus** [comment]
@kimsungtaek1 
안녕하세요 ~
API 호출 시 페이지의 location.href 값과 등록한 서비스 url이 동일한지 확인해보셔야 할 듯 합니다.

**Comment by thetaiz** [comment]
이슈를 닫습니다.
