### ISSUE TITLE
지도검색후 상세보기 code값 가져오는 방법이 있는지요.

### ISSUE THREAD

**Issue by jklsj1252** [navermaps/maps.js#103]
예를 들어서 네이버지도에 "의림지" 검색을 하면  [충청북도 제천시 모산동 241] 소재의 의림지가 A라는 항목으로 검색이되고 지도에도 A마크가 찍히는데 

해당 마크를 눌렀을때 "상세보기" 버튼이 있습니다. 버튼의 링크는
http://map.naver.com/local/siteview.nhn?code=13400760

이렇게 걸려있고요. 이 링크를 활용하고 싶어서 그러는데 위 링크의 code값을 지도api로 받아올 수 있는
방법이 있을까요?

**Comment by junthus** [comment]
@jklsj1252 
안녕하세요. 해당 코드나 상세보기의 내용은 현재 API로 제공되지 않습니다. 양해 부탁드립니다.

**Comment by jklsj1252** [comment]
@junthus  
네. 답변감사합니다^^
