### ISSUE TITLE
크롬에서 파노라마뷰가 깨집니다.

### ISSUE THREAD

**Issue by stnyaong** [navermaps/maps.js#104]
네이버 지도 api v3 사용중입니다.
크롬에서 파노라마뷰가 깨져서 나옵니다.
익스플로러에서는 정상적으로 나타나구요.
참고로 api가 아닌 네이버 지도에서 거리뷰 등은 깨지지 않고 잘 나옵니다.

**Comment by myounggun-chae** [comment]
@stnyaong 
안녕하세요.
파노라마뷰 깨진 화면 캡쳐해서 올려주실 수 있나요?
OS 환경과 크롬 버전 정보도 함께 알려주시면 확인해 보겠습니다~

**Comment by stnyaong** [comment]
![20170120_134154](https://cloud.githubusercontent.com/assets/25238496/22136209/783172ec-df16-11e6-93eb-29a70c4802b3.png)

Windows 10 X64, Chrome v 55.0.2883.87 m 입니다.

**Comment by myounggun-chae** [comment]
@stnyaong 
Window 10/Chrome 최신버전에서 이슈 확인했습니다.
브라우저 문제로 보이는데요. 원인 파악해 보고 답변 드리겠습니다.
원인 파악 전까지 불편하시겠지만 양해 부탁드릴께요~

감사합니다.

**Comment by stnyaong** [comment]
네 감사합니다!^^

**Comment by myounggun-chae** [comment]
@stnyaong 

`Window 10 + 64bit / Chrome v55.0.2883.87 m`에서 브라우저 버그로 확인했는데요.

`Chrome v56 beta` 버전에서 파노라마 깨짐 이슈가 재현되지 않았습니다.
v56 릴리즈 일정은 `2017/1/31 (예상)`로 확인하였습니다.
2월 초에 v56 버전 릴리즈 후 동일한 문제가 발생하는지 확인 부탁드릴께요~

#### [참고]
- Chrome Releases -  v55.0.2883.87 m (Stable) 2016/12/9 배포
https://www.google.com/chrome/browser/beta.html?platform=win64

- Chrome Release Channels - Beta channel for Windows (64-bit) 다운로드 (v56.0.2924.67)
http://www.chromium.org/getting-involved/dev-channel

- Chromium Development Calendar and Release Info
https://www.chromium.org/developers/calendar
```
Estimated* Stable Dates
- 56	 Jan 31st, 2017

win64    beta      56.0.2924.67    01/18/17	
win64    stable    55.0.2883.87    12/09/16
```

감사합니다.

**Comment by stnyaong** [comment]
감사합니다. 해결되었습니다.

**Comment by myounggun-chae** [comment]
@stnyaong 확인 감사합니다. ^^
