### ISSUE TITLE
파노라마 샘플이 실행이 안됩니다

### ISSUE THREAD

**Issue by dhwnsthf** [navermaps/maps.js#105]
API Key랑 라이브러리 설정 다하고서 실행했는데도 안되네요 왜 이런지 아시는분 계신가요? ㅠㅠ
https://cloud.githubusercontent.com/assets/18160847/22184678/5542958a-e11a-11e6-837f-6b2aa7366edd.png

**Comment by myounggun-chae** [comment]
@dhwnsthf 
안녕하세요. 
캡쳐화면은 어떤 브라우저에서 찍은건가요? (혹시 IE10 이하인가요?)
브라우저 테스트 환경을 알려주시면 정확한 답변이 가능할 것 같습니다.

**Comment by dhwnsthf** [comment]
다른 작업부터 하고있느라 답장이 늦었습니다. 캡처화면은 크롬으로 실행시켰을 때에 화면이고요. IE 11버전에서 실행해도 화면이 나오지 않습니다. 혹시 인터넷버젼과 관련이 있는 문제인가요?

**Comment by myounggun-chae** [comment]
@dhwnsthf 

안녕하세요. 
파노라마는 CSS3 + Flash 버전으로 구성되어 있습니다.
CSS3가 동작하지 않는 IE10 이하 환경에서 Flash 버전을 사용하고 있어서 여쭤봤습니다.

Window/Mac 크롬에서 아래 `파노라마 이벤트 처리하기` 페이지 접근하면 정상적으로 나오는데,
개발환경으로 코드를 옮기면 안된다고 하셔서 동일한 환경에서 이슈 재현을 해봐야 원인을 알 수 있을 것 같습니다.

https://navermaps.github.io/maps.js/docs/tutorial-3-panorama-event.example.html

확인 가능한 url을 공유해 주실 수 있을까요?

**Comment by dhwnsthf** [comment]
현재 공유가능한 URL이 없어서 실행한 코드를 대신 올려드립니다.

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>파노라마 기본 예제</title>
    <script src="../../docs/js/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="../../docs/js/examples-base.js"></script>
    <script type="text/javascript" src="../../docs/js/highlight.min.js"></script>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=FWaZsewDskG9FBsD05AM&amp;submodules=panorama"></script>
    <link rel="stylesheet" type="text/css" href="../../docs/css/examples-base.css" />
</head>
<body>



<div id="wrap" class="section">
    <h2>파노라마 기본 예제</h2>
    <p>파노라마 기본 예제입니다.</p>
    <div id="pano" style="width:100%;height:800px;"></div>
    <code id="snippet" class="snippet"></code>
</div>

<script id="code">
var pano = null;
naver.maps.onJSContentLoaded = function() {
    // 아이디 혹은 지도좌표로 파노라마를 표시할 수 있습니다.
    pano = new naver.maps.Panorama("pano", {
        // panoId: "OregDk87L7tsQ35dcpp+Mg==",
        position: new naver.maps.LatLng(37.3599605, 127.1058814),
        pov: {
            pan: -135,
            tilt: 29,
            fov: 100
        }
    });
};
</script>

</body>
</html>

파노라마 샘플 중 첫번째 샘플입니다. 참고로 파노라마 샘플 외에 다른 샘플들은 정상작동합니다.

**Comment by myounggun-chae** [comment]
안녕하세요~
개발자 센터에서 Client ID를 발급 받아서 웹서비스 URL 넣고 아래 `파노라마 기본 예제`를 테스트 해보았는데요.
- https://navermaps.github.io/maps.js/docs/tutorial-1-panorama-simple.example.html

아래 운영체제 + 브라우저 환경에서 파노라마 샘플 동작에 문제가 없었습니다. 
다른 원인이 있을 것 같은데, 확인 가능한 URL이 없다면 이슈 원인 파악이 힘들 것 같습니다. 
- Window 8.1 + IE11 / Chrome 56
- Window 10 + IE11 / Chrome 56
- macOS + Chrome 56 

아래 주소는 파노라마를 사용하는 서비스인데,
좌측패널에서 `이 아파트의 거리뷰/항공뷰 보기`를 눌러도 이슈 재현이 되는지요?
- https://hogangnono.com/apt/1Vkf9/0/22

**Comment by dhwnsthf** [comment]
아파트 거리뷰/항공뷰 보기를 누르면 이슈 재현이 됩니다.
혹시 파노라마 샘플을 동작하게 하신 코드를 한번 보여주실 수 있을까요?

**Comment by myounggun-chae** [comment]
파노라마 샘플 코드는 아래와 같습니다. 

-  Client ID: iNhtpwAcIUoimBpoqwOT
- 웹서비스 URL: http://localhost:3003

```html
<!DOCTYPE html>
<html>
<head>
    <title>파노라마 기본 예제</title>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=iNhtpwAcIUoimBpoqwOT&amp;submodules=panorama"></script>
</head>
<body>

<div id="pano" style="width:100%;height:800px;"></div>

<script>
var pano = null;
naver.maps.onJSContentLoaded = function() {
    pano = new naver.maps.Panorama("pano", {
        position: new naver.maps.LatLng(37.3599605, 127.1058814),
        pov: {
            pan: -135,
            tilt: 29,
            fov: 100
        }
    });
};
</script>

</body>
</html>
```

**Comment by cs09g** [comment]
캡처사진 보니까 스타일이 동작안하는거같은데, 관련이 있을까요?

**Comment by thetaiz** [comment]
@dhwnsthf 님, 크롬 시크릿 모드에서 동일하게 재현이 되는지 확인을 부탁드립니다.

**Comment by thetaiz** [comment]
메일로 답변을 드린 상태로 이슈를 닫습니다.
