### ISSUE TITLE
ie8에서 infoWindow 생성시에 대해 문의드립니다.

### ISSUE THREAD

**Issue by jpjp4521** [navermaps/maps.js#106]
ie8에서만 확인된 문제입니다.
더 이하버젼은 테스트 하지 못했습니다.

    var infoWindow = new naver.maps.InfoWindow({
        content: MARKER_SPRITE_POSITION[key][2],
		backgroundColor:"transparent",
		borderWidth: 0,
		maxWidth: 40,
		disableAnchor: false,
		anchorSize:0
	});

위의 내용중 anchorSize 이 변수를 값을 대입하면 에러가 발생합니다.
여러방식으로 넣어봐도 값이 있으면 무조건 아래와 같은 에러가 발생합니다.
값을 설정하지 않으면 발생하지 않습니다.
답변 부탁드립니다.

웹 페이지 오류 세부 정보

사용자 에이전트: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; WOW64; Trident/4.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
타임스탬프: Mon, 23 Jan 2017 07:45:37 UTC

메시지: Script error
줄: 0
문자: 0
코드: 0
URI: https://openapi.map.naver.com/openapi/v3/maps.js?clientId=****

**Comment by junthus** [comment]
@jpjp4521 님 안녕하세요.

`anchorSize` 옵션의 스펙은 naver.maps.Size의 인스턴스 입니다. [참고](https://navermaps.github.io/maps.js/docs/naver.maps.InfoWindow.html)
현재로서는 `anchorSize: new naver.maps.Size(0,0)` 로 정의해 주어야 하고, 이 부분 [사이즈 리터럴](https://navermaps.github.io/maps.js/docs/global.html#SizeLiteral)이 사용 가능하도록 업데이트 할 예정입니다(1/25일 예정).

ps. API가 ie8 이상을 지원하기 때문에 더 하위 버전까지는 테스트하지 않으셔도 됩니다.

감사합니다.

**Comment by junthus** [comment]
@jpjp4521 님 `anchorSize` 옵션에 사이즈 리터럴 사용 가능하도록 패치되었습니다.

**Comment by jpjp4521** [comment]
답변 감사합니다.
혹시 동일한 문제가 겪으시는분이 있을까봐 남깁니다.
여러가지 테스트 이후
ie8버젼 포함 상위 버젼이 적용되려면
anchorSize:new naver.maps.Size(0,-80)
형태가 되어야 하는것을 확인했습니다.
new naver.maps.Size(0,0)이라고 설정하면 바로위 생성될거라고
예상했지만 값을 주지 않았을때의 디폴트 위치에 생성되더라구요.
최초 시도는 new naver.maps.Size(-80,-80) 이라고 적용하니
ie8에서만 또 스크립트에러가 발생했구요. width 부분은 0으로 하고
height 부분만 음수값을 줘야 ie8도 정상적으로 표현되었습니다.
조금씩 미세하게 차이가 있네요^^ 어쨋든 결과는 ie8에서 문제있던부분을
수정완료되어서 기쁩니다. 감사합니다.

**Comment by boxersb** [comment]
@jpjp4521 안녕하세요?

`anchorSize` 옵션은 말풍선 꼬리의 사각형 영역 크기에 해당되는 값으로.. 음수 값은 본래 허용하지 않으나, anchorSize 의 height 가 InfoWindow 본문의 위치를 결정하는 요소로 사용되기 때문에 height 에는 적용이 되었던것 같습니다.

말풍선 꼬리를 사용하지 않으시려면, `disableAnchor` 옵션을 `true` 로 설정하시면 됩니다.

### InfoWindowOptions
> https://navermaps.github.io/maps.js/docs/naver.maps.InfoWindow.html#~InfoWindowOptions

감사합니다.

**Comment by junthus** [comment]
이슈 클로징하겠습니다. ^^
