### ISSUE TITLE
크롬에서 마커 이벤트 핸들링이 잘 안되는것 같습니다.

### ISSUE THREAD

**Issue by SaintJuny** [navermaps/maps.js#107]
안녕하세요. Point Type의 GeoJSON 데이터를 받아서 마커를 생성했습니다.

마커는 잘 나오지만 이벤트 핸들링이 잘 안되는것 같습니다. ( 마우스 오버, 클릭 )

https://navermaps.github.io/maps.js/docs/tutorial-1-datalayer.example.html

IE11, Edge, FF에선 잘 되는데 Chrome, Opera 에선 안되네요. 확인 좀 부탁드릴게요.

**Comment by junthus** [comment]
@SaintJuny 님 안녕하세요 ~

크롬(55 버전)에서 확인 시 별 다른 문제점이 발견되지 않는데요..
저희가 테스트 해 볼 수 있는 URL 을 제공해주셔야 살펴볼 수 있을 듯 합니다. ㅠㅠ

참고로 오페라 브라우저는 API의 지원 범위가 아닙니다. 

감사합니다.

**Comment by SaintJuny** [comment]
예제 그 자체가 실행이 안되는 부분이라서요.
개발용 노트북 2대에서는 작동이 안되는데 집의 데스크탑에서는 또 동작을 하네요.
참고로 노트북 환경에서는 예제 페이지에 들어갔을 때, 이런 메시지가 개발자 도구 콘솔로 나옵니다.
저의 크롬 버젼은 방금 업데이트해서 버전 56.0.2924.76 (64-bit)이 되었습니다.
A Parser-blocking, cross-origin script, https://openapi.map.naver.com/openapi/v3/maps-panorama.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
n @ maps.js?clientId=MK_1sBFRuO6XEvDi29iW&submodules=panorama,geocoder:14
n @ maps.js?clientId=MK_1sBFRuO6XEvDi29iW&submodules=panorama,geocoder:14
(anonymous) @ maps.js?clientId=MK_1sBFRuO6XEvDi29iW&submodules=panorama,geocoder:14
(anonymous) @ maps.js?clientId=MK_1sBFRuO6XEvDi29iW&submodules=panorama,geocoder:14
(anonymous) @ maps.js?clientId=MK_1sBFRuO6XEvDi29iW&submodules=panorama,geocoder:14

**Comment by junthus** [comment]
@SaintJuny 님 안녕하세요~ 연휴 잘 보내셨나요 ? ^^

크롬 56 버전에서 다시 확인해도 제보해주신 증상이 확인되지 않습니다. 영향을 미칠만한 요인이 있는지, 개발 환경에서 검토가 필요한 것 같습니다. ㅜㅜ 도움을 드리지 못해 죄송합니다.

참고로 현재 개발자 도구 콘솔에 나오는 내용은 `document.write` 사용을 경고하는 내용으로 제보해 주신 증상과는 무관합니다.
감사합니다.
