### ISSUE TITLE
Geocoder  주소 -> 좌표 변환시 반환 값 관련

### ISSUE THREAD

**Issue by stnyaong** [navermaps/maps.js#108]
Geocoder로 구 지번주소를 이용해 좌표 변환시 '산000'와 같은 형식인 지번의 경우

반환되는 값에서 result.items.address 값이 들어 있지 않습니다.

이 부분 체크 부탁드립니다.

**Comment by junthus** [comment]
@stnyaong 님 안녕하세요 ^^

`전라북도 진안군 마령면 평지리 산2`으로 테스트 해 봤는데 address 값 정상적으로 확인됩니다. 
문제가 되는 주소를 알려주시면 테스트 해 보겠습니다.

![image](https://cloud.githubusercontent.com/assets/5088669/22452483/8f414cda-e7ba-11e6-9a8e-18dad0977217.png)

**Comment by stnyaong** [comment]
대구광역시 수성구 대흥동 산42-3

등 대도시에 있는 산00 주소에서 테스트 해 보았는데 값이 들어오지 않았습니다.

**Comment by junthus** [comment]
@stnyaong 

![image](https://cloud.githubusercontent.com/assets/5088669/22453137/eff4c9e4-e7bf-11e6-92fe-cd4e24ca9bca.png)

알려주신 쿼리는 문제 없이 동작합니다. 해당 종류의 주소만 응답이 올바르지 않다면 query 인코딩 같은 다른 요인이 의심됩니다. 검토 부탁드려요 ~

**Comment by thetaiz** [comment]
이슈를 닫습니다.
