### ISSUE TITLE
마커 클러스터 이용시 깃허브와 네이버api홈페이지의 코드가 다릅니다.

### ISSUE THREAD

**Issue by KangSoYeon** [navermaps/maps.js#109]
네이버 홈페이지에는 다음과 같이 되어있고 
var markerClustering = new **MarkerClustering**({
        minClusterSize: 2,
        maxZoom: 8,
        map: map,
        markers: markers,
        disableClickZoom: false,
        gridSize: 120,
        icons: [htmlMarker1, htmlMarker2, htmlMarker3, htmlMarker4, htmlMarker5],
        indexGenerator: [10, 100, 200, 500, 1000],
        stylingFunction: function(clusterMarker, count) {
            $(clusterMarker.getElement()).find('div:first-child').text(count);
        }
    });
}

깃허브에는 저 부분이 Markerclusterer와 같이 되어있네요 Markerclusterer로 하면 오류가 나서 
Markerclustering으로 해도 동작은 여전히 안하네요

**Comment by junthus** [comment]
헉 @KangSoYeon 님 안녕하세요. 

`Markerclustering` 으로 사용하시는게 맞습니다. ㅠㅠ readme가 수정이 덜 되어서 혼동을 드렸네요, 제보 감사드립니다.

`Markerclustering` 으로 정의한 후에도 동작하지 않는다면
콘솔창의 오류 등등 상황을 파악할 수 있는 내용을 함께 적어주세요 ~

**Comment by junthus** [comment]
헉 document 페이지의 [예제](https://navermaps.github.io/maps.js/docs/tutorial-marker-cluster.example.html)가 정상 작동하지 않는군요;; 

바로 조치하겠습니다. 조금만 기다려 주세요 ~

**Comment by junthus** [comment]
@KangSoYeon 님 

패치 완료했습니다. 
[깃헙 페이지](https://github.com/navermaps/marker-tools.js/tree/master/marker-clustering)
[예제](https://navermaps.github.io/maps.js/docs/tutorial-marker-cluster.example.html)

제보 감사드립니다 ^0^
확인하시고 이슈 클로징 부탁드려요 ~

**Comment by thetaiz** [comment]
배포되었기에 이 이슈는 닫습니다.
