### ISSUE TITLE
How to clear markers on button click from Naver Map

### ISSUE THREAD

**Issue by dkchittimilla** [navermaps/maps.js#11]
Hi Team,

I would like to know the specific method to clear the markers from my map.

Thanks.

**Comment by junthus** [comment]
Hi again @dkchittimilla ,

All you have to do is use the 
```js
maker.setMap(null);
```
to all markers.

**Comment by dkchittimilla** [comment]
Hi Junthus,

Thanks for the update. But is there any way like map.ClearMarkers() to clear all the markers?

**Comment by junthus** [comment]
Oh, I understand what you need, But does not supported such way. You should have hold the marker instances and clear those.

**Comment by dkchittimilla** [comment]
Hi Junthus,

I tried this using the code below.

 $.each(navermarkers, function (index, nmarker) {
                nmaker.setMap(null);
            });

**navermarkers** is my array which holds all the markers and when I try to execute the code above, it is giving me the error 
"Uncaught ReferenceError: nmaker is not defined"

Please help me on this.

**Comment by junthus** [comment]
You misspelled. Look carefully... var name is 'nmarker' not 'nmaker'
