### ISSUE TITLE
데이터 레이어 관련해서 질문이 많아요.

### ISSUE THREAD

**Issue by SaintJuny** [navermaps/maps.js#110]
안녕하세요. 
서버단에서 GeoJSON 을 만들어서 데이터 레이어를 추가해 지도에 뿌려주고있습니다.
이렇게 하니 클러스트링과 겹칩 기능을 못쓰는거 같은데,
이걸 쓰지말고 다 Maker로 변환해서 써야하는지 알고 싶어요.
그리고 getAllFeature() 와 같이 getAllMarker() 기능은 없는지 궁금합니다.
그리고 Maker는 setProperty() 는 없는지도 알고 싶어요.
뭘 써야할지 고민이 됩니다. 시원한 답변 부탁드릴게요.

**Comment by junthus** [comment]
안녕하세요 @SaintJuny 님

API의 구조상 만들어진 오버레이를 일괄적으로 관리하지 않기 때문에 `getAllMarker` 기능은 없습니다.
데이터 레이어의 경우 GeoJson의 스펙과 유사하도록 계획하였기 때문에 `getAllFeature`를 지원하고 있는데요, 
만약 데이터레이어를 통해 만들어진 마커들만 얻고 싶다면 아래같은 필터 펑션을 추가하여 사용하시면 될 것 같습니다.
(데이터레이어를 통해 만들어진 마커는 `new naver.maps.Marker(...)` 로 생성된 마커와 동일하기 때문에 변환할 필요가 없습니다.)

```js
// 예시입니다 ^^
function getAllMarker() {
    let isMarkerInstance = (el) => {
        return (el instanceof naver.maps.Marker);
    }

    let allMarkers = [];

    map.data.getAllFeature().forEach((feature) => {
        let overlays = feature.getOverlays();

        if (overlays.every(isMarkerInstance)) {
            allMarkers = allMarkers.concat(overlays);
        }
    });

    return allMarkers;
}
```

클러스트링과 겹침 판별 기능은 이렇게 필터 펑션으로 걸러진 마커 인스턴스를 가지고 작업하시면 제공하는 예제와 비슷하게 적용 가능하실듯 합니다. 물론! [클러스트링이나 겹침마커 소스](https://github.com/navermaps/marker-tools.js/)를 알맞게 수정해서 쓰셔도 되고요. 

그리고 `setProperty`는 GeoJson의 `properties`속성을 이용하기 위한 메서드 입니다. 고로 기본 마커에는 해당 메서드가 없고, 기본 옵션을 설정하는 [setOptions](https://navermaps.github.io/maps.js/docs/naver.maps.Marker.html#setOptions__anchor)정도가 있다고 보시면 됩니다.

시원한 대답이면 좋겠네요 ^.^ 도움이 되시길 바랍니다.
감사합니다.

**Comment by SaintJuny** [comment]
감사합니다 많은 도움이 되었습니다.
