### ISSUE TITLE
마커 마우스 이벤트 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by SaintJuny** [navermaps/maps.js#111]
안녕하세요. 자주 문의 드리네요.
저번주엔가 문의를 드리긴했는데, 증상을 영상과 함께 다시 문의를 드려야할 것 같아서...
크롬에서 마커 마우스 관련 이벤트가 작동하지 않아요 ㅠㅠ
해결할 수 있는 방법이 있다면 알려주세요.
개발환경에 대한 정보가 필요하시다면 알려드릴게요.
감사합니다.

[영상링크](https://youtu.be/2QILuU-Njcc)

**Comment by thetaiz** [comment]
안녕하세요. 

해당 영상의 예제를 크롬에서 봤을 때 정상적으로 동작하고 있습니다. 시크릿 모드에서 확인을 한 번 더 부탁을 드립니다.
더불어 해당 크롬의 버전 정보도 부탁드립니다.

감사합니다.

**Comment by SaintJuny** [comment]
크롬은 버전 56.0.2924.87 (64-bit) 이며 시크릿모드에서도 동작을 안하네요.

**Comment by thetaiz** [comment]
@SaintJuny 님, 개발 환경 정보를 공유해 주시면 확인해 보겠습니다. 저희 환경에서는 정상적으로 동작을 하고 있어서요.

**Comment by SaintJuny** [comment]
문제 원인을 찾았습니다. 
chrome://flags/#touch-events 
사용 중지로 하니깐 정상작동하네요. 
신경 써 주셔서 감사합니다.

**Comment by thetaiz** [comment]
@SaintJuny 다행이네요~ ^^ 내부적으로 터치 이벤트가 바인딩이 안된 상태에서 에뮬레이터가 터치로 동작해 발생한 것으로 보입니다. ^^ 그럼 이 이슈를 닫아주세요~ ^^
