### ISSUE TITLE
브라우저 확대율에 따른 파노라마 표출 에러

### ISSUE THREAD

**Issue by cs09g** [navermaps/maps.js#112]
안녕하세요,

파노라마 예제를 보다가 미세하게 라인이 그려져 있는 것을 확인했습니다.
![image](https://cloud.githubusercontent.com/assets/7428017/22682322/6822d8f8-ed55-11e6-8d8c-bd91a5a578a2.png)

일시적인 현상인가 싶어 브라우저 화면을 확대(컨트롤 스크롤)해보니
확대시:
![image](https://cloud.githubusercontent.com/assets/7428017/22682342/8613b2ec-ed55-11e6-9bc3-a1bc8b8ab9f2.png)

축소시: 
![image](https://cloud.githubusercontent.com/assets/7428017/22682349/8eb170ec-ed55-11e6-836e-3232ddc0c96b.png)

요런 현상이 나타납니다.
확대/축소 한 상태에서 브라우저 새로고침을 해도 결과는 같습니다.

윈도우즈 크롬 55.0.2883.87 에서 확인했습니다.

----------------------
[수정]
크롬 버전 56.0.2924.87 에서 다시 확인한 결과
![image](https://cloud.githubusercontent.com/assets/7428017/22682578/b4cd8742-ed56-11e6-8da3-68ebef8b8e26.png)

확대시:
![image](https://cloud.githubusercontent.com/assets/7428017/22682588/bfa716b0-ed56-11e6-9e17-1e4c74d0fdae.png)

축소시:
![image](https://cloud.githubusercontent.com/assets/7428017/22682594/c8305a08-ed56-11e6-81e3-9634bf9d7069.png)

극단적이지는 않지만 조금 거슬리는데, 혹시 수정중이신지 궁금합니다.

**Comment by myounggun-chae** [comment]
@cs09g 

안녕하세요. 
`pixelRatio = 1`인 경우, Cube Face 경계 부분에 1 픽셀 라인이 보입니다. (레티나급 해상도에서는 정상)
CSS3로 perspective를 처리하고 있어서 완벽하진 않지만 거슬리지 않도록 수정할 예정입니다.
배포 일정은 2월 말 정도로 잡고 있습니다.

감사합니다.

**Comment by cs09g** [comment]
pixelRatio 가 몇인 경우에 정상으로 표시되나요?
http://stackoverflow.com/questions/16382542/how-to-simulate-pixel-ratio-to-test-media-queries-with-google-chrome-or-firefox#answer-17228026
위 글을 참고해 Firefox(51.0.1 (32비트)) 에서 pixelRatio =2 설정 후 테스트 해보니 라인이 사라졌다가 다시 생기는 경우가 있습니다.
1. 왼쪽으로 드래그(횡단보도에 사람들이 중앙에 오도록)
2. 뒤에 보이는 아파트 꼭대기로 드래그 이동(최상단)
3. 카메라가 있는 자동차로 드래그 이동(최하단)
4. 다시 횡단보도에 사람들이 중앙에오도록 드래그
5. 오른쪽으로 드래그 이동(시작 지점)
[결과]
![image](https://cloud.githubusercontent.com/assets/7428017/22723838/ec312762-ee04-11e6-96de-aa94d199fd2f.png)

+Firefox 에서는 휠확대 기능도 에러가 있는 것 같습니다.

**Comment by myounggun-chae** [comment]
@cs09g

PC웹에서 이미지 렌더링 방식을 수정하면 아래 2가지 문제는 해결될거라 생각합니다.
- 경계 부분에 라인이 보이는 문제 (완화)
- 브라우저 배율 확대 시 발생하는 에러 (해결)

2월 말 배포 시 FireFox 환경까지 고려하겠습니다.
배포 후 한번 더 확인요청 드리겠습니다.

감사합니다.

**Comment by myounggun-chae** [comment]
@cs09g

아래 이슈 패치한 버전 배포되었습니다.
확인해 보신 후 이슈 종료 부탁드릴께요~ ^^

- 경계 부분에 라인이 보이는 문제 완화 
  - CSS3로 Perspective를 처리하다 100% 해결은 힘든 점 양해 부탁드려요.
- FireFox에서 MouseWHeel 확대/축소 버그

감사합니다.

**Comment by thetaiz** [comment]
배포를 했으므로 이 이슈는 닫습니다.

**Comment by cs09g** [comment]
많이 좋아진것 같습니다 
p.s.
네이버 사옥 앞에 아파트가 이상한데. 이건 데이터 문제인가요?
![image](https://cloud.githubusercontent.com/assets/7428017/23351624/90280246-fd05-11e6-8413-d44181dad8fd.png)

**Comment by myounggun-chae** [comment]
@cs09g 

안녕하세요~
여러대의 카메라로 촬영한 이미지를 360도 이미지로 합치면서 흔히 발생하는 현상입니다.

감사합니다.
