### ISSUE TITLE
xyz를 bounding box 로 어떻게 변환하나요?

### ISSUE THREAD

**Issue by issacx2** [navermaps/maps.js#113]
네이버지도위에 
GeoServer로 구축한 WMS 서비스를 중첩하려고 하는데요. bbox 로 호출을 해야해서
네이버 tile 의 xyz 를 어떻게 bbox 정보로 변환해야하나요?

http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Java
여기에 비슷한 정보가 있어서 적용을 해봤는데, 잘 안됩니다...

**Comment by junthus** [comment]
@issacx2 님 안녕하세요~

꼭 타일의 인덱스로 bbox 를 만들어야 하는지가 궁금합니다. 현재 화면의 boundary 등으로 대체할 순 없을까요 ?

**Comment by issacx2** [comment]
사용자 지도 유형 만들기를 참고해서 getTile 함수를 구현하려고 위 질문을 한것이구요.

원래 목적은 네이버 지도위에 lx지적공사의 지번레이어를 추가로 올려서 중첩하려는 거에요.

네이버의 지적도 서비스가 있지만, 지번레이어의 과거를 보고 싶거나 최신을 보고 싶은 용도입니다.

맵의 bounds 사이즈만큼 geoServer에서 한장의 PNG로 만들어서 중첩하는 시도도 해봐야겠네요.

화면사이즈만큼 PNG를 구해서 중첩시켜도 되지만, 이왕이면 GeoServer의 WebCache를 활용하려면
256*256으로 작업하는게 성능적으로는 좋을거 같다라는 생각이 들어요.

**Comment by junthus** [comment]
@issacx2 아하 설명 감사합니다. map의 bound를 사용하는건 무리가 있을 수 있겠군요.

레이어 구현은 [이 예제](https://navermaps.github.io/maps.js/docs/tutorial-1-maptypes-tilecheck.example.html)를 참고하시면 될 듯 하고요, 타일 인덱스로 bbox를 얻는 방법은 아래와 같습니다.
도움이 되시길 바랍니다 ^^.

```js
// 위에 링크한 예제의  getTile 메서드 안에 추가했습니다. 
var map = new naver.maps.Map('map', {
    center: new naver.maps.LatLng(37.3595704, 127.105399),
    zoom: 10
});

var tileGridLayer = new naver.maps.Layer('tileGrid', {
    name: "TileGrid",
    minZoom: -1,
    maxZoom: 14,
    tileSize: new naver.maps.Size(256, 256),
    getTile: function(x, y, z) {
        // 여기
        var p = map.getProjection(),
            lbPoint = new N.Point(x * this.tileSize.width, (y+1) * this.tileSize.height),
            rtPoint = new N.Point((x+1) * this.tileSize.width, y * this.tileSize.height),
            normalizedLbPoint = p.scaleDown(lbPoint, map.getZoom()),
            normalizedRtPoint = p.scaleDown(rtPoint, map.getZoom()),
            lb = p.fromPointToCoord(normalizedLbPoint),
            rt = p.fromPointToCoord(normalizedRtPoint),
            bbox = [lb.x, lb.y, rt.x, rt.y];

        console.log(bbox);

        var div = $('<div class="tilegrid">('+ [z, x, y].join(', ')+')</div>');

        return div[0];
    }
});

tileGridLayer.setMap(map);
```

**Comment by junthus** [comment]
@issacx2 오 근데 생각해보니 그 서비스 궁금하네요 !! 혹시 런칭하시면 구경하게 사이트 알려주세요 ~~

**Comment by issacx2** [comment]
와우 잘 됩니다...^^
감사합니다. 덕분에 쉽게 해결했습니다.
이 서비스는 공공기관에서 현장조사를 위한 내부프로그램이라 일반인 대상으로 서비스는 하지 않을계획입니다. ^^
필지에 대해 분할이나 합병이 일어날 경우 과거나 최신의 지적도 정보가 필요해서 진행중에 있습니다. ^^
