### ISSUE TITLE
네이버 지도 api 호출 문의

### ISSUE THREAD

**Issue by msg111** [navermaps/maps.js#114]
기존에 쓰던 api 호출 url인데 지금 어떻게 변경된 건지 문의 드립니다.
http://openapi.naver.com/map/getStaticMap?version=1.0&crs=EPSG:4326&center=126.9235992,37.4925380&level=10&w=433&h=443&maptype=default&exception=inimage&markers=126.9235992,37.4925380&format=png&key=5dd88d6c905cd804d784f9edef467bdc&uri=bzm.kr

**Comment by thetaiz** [comment]
키(key)를 이용한 API는 12월 26일부로 종료되었습니다(https://developers.naver.com/notice/article/10000000000030648921).

아래 링크를 참조하여 API 변경을 부탁드립니다.

- https://developers.naver.com/docs/map/overview

**Comment by thetaiz** [comment]
이슈를 닫습니다.
