### ISSUE TITLE
InfoWindow 관련 문의 드립니다.

### ISSUE THREAD

**Issue by jungdongyong** [navermaps/maps.js#115]
v2 에서는 InfoWindow 클래스를 여러번 사용을 했었는데요. 
Mark를 여러개 올려놓고..  각 Mark 에 InfoWindow 를 각각 넣었습니다.
v3 마이그레이션 하는데..   가장 마지막에 생성한 InfoWindow 만 보이고 
다른 정보창윈도우는 보이질 않는데요..
사용법을 잘못한것인지.. 
v3 에서는 위 방법으로 각 Mark 에 정보창을 넣을수 없는것인지요?
코딩상에서는 특별한 문제점을 찾아볼수가 없어서요.

가능하다면 관련 샘플 코드 바랍니다.

**Comment by junthus** [comment]
안녕하세요, @jungdongyong 님

네 코드는 문제가 아닙니다만 ㅠㅠ `InfoWindow` 클래스가 애당초 지도상에 하나의 정보창만 표시하는 스펙이기 때문에 여러개를 표시할 수 없습니다.

고로 `InfoWindow`클래스를 이용할 순 없고 HTML 마커나 CustomOverlay 를 구현하는 방법을 사용해야 하는데요, 각 마커별로 정보창이 필요하다면 HTML 마커로 구현하는 것을 추천드립니다. (HTML 마커는 마커의 컨텐츠(아이콘 등등)을 직접 정의한 dom으로 사용할 수 있도록 하는 기능입니다. 지도 상태 변경시에 위치변경등이 자동으로 되기 때문에 CustromOverlay 구현보다 편리한 점이 있습니다.)

http://codepen.io/navermaps/pen/xONGbY
위의 예제의 71 ~ 110 라인 구문이 HTML 마커로 각각의 인포윈도우를 표현하고 있습니다. 아래 HTML 마커 내용과 함께 참고하시면 손쉽게 구현 가능할 듯 합니다.
[HTML 마커 예제](https://navermaps.github.io/maps.js/docs/tutorial-5-marker-html-icon.example.html), [HTML 마커 옵션](https://navermaps.github.io/maps.js/docs/naver.maps.Marker.html#toc33__anchor)

추가로, 위의 예제는 [네이버 지도 JavaScript API 완벽 가이드 – 오버레이 편](http://d2.naver.com/helloworld/3380225)에서 발췌했습니다. 혹시 CustomOverlay 등 다른 방법도 궁금하시면 저 글을 한 번 읽어보시는 것도 도움이 될 듯 합니다. 

도움이 되시길 바랍니다.

**Comment by thetaiz** [comment]
이슈를 닫습니다.
