### ISSUE TITLE
네이버 지도 api v3 마커 문의

### ISSUE THREAD

**Issue by hyeongsooshin** [navermaps/maps.js#116]
안녕하세요.
v2 에서 v3 로 변경 과정에서 , 마커 부분이 지도 확대/축소 할때 같이 따라 움직입니다..
아래와 같이 변경했습니다. 어떤부분이 빠져 있나요?
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=XXXXX"></script>
<div id ="map" style="width:100%; height:380px; "></div> 
<script>
var position = new naver.maps.LatLng(위치 절대값);
var map = new naver.maps.Map('map', { 
	center: position,
	zoom: 12	
}); 
var marker = new naver.maps.Marker({
	position: position, 		
	map:map,
	icon: { 
		url: '이미지URL',
		size: new naver.maps.Size(206, 93), 	
		origin: new naver.maps.Point(0, 0),
		anchor: new naver.maps.Point(25, 26)
		}	
});

</script>

**Comment by thetaiz** [comment]
@hyeongsooshin 님, 혹시 저희가 확인할 수 있는 URL이 있나요? 그리고 위치 절대값은 위/경도 값을 말씀하신거죠?

**Comment by hyeongsooshin** [comment]
마커 모양이 이미지로 변경하면 지도 확대/축소 할때 마다 마커 위치가 이동하네여... 
그냥 네이버에서 기본으로 제공한 마커모양으로 해결 했습니다.

절대값은 위도/경도 값입니다.

**Comment by thetaiz** [comment]
@hyeongsooshin 님, 저희쪽에서도 테스트를 해보겠습니다. 아래와 같은 과정으로 재현을 해보면 될까요?

1. 기본 마커가 아닌 별도의 이미지 마커를 이용(혹시 사용하신 이미지의 주소를 알려주실 수 있나요?)
2. 앞서 알려주신 코드 상태에서 지도를 확대/축소할 때 마커의 위치가 아예 다른 위치로 이동

**Comment by hyeongsooshin** [comment]
네에~ 입력 해주신 과정으로 재현 하시면 될거같습니다..
이미지 주소 같은경우는 회사 정책상 불가능 할거같습니다. 로컬 일반 이미지경로로 하셔도 될거같아요.
감사합니다.

**Comment by thetaiz** [comment]
넵, 감사합니다. ^^ 혹시 저희 예제 역시 그렇게 동작하나요? 아래는 이미지 마커를 이용한 예제입니다.

- https://navermaps.github.io/maps.js/docs/tutorial-4-marker-sprite-image-icon.example.html

**Comment by cs09g** [comment]
anchor 값에 따라 바뀌어 보일수도 있을 것 같습니다.

**Comment by hyeongsooshin** [comment]
@thetaiz 정상적으로 보이고 있습니다.
예제 참고 해서 다시 적용 해보겠습니다.

**Comment by thetaiz** [comment]
감사합니다. 이슈를 닫습니다.

**Comment by sdh2621** [comment]
저도 질문자님과 똑같은 현상이 일어납니다. 확인 부탁드립니다. url 첨부합니다.
http://sdh2621.dothome.co.kr/project1/main.html
