### ISSUE TITLE
Javascript runtime 오류: 정의되지 않음 또는 null 참조인 'fromLatLngToUTMK' 속성을 가져올 수 없습니다.

### ISSUE THREAD

**Issue by yidmire** [navermaps/maps.js#117]
[정의되지 않음 또는 null 참조인 'fromLatLngToUTMK' 속성을 가져올 수 없습니다.]

좌표계 변환 시 위와 같은 문구가 나옵니다. 

좌표계 변환을 사용하지 않고 실행을 하면, 
[정의되지 않음 또는 null 참조인 'style' 속성을 가져올 수 없습니다.]
라는 에러가 나오네요.. 

map api 사용을 잘못한건지, 다른 소스가 잘못된건지 혹시 아시나요

**Comment by thetaiz** [comment]
@yidmire 님, 혹시 구현한 코드를 볼 수 있을까요? https://navermaps.github.io/maps.js/docs/tutorial-1-geocoder-transcoord.example.html 예제에서 fromLatLngToUTMK를 사용하고 있는데 정상적으로 동작하는 것을 봐서는 API 이슈는 아닌 것으로 보입니다. @yidmire 님의 구현 코드를 보면 좀 더 도움이 될 것 같습니다.

**Comment by yidmire** [comment]
창피합니다만.. 
소스가 좀 길지만.. 이래저래 바꿔보기도 하고,, 
꼼꼼히 분석 해 보았는데 뭐가 문제인지 모르겠어서요..

소스가 좀 길어서 링크로 올려봅니다....

기존에 olleh map api로 적용되어있던걸 naver map api로 옮기는 방식으로 작업을 한 내용입니다. 
이 소스만으로는 알기 힘들면 좀 더 해보아야 겠네요... 

http://naver.me/GfUWEcKl

**Comment by thetaiz** [comment]
@yidmire 님, 오류가 나는 위치(파일, 줄 번호) 정보를 알려주실 수 있나요?

**Comment by thetaiz** [comment]
@yidmire 님, 그리고 LatLng 인터페이스를 사용할 때 좌표가 반대로 들어가는게 있네요.

var truckPositionWSG = new naver.maps.LatLng(longitude, latitude);

new naver.maps.LatLng(latitude, longitude) 순서입니다.

**Comment by yidmire** [comment]
@thetaiz 님. 감사합니다.. 
계속 Sign in이 안되다가 이제 되네요;; 

좌표 순서는 lat, lon 으로 바꿔서 넣어도 계속 안되더라구요.. 그런데 Lat, Lng 순서로 바꿔두어야겠네요 그게 맞는거니...

에러는.. 해당 소스에서 나지 않고... 
http://naver.me/Fd3bJ3su  
이 jquery-1.7.1.js의 7587줄에 throw e 부분이 블락쳐지면서 
[Unhandled exception at line 7587, column 6 in http://localhost:16757/Scripts/jquery-1.7.1.js
0x800a138f - JavaScript 런타임 오류: 정의되지 않음 또는 null 참조인 'style' 속성을 가져올 수 없습니다..] 
라는 메세지가 뜨면 continue 버튼 눌러 진행해보고 있습니다. 
 
좌표 바꿔보니.. 맵은 뜨네요.. ㅎㅎ 마커 이미지는 아마 HOME_PATH 경로 문제나 파일 문제일테니 해결해 본다 치고.. 
해당 메뉴 접근 할 떄 마다 위 메세지가 디버거에서 뜹니다. 

VisualStudio asp.net 으로 작성한 .cshtml파일인데.. 
그 때문에 생기는 문제일수도 있을런지요??

**Comment by thetaiz** [comment]
해당 파일로 인한 것인지는 제가 확답을 드리지 못하겠네요. 혹시 jQuery 에러에 대한 로그 스택이 어떻게 되는지 확인을 부탁드려요. 어떤 부분에서 어떤 값을 전달하면서 에러가 나는지...

**Comment by thetaiz** [comment]
@yidmire 님, 해결이 되셨나요?

**Comment by yidmire** [comment]
@thetaiz 감사합니다.. 다른 유지보수 업무들과 병행해서 개발하다보니 지금 못잡고 있었네요.. ㅜㅜ
이게.. 어디에서 값을 넘기는 때에 해당 오류가 뜨는지 VS디버거에 뭐가 뜨질 않네요;;
일단은 웹 페이지 자체도 돌아가긴 하고.. 지도도 출력되긴 하고..(마커아이콘은 아직 경로를 못잡아서 안뜨지만) 다른 메뉴로 이동도 되고 하는거 보니 뭔가 다른 에러 같기도 해서요.. 

로컬 말고 웹서버 IIS에 한번 게시 해서 돌려보기도 할까 합니다. 

0x800a138f - JavaScript 런타임 오류: 정의되지 않음 또는 null 참조인 'style' 속성을 가져올 수 없습니다.
이 메세지창의 'style'이 'fromLatLngtoUTMK'라던가 바뀌는 것을 보니 다른 접근을 해 보려 합니다.

**Comment by yidmire** [comment]
@thetaiz 제가 질문이랄까, 문제 상황 설명도 뭔가 좀 쉽게 되지 않아 죄송합니다;; 한번 다시 정리좀 해 보고 도움을 구해야겠어요....ㅜㅜ

**Comment by thetaiz** [comment]
@yidmire 님, 넵~ ^^ 우선 이 이슈는 닫겠습니다. 정리 후 필요 시 다시 이슈를 열어주세요.
더불어 저희쪽에서 확인해 도움을 줄 수 있는 URL을 알려주시면 빠르게 도움을 드릴 수 있을 것 같아요~ ^^
