### ISSUE TITLE
네이버 좌표 가져오기

### ISSUE THREAD

**Issue by kyeongjin** [navermaps/maps.js#118]
안녕하세요.
네이버 지도 이용하여 쇼핑몰 운영중에 있습니다

주소 -> 좌표 를 통한 좌표를 얻어와 지도에 마커 표시를 하기 위한 예제 소스를
찾기 힘들어 문의 드립니다.

어디서 찾아 볼수 있을까요??

**Comment by kyeongjin** [comment]
추가적으로 좌표를 불러올 수 있는 url 안내 부탁 드리겟습니다

**Comment by thetaiz** [comment]
@kyeongjin 님, 좌표를 얻어 지도에 마커를 표시하는 예제는 아래를 참조하면 됩니다.

- https://navermaps.github.io/maps.js/docs/tutorial-3-geocoder-geocoding.example.html

위 예제는 정보 창을 해당 위치에 올리는데 정보 창 대신 마커를 올리면 됩니다.

좌표를 불러올 수 있는 URL이란게 주소 -> 좌표 변환 API를 말씀하신거죠? 두 가지 방법이 있습니다.

- 위 예제의 searchAddressToCoordinate() 처럼 JavaScript를 이용하는 것이 있습니다. https://navermaps.github.io/maps.js/docs/tutorial-Geocoder-Geocoding.html 튜토리얼을 참고해 주세요.
- https://developers.naver.com/docs/map/overview/ 링크의 https://openapi.naver.com/v1/map/geocode API를 이용하는 것이 있습니다. 해당 API 명세를 참고해 주세요.

**Comment by thetaiz** [comment]
이슈를 닫습니다.
