### ISSUE TITLE
주변 지하철역, 버스정류장 정보를 받아올 수 있을까요?

### ISSUE THREAD

**Issue by aiden9999** [navermaps/maps.js#119]
지도에 마커로 해당 지역 표시하면서 하단에 주변 지하철역, 버스정류장 표시하려하는데 정보를 받아올 수 있는 방법이 있을까요?

**Comment by thetaiz** [comment]
@aiden9999 님, 아쉽게도 해당 데이터를 제공하는 API를 Open API 형태로 제공하지 않습니다. 죄송하네요~

**Comment by thetaiz** [comment]
@aiden9999 님, 공공데이터포털을 이용해 보시는 것도 한 방법이네요~

http://data.go.kr/dataset/15000759/openapi.do

**Comment by aiden9999** [comment]
답변 감사합니다~
