### ISSUE TITLE
교통경로나 이동시간정보도 이용할수있나요 

### ISSUE THREAD

**Issue by gksthf2845** [navermaps/maps.js#12]
만들고싶은 어플이있는데 
구글맵은 한국에서 이동경로를 지원을 안해서 혹시 네이버는 되나 궁금합니다

**Comment by myounggun-chae** [comment]
@gksthf2845 
안녕하세요. 아쉽게도 길찾기 기능은 현재 오픈 API로 제공하고 있지 않습니다.

감사합니다.
