### ISSUE TITLE
geocoder 서브모듈 사용시 문의사항

### ISSUE THREAD

**Issue by yoongiljoong** [navermaps/maps.js#120]
geocode 서브모듈 동작은 기본적으로 sync방식인가요? async 방식인가요?

**Comment by thetaiz** [comment]
@yoongiljoong 님, 비동기 방식입니다.

**Comment by yoongiljoong** [comment]
@thetaiz 그럼 동기식으로 구동시킬수 있나요??

**Comment by boxersb** [comment]
@yoongiljoong 혹시 서브모듈 js 로딩 방식을 말씀하시는지요..?

- 서브모듈 로딩방식은 동기식/비동기식 둘 다 가능합니다.. 
- geocode, reversegeocode API 호출 자체는 동기식으로 구동시키는것이 불가능합니다.

**Comment by yoongiljoong** [comment]
@boxersb geocode(reversegeocode)는 무조건 비동기로 동작하나보군요... 흐음.. 그럼 결국 제공되는 geocode를 이용하지않고 직접 ajax로 직접 호출해야하는 건가요??

**Comment by boxersb** [comment]
@yoongiljoong ajax 로 호출하시려면, https://developers.naver.com/docs/map/overview/ 를 참조하시어, 서버 사이드 스크립트를 직접 작성하시면 됩니다. 

감사합니다.

**Comment by yoongiljoong** [comment]
@boxersb 친절한 답변 감사합니다.
