### ISSUE TITLE
V1에 있던 enableWheelZoom나 enableDragPan 값은 어떻게 변경되었나요?

### ISSUE THREAD

**Issue by Happy2You** [navermaps/maps.js#121]
V1에 있던.. 옵션값은 어떻게 사용해야 하나요?
``
enableWheelZoom : false,
enableDragPan : true,
enableDblClickZoom : false,
activateTrafficMap : false,
activateBicycleMap : false,
``

**Comment by thetaiz** [comment]
@Happy2You 님, 아래와 같이 지도 옵션을 참고해 설정하면 됩니다.

- https://navermaps.github.io/maps.js/docs/naver.maps.html#.MapOptions

단, 교통상황지도와 자전거지도는 지도 옵션을 이용할 수 없고 아래 예제를 참고해 구현해야 합니다.

- https://navermaps.github.io/maps.js/docs/tutorial-3-traffic.example.html
- https://navermaps.github.io/maps.js/docs/tutorial-1-bicycle.example.html

**Comment by thetaiz** [comment]
이슈를 닫습니다.
