### ISSUE TITLE
geocoder 서브 모듈 문의 드립니다.

### ISSUE THREAD

**Issue by G-hoon** [navermaps/maps.js#122]
input text 박스를 만들어서, 예제를 참고하여 
input text 박스에 주소를 입력하고 위치로 이동하는 것까진 만들었는데요.
주소가 시,구,동 까지밖에 안되더라고요.
예컨대 서울대학교, 서울대학교 병원, 혜화역, 강남대로, 도곡동 삼성 래미안아파트
이런 식의 검색은 찾지 못하더라고요.
네이버 지도나, 네이버 홈페이지 검색창에서처럼 상세주소까지 검색하려면 어떻게 해야할까요?

**Comment by thetaiz** [comment]
@G-hoon 님, 안녕하세요.

우선 네이버 지도나 네이버 메인에서 제공하는 서울대학교, 서울대학교 병원 등의 검색어는 별도로 대응하는 것이라 주소 -> 좌표 API에서 처리하지 못합니다. 

상세 주소가 어느 정도 수준인지 예를 들어주시면 파악해 알려드리겠습니다. ^^

우선 도로명 경우 아래와 같은 형식을 취합니다.

* 시 + 구 + 도로명 + 건물번호 + 상세주소
* 도 + 시 + 도로명 + 건물번호 + 상세주소

**Comment by thetaiz** [comment]
이슈를 닫습니다.
