### ISSUE TITLE
블로그API 등록시 네이버 지도 등록 가능여부

### ISSUE THREAD

**Issue by Taebu** [navermaps/maps.js#123]
안녕하세요. 

블로그 API 로 등록시 네이버 지도가 등록되었으면 해서 여러 방법 중 iframe, object 로 등록하도록 하였으나 구현되지 않고 소스에서 일부가 유실되도록 되어 있더군요.

이번 버전이 맵 v3 이 되면서 이런 부분이 등록  가능하도록 할 수 있다면 어떻게 해야 하나요?

**Comment by junthus** [comment]
@Taebu 님 안녕하세요 ~
문의주신 내용이 정확히 파악이 되지 않네요 ㅠㅠ
어떤식으로 구현을 하신건지 조금 설명 부탁드리고요, 저희가 접근해 볼 수 있는 URL 이 있다면 알려주세요.
감사합니다.

**Comment by thetaiz** [comment]
@Taebu 님, 확인 부탁드려요~ ^^

**Comment by Taebu** [comment]
음.  로그인을 해야 확인이 가능하게 해놔서 기본적으로 블로그 api에서 요청하는 access_token을 리프래시 토큰을 이용해서 인증후 기본제공하는 것으로 블로그에 등록하도록 했습니다.

http://blog.naver.com/mdagency153/220968304866

그래서 위의 링크에 가운데 있는 맵 처럼 등록이 되게 하려고 여러 모로 해봤는데 답을 찾기 어려워서 문의 해봅니다.

**Comment by junthus** [comment]
@Taebu 님 

링크 주신 블로그의 경우 스마트에디터(3)으로 저작한 지도이기 때문에 구현하시려는 내용과 인증 체계가 다릅니다.

직접 페이지 컨텐츠 내에 지도를 삽입하시려면 지도 API 사용 신청 후 해당 URL(ex-`http://blog.naver.com/id/`) 을 등록해야 하고, 페이지 내에도 지도 API js를 직접 로드해야 할 것으로 예상됩니다. 
(참고로 지도 API와  블로그 API의 권한(access_token)은 별개입니다. 위와 같은 방법으로 구현하셨다면 발급받은 키에 지도 API 이용 권한이 있는지 살펴봐 주세요.)

자세한 내용은 페이지를 직접 확인해야 알 수 있습니다. 혹시 더 도움이 필요하시다면 '구현되지 않고 소스에서 일부가 유실되는'... 저 페이지 url을 알려주시면 좋을 듯 합니다.

감사합니다.

**Comment by thetaiz** [comment]
@Taebu 님, 추가 문의가 있으신가요? 이슈 해결이 되었는지 궁금합니다.

**Comment by thetaiz** [comment]
이슈를 닫습니다. 추가로 문의가 필요한 경우 다시 열어주세요.
