### ISSUE TITLE
tutorial-0-Getting-Started.html 오타 수정 요청

### ISSUE THREAD

**Issue by artiveloper** [navermaps/maps.js#124]
안녕하세요.
지도 생성하기 부분, 비동기방식 예제에 callback 매개변수에 오타가 있습니다.  확인 부탁드립니다~

iniMap -> initMap

좋은 서비스 제공해주셔서 감사합니다.

**Comment by thetaiz** [comment]
@artiveloper 님, 감사합니다. ^^ 수정하겠습니다.

**Comment by thetaiz** [comment]
금일 배포되었습니다. 이슈를 종료합니다.
