### ISSUE TITLE
내부망 에서 네이버 지도 개발시 오픈방화벽 정보

### ISSUE THREAD

**Issue by mon1115** [navermaps/maps.js#125]
내부망에서 네이버지도를 개발 해야 하는데 방화벽 오픈을 요청해야 합니다. 어떤 url과 port를 오픈 해야 하나요 ?.

**Comment by junthus** [comment]
@mon1115 안녕하세요 ~

아마 IP를 말씀하시는 듯 합니다만 IP 정보는 통보없이 바뀔 수 있으므로 적절한 주기로 nslookup으로 IP정보를 확인하거나, ASN(Autonomous System Numbers) 정보로 IP 대역을 파악하셔야 합니다.
포트는 80, 443 입니다.

도움이 되시길 바랍니다 ^.^
