### ISSUE TITLE
검색이안되어요.

### ISSUE THREAD

**Issue by smzziu** [navermaps/maps.js#126]
크롬환경에서 상단 레이어 검색 팝업에 반응이없습니다.... 
진행상황 프로그래스바 이미지라도 돌아갔으면 좋겠습니다.

호출전에 말이죠... 근데 진짜로 안되는건지 헣허허허

**Comment by thetaiz** [comment]
@smzziu 님, 아래 예제 페이지를 말씀하시는건가요?

- https://navermaps.github.io/maps.js/docs/tutorial-3-geocoder-geocoding.example.html

**Comment by smzziu** [comment]
아니요. 메뉴에서 상단 GNB 영역에서 검색할 경우 레이어 팝업으로 검색결과가 나타나는듯 하는데 반응이없어서요. 해당부분 예제가 아니여요.

**Comment by thetaiz** [comment]
@smzziu 님, https://navermaps.github.io/maps.js/docs/index.html 요기의 상단 검색창을 말씀하시는거죠? 팝업으로 검색결과가 나타나는 것은 웹브라우저에서 캐싱된 검색어가 나타나내요. 실제 문서 검색은 검색어 입력 후 엔터를 넣어야 동작합니다. 해당 부분은 템플릿을 사용하고 있는거라 저희가 직접 수정하기는 어려울 수도 있습니다. ^^ 당장은 어렵지만 내부적으로 검토는 해보겠습니다.
