### ISSUE TITLE
rightclick 이벤트 관련

### ISSUE THREAD

**Issue by monkeychoi** [navermaps/maps.js#127]
naver.maps.Event.addListener(map, 'click', function (e) {
    alert("맵클릭");

    var point = e.coord;

    var marker = new naver.maps.Marker({
        map: map,
        position: point,
        icon: {
            url: './images/marker1.png',
            size: new naver.maps.Size(30, 45),
            origin: new naver.maps.Point(0, 0),
            anchor: new naver.maps.Point(15, 40)
        }
    });

    naver.maps.Event.addListener(marker, "click", function (ex) {

        alert("마커클릭");
    });

});

위 코드의 경우 맵을 클릭하면 "맵클릭" alert 와 함께 마커가 추가되고 추가된 마커 클릭 시 "마커클릭" alert 가 발생합니다.
이건 정상적인 동작 같은데요....
맵과 마커의 addListener 모두 click 이 아닌 rightclick 으로 바꾸면 다르게 동작을 합니다.
마커 rightclick 시 "맵클릭" alert 도 발생을 합니다. 이벤트 버블링(캡쳐링?)이 되는 것 같은데요 이거 의도된 동작인가요 ??
Chrome 에서 테스트 했습니다.

**Comment by thetaiz** [comment]
@monkeychoi 님, 확인 후 알려드리겠습니다.

**Comment by junthus** [comment]
@monkeychoi 마커 `rightclick` 시 지도의 `rightclick`이 동작하지 않도록 패치 하겠습니다. 해당 내용은 4월 정기배포(27일)에 포함될 예정입니다. 이슈 제보 감사드립니다 ^^.

**Comment by thetaiz** [comment]
@monkeychoi 님, 해당 부분은 버그입니다. ㅠㅠ 마커에서 마우스 오른쪽 클릭 시 @monkeychoi 님 말씀처럼 마커의 이벤트만 나가야 합니다. 4월 말에 있을 정기배포에 릴리즈하도록 하겠습니다. 감사합니다.
