### ISSUE TITLE
마커  "click", "dblclick" 이벤트 동시적용시

### ISSUE THREAD

**Issue by monkeychoi** [navermaps/maps.js#128]
제목대로 마커에 click 과 dblclick 둘다 addListener 한 경우 
마커에서 dblclick 을 하면 click 이벤트가 같이 발생하는데 이거 의도한 설계인가요 ??
확인 좀 부탁드립니다.

**Comment by junthus** [comment]
안녕하세요 @monkeychoi 님

기본적으로 브라우저에서 native dblclick 시에도 click 이벤트는 동시에 발생하기 때문의 제보해 주신 현상은 오 동작이 아닙니다. 다만 지도의 경우 두 번 째 `click`은 발생시키지 않고 `dblclick` 으로 발생시키고 있습니다. 

혹시 문제가 되는 상황이 있다면 코멘트 주세요 ~ 감사합니다.

(참고)
![image](https://cloud.githubusercontent.com/assets/5088669/24735656/fa75d73c-1abe-11e7-99da-073b58b90e98.png)

**Comment by cs09g** [comment]
참고로, 보통 이런 경우때문에 이벤트에 일정 타임을 걸어 singleclick 과 같이 구현되어있는 곳도 있습니다.

**Comment by monkeychoi** [comment]
감사합니다.
