### ISSUE TITLE
location.href 체크

### ISSUE THREAD

**Issue by davidshimjs** [navermaps/maps.js#129]
안녕하세요.

저희가 네이버 맵으로 변경한지 이제 몇 개월 돼가는데요, 구글 맵에서는 url을 strict하게 체크 안해서 그런지 유독 네이버 맵을 쓸 때에 아래와 같은 CS가 많이 들어옵니다.
![default](https://cloud.githubusercontent.com/assets/3103540/24739724/54a92baa-1ad8-11e7-9b46-8c08d699ca1a.jpg)

저희가 몇 개를 살펴보니, IE 툴바 등에서 페이지를 요청할 때 iframe 등으로 씌워서 보내기 때문에 location.href가 hogangnono.com이 아닌, 다른 URL로 얻어져서 생기는 문제였습니다.

이런 문제를 해결할 수 있는 방법이 있을까요?
(요즘도 한 달에 3~4건씩은 꾸준히 들어옵니다 ㅠㅠ)

**Comment by thetaiz** [comment]
@davidshimjs 님, 안녕하세요~ 음... 인증 시 location.href의 도메인과 등록된 도메인을 확인하고 있기 때문에... 함 확인 후 공유를 드릴께요~

**Comment by thetaiz** [comment]
@davidshimjs 님, 혹시 IE 툴바라는게 어떤건가요? ^^

**Comment by boxersb** [comment]
@davidshimjs 님.. 해당 환경의 `location.href` 또는 식별할 수 있는 url 정보가 어떻게 뜨나요..?  
네이버 개발자센터가 멀티 도메인을 등록할 수 있도록 개선되었으므로, 해당 url 정보를 추가하면 임시 해결은 가능하실것 같습니다.

**Comment by thetaiz** [comment]
@davidshimjs 님, @boxersb 님이 문의한 location.href가 어떻게 나가나요? 확인 부탁드려요~

**Comment by davidshimjs** [comment]
@boxersb @thetaiz 답변이 늦어 죄송합니다~! 문제가 발생하는 PC를 현재는 구할 수 없네요; (어플리케이션 key에서 조회를 시도한 url 기록을 볼 수 있는 화면이 있으면 좋겠네요 ㅠㅠ) IE 툴바는 특정 툴바를 지칭한건 아닌데요, 주로 저런 CS가 들어오면 크롬을 사용하시라고 조언 드려서 해결 했었습니다.

근데 이번엔 크롬을 써도 안된다고 하시는거보면... DNS 문제일 가능성도 있을 것 같아요.

현상이 2개인데
1) 명백히 다른 도메인 환경에서 찔러서 항상 오류가 발생하는 경우
2) 간혹가다 오류가 발생하는 경우

였던 것 같아요. 저희가 사용자 PC에서 디버깅하기는 어려우므로 몇 일동안 `location.href`에 대한 로그를 쌓아보겠습니다.

**Comment by davidshimjs** [comment]
이 부분은 다시 해당 이슈가 발생하면 리포팅 하겠습니다~!
