### ISSUE TITLE
하이브리드 앱 적용 문의.

### ISSUE THREAD

**Issue by kdu0801** [navermaps/maps.js#13]
안녕하세요. 안드로이드 하이브리드 앱을 공부 중인 학생입니다.
네이버 지도 v3을 사용하려고 보니 자바스크립트로 이루어져있던데 api 키만 발급받고 바로 하이브리드 앱 내의 html 소스에 넣어봤는데 클라이언트 키를 제대로 입력했음에도 불과하고 Open API 인증이 실패했다고 뜹니다.

API를 신청할 때 비로그인 API 환경에서 안드로이드 앱 패키지명만 입력했는데 웹 사이트 URL도 같이 입력을 해야하나요? 입력해야 한다면 어떤 주소를 입력해야하나요?(웹 사이트가 아니라 애플리케이션이라 URL이 필요없을거 같아서 일단 비워놓고 신청했었습니다.)

하이브리드 앱에 네이버 지도 API가 적용된 사례를 찾지 못해서 궁금합니다.

(수정추가) api 신청 시 비로그인 오픈 api 서비스 환경에서 웹 서비스 URL에 file:///android_asset/www/index.html 이런식으로 하이브리드 앱 시작 URL을 적어주니 지도는 나옵니다.

추가로 질문이 있는데 네이버 지도 앱처럼 제가 주소를 입력하여 검색하고 그 장소로 마커가 표시되도록 하려면 어떤 Example을 봐야하나요? 지도v3 홈페이지 문서를 봤는데 이와 관련된 부분이 없는 것 같아서 질문드립니다.

**Comment by boxersb** [comment]
@kdu0801 안녕하세요? 개발자센터에서 애플리케이션 등록시 웹 사이트 URL을 입력하도록 되어 있는데요..
말씀하신것처럼, file:/// url을 입력해주시면 인증이 잘 됩니다.

추가 질문주신 주소->좌표 API는 https://developers.naver.com/docs/map/overview 페이지에서 `3.2. 주소 -> 좌표 변환 API (geocode API)` 항목을 참고 부탁드립니다.

감사합니다.
