### ISSUE TITLE
좌표계 변환하기 예제안되는데요????????????????

### ISSUE THREAD

**Issue by kyungjoongo** [navermaps/maps.js#130]
좌표계 변환하기 예제 애러나요
Geocoder 서브모듈의 TransCoord 객체를 사용한 좌표계 변환 예제입니다.
(https://navermaps.github.io/maps.js/docs/tutorial-1-geocoder-transcoord.example.html)

##애러코드
Uncaught TypeError: Cannot read property 'fromLatLngToUTMK' of undefined
    at t.initGeocoder [as onJSContentLoaded] (geo_map.html:25)
    at n (maps.js:14)
    at maps.js:14

**Comment by thetaiz** [comment]
@kyungjoongo 님, https://navermaps.github.io/maps.js/docs/tutorial-1-geocoder-transcoord.example.html 요 페이지가 에러가 나는건 아니죠? 확인해 보니 정상적으로 동작하고 있습니다. @kyungjoongo 님이 사용하고 있는 geo_map.html 코드를 보여주시면 확인하는데 도움이 되겠습니다.

**Comment by kyungjoongo** [comment]
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
  <title>간단한 지도 표시하기</title>
  <script
    src="https://code.jquery.com/jquery-2.2.4.js"
    integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
    crossorigin="anonymous"></script>
  <script type="text/javascript"
          src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=fZRvViGHXfpSnDAPx11j"></script>
</head>
<body>
<div id="map" style="width:80%;height:800px;"></div>


<script>
  var map = new naver.maps.Map("map", {
      center: new naver.maps.LatLng(37.376208137, 127.1143300127),
      zoom: 11
    }),
    infoWindow = null;

  function initGeocoder() {
    var latlng = map.getCenter();
    var utmk = naver.maps.TransCoord.fromLatLngToUTMK(latlng); // 위/경도 -> UTMK
    var tm128 = naver.maps.TransCoord.fromUTMKToTM128(utmk);   // UTMK -> TM128
    var naverCoord = naver.maps.TransCoord.fromTM128ToNaver(tm128); // TM128 -> NAVER

    infoWindow = new naver.maps.InfoWindow({
      content: ''
    });

    map.addListener('click', function (e) {
      var latlng = e.coord,
        utmk = naver.maps.TransCoord.fromLatLngToUTMK(latlng),
        tm128 = naver.maps.TransCoord.fromUTMKToTM128(utmk),
        naverCoord = naver.maps.TransCoord.fromTM128ToNaver(tm128);

      utmk.x = parseFloat(utmk.x.toFixed(1));
      utmk.y = parseFloat(utmk.y.toFixed(1));

      infoWindow.setContent([
        '<div style="padding:10px;width:300px;font-size:14px;line-height:20px;">',
        '<strong>LatLng</strong> : ' + latlng + '<br />',
        '<strong>UTMK</strong> : ' + utmk + '<br />',
        '<strong>TM128</strong> : ' + tm128 + '<br />',
        '<strong>NAVER</strong> : ' + naverCoord + '<br />',
        '</div>'
      ].join(''));

      infoWindow.open(map, latlng);
    });
  }

  naver.maps.onJSContentLoaded = initGeocoder;

</script>
</body>
</html>

**Comment by kyungjoongo** [comment]
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
  <title>간단한 지도 표시하기</title>
  <script
    src="https://code.jquery.com/jquery-2.2.4.js"
    integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
    crossorigin="anonymous"></script>
  <script type="text/javascript"
          src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=fZRvViGHXfpSnDAPx11j"></script>
</head>
<body>
<div id="map" style="width:80%;height:800px;"></div>


<script>
  var map = new naver.maps.Map("map", {
      center: new naver.maps.LatLng(37.376208137, 127.1143300127),
      zoom: 11
    }),
    infoWindow = null;

  function initGeocoder() {
    var latlng = map.getCenter();
    var utmk = naver.maps.TransCoord.fromLatLngToUTMK(latlng); // 위/경도 -> UTMK
    var tm128 = naver.maps.TransCoord.fromUTMKToTM128(utmk);   // UTMK -> TM128
    var naverCoord = naver.maps.TransCoord.fromTM128ToNaver(tm128); // TM128 -> NAVER

    infoWindow = new naver.maps.InfoWindow({
      content: ''
    });

    map.addListener('click', function (e) {
      var latlng = e.coord,
        utmk = naver.maps.TransCoord.fromLatLngToUTMK(latlng),
        tm128 = naver.maps.TransCoord.fromUTMKToTM128(utmk),
        naverCoord = naver.maps.TransCoord.fromTM128ToNaver(tm128);

      utmk.x = parseFloat(utmk.x.toFixed(1));
      utmk.y = parseFloat(utmk.y.toFixed(1));

      infoWindow.setContent([
        '<div style="padding:10px;width:300px;font-size:14px;line-height:20px;">',
        '<strong>LatLng</strong> : ' + latlng + '<br />',
        '<strong>UTMK</strong> : ' + utmk + '<br />',
        '<strong>TM128</strong> : ' + tm128 + '<br />',
        '<strong>NAVER</strong> : ' + naverCoord + '<br />',
        '</div>'
      ].join(''));

      infoWindow.open(map, latlng);
    });
  }

  naver.maps.onJSContentLoaded = initGeocoder;

</script>
</body>
</html>

**Comment by kyungjoongo** [comment]
코드입니다 포멧팅이 안되서 죄송.확인부탁드림.

**Comment by kyungjoongo** [comment]
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
  <title>간단한 지도 표시하기</title>
  <script
    src="https://code.jquery.com/jquery-2.2.4.js"
    integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
    crossorigin="anonymous"></script>
  <script type="text/javascript"
          src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=fZRvViGHXfpSnDAPx11j"></script>
</head>
<body>
<div id="map" style="width:80%;height:800px;"></div>


<script>
  var map = new naver.maps.Map("map", {
      center: new naver.maps.LatLng(37.376208137, 127.1143300127),
      zoom: 11
    }),
    infoWindow = null;

  function initGeocoder() {
    var latlng = map.getCenter();
    var utmk = naver.maps.TransCoord.fromLatLngToUTMK(latlng); 
    var tm128 = naver.maps.TransCoord.fromUTMKToTM128(utmk);   
    var naverCoord = naver.maps.TransCoord.fromTM128ToNaver(tm128); 

    infoWindow = new naver.maps.InfoWindow({
      content: ''
    });

    map.addListener('click', function (e) {
      var latlng = e.coord,
        utmk = naver.maps.TransCoord.fromLatLngToUTMK(latlng),
        tm128 = naver.maps.TransCoord.fromUTMKToTM128(utmk),
        naverCoord = naver.maps.TransCoord.fromTM128ToNaver(tm128);

      utmk.x = parseFloat(utmk.x.toFixed(1));
      utmk.y = parseFloat(utmk.y.toFixed(1));

      infoWindow.setContent([
        '<div style="padding:10px;width:300px;font-size:14px;line-height:20px;">',
        '<strong>LatLng</strong> : ' + latlng + '<br />',
        '<strong>UTMK</strong> : ' + utmk + '<br />',
        '<strong>TM128</strong> : ' + tm128 + '<br />',
        '<strong>NAVER</strong> : ' + naverCoord + '<br />',
        '</div>'
      ].join(''));

      infoWindow.open(map, latlng);
    });
  }

  naver.maps.onJSContentLoaded = initGeocoder;

</script>
</body>
</html>

**Comment by kyungjoongo** [comment]
zip파일압축

**Comment by thetaiz** [comment]
@kyungjoongo 님, 위 코드로 확인해 보겠습니다. ^^

**Comment by thetaiz** [comment]
@kyungjoongo 님, 좌표변환을 이용하려면 Geocoder 서브모듈을 함께 로드해야 합니다. 아래 튜토리얼을 참고해 주세요. 그리고 정보 창에 넣는 콘텐츠 문법 오류도 확인 부탁드려요~ 

- https://navermaps.github.io/maps.js/docs/tutorial-Geocoder.html

**Comment by thetaiz** [comment]
@kyungjoongo 님, 문제가 해결되었나요? ^^

**Comment by kyungjoongo** [comment]
잘됩니다 ^^ 감사합니둥
