### ISSUE TITLE
marker rotate 관련

### ISSUE THREAD

**Issue by joshuayun** [navermaps/maps.js#131]
url을 통해 마커이미지를 생성후

그린 marker를 회전시키고 싶은데요..

marker 회전메소드는 따로 구현이 되지 않아

marker 의 id값을 가져와서 회전시키는 방법을 구현하고자합니다.

마커 회전메소드가없다면, html 소스로 id값을 얻는 방법은 없을까요?

**Comment by thetaiz** [comment]
@joshuayun 님, 우선 마커에 아이디를 부여하고 싶으시다면...(Open API에서 넣는 아이디 외) 마커를 생성할 때 아래와 같이 옵션에 넣어주시면 해당 아이디를 marker.custom_id와 같이 접근해 이용할 수 있습니다.

`
var marker = new naver.maps.Marker({
  position: myLatlng,
  map: map,
  title: 'Hello World!',
  custom_id: 11111
});
`

**Comment by thetaiz** [comment]
@joshuayun 님, 해결이 되셨나요?

**Comment by joshuayun** [comment]
제가 말씀드린건 html 안의 id 값을 말씀드린거라 htmlImage로 변경하여 maker값을 구현하여 해결하였습니다.

**Comment by thetaiz** [comment]
넵, 이슈를 닫겠습니다.
