### ISSUE TITLE
InfoWindow 관련 문의

### ISSUE THREAD

**Issue by joshuayun** [navermaps/maps.js#132]
새로운 InfoWindow 객체를 만들고
InfoWindow .open(Map, Marker);
함수를 호출하면 자동으로 SetCenter 처럼 화면이 이동하는데
InfoWindow  객체를 만들고 open할때 SetCenter 가 안되게 할수 있는 방법은 없나요?

**Comment by thetaiz** [comment]
@joshuayun 님, 정보 창은 기본적으로 정보 창이 잘 보이도록 위치를 조정하고 있습니다. 정보 창 생성 시 옵션 `disableAutoPan`을 `true`로 설정하면 동작하지 않습니다.
