### ISSUE TITLE
fromPointToCoord 함수 오차 문의드립니다.

### ISSUE THREAD

**Issue by shchoung** [navermaps/maps.js#134]
아래소스에서 타일 레이어의 bbox의 좌표를 받아오는 과정에서
fromPointToCoord 함수를 거쳐 나온 결과값이 포인트별 오차가 발생하여 문의드립니다.
 getTile: function(x, y, z) {
	                    var lbPoint = new N.Point(x * this.tileSize.width, (y+1) * this.tileSize.height),
	                        rtPoint = new N.Point((x+1) * this.tileSize.width, y * this.tileSize.height),
	                        normalizedLbPoint = p.scaleDown(lbPoint, z),
	                        normalizedRtPoint = p.scaleDown(rtPoint, z),
	                        
	                        lb = p.fromPointToCoord(normalizedLbPoint),
	                        rt = p.fromPointToCoord(normalizedRtPoint),
	                        bbox = [lb.x, lb.y, rt.x, rt.y];
}
예를 들어서
(124.609375,186.1015625 ) -->  (128.7287196,35.8798**477**)
(124.625,186.1015625)  --> (128.7301373,35.8798**332**)
같은 y값을 변환하여서 결과값이 오차가 발생합니다. 
가능하시다면 답변 또는 해결 부탁드립니다.

**Comment by thetaiz** [comment]
@shchoung 님, 세계좌표를 지도좌표(경위도좌표계)로 변환할 때 UTMK 좌표 변환을 사용합니다. 위도 좌표를 계산할 때 `x`를 축척 계수 등으로 나눈 값을 이용하는 공식이 있습니다. `x` 값에 영향을 받기 때문에 동일한 `y` 값이라도 위도 값이 다르게 나옵니다.

**Comment by junthus** [comment]
@shchoung 포인트 좌표계는 평면직교좌표계이고 경위도 좌표계는 구면 좌표계 이기 때문에 x,y중 한 값이 같다고 같은 값으로 서로 변환되지 않습니다. 아래 그림 참고하시면 이해가 쉬우실둣 합니다. 

![image](https://cloud.githubusercontent.com/assets/5088669/25177802/22e414e8-253e-11e7-9a83-fceb3f5ebc68.png)

**Comment by shchoung** [comment]
답변 감사합니다. ^^
저 오차때문에 bbox 들 끼리 어긋나게 표현이 되네요~ㅠㅜ
![poi](https://cloud.githubusercontent.com/assets/27760904/25207625/fd984142-25aa-11e7-876a-5a8092e616c6.png)
혹시나 소숫점 자리를 보정하거나 또는 다른 해결 팁 있을까요?

**Comment by thetaiz** [comment]
@shchoung 님, 저희쪽에서 확인할 수 있게 접근할 수 있는 URL 또는 소스 코드를 알려주실 수 있으신가요? 공개가 어려우면 @junthus 님 메일로 보내주셔도 됩니다.

**Comment by shchoung** [comment]
죄송하지만 URL은 내부망이라 외부에서 접근이 불가합니다.  
소스 코드는 다음과 같고 지오서버의 레이어를 wms로 중첩하고 합니다. 

var map = new naver.maps.Map('map', {
    center: new naver.maps.LatLng(37.3595704, 127.105399),
    zoom: 10
});

var p = map.getProjection();

var tileGridLayer = new naver.maps.Layer('tileGrid', {
    name: "TileGrid",
    minZoom: -1,
    maxZoom: 14,
    tileSize: new naver.maps.Size(256, 256),
    getTile: function(x, y, z) {
        
      var lbPoint = new N.Point(x * this.tileSize.width, (y+1) * this.tileSize.height),
            rtPoint = new N.Point((x+1) * this.tileSize.width, y * this.tileSize.height),
            normalizedLbPoint = p.scaleDown(lbPoint, z),
            normalizedRtPoint = p.scaleDown(rtPoint, z),
            lb = p.fromPointToCoord(normalizedLbPoint),
            rt = p.fromPointToCoord(normalizedRtPoint),
            bbox = [lb.x, lb.y, rt.x, rt.y];

        // geoserver wms 
            var tilegrid = http://localhost/geoserver/cite/wms?layers=ex
            ...
            &SRS=ESPG:5179
            &BBOX=" +**lb.x +','+lb.y+','+rt.x+','+rt.y**+"
            &width=256
            &height=256

            return $('<img src=" + tilegrid +"/>')[0];
    }
});

tileGridLayer.setMap(map);

**Comment by junthus** [comment]
@shchoung 잘 이해가 안 되어서요 ㅜㅜ

![image](https://cloud.githubusercontent.com/assets/5088669/25230546/4f5e4198-260f-11e7-8ca6-9f205ac8fbc7.png)

이 그림은 어떤 데이터를 가지고 어떻게 그리신 건지 설명좀 부탁드려요 ㅋㅋㅋ

**Comment by shchoung** [comment]
아네.ㅎ
위코드에서 타일 그리드 레이어
의 좌표(lb.x, lb.y, rt.x, rt.y)를 추출하여 gis툴을 이용하여 포인트를 찍어본것이고 
빨간점은 원데이터 그대로이고
녹색점은 소수점을 네자리로 보정해본 결과입니다.

**Comment by thetaiz** [comment]
@shchoung 님, 해결이 되셨나요? 이슈를 닫으셔서 여쭤봅니다. ^^ 해결하셨다면 어떻게 하셨는지 공유를 부탁드립니다.

**Comment by shchoung** [comment]
ㅎㅎㅎ 답변이 없으셔서 내렸습니다~ 
샘플 이미지 하나 올릴께요~ 
![1](https://cloud.githubusercontent.com/assets/27760904/25426879/9f2624f2-2aab-11e7-948e-ffb9bd7e0100.png)

**Comment by thetaiz** [comment]
@shchoung 넵, 저희도 살펴보도 있습니다. 파악되면 공유를 드릴께요.

**Comment by thetaiz** [comment]
@shchoung 님, 네이버 지도 타일을 배경으로 브이월드의 지적도를 올려보았습니다. 지도 생성 시 프로젝션을 UTMK를 이용하도록 아래와 같이 수정해서 확인을 부탁드려요.

```js
var map = new naver.maps.Map('map', {
    center: new naver.maps.Point(965784, 1929680),
    zoom: 8
    mapTypeId: 'normal',
    mapTypes: new naver.maps.MapTypeRegistry({
        'normal': naver.maps.NaverMapTypeOption.getNormalMap({
            projection: naver.maps.UTMKCoord
        }),
        'terrain': naver.maps.NaverMapTypeOption.getTerrainMap({
            projection: naver.maps.UTMKCoord
        }),
        'satellite': naver.maps.NaverMapTypeOption.getSatelliteMap({
            projection: naver.maps.UTMKCoord
        }),
        'hybrid': naver.maps.NaverMapTypeOption.getHybridMap({
            projection: naver.maps.UTMKCoord
        })
    })
});
```

**Comment by thetaiz** [comment]
아~ 참고로 위와 같이 UTMK 프로젝션을 이용하고 브이월드의 지적도를 올리면 타일이 어긋나는 현상 없이 잘 보입니다. 단, 배경 지도와 레이어 간 딱 맞아 떨어지지는 않는데 그 부분은 저희쪽 타일 생성 시 사용한 데이터와 브이월드의 레이어 생성 시 사용한 데이터가 달라 발생한 것으로 보입니다. ^^

**Comment by thetaiz** [comment]
![grid_layer_mashup](https://cloud.githubusercontent.com/assets/1366046/25429129/f1570f78-2ab2-11e7-9e17-8523f0725a91.png)

**Comment by thetaiz** [comment]
@shchoung 님, 레이어가 어긋나는 것은 해결이 되셨나요?

**Comment by shchoung** [comment]
아고 메일 지금 확인했네요.
죄송해요~
저희쪽 지적도 좌표계를 WGS84기준
으로 사용하다보니 UTMK좌표로
사용할 수가 없네요.(보내주신 코드 테스트 해봤는데
지도가 나오지 않아요~)
저번에 답변 주신 평면직교와 구면좌표계
문제인거 같네요..ㅠㅜ
좌표계 변환만이 해결방안일까요?-----Original Message-----

**Comment by thetaiz** [comment]
@shchoung 님, SRS=EPSG:5179 요기요 그럼 WGS84 기준으로 레이어를 호출하는거죠? SRS=EPSG:5179 요렇게 되어 있어서 UTMK라고 생각해서요~ WGS84면 SRS=EPSG:4326으로 호출해야 할 것 같아서요.

**Comment by shchoung** [comment]
앗 넵. 그부분은 제가 잘 못 보냈네요.ㅎ
4326으로 호출하고 있습니다.~-----Original Message-----

**Comment by thetaiz** [comment]
넵, 그럼 다시 확인해 보겠습니다. ^^

**Comment by shchoung** [comment]
ㅎ 확인해보셨나요?

**Comment by thetaiz** [comment]
@shchoung 님, 늦어서 죄송합니다. ㅠㅠ 브이월드를 이용해 타일 인덱스를 가지고 생성한 위경도 좌표를 EPSG:3857로 설정해 보면 정상적으로 보이나, EPSG:4326에서는 레이어의 타일이 어긋나는게 있네요. 아무래도 좌표계 차이로 인해 발생하는 것 같아요 ㅠㅠ 큰 도움을 드리지 못해 죄송합니다.

**Comment by shchoung** [comment]
ㅠㅜ 네 알겠습니다. 그럼 이슈는 내리겠습니다.

**Comment by thetaiz** [comment]
@shchoung 님, 구글 지도 Open API를 이용해 시도해보았으나 네이버 지도와 동일하게 타일이 어긋나거나 중복(?)되어 겹치는 문제가 발생하고 있습니다. 반대로 네이버 지도 세계지도, 네이버 지도에 아래와 같이 OpenLayers WMS를 이용해 올려보면 EPSG:4326이나 정상적으로 나오고 있습니다. 참고해 주세요~ ^^

- http://www.gisdoctor.com/v3/openlayers_wms.html

**Comment by shchoung** [comment]
주신 URL소스에서 저희 지적도 WMS 올려서 테스트 해보니 역시 깔끔하게 잘 나오네요~ㅎ
![default](https://cloud.githubusercontent.com/assets/27760904/25989283/7261e018-3736-11e7-9cd3-107fd4a0941e.png)
위 네이버 지도 세계지도(?),
혹시 네이버 지도에서는 무리인가요? ^^

**Comment by shchoung** [comment]
네이버세계지도는
Api 있나요?-----Original Message-----

**Comment by thetaiz** [comment]
@shchoung 님, 네이버 세계지도는 현재 1 ~ 7 레벨 정도만 제공하고 있습니다. 아래 지도 유형을 참고해 주세요.

- https://navermaps.github.io/maps.js/docs/naver.maps.NaverMapTypeOption.html

그리고 구글 지도 위에 지적도를 올리신거죠? 음.. 해당 지적도를 저희쪽에서 올려볼 수 있으면 좋을 것 같습니다 ㅠㅠ

**Comment by shchoung** [comment]
@thetaiz 님 네이버 지도에 저희 지적도 중첩에 성공했네요. ^^
![ok](https://cloud.githubusercontent.com/assets/27760904/26671665/513bf89a-46f1-11e7-8f5f-48064387c0cf.png)

        lb = p.fromPointToCoord(normalizedLbPoint),
        rt = p.fromPointToCoord(normalizedRtPoint),
        
        var p1=WGS84To5179(lb.x, lb.y);  ///// 좌표 변환 //////
	var p2=WGS84To5179(rt.x, rt.y);
        
    // geoserver wms 
        var tilegrid = http://localhost/geoserver/cite/wms?layers=ex
        ...
        &SRS=ESPG:5179
        &BBOX=" +**p1.x +','+p1.y+','+p2.x+','+p2.y**+"
        &width=256
        &height=256
지적도레이어는 EPSG:4326 이지만 지오서버에서 호출할때 다시 변환 하는군요.
공유해드립니다~ 감사합니다.
