### ISSUE TITLE
HTML5 Geolocation API 마커 수정 방법

### ISSUE THREAD

**Issue by haewd2** [navermaps/maps.js#135]
안녕하세요. 질문 드립니다.

질문1. HTML5 Geolocation API 사용했는데 화면 중간에 현재 위치가 흰색 박스로 좌표와 함께 표시 됩니다.
흰색 박스를 이미지 마커등으로 교체 할 수 있나요?

질문2. Geolocation에서 getCurrentPosition을 사용했을 경우는 문제가 없는데 watchPosition를 사용했을 경우 아이폰 및 아이패드에서는 처음 한번 위치를 찾고난 후 두번째 부터는 onErrorGeolocation으로 애러 메세지를 띄웁니다. 안드로이드는 잘되는데 ... 어떤 문제인지요?

**Comment by thetaiz** [comment]
@haewd2 아래와 같이 답변을 드려요.

- 질문1: 현재 구현한 코드가 무엇인지 모르겠지만... ^^ 아마도 아래와 같은 예제 코드를 사용하신것으로 보입니다. 받아온 좌표를 이용해 마커의 위치를 갱신해 사용하면 됩니다. 

https://navermaps.github.io/maps.js/docs/tutorial-6-map-geolocation.example.html

- 질문2: 음... iOS10 이상에서는 위치 정보를 사용하려면 HTTPS를 사용해야 하는 것으로 파악이 됩니다. 혹시 이 이슈가 아닌지 확인을 부탁드려요.

구현한 코드를 볼 수 있는 URL 또는 소스 코드를 알려주시면 저희쪽에서 파악하는데 도움이 될 것 같습니다.

**Comment by thetaiz** [comment]
@haewd2 님, 혹시 이슈 해결이 되었나요?

**Comment by haewd2** [comment]
1번 질문은
https://navermaps.github.io/maps.js/docs/tutorial-6-map-geolocation.example.html
페이지 소스 맞구요. 
중간에 흰색 박스가 보기 싫어서 단순한 이미지 마커로 교체하고 싶은데 
아직 해결을 하지 못하였습니다.

2번 질문 드린 부분은 https 때문인것 같아서 watchPosition를 사용하지 않기로 하였습니다. ㅠ.ㅠ

**Comment by thetaiz** [comment]
@haewd2 님, 해당 예제 코드에서는 정보 창을 생성해서 노출해 주고 있습니다. 그걸 제거하고 마커 위치를 갱신하도록 코드를 넣어주면 됩니다.

**Comment by thetaiz** [comment]
@haewd2 님, 마커로 교체를 하셨나요?

**Comment by haewd2** [comment]
`var map = new naver.maps.Map('map', {
		center: new naver.maps.LatLng(35.746943, 128.207321),
		zoom : 6, // - 초기 줌 레벨은 10으로 둔다.
		enableWheelZoom : true,
		enableDragPan : true,
		enableDblClickZoom : false,
		mapMode : 1, //0으로 하면 초기 일반지도, 1로하면 초기 위성지도.
		activateTrafficMap : false,
		activateBicycleMap : false,
		minMaxLevel : [ 1, 14 ],
		zoomControl: true,
		scaleControl: true,
		mapTypeControl: true,
		mapTypeId: naver.maps.MapTypeId.HYBRID
	});`
