### ISSUE TITLE
EPSG:5186 좌표계 사용 가능 여부

### ISSUE THREAD

**Issue by special9486** [navermaps/maps.js#136]
안녕하세요~ 좌표계 관련하여 문의 드립니다.

제가 가지고 있는 데이터가 EPSG:5186 좌표계를 따르는 Point 데이터가 있습니다.
Naver 지도를 통해 해당 데이터를 표시하고자 하는데요 몇가지 질문 드릴게 있습니다.

1. EPSG:5186의 Point 데이터를 Naver에서 쓰는 위도, 경도로 변환하는 방법이 있을까요?
2. Naver에서 사용하는 좌표계는 무엇인가요? 인터넷에서 찾아보니 EPSG:5179로 나오던데 맞는건가요?

**Comment by thetaiz** [comment]
@special9486 님, 아래와 같이 답변드립니다.

1. 현재 EPSG:5186을 WGS84 경위도 좌표계로 변환하는 방법을 제공하고 있지 않습니다. 별도의 라이브러리를 이용해 WGS84 경위도 좌표계로 변환이 필요합니다.

2. 네이버 지도 Open API v3는 기본적으로 EPSG:5179 UTMK 프로젝션을 사용하고 있습니다(사실은 UTMK를 확장한 네이버 좌표계 프로젝션). 그러나 인터페이스에서 기본적으로 사용하고 있는 기본 좌표계는 WGS84 경위도 좌표계입니다. 아래 Geocoder 서브모듈의 튜토리얼을 보시면 이해가 쉬울 것 같습니다.

- https://navermaps.github.io/maps.js/docs/tutorial-Geocoder.html

**Comment by thetaiz** [comment]
@special9486 님, 궁금하신 부분이 해결이 되었나요?

**Comment by davidshimjs** [comment]
@special9486 proj4와 같은 모듈을 사용해서 사전에 좌표를 변환하셔서 사용하실 수 있습니다. 대부분의 지도 API가 wgs84 위경도 좌표를 사용하고 있습니다. 참고) https://github.com/temsa/node-proj4js

**Comment by special9486** [comment]
말씀해 주신대로 좌표 변환 작업을 해봐야 겠네요.
답변 감사드립니다.
