### ISSUE TITLE
마커관련 문의

### ISSUE THREAD

**Issue by lee-changmin** [navermaps/maps.js#138]
html 문서 내에서 마크 객체를 생성하고 위치값을 반환하려면 getPosition 함수를 쓰면 가능한데

드로잉 매니져를 사용해서 만든 마크 객체는 위치값을 얻으려면 어떻게 해야하나요.
이벤트 리스너를 통해 마크(오버레이)의 id와 유형을 얻는 것은 가능했지만

그 id에 해당하는 마크에 어떤 설정값을 줄 수 있는지 궁금합니다.

**Comment by junthus** [comment]
@lee-changmin 

드로잉 매니저를 사용해서 만들어진 마커는 기본 마커와 동일합니다. 그리고 이벤트 리스너를 통해 전달되는 객체가 해당 객체이므로 아래처럼 바로 `getPosition()`을 이용할 수 있고요, id를 통해 드로잉 매니저에서 찾아올 수도 있습니다. 
도움이 되시길 바랍니다 ^^ 감사합니다. 

![image](https://cloud.githubusercontent.com/assets/5088669/25787515/0ab4fa74-33dd-11e7-966e-a441b3110774.png)

**Comment by thetaiz** [comment]
@lee-changmin 님, 이슈 해결은 되었나요?
