### ISSUE TITLE
500error 문의

### ISSUE THREAD

**Issue by specialclock** [navermaps/maps.js#139]
지도 연동 테스트를 하려고 어플리케이션 등록하여 클라이언트아이디 부여받고 예제소스를 돌려보는데 이부분에서 계속 에러가 납니다. 

-소스-

`<script` type="text/javascript" `src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=클라이언트아이디"></script>`    
    `<script `type="text/javascript">`
        `var` mapOptions = `{`
           `center: new naver.maps.LatLng(37.3595704, `127.105399),`
            `zoom: 10`
        `}`

        `var map = new naver.maps.Map('map', `{`
            center: new naver.maps.LatLng(37.3595704, 127.105399),
            zoom: 10
        });       
    </script>`

`<div` id="map" `style="width:100%;height:400px;"></div>`

--에러메시지--
HTTP500: SERVER ERROR - 서버에서 요청을 수행할 수 없도록 하는 예기치 않는 조건이 발생했습니다.
GET - http://openapi.map.naver.com/v1/validatev3?clientId=클라이언트아이디&uri=유알엘&time=1494313737143

혹시 지금 서버에 무슨 문제가 있는건지 아니면 제가 빼먹은게 있는지 문의드립니다.

**Comment by thetaiz** [comment]
@specialclock 님, 네이버 개발자 센터에 등록한 URL이 "http://127.0.0.1"입니다. 근데 실제 사용한 URL은 "http://localhost"라서 인증이 실패했습니다. 네이버 개발자 센터에 localhost를 등록해 주시면 됩니다.

**Comment by specialclock** [comment]
바로 되네요!! 답변 감사합니다.

**Comment by thetaiz** [comment]
@specialclock 님, 잘 동작한다니 다행이네요~ 이슈는 닫겠습니다~ ^^
