### ISSUE TITLE
튜토리얼에 지도 컨트롤 부분 예제에 오류가 있습니다.

### ISSUE THREAD

**Issue by klover5** [navermaps/maps.js#14]
https://navermaps.github.io/maps.js/docs/tutorial-Controls.html

position: naver.maps.BOTTOM_RIGHT
를
position: naver.maps.Position.BOTTOM_RIGHT

으로 5가지 예제 전부 바꿔야 합니다.

**Comment by boxersb** [comment]
@klover5 제보 감사합니다 ^^ 즉시 수정해두도록 하겠습니다~

**Comment by boxersb** [comment]
@klover5 안녕하세요? 수정내용 반영 완료했습니다. 감사합니다~~
