### ISSUE TITLE
확대 축소 중앙기준점 질문입니다.

### ISSUE THREAD

**Issue by knu0313** [navermaps/maps.js#140]
모바일 웹에서 지도영역을 css에 transform:scale(2);로잡으니 중앙점이 우측 하단으로 잡히는 문제가 발생합니다 해결방법이 없을까요?

**Comment by thetaiz** [comment]
@knu0313 님, 확인 후 알려드리겠습니다. 근데 스케일을 조정한 이유가 있나요?

**Comment by knu0313** [comment]
고해상도 화면이라 지도를 최대로 확대해도 너무 작게 나와서요
혹시 스케일 사용하지않고 고해상도에서 크게 볼수 있는방법은 없을까요?

**Comment by thetaiz** [comment]
@knu0313 님, 혹시 사용하는 브라우저, OS 환경 등이 어떻게 되는지 궁금합니다. 또한 저희쪽에서 확인할 수 있는 URL이 있으면 더 좋구요. 해상도에 따라 내부적으로 고해상도 지도 타일을 이용하도록 되어 있습니다. 따라서 @knu0313 님이 직접 수정하지 않으셔도 됩니다.

**Comment by knu0313** [comment]
그리고 zoom:2으로 잡을경우에는 첫화면은 중앙이 잘잡히는데 확대 축소시 줌되기전에 화면을 기준으로 잡혀서 그런지 중앙점이 우측으로 쏠리는 현상있네요

**Comment by knu0313** [comment]
외부에서 접속할수가 없네요 ㅜ

**Comment by knu0313** [comment]
갤럭시노트5 기본 브라우져 사용해서 확인하고있습니다.

**Comment by thetaiz** [comment]
@knu0313 안드로이드 버전도 부탁드려요~ ^^

**Comment by thetaiz** [comment]
@knu0313 님, HTML 마크업 구조도 알려주시면 빠르게 확인이 가능하겠네요~ ^^

**Comment by knu0313** [comment]
<meta name="viewport" content="width:device-width,initial-scale=0.25,user-scale=no">

<div style="height:900px;position:relative">
	<div style="position:absolute;transform:scale(2);width:100%;height:450px;top:225px;left:0">
	 scale 사용 지도영역
	</div>
</div>

<div style="height:900px">
	<div style="zoom:2;width:100%;height:100%;">zoom 사용 지도</div>
</div>
폰으로 작성하느라 좀걸렸네요
대략 구조는 이렇고 노트5 안드로이드 6.0.1, 아이폰6으로 테스트 했는데 둘다 동일한 문제가 발생하네요. 답변부탁드립니다 ㅜ

**Comment by knu0313** [comment]
&lt;

**Comment by thetaiz** [comment]
@knu0313 님, 아래 예제도 동일하게 그렇게 보이는지 확인을 부탁드려요. 저희쪽에서 확인해보면 정상적으로 나오고 있습니다.

- https://navermaps.github.io/maps.js/docs/tutorial-1-map-simple.example.html

**Comment by knu0313** [comment]
&lt;meta name="viewport" content="width:device-width,initial-scale=0.25,user-scale=no"&gt;

&lt;div style="height:900px;position:relative"&gt;
	&lt;div style="position:absolute;transform:scale(2);width:100%;height:450px;top:225px;left:0"&gt;
	 스케일 사용 지도영역
	&lt;/div&gt;
&lt;/div&gt;

&lt;div style="height:900px"&gt;
	&lt;div style="zoom:2;width:100%;height:100%;"&gt;zoom code 사용지도&lt;/div&gt;
&lt;/div&gt;

**Comment by knu0313** [comment]
소스다시올려요 뷰포트가0.25라서요

**Comment by knu0313** [comment]
해당페이지는 정상적으로 나와요

**Comment by thetaiz** [comment]
@knu0313 님, initial-scale을 0.25로 하신 이유가 있나요? 해당 값을 1로 두고 transform:scale(2), zoom:2를 제거하면 정상적으로 나올 거에요.

**Comment by knu0313** [comment]
그걸 변경할수가 없어서 질문드리는거에요... ㅜㅜ

**Comment by knu0313** [comment]
방법이 없을까요?

**Comment by junthus** [comment]
@knu0313 안녕하세요. 

기본적으로 지도 div에 transform 등의 변환을 거는 것은 지원하지 않습니다.
가장 좋은 방법은 viewport scale 을 1로 두는 아주 일반적인 방법이 있겠으나... 
그게 불가능하시다니 저희도 당장 보증할 수 없는 방법으로 도와 드릴 밖에 없는 점 확인 부탁드려요.

0.25배 축소된 화면에서 정상적으로 동작하는 배경만이라도 의미가 있다면 지도 div를 transfrom:scale(n)제거하고 타일 크기를 늘려주는 방법이 그나마 나을 듯 합니다. (물론 줌 컨트롤, 지도 타입 컨트롤은 확대되지 않습니다.)

이렇게 구현된 코드는 업데이트에 의해 어느 순간 동작하지 않을 수도 있고 메모리를 상당히 쓸 지도 모르겠네요...
그럼에도 불구하고 필요하시면 ㅠ 사용하시기 바랍니다. 

```js
var map = new naver.maps.Map("map", {
    mapTypes: new naver.maps.MapTypeRegistry({
        normal: naver.maps.NaverMapTypeOption.getNormalMap({
            tileSize: [256 * 4, 256 * 4] // 기본 사이즈는 256 입니다. 고로 네 배 확대한 것입니다. 
        })
    }),
    mapTypeId: 'normal'
});
```

위 코드에 대한 추가적인 내용이 궁금하시면 [이 페이지](https://navermaps.github.io/maps.js/docs/naver.maps.NaverMapTypeOption.html)를 참고해주세요.

**Comment by junthus** [comment]
@knu0313 확인해보니 구글지도는 문제없이 동작하는 듯 합니다. 구글지도를 사용하시는것도 해당 환경에선 방법이 될 듯 하네요..

**Comment by knu0313** [comment]
잘되네요 감사합니다^^

**Comment by thetaiz** [comment]
@knu0313 님, 잘 동작한다니 다행이네요~ 이슈는 닫겠습니다.
