### ISSUE TITLE
저에게는 레이어가 보이지 않습니다...

### ISSUE THREAD

**Issue by mlmlmlm** [navermaps/maps.js#141]
질문 글을 다시 작성하겠습니다...

**Comment by boxersb** [comment]
@mlmlmlm 확인 가능한 github 저장소나, url 등이 있으신가요..?

그리고, Chrome 에서 확인 시 Console 에 오류 메세지등이 나오는것이 있으면 공유 부탁드립니다.

**Comment by mlmlmlm** [comment]
https://navermaps.github.io/maps.js/전체를 외장형 하드디스크 root directory에 두었는데,
제가 github를 처음 써봐서 github 에 저장하는 방법을 모릅니다. TT
chrome 상에서 오류메시지는 나타나지 않았습니다. 그냥 제 기능이 안나타날 뿐입니다...

**Comment by boxersb** [comment]
저희가 확인을 할 수가 없어서.. 도움을 드리기가 어려울것 같군요..

Open API ClientId 를 발급받아서, 인증은 성공 하신건지요..?

**Comment by cs09g** [comment]
혹시 네이버 개발자센터에서 키발급등의 과정없이 단순히 지금 이 리포지토리의 데이터만으로 지도를 띄우려고 하신건가요?

**Comment by mlmlmlm** [comment]
아, 네... 
인증키는 발급 받은 상태입니다. 감사합니다.
example code에 나와 있는 Client ID 대신에, 제가 발급받은 Client ID를 대신 바꿔 넣었습니다.
github 사용법을 얼른 익혀서 제가 어떻게 했는지 보여드리겠습니다.

**Comment by mlmlmlm** [comment]
안녕하세요?
저의 github의 mlmlmlm/NaverMap/에 제가 작업한 코드를 올려놨습니다.
(혹시 안보이시나요?)
Naver의 example 코드에서 인증키만 바꾼 것입니다만,
https://navermaps.github.io/maps.js/docs/tutorial-digest.example.html
에서 볼 수 있는 기능들이 제가 인증키만 바꾼 코드에서는 작동하지 않는 경우도 있고 작동하는 경우도 많은 것 같습니다. 또한 PC마다 되거나 안되는 현상이 다른 것 같습니다.
(코드의 문제보다는 제가 모르고 있는 것들이 있어서 그럴 것 같습니다...)

예를 들면 NaverMap/examples/datalayer/에 있는 것들은 제가 시험해본 2개의 PC 모두에서 작동하지 않았고
mlmlmlm/NaverMap/examples/visualization/에 있는 것들도 2개의 PC 모두 작동하지 않았습니다.
특히, mlmlmlm/NaverMap/examples/visualization/에 있는 것들은 인증키를 기입하는 부분도 포함되지 않습니다만, 
https://navermaps.github.io/maps.js/docs/tutorial-4-visualization-heatmap-w.example.html에서 볼 수 있는 것처럼 작동하려면 어떻게 해야하는지요...

**Comment by junthus** [comment]
@mlmlmlm 올려주신 다른 이슈에서 이어가겠습니다, 이 이슈는 클로징 할게요.
