### ISSUE TITLE
지도 위 기본 커서모양 변경 문의

### ISSUE THREAD

**Issue by isbncd89** [navermaps/maps.js#142]
안녕하세요 . 네이버 지도를 사용하는 중에 문의가 있어 글을 남깁니다.
다름이 아니라 네이버 지도위에 기본적으로 표현되고 있는 커서모양(=손모양)을 크기와 모양을 바꿀수가 있는지 궁금합니다.

저희 시스템의 해상도가 커서 멀리서는 마우스의 포인터가 보이질 않아서 그렇습니다.
방법이 있을지 문의 드립니다.

**Comment by thetaiz** [comment]
@isbncd89 님, 해당 기능은 제공하지 않습니다. ㅠㅠ
