### ISSUE TITLE
panToBounds에 margin 설정 기능

### ISSUE THREAD

**Issue by hyeonseok** [navermaps/maps.js#143]
fitBounds처럼 panToBounds에도 margin이 설정 가능했으면 좋겠어요.

**Comment by boxersb** [comment]
@hyeonseok 님 안녕하세요?
해당 기능의 추가를 검토해보도록 하겠습니다. 의견 감사합니다~

@thetaiz 검토 부탁드려요~~

**Comment by thetaiz** [comment]
@hyeonseok 님, 차주 목요일 정기 업데이트에 반영될 예정입니다.

**Comment by hyeonseok** [comment]
우와 광속업데이트 짱입니다.

**Comment by junthus** [comment]
@hyeonseok 배포되었습니다. 확인 부탁드려요 ~
