### ISSUE TITLE
example 코드에 대한 문의

### ISSUE THREAD

**Issue by mlmlmlm** [navermaps/maps.js#144]
안녕하세요?
이전에 썼던 질문글을 정리했습니다.

https://navermaps.github.io/maps.js/docs/tutorial-digest.example.html
에서 볼 수 있는 기능들이 제가 인증키만 바꾼 코드에서 작동 여부가 PC마다 다른 것 같습니다.

예를 들면, /examples/datalayer/에 있는 코드들은 제가 시험해본 2개의 PC (각각, Windows 7과 Windows 10에서 Chrome, IE를 사용) 모두에서 작동하지 않았고
/examples/visualization/에 있는 코드들은 2개의 PC 모두에서 작동하지 않았습니다.

한쪽 PC에서 maps.js/examples/datalayer/1-datalayer.html
을 실행하면
https://navermaps.github.io/maps.js/docs/tutorial-1-datalayer.example.html
에 보이는 것과 똑같은 지도가 나타는데

마커, 빨간색의 NAVER라는 글씨, 빨간 선 같은 부가적인 레이어가 보이지 않고
지도의 하단에 line 28 이하의 코드가 보입니다.
(그런데 line 28 이하의 코드는 https://navermaps.github.io/maps.js/docs/tutorial-1-datalayer.example.html에서도 보이네요. 보여도 되는 것인가요?)

사실 maps.js/examples/ 하의 모든 html 파일들이 제가 시험한 PC들에서는 이런 식으로 지도만 보이고 부가기능은 작동하지 않았습니다.

추가로 궁금한 것은, /examples/visualization/에 있는 것들은 인증키를 기입하는 부분도 포함되지 않습니다만,
https://navermaps.github.io/maps.js/docs/tutorial-4-visualization-heatmap-w.example.html에서 볼 수 있는 것처럼 작동하려면 어떻게 해야하는지요...

.js 파일들은 적절한 상대적 경로 상의 폴더에 위치해 있습니다.

제가 example 코드 상에서 client id 외에 더 고쳐야 할 부분이 있거나 PC나 web browser의 설정을 바꾸거나 추가로 설치해야 할 프로그램이 있는 것인지요.

**Comment by cs09g** [comment]
github 의 코드는 가이드 페이지를 위한 것이므로, 코드를 그대로 다운 받아 사용하시는 것 보다(이럴 경우 지도 외에 가이드 페이지 자체를 구성하는 추가적인 부분이 많으므로) 가이드 페이지의 지도 하단에 첨부된 코드만 참고하시는게 좋습니다. 아래 링크는 jsfiddle 도메인으로 테스트 키를 발급받아 작성한 예입니다.
https://jsfiddle.net/k7k4d0w4/1/

**Comment by junthus** [comment]
@mlmlmlm 앗 확인이 늦어 죄송합니다. 바로 확인해볼게요 !

**Comment by junthus** [comment]
@mlmlmlm 아마 도메인 문제일 것으로 생각됩니다. 

문의주신 데이터 레이어나 히트맵 예제는 데이터 파일이 따로 존재하기 때문에, 페이지 내에서 해당 데이터 파일을 불러오게 되어 있는데요. file:// 프로토콜 사용하고 계신다면 cross origin 문제가 생깁니다. 간단한 웹서버를 로컬 환경에 띄우셔서 확인하시면 정상 작동할 듯 합니다. ^^

그리고 line28? 은 아마 하단에 보이는 코드를 말씀하시는 듯 한데요, 그 부분은 API 사용에 참고하시라고 부러 노출하고 있습니다. 

아래 스샷은 http://localhost:8000 웹서버에서 예제를 돌려본 모습입니다. 혹시 도메인 문제가 아니라면 다시 코멘트 주세요 ~ !
![image](https://cloud.githubusercontent.com/assets/5088669/26397136/432c7cbc-40b0-11e7-9ea9-39c360ec37ca.png)

**Comment by junthus** [comment]
@mlmlmlm 혹시 웹서버를 띄우기가 번거로운 상황이라면 아래처럼 script 태그로 로딩하시면 file:// 프로토콜에서도 잘 작동합니다.

![image](https://cloud.githubusercontent.com/assets/5088669/26397637/f3e476f8-40b1-11e7-9a50-314bc28d2c6d.png)
