### ISSUE TITLE
네이버지도 마커 갯수에 따른 표시 문제

### ISSUE THREAD

**Issue by changsunwon** [navermaps/maps.js#145]
안녕하세요 이전에도 문의드렸었던 사람입니다.
시스템 특성상 마커의 갯수가 떄에 따라서 갯수가 많을수 있습니다. 1000~2000개 마커 동시 표출도 예상가능.

[문제현상]
서울역 중심으로 왼쪽에는  마커가 표시 안되고, customOverlay html팝업을 띄웠을시 서울역 중심 왼쪽으로 드래그시 레이어가 뒤로 숨는현상 발생
테스트 결과 약 400개 정도의 마커는 정상 작동하나 500 개 이상 의 마커 표출시 위의 문제 현상 발생

[동작환경]
브라우저 : 크롬
해상도 : 5760x2160  (실제 어플리케이션 동작 환경이 이 해상도여야 하며, 더 낮은 해상도에서는 문제 발생안함)
 
아마도 고해상도에서 다량의 마커 표시시 문제가 발생하면서 z-index 순서등의 이슈가 아닐까 예상되는데요 표시 마커갯수를 줄이거나 해상도를 낮추면 이런 현상이 발생안합니다. 

예전에 터치 버그로 고생했었는데 이번에도 이런 글을 올리게 되어 유감입니다.
서울시 중요 프로젝트에 네이버 지도를 채택해서 오픈임박한 시점에 이슈 발생되어 오픈 일정이 늦어질수 있는점 착안하셔서 빠른 답변 부탁드리겠습니다.

**Comment by thetaiz** [comment]
@changsunwon 저희가 재현할 수 있게 코드를 알려주실 수 있나요?

**Comment by changsunwon** [comment]
접속 : 211.57.200.151:8181
로그인 : digitalmayor / test123
인증후

문제가 되는 페이지
211.57.200.151:8181/realTimeCity/safetyInfoMain

줌인 1~2 레벨후 지도이동시 서울역 부근중심으로 좌측 cctv모양마커사라짐

*크롬에서 해상도를 5760 × 2160으로 설정후 테스트
긴급사항입니다

*대외비입니다 보안신경써주세요


2017. 5. 23. 오후 2:25에 "Yonghwan Lee" <notifications@github.com>님이 작성:

**Comment by boxersb** [comment]
@changsunwon 메일로 github comment 회신하신것 같은데.. github 에 코멘트가 등록이 됩니다. 

보안에 유의해달라고 하셔서 내용 확인 후 지웠습니다. 양해 바랍니다.

**Comment by changsunwon** [comment]
신경써주셔서 감사드립니다

조속한 확인이 필요한 시점입니다 ㅜ

부탁드리겠습니다

2017. 5. 23. 오후 4:39에 "Kyoungtaek Koo" <notifications@github.com>님이 작성:

**Comment by thetaiz** [comment]
@changsunwon 재현은 했으며, 어떤 이슈인지 확인 중입니다. 보다 정확한 내용은 내일 정도 공유를 드릴 수 있을 것 같아요. 

크롬에서는 엄청나게 큰 해상도에서 가운데를 기준으로 왼쪽편을 제대로 렌더링하지 못하는 것을 확인했습니다. 마커 엘리먼트는 정상적으로 위치해 있고, 가지고 있어야 할 CSS 속성도 제대로 가지고 있었지만, 왼쪽편의 것을 제대로 그리지 못하고 있습니다. 예를 들어, 배경 컬러를 변경해도 오른쪽편만 적용이 되는...

우선은 윈도우를 사용하고 있다면 엣지 브라우저를 사용해 주세요. 해당 브라우저에서는 정상적으로 동작하는 것을 확인했습니다.

**Comment by changsunwon** [comment]
크롬은 안됩디다
크로스브라이징표방 네이버 지도였습니다
그리고 문제점도 파악하신 시점에 서울시 브라우저를 타브라우저를 바꾸라는건 조금 적절치못합니다

그리고 하나더 제가 3차례 트러블슈팅 요청시마다 이슈가 된 쟁점은 zinex고 그것은 우리를 다음 혹은 구글로 변경하고자 고민한
주요사안입니다 부디 우리를 네이버지도로 완주하게 하십시요

2017. 5. 23. 오후 9:44에 "Yonghwan Lee" <notifications@github.com>님이 작성:

**Comment by changsunwon** [comment]
트래킹 요청 몇시간후 타브라이저 사용권장은 옳지않습니다
재고 해주세요

사이드인팩이 심각합니다 그이유는 크롬의 웻킷엔진입니다 그걸 대처할 자신이있는지요?

2017. 5. 23. 오후 10:07에 "유툽cs" <chang.sun.won@gmail.com>님이 작성:

**Comment by changsunwon** [comment]
내일은 유쾌하게서로 대화하길바랍니다

2017. 5. 23. 오후 10:09에 "유툽cs" <chang.sun.won@gmail.com>님이 작성:

**Comment by boxersb** [comment]
@changsunwon 님.. 말씀이 너무 지나치시네요..

저희는 @changsunwon 님이 급하게 문의를 주셔서 다른 업무를 제쳐두고 최선을 다해 고해상도의 실제 기기를 공수하고 원인을 파악해서 공유드렸습니다.  
그리고, 그 대안으로 다른 브라우저에서는 정상적으로 표현되니 브라우저를 변경하여 테스트 해주십사 요청을 드린것입니다.

이 프로세스에 문제가 있었는지요..?  

정상적인 코드의 흐름이고, 단지 높은 해상도와 많은 수의 오브젝트에 의한 특정 브라우저에서 발생하는 이슈라고 판단하여 말씀을 드린것입니다.  크롬의 blink 렌더링 엔진 또는 크롬 자체의 버그인것으로 보입니다.

단기간에 지도 API 자체의 코드 수정으로 해결책을 제시해드릴 수 없기 때문에, 브라우저 교체외에는 더 드릴 말씀이 없으며.. 이 답변에 만족하지 않으신다면.. 저희는 더 이상 고객 지원을 해드릴 수 없습니다.

만약, 다음 지도 API 또는 구글 지도 API를 사용하였을때 동일한 환경의 크롬 브라우저에서 이 문제가 더 이상 발생하지 않을것이라고 판단되시면.. 지도 API 교체를 권해드립니다.  

프로젝트의 성공을 빕니다.

**Comment by changsunwon** [comment]
감정적으로 하자는게 아닙니다 다만 그동안 같은 개발자로써 트러블슈핑을 해온게 여러번인데 오히려 이것은 답장하시는분이 말씀이 지나치신거
같습니다


네이버지도를 쓰는 유저가 일반유저인가요?
아님 네이버지도 유저가 유료 유저인가요?
만일 답변주시는 분의 독단적 의견이시라면 제고 해주세요

그리고 하냐더 대한민국 대표 포털에서 고객센터로 깃허브로 남기라구해서 이런답변듣는다면 분명 우리 둘중 제고를 해야할 사항입니다


더이상 감정적 소모를 떠나서 문제 해결에 집중을 해주셰요
문제 현상
문제 파악
소스도 제공했습니다
빠른 문제 해결을 위해 힘을 모아주세요
문제해결이 아닌 감정 소모시는 원치않는 방향으로 가지는 건지 재문 합니다..

2017. 5. 23. 오후 10:46에 "Kyoungtaek Koo" <notifications@github.com>님이 작성:

@changsunwon <https://github.com/changsunwon> 님.. 말씀이 너무 지나치시네요..

저희는 @changsunwon <https://github.com/changsunwon> 님이 급하게 문의를 주셔서 다른 업무를
제쳐두고 최선을 다해 고해상도의 실제 기기를 공수하고 원인을 파악해서 공유드렸습니다.
그리고, 그 대안으로 다른 브라우저에서는 정상적으로 표현되니 브라우저를 변경하여 테스트 해주십사 요청을 드린것입니다.

이 프로세스에 문제가 있었는지요..?

정상적인 코드의 흐름이고, 단지 높은 해상도와 많은 수의 오브젝트에 의한 특정 브라우저에서 발생하는 이슈라고 판단하여 말씀을
드린것입니다. 크롬의 blink 렌더링 엔진 또는 크롬 자체의 버그인것으로 보입니다.

단기간에 지도 API 자체의 코드 수정으로 해결책을 제시해드릴 수 없기 때문에, 브라우저 교체외에는 더 드릴 말씀이 없으며.. 이
답변에 만족하지 않으신다면.. 저희는 더 이상 고객 지원을 해드릴 수 없습니다.

만약, 다음 지도 API 또는 구글 지도 API를 사용하였을때 동일한 환경의 크롬 브라우저에서 이 문제가 더 이상 발생하지 않을것이라고
판단되시면.. 지도 API 교체를 권해드립니다.

프로젝트의 성공을 빕니다.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/navermaps/maps.js/issues/145#issuecomment-303403007>,
or mute the thread

**Comment by changsunwon** [comment]
그리고 다시는 크롬말고 타브라우저 쓰라는 말씀하지마십시요

문제가 크리티컬하고 명제를 드렀는데 답변그리 날라오면 고객께 브라우저바꾸라고 하면 문제 해결됩니까? 그리말씀하시고 말씀이지나치시다는것은
조금 무리있습니다

다시말씀드립니다
문제 현상
소스 다제공해드리고 답변기다리는 입장입니다
부디현명하고 좋은 답변을 기다리니바니 더이상 감정적인 얘기로 불필요한 시간소모를 하지마시길 바랍니다
마지막입니다

2017. 5. 23. 오후 11:04에 "유툽cs" <chang.sun.won@gmail.com>님이 작성:

**Comment by changsunwon** [comment]
상황정황 증거 만들고 증적 남겼고 특히 개입하셔서 말씀이 심하다와 상대적으로 논점넘어선 답변 증거채택해서 시차원에서 공문보낼예정입니다
참고하세요

2017. 5. 23. 오후 4:39에 "Kyoungtaek Koo" <notifications@github.com>님이 작성:

**Comment by changsunwon** [comment]
작성완료

2017. 5. 24. 오전 1:12에 "유툽cs" <chang.sun.won@gmail.com>님이 작성:

**Comment by boxersb** [comment]
저희는 문제해결이 단기간에 어려우니 대안으로 이미 말씀 드렸습니다.  
그런데도 처음부터 시작된 계속적인 고압적인 태도로 저희 개발자들을 압박하시는 것에 대해 제가 말씀이 지나치다고 말씀 드렸던 겁니다.  

사과할일이 있으면 사과 하겠습니다.  
그러나, 제가 드릴 사과의 말씀은 "문제 해결에 원하는 도움을 드리지 못해 죄송합니다" 라는 것 뿐입니다.  

말씀하셨듯이, 네이버 지도는 유로 서비스를 하지 않고 있습니다.  

공문 기다리고 있겠습니다. 반드시 보내시기 바랍니다.

**Comment by changsunwon** [comment]
네 저도 감정적으로 대응한것 같네요.
고경택님, 그렇다면 반대로 저희 입장에서는 생각해보셨는지요. 긴급사안이라고 말씀드린것은 바로 서비스가 오픈되었고 마커의 절반이 나오지
않는
크리티컬한 이슈이기때문에 말씀드린것입니다. 그것이 압박하시는것으로 느껴지셨다면 사과드리겠습니다.
반대로 그렇다면 크롬이 안되니 브라우저를 바꿔라, 네이버지도는 해결을 못하니 다음이나 구글지도로 바꿔라.  이 말씀은 모두 개발완료되고
오픈까지 한 상태에서 하실수 있는 최선의 방안이라고 생각하셔서 말씀하셨습니까?

그리고 어제 제가 해당 url을 드렸는데 고경택님은 보시고 말씀하시는거 맞나요? 문제 발생이 450개 갯수 이하일때는 해당 오류가
발생하지 않아서 제가 쿼리에서 임의로 450 이하의 마커만 나오게 처리했었던 사실을 잊고, 주소를 드렸었습니다. 즉, 재현이 되지 않는
상태로 드렸던것인데 어떻게 재현을 하셨고 그것이 크롬의 버그라고 단정은 어떤 근거로 내세우시는건지도 궁금해졌네요

마지막으로 한말씀드리면, 모든 문제를 100% 해결해주실수는 없는 한계점을 엔지니어 입장으로서도 알고 있습니다.
하지만 마지막에 언급하셨는데 네이버 지도는 유료서비스가 아니다. 라고 말씀하셨는데 그러면 깃허브로 왜 서비스 대응하고 계시는건가요?
왜 지도 서비스하시는데요? 그런말씀은 어떤 API제공사나 다른 사례에서도 유료 무료 서비스를 언급하진 않습니다.

그리고 공문 기다리겠다. 반드시 보내라는것. 이슈를 일정적으로 close하신점이 말로 고경택님이 말씀하신 고압적인 태도 인점을 아시기
바랍니다.


끝으로, 지금 컨택되었던 고경택님을 포함하여 더이상 문제 해결 요청 및 기대 하진 않겠습니다.
다만, 지금까지의 대응과 언급하신 내용들은 좀더 고민해보고 타 커뮤니티에도 알려 현재 네이버 지도 서비스 대응 수준은 공유 할수 있음을
미리 말씀드립니다.

수고하십시요




2017년 5월 24일 오전 10:51, Kyoungtaek Koo <notifications@github.com>님이 작성:

**Comment by boxersb** [comment]
@changsunwon 님.. 저도 감정적으로 대응해서 죄송합니다.  

말씀하신 이슈는 별도로 저희가 계속 해결책을 찾아보았고.. 트레이드 오프가 있지만 해결 방법을 찾았으므로,
내일 오전 중에 해결된 버전을 배포할 계획임을 공유드립니다.  

저희가 해결한 방법은, 임시로 해당 조건의 브라우징 환경에서는 GPU 가속 기능을 off 하는것입니다.  
물론, 장기적으로 보았을때는 근본적인 해결책이 아닙니다만, @changsunwon 님 측 프로젝트 일정을 고려하여 임시 조치하였으며, 가능한 빠른 시일내 추가적인 보완을 할 예정입니다.

배포 완료된 후에 다시 공유 드리겠습니다. 참고 부탁드립니다.

**Comment by changsunwon** [comment]
저역시 죄송하게 생각합니다. 문제해결에 아무 도움이 되지 못하는 발언이었던점 인정합니다.

먼저 부가 상황 설명을 드리면 이번 네이버지도가 사용되어진 시스템은 서울시 시장실님이 사용하시는 관제 및 종합 상황실로 금번
청와대에서도 방문하여 벤치마킹 할 정도로 높은 관심과 기대가 높습니다.
특히나 시스템 특성상 위치정보가 많이 표출되는 관계로 지도부분은 여러 기술검토 끝에 일부 반대 의견도 있었지만 제가(PL) 네이버
지도로 채택하였고 설득시킨 과정이 있는 만큼 책임감 때문에 다소 민감하게 반응하였습니다.
현재 오픈된지 얼마 안된 시점임에도 타 지자체와 정부에서도 관심을 갖고 있으며, 시스템의 상당 부분이 네이버지도API를 사용하고
있다는것은 시 관련 공무원분들 역시 인지하고 있는 상황을 착안하셔서 좋은 결과가 되길 부탁드립니다.
그리고 언급하신대로 조금 이번 이슈가 특이한것이 타 브라우저에서는 정상적으로 동작된다는점과 크롬도 고해상도가 아닌 상황에서는
정상작동한다는점이 트러블슈팅과정을 어렵게 만들 요인이라는 점입니다.
(제안주신 타 브라우저 사용은 불가한 실정입니다. 음성인식으로 동작되는 UX 컨트롤이 비중이 높은데 이때 사용하는 음성인식 모듈이
크롬이 제공하는 음성인식 모듈이기 때문입니다)

서울시 전반적인 시설과 공공데이터가 표출되는 만큼(CCTV,도로교통,소방시설,수방시설,지하철,버스등) 마커 표시 양이 상당히 많습니다.
(full표출시 약 3000개 마커. 하기그림 참고)
[image: 본문 이미지 1]

따라서 클라이언트 환경도 매우 고사양으로 세팅되어 있다는점을 참고사항으로 말씀드립니다.

별도로 구글코리아에도 크롬의 이런 특이점을 이슈 레포팅을 할 예정입니다.

끝으로 이전 이슈상황일때도(터치스크린환경에서 마커터치안되는 현상) 적극적으로 해결해주셔서 네이버지도에 대한 신뢰도가 긍정적인
상황입니다. 네이버지도API가  지도기반의 공공데이터 활용의 좋은 귀감과 레퍼런스가 되었으면 합니다.


감사합니다.

2017년 5월 24일 오후 6:15, Kyoungtaek Koo <notifications@github.com>님이 작성:

**Comment by boxersb** [comment]
@changsunwon 안녕하세요?

조금전에 수정 배포가 완료되었고, 저희쪽 환경에서는 잘 반영되었음을 확인했습니다.  

확인 한번 부탁드립니다~

**Comment by changsunwon** [comment]
네 확인중에 있습니다. 확인후 결과 말씀드리겠습니다.

감사합니다

2017-05-25 12:29 GMT+09:00 Kyoungtaek Koo <notifications@github.com>:

**Comment by changsunwon** [comment]
오늘까지 테스트가 더 이루어질거같습니다만
확인결과 크게 이상없이 잘 표출되고 있습니다
감사드립니다
빠른처리와 긴급배포로 이루어졌다고 보고드렸습니다

다시한번 감사드리겠습니다


2017. 5. 25. 오후 2:08에 "유툽cs" <chang.sun.won@gmail.com>님이 작성:
