### ISSUE TITLE
clientId 와 서비스 url은 일치 함에도 불구하고 API 인증 실패 - 

### ISSUE THREAD

**Issue by joshiekim** [navermaps/maps.js#146]
어느부분을 살펴 봐야할까요 ;; 

https://openapi.map.naver.com/openapi/v3/maps.js?clientId=클라이언트id&callback=iniMap

// 지도 초기 설정 
function iniMap(){

	map = new naver.maps.Map('map', {
		scrollWheel: false,
        scaleControl: true,
        logoControl: true,
        mapDataControl: true,
        zoomControl: true,
        zoomControlOptions: {
            position: naver.maps.Position.TOP_RIGHT
        },
        mapTypeControl: true,
        center: new naver.maps.LatLng(lat, lng),
        zoom: 10
	});
}

**Comment by thetaiz** [comment]
캐시를 지우고 다시 한번 확인을 부탁드려요~ 정기 배포 중 인증 API 관련 이슈가 있었으나 현재 정상화되었습니다.

**Comment by joshiekim** [comment]
아핫 정상작동 합니다. 수고하세요^^

**Comment by changsunwon** [comment]
저희쪽도 동일한 문제가 발생되었었네요.
모든 클라이언트들을 캐시 삭제하라고 공지 할수 없는 상황일텐데 서버측에서 no-cache header 주실순없을런지요..

**Comment by buo** [comment]
번거롭지만 `v=20172015`와 같은 파라미터 하나를 추가하면 클라이언트 캐시 문제를 간단히 해결할 수 있습니다.

```html
<script src="https://openapi.map.naver.com/openapi/v3/maps.js?v=20170525&..."></script>
```

**Comment by thetaiz** [comment]
@buo 님, 감사합니다. ^^

**Comment by thetaiz** [comment]
@changsunwon 님, 헤더 세팅은 요청 헤더에 설정해야 하는 사항이라 저희쪽에서 컨트롤할 수 없습니다. 감사합니다.

**Comment by boxersb** [comment]
@changsunwon 님.. Response Header 에 no-cache 를 설정하여, 항상 콘텐츠를 새롭게 받아오도록 설정하기는 서버 부하 부담상 어려운점 양해바랍니다.

**Comment by changsunwon** [comment]
네 알겠습니다

2017. 5. 25. 오후 3:31에 "Kyoungtaek Koo" <notifications@github.com>님이 작성:
