### ISSUE TITLE
DEPRECATED 경고 메시지 표시 시점 변경

### ISSUE THREAD

**Issue by buo** [navermaps/maps.js#149]
maps.js 로딩 시점이 아닌 `naver.maps.Marker` 초기화 시 `shadow` 옵션 사용할 경우에만
(MapPanes의 'overlayShadow', 'floatShadow' 옵션 또한 마찬가지로)
해당 경고 메시지를 출력하도록 개선해야 합니다.

현재 maps.js 로딩 시 무조건 콘솔에 DEPRECATED 경고 메시지를 띄우고 있는데요,
`shadow` 옵션을 사용하지 않음에도 불구하고 이런 경고문을 띄우는 것은
정상 사용 중인데도 경고 메시지를 띄우는 것이기 때문에 개선되어야 된다고 생각합니다.

예를 들어, 저희 어플리케이션에서는 자동화 도구를 통해 콘솔에서 error, warning 로그를 검출하고 있는데,
네이버 지도 API로 인하여 false alarm이 발생하고 있는 상태입니다.

해당 옵션 사용 시마다 띄우면 DEPRECATED 메시지가 도배될 것이 우려되더라도
정상 사용에 경고 메시지를 띄우는 것은 피해야 된다고 생각합니다.

**Comment by junthus** [comment]
@buo 그런 경우를 미처 생각하지 않았네요;; 의견 감사드립니다, 다음 배포에 반영하도록 하겠습니다.

**Comment by junthus** [comment]
@buo 
변경 예정에 대한 공지라서 가능하면 많은 분이 확인할 수 있도록 로딩시점에 노출하는 것은 유지하고 다만 info 레벨로 조정하였습니다. 변경 후에는 의견 주신 대로 해당 메서드/옵션 사용시에 안내할 예정입니다.

감사합니다.
