### ISSUE TITLE
마커 클러스트링이 가능한지 궁금합니다.

### ISSUE THREAD

**Issue by leeho7** [navermaps/maps.js#15]
구글과 다음의 경우 클러스트링 기능을 API로 지원하고 있습니다. 
네이버에서도 동일 기능을 지원하는지 궁금해서 질문남깁니다. 

빠른 답변 부탁드립니다. 
감사합니다.

**Comment by thetaiz** [comment]
@leeho7 님, 안녕하세요. 저희 API에서는 클러스터링 기능을 지원할 계획이 없습니다. 대신, 빠른 시일내에 클러스터링 예제를 공개하도록 하겠습니다.

**Comment by boxersb** [comment]
@leeho7 다음 지도 API는 `라이브러리`로 제공하고 있으나, 구글 지도 API는 오픈 소스로 마커 클러스터링 예제를 공개하고 있습니다.
저희 네이버 지도 API도 빠른 시일내 마커 클러스터링 예제를 Github 에 오픈소스로 공개하도록 하겠습니다.

감사합니다~

**Comment by leeho7** [comment]
답변 감사합니다. 

수고하세요. ^^

나의 iPhone에서 보냄

2016. 8. 12. 오전 9:26 Kyoungtaek Koo <notifications@github.com> 작성:

**Comment by leeho7** [comment]
답변 감사합니다. 

수고하세요. ^^


나의 iPhone에서 보냄

2016. 8. 12. 오전 9:11 Yonghwan Lee <notifications@github.com> 작성:
