### ISSUE TITLE
naver.maps.Service = undefined

### ISSUE THREAD

**Issue by cocacrave** [navermaps/maps.js#150]
Sorry, I can't type Korean, but you can reply in Korean if you wish.
In https://navermaps.github.io/maps.js/docs/tutorial-3-geocoder-geocoding.example.html, it explains to use naver.maps.Service.geocode to search address. But naver.maps.Service is undefined.

**Comment by junthus** [comment]
@cocacrave 

To use Geocoder, you must load the Geocoder submodule JavaScript file. 
Please make sure your script tag is equal to this.

```html
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=YOUR_CLIENT_ID&submodules=geocoder"></script>
```

If you have not been issued a client id, please check the checklist below first, then try above.

1. Create a Naver ID
2. go [this](https://developers.naver.com/apps/#/register) page(naver dev center), and register.
> select what API you need
![image](https://cloud.githubusercontent.com/assets/5088669/26535050/e324401c-4464-11e7-97aa-f591f94d7762.png)
> enter your sevice/develop domains
![image](https://cloud.githubusercontent.com/assets/5088669/26535108/4efb25da-4465-11e7-89af-24be3547806a.png)

I hope it helps. if it doesn't work, comment again.

**Comment by cocacrave** [comment]
Thanks, I got it now.
