### ISSUE TITLE
지도 api 모바일웹에서 작동 여부 

### ISSUE THREAD

**Issue by joshiekim** [navermaps/maps.js#151]
확인 부탁 드립니다. 
PC web 에서 잘되는 소스가 
Mobile web (chrome UA Spoofer) 에서 작동을 안하네요.
지난 25일 인증오류때는 인증 오류 팝업이 떳지만 지금은 팝업은 안뜹니다만. 
개발자 툴에서 뜨는 안내 코맨트는 동일하게 뜹니다. (아래 첨부)

협조 부탁 드립니다~

maps.js?clientId=클라이언트아이디 &callback=iniMap:6  NAVER Maps JavaScript API v3 

The 'shadow' option of naver.maps.Marker will be DEPRECATED and will be ignored in future versions of the NAVER Maps JavaScript API v3.
'overlayShadow' and 'floatShadow' panes of MapPanes also will be DEPRECATED.
Please review your application and see https://github.com/navermaps/maps.js/releases for more details.

naver.maps.Marker의 'shadow' 옵션은 지원 중단되며 향후 버전의 NAVER Maps JavaScript API v3에서는 무시됩니다.
MapPanes의 'overlayShadow', 'floatShadow' 페인 역시 지원 중단됩니다.
애플리케이션이 문제가 없는지 검토하세요. 향후 변경에 대한 자세한 내용은 릴리스 노트(https://github.com/navermaps/maps.js/releases)를 참조하세요.

**Comment by thetaiz** [comment]
@joshiekim 님, 혹시 저희가 볼 수 있는 URL이 있나요? 그리고 별도의 에러 메시지는 나오지 않는 것이죠? (저 위의 에러는 빼구요)

**Comment by joshiekim** [comment]
넵  아직 로컬 개발 중이라서요... 별도의 에러메시지는 안나옵니다 ;;
PC web에서는 문제없이 마무리 되었는데 그 소스 활용해서 mobile web 으로 하려니 안되네요 ㅠㅠ

**Comment by thetaiz** [comment]
@joshiekim 님, 저희쪽에서 재현할 수 있게 코드를 mapsopenapi@naver.com 으로 보내주실 수 있으세요? 그리고 발생한 환경은 어떤지도 궁금합니다. 마지막으로 저희쪽 예제 코드 역시 모바일웹에서 안보이나요?

**Comment by joshiekim** [comment]
앗 ㅠㅠ CSS 에서 map을 싸고 있는 영역에 사이즈를 않줬었네요;; 허허 번거롭게 해드려 죄송합니다.^^ 
그래도 답변 감사합니다.

**Comment by thetaiz** [comment]
@joshiekim 님, 해결이 되어 다행입니다. ^^ 이 이슈는 닫겠습니다. 감사합니다.
