### ISSUE TITLE
네이버 지도 api 인증 문의

### ISSUE THREAD

**Issue by sh-jykim** [navermaps/maps.js#152]
모바일(지도)에서 기존 사용(V1)했던 네이버지도가 작년12월경에 중지되어 새롭게 v3로 마이그레이션을 해야하는 상황입니다.  

어제 내 애플리케이션 등록하여 클라이언트 아이디와 클라이언트 시크릿키를 부여받아,
간단한 예제를 통해 확인을 해보고자 클라이언트 아이디 부분에 부여받은 20자리 키를 입력하고, 
URL을 실행(웹, 모바일)하니

지도가 잠깐 보이면서(1초정도)  "네이버 지도 Open API 인증이 실패했습니다" 라는 
화면으로 이동되었습니다.

아래자료를 참고하셔서 무엇이 잘못된건지 도움 부탁드립니다.

1. 작업한 소스
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>간단한 지도 표시하기</title>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=WD2JTZybtOzh03N7gUOh"></script>
</head>
<body>
<div id="map" style="width:100%;height:400px;"></div>

<script>
var mapOptions = {
    center: new naver.maps.LatLng(37.3595704, 127.105399),
    zoom: 10
};

var map = new naver.maps.Map('map', mapOptions);
</script>
</body>
</html>

2. http://mbiz.shinhung.co.kr/navermapv3.asp

**Comment by sh-jykim** [comment]
1. 작업한 소스에 <!DOCTYPE html> , <html>, <head>, <body> 태그를 넣었는데 글이 등록된 후에는 태그가 보이지 않은 점 참고해주세요.

**Comment by thetaiz** [comment]
@sh-jykim 님, 내 애플리케이션에서 `API 설정` 탭을 누르고, `사용 API`에서 **지도 (웹)**을 선택해 추가해 주세요. 그래야 자바스크립트 API를 사용할 수 있습니다. 그게 설정이 안되어 인증이 실패했습니다.

**Comment by sh-jykim** [comment]
지도(웹) 추가하니 지도 정상적으로 확인 했습니다.
