### ISSUE TITLE
네이버 지도 v3 겹침 마커 처리하기 처리시 에러?

### ISSUE THREAD

**Issue by sportsst** [navermaps/maps.js#153]
예제에서 겹침 마커 처리하기 를 참고하여 겹치는 마크 눌렸을때 리스트가 나오는부분에서 너무 길었을때 max-height 를 사용해서 스크롤바가 나오게 처리 했습니다만, 크롬에서는 스크롤 바를 선택해서 움직일 수 있는데 ie(10.9.9200.17609) 와 파이어폭스 에서는 스크롤 바가 작동이 안되고 뒤에 지도가 잡혀서 움지이는데요. 
그리고 ie(10.0.9.9200.17609IS)에서는 max-height 가 안먹히는거 같습니다.

아래 리스트 출력 부분 소스 입니다.  확인 좀 부탁 드립니다.

var MarkerOverlapRecognizer = function(opts) {
    this._options = $.extend({
        tolerance: 5,
        highlightRect: true,
        highlightRectStyle: {
            strokeColor: '#ff0000',
            strokeOpacity: 1,
            strokeWeight: 2,
            strokeStyle: 'dot',
            fillColor: '#ff0000',
            fillOpacity: 0.5
        },
        intersectNotice: true,
        intersectNoticeTemplate: '<div style="border:solid 1px #333;background-color:#fff; padding:5px; font-size: 12px; letter-spacing: -1px; text-decoration: none;"><em style="font-weight:bold;color:#f00; ">{{count}}</em> 개의 결과가 있습니다.</div>',
        intersectList: true,
        intersectListTemplate: '<div style="z-index: 99999999; width:250px; border:solid 1px #333;background-color:#fff;padding:5px; max-height: 148px; overflow-x: hidden; overflow-y: auto; position: relative;">'
            + '<ul style="list-style:none;margin:0;padding:0;">'
            + '{{#repeat}}'
            + '<li style="height: 20px; line-height: 20px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><a style="color: #454545; font-size: 12px; letter-spacing: -1px; text-decoration: none;"href="#"> {{title}}</a></li>'
            + '{{/#repeat}}'
            + '</ul>'
            + '</div>'
    }, opts);

**Comment by junthus** [comment]
@sportsst 님 안녕하세요 ~

지도 엘리먼트 내에서 리스트를 표현하고 있기 때문에 지도의 기본 인터랙션에 영향을 받고 있는 상황입니다.
mousewheel이나 mousedown 시에 이벤트 버블링을 멈춰주시거나 / 스크롤이나 클릭 시에 지도 인터랙션을 잠시 멈춰주시면 스크롤/클릭-드래그 모두 가능합니다. 다만 휠 이벤트는 다루기가 까다로우니... 크게 상관이 없다면 아래처럼 지도 옵션을 on/off 하는게 더 수월할 듯 합니다. ^^

아래 옵션에 대한 자세한 내용은  [mapOptions](https://navermaps.github.io/maps.js/docs/naver.maps.html#.MapOptions)를 참고해주세요.

```js
// 리스트 show 시점에 
map.setOptions({scrollWheel: false, draggable: false});

// ...
// 리스트 hide 시점에
map.setOptions({scrollWheel: true, draggable: true});
```

p.s. 제 pc의 ie10은 max-height를 잘 표현합니다만... max height이 안된다는건 좀 더 살펴보시면 해결하실 수 있을 듯 합니다. 

더 궁금한 점이 있다면 코멘트 주세요.
도움이 되시길 바랍니다.
