### ISSUE TITLE
지도 마커 표시가 되는컴퓨터가 있고 안되는컴퓨터가 있어요

### ISSUE THREAD

**Issue by poinsettia85** [navermaps/maps.js#154]
http://poinsettia85.ivyro.net/

여기에 엑셀로 주소를 넣으면 마커가 표시 되는데요

되는 컴퓨터가 있고 안되는 컴퓨터가 있어요

느낌상 좋은컴퓨터는 되고 안좋은 컴퓨터는 안되는거같은데

왜그런지 알고 싶어요

**Comment by junthus** [comment]
@poinsettia85 님 안녕하세요 ㅎ.ㅎ 도움을 드리기 위해선 좀 더 자세한 설명이 필요합니다. 
이슈가 재현되는 환경(브라우저 종류, 버전)을 알려주세요.

**Comment by poinsettia85** [comment]
익스플로러11  쓰고 있고
네이버지도api v3 사용하고 있습니다
엑셀에 주소를 적어서 업로드를 하면 그 주소가 네이버 지도에 표시되게 만들었는데요
이게 표시가 되는 컴퓨터가 있고 그냥 아무것도 표시가 안되는 컴퓨터가 있어요
안되는 컴퓨터에서 익스플로러 버전 문제일까 해서 익스플로러11로 업데이트 하고 돌려봐도
화면이 하얗게만 나오고 아무것도 표시가 안되요
둘 차이를 찾지 못해 해결을 못하는중인데 그 이유를 알고싶습니다

**Comment by junthus** [comment]
@poinsettia85 님
페이지 소스를 보니 html 문서가 말폼인듯 싶습니다. html 루트 태그가 두 개라...;; 아마 하얗게 나오는 브라우저는 아래 html 소스를 읽지 않는 듯 하네요. 이 부분 수정해서 테스트 해보시길 바랍니다.

**Comment by poinsettia85** [comment]
<html> </html> 이것을 하나로 줄여도 증상의 변함이 없습니다

무엇이 도대체 문제일지

**Comment by junthus** [comment]
@poinsettia85 

ㅜㅜ 헛 그렇군요..
제 ie 11 에서는 별 문제 없이 동작하고 있어서 말씀하시는 상황을 확인할 수가 없는데요....
화면 자체가 하얗게 나온다면 사실 지도 API의 문제이기보다 html 말폼등 다른 이슈일 가능성이 큽니다. (`파일명` 업로드 성공 <- 이 텍스트도 안 나오는거죠?)

일단 콘솔에 아래같은 워닝이 뜨는데 이런것들을 먼저 해결해보시는게 어떨까 합니다. 
![image](https://user-images.githubusercontent.com/5088669/26861997-f1b4190c-4b82-11e7-9d88-752593538733.png)
그리고 혹시 호환성 보기가 켜져있다던지 문서모드가 표준이 아니라던지 하는 환경도 확인해 보시기 바랍니다.
도움이 되시기 바랍니다.

**Comment by cs09g** [comment]
저도 한번 테스트 해봤는데, `SCRIPT438: 개체가 'getElement' 속성이나 메서드를 지원하지 않습니다.` 요런 에러가 169번째 줄에서 발생하네요. 그런데 그 외에 @junthus 님 말씀대로 코드정리가 먼저 필요할 것 같습니다. 에러가 발생할 때 IE 디버거로 코드를 확인 했더니 body 가 두 개 보여요.
