### ISSUE TITLE
파노라마 가이드 따라 했는데 로드가 안됩니다

### ISSUE THREAD

**Issue by BROUDING** [navermaps/maps.js#155]
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>간단한 지도 표시하기</title>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=ㅏKEYKEYKEY&submodules=panorama&callback=pano"></script>
</head>
<body>
<div id="pano" style="width:100%;height:400px;"></div>

<script>

var pano = new naver.maps.Panorama("pano", {
    position: new naver.maps.LatLng(37.3599605, 127.1058814),
    size: new naver.maps.Size(800, 600),
    pov: {
        pan: -135,
        tilt: 29,
        fov: 100
    }
});

</script>
</body>
</html>

튜토리얼 보고 따라했는데... 개발자 콘솔에서 네트워크 부분 보면 아래 부분에서 fail이 뜹니다..

file://pvxml.map.naver.com/api/panorama/mappings/instant.jsonp?callback=__naver_maps_callback__1&look_at=127.1058814,37.3599605&pano_type_cd=3&radius=300&limit=1&caller=naver_map_v3

무엇이 잘못된건가요~? (물론 clientKey 는 있습니다)

**Comment by junthus** [comment]
@BROUDING 님 안녕하세요.
API 콜이 실패하고 있네요. file 프로토콜을 사용하지 마시고 로컬 웹서버를 올려 http를 사용해주세요.

**Comment by BROUDING** [comment]
@junthus  의견 감사합니다...
그럼 로컬에서는 안된다는 말씀이신가요...?

그냥 지도 샘플은 잘 되던데 왜 파노라마만 그런거죠 ㅜㅜ

**Comment by junthus** [comment]
@BROUDING 아마 파노라마 API 요청 로직이 현재 사용자의 프로토콜로 요청하도록만 되어 있는 듯 합니다. 이 부분은 수정이 가능할지 검토해 보겠습니다만...
일단 사용해보시려면 예제가 http 프로토콜을 사용하도록 해야 합니다. 로컬에서 웹서버를 하나 띄워서 http://localhost 등의 도메인에서 확인해보시면 정상 동작합니다. 파이썬 심플 서버나 노드 http 서버 등으로 한번 검색해 보셔요. ^^

**Comment by BROUDING** [comment]
이 부분만 해결해 주시면 서버개발자 없이도 파노라마뷰를 보여줄 수 있는데.. 수정가능한지 검토 꼭 부탁드릴께요..ㅜㅜ

**Comment by junthus** [comment]
@BROUDING 님 안녕하세요, 해당 이슈 수정되어 배포되었습니다. 확인 부탁드려요 ~

**Comment by BROUDING** [comment]
@junthus  감사합니다 ! 감사합니다 !!!

**Comment by junthus** [comment]
@BROUDING 헛 저도 감사합니다 ㅠㅠ
이 이슈는 닫겠습니다, 추후 또 문제가 생기면 새로운 이슈로 등록해주세요 ^^
