### ISSUE TITLE
네이버 지도 타일셋 범위가 궁금합니다.

### ISSUE THREAD

**Issue by shchoung** [navermaps/maps.js#156]
안녕하세요~ ^^ 네이버지도와 Geoserver를 이용하여 저희 지적도 
중첩까지 성공하였고 퍼포먼스 향상을 위해 케시작업 테스트중입니다. 
그래서 네이버지도 타일셋과 동일하게 맞추고자 합니다.
네이버지도의 전체 bound(minX,minY,maxX,maxY) 와 
타일메트릭스셋(레벨별 축적비율) 정보를 알 수 있을까요?

**Comment by junthus** [comment]
@shchoung 

0레벨일 때 기본 프로젝션 (UTMK_NAVER) 기준입니다. 

최대 `bounds` 는 이 정도고요
![image](https://cloud.githubusercontent.com/assets/5088669/26768275/bc7f2d78-49e1-11e7-898d-a616df4473d4.png)

축적은 0레벨 일때 1픽셀당 8192m 이고 1 레벨 증가시에 1/2 로 감소합니다. 지도 화면의 우측 하단(기본위치)의 스케일 바가 50px 이니 참고하셔서 계산하시면 될 듯합니다. 

도움이 되시길 바랍니다.

**Comment by shchoung** [comment]
@junthus 님 잘 되네요~ 감사합니다. ^^
