### ISSUE TITLE
panTo와 동시에 setZoom을 할 경우 pan되지 않습니다.

### ISSUE THREAD

**Issue by zeakd** [navermaps/maps.js#157]
안녕하세요. 

#2 와 관련있는 것 같습니다만, 
```
map.panTo (...)
map.setZoom (...)
```
의 순서로 할 경우 거리가 멀면 애니메이션없이 이동되어 잘 작동하지만 거리가 가까운 경우엔 panTo 동작이 무시됩니다. 애니메이션 전환이 취소되면서 일어나는 현상 같습니다.

순서를 바꿔서
```
map.setZoom (...)
map.panTo (...)
```
로 실행할 경우 잘 동작합니다.

**Comment by thetaiz** [comment]
@zeakd 님, `morph(coord, zoom, transitionOptions)`를 사용해 주세요~ ^^

**Comment by zeakd** [comment]
감사합니다 :)

**Comment by zeakd** [comment]
별개로 morph 와 관련된 내용이 [move example](https://navermaps.github.io/maps.js/docs/tutorial-5-map-moves.example.html) 에 있으면 좋겠어요

**Comment by thetaiz** [comment]
@zeakd 님, 관련 예제를 보강하도록 하겠습니다. 감사합니다.
