### ISSUE TITLE
InfoWindow 같은 map에 2개 생성시 질문입니다.

### ISSUE THREAD

**Issue by joshuayun** [navermaps/maps.js#158]
--------------------------------------------------------------------
1.
sPoint = new naver.maps.LatLng(lat, lon);
	sInfoWnd = new naver.maps.InfoWindow({
		position: sPoint,
		content: cts,
		borderWidth: 0,
	    disableAnchor: true,
	    backgroundColor: 'transparent',
	    anchor: new naver.maps.Point(17.5, 46),
	    pixelOffset: new naver.maps.Point(0,0)
	});
	sInfoWnd.open(oMap, sMarker);

---------------------------------------------------------------
2.
oPoint2 = new naver.maps.LatLng(lat, lon);
	oInfoWnd2 = new naver.maps.InfoWindow({
		position: oPoint2,
		content: cts,
		borderWidth: 0,
	    disableAnchor: true,
	    backgroundColor: 'transparent',
	    anchor: new naver.maps.Point(17.5, 46),
	    pixelOffset: new naver.maps.Point(0,0)
	});
	oInfoWnd2.open(oMap, oMarker2);

------------------------------------------------------------------

위와 같이 같은 oMap에 infowindow의 변수를 다르게 하여 두개다 open할경우
먼저 그려졋던 infowindow는 자동으로 사라지게 되는데 2개의 infowindow창을 모두 열수있는 방법은 없을까요?

**Comment by thetaiz** [comment]
@joshuayun 님, 인포윈도우는 스펙 상 하나만 열리게 되어 있습니다. 두 개 이상을 동시에 올리려면 사용자 정의 오버레이를 구현해야 합니다. 아래 링크의 문서를 참고해 주세요.

- http://d2.naver.com/helloworld/3380225
