### ISSUE TITLE
최신기종 지오로케이션

### ISSUE THREAD

**Issue by haewd2** [navermaps/maps.js#159]
https://navermaps.github.io/maps.js/docs/tutorial-6-map-geolocation.example.html
위 주소의 네이버 지오로케이션 소스를 사용하여 지정된 위치와 나의 현재 위치를 불러오도록 만들었습니다. (getCurrentPosition)

예전 폰에서는 자동으로 사용자 동의가 나타나서 설정을했는데 신기종 휴대폰에서는 동의가 자동으로 나타나질 않아서 에러가 뜨는 것 같습니다.
위치정보 사용에대해 동의를 구하도록 강제로 설정할 방법이 있나요?

**Comment by thetaiz** [comment]
@haewd2 님, HTTPS를 이용하시고 있는거죠? 저희쪽에서 접근해 볼 수 있는 URL이 있나요? 구현 소스와 휴대폰 모델, OS 버전을 알려주시면 재현해 살펴보겠습니다.

**Comment by haewd2** [comment]
웹 주소 : http://80000way.com/sm122.php (https를 사용해야하나요?)

OS 버전 : 기종은 갤럭시s8이구요.  os는 안드로이드 7.0 입니다.

지오로케이션 소스 : 중간에 polyline 소스가 너무길어서 삭제 하고 나머지 부분만 올려 드립니다.

<script>

	var map = new naver.maps.Map('map', {
		center: new naver.maps.LatLng(35.746943, 128.207321),
		zoom : 6, // - 초기 줌 레벨은 10으로 둔다.
		enableWheelZoom : true,
		enableDragPan : true,
		enableDblClickZoom : false,
		mapMode : 1, //0으로 하면 초기 일반지도, 1로하면 초기 위성지도.
		activateTrafficMap : false,
		activateBicycleMap : false,
		minMaxLevel : [ 1, 14 ],
		zoomControl: true,
		scaleControl: true,
		mapTypeControl: true,
		mapTypeId: naver.maps.MapTypeId.HYBRID
	});

	var polyline = new naver.maps.Polyline({
		map: map,
		path: [
	new naver.maps.LatLng(35.708749, 128.358042),
	new naver.maps.LatLng(35.800534, 128.097499)		

		],
		strokeColor: '#ff0000',
		strokeOpacity: 0.6,
		strokeWeight: 5
	});


	var infowindow = new naver.maps.InfoWindow();

	function onSuccessGeolocation(position) {
		var location = new naver.maps.LatLng(position.coords.latitude,
											 position.coords.longitude);

		map.setCenter(location); // 얻은 좌표를 지도의 중심으로 설정합니다.
		map.setZoom(6); // 지도의 줌 레벨을 변경합니다.

		infowindow.setContent('<div style="padding:10px; width: 70px; text-align: center;">내위치</div>');

		infowindow.open(map, location);
	}

	function onErrorGeolocation() {
		var center = map.getCenter();
	}
	

	if (navigator.geolocation) {
		navigator.geolocation.getCurrentPosition(onSuccessGeolocation, onErrorGeolocation);
	} else {
			
	}
	
	$('.go_point').click(function() {
		navigator.geolocation.getCurrentPosition(onSuccessGeolocation, onErrorGeolocation);
	});

</script>

감사합니다.

**Comment by thetaiz** [comment]
@haewd2 님, 안드로이드 7.0이면 크롬 브라우저일거에요~ 크롬 최신에서는 위치 정보를 다룰 때 HTTPS가 아니면 안됩니다. 크롬 개발자 도구를 이용해 보시면 아래와 같이 안내가 나옵니다.

>[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by haewd2** [comment]
https로 설치해야 겠네요.
답변 감사합니다.
