### ISSUE TITLE
네이버지도/네이버지도어플로 연결되게 하고 싶습니다.

### ISSUE THREAD

**Issue by damdaepark** [navermaps/maps.js#16]
1. 네이버 logo control을 누르거나
2. 지도를 더블클릭했을 때

PC의 경우 네이버지도로, 모바일의 경우 네이버지도어플로 연결되는 코드가 있나요?
+ 연결되었을때 설정된 위도/경도로 이동되었으면 좋겠어요.

**Comment by thetaiz** [comment]
@damdaepark 님, 안녕하세요.

아쉽게도 네이버 지도 앱으로 연결할 수 있는 URL Scheme을 지원하고 있지 않습니다.
URL Scheme 지원이 되면 네이버 개발자 센터를 통해 공개하도록 하겠습니다.

**Comment by boxersb** [comment]
@damdaepark LogoControl 클릭시의 처리를 위해서는 `map.logoControl.getElement()` 이후에 a 테그를 찾아서 처리해주셔야 합니다.
더블 클릭시의 반응은 Map의 `dblclick` 이벤트를 사용하여 구현하셔야 합니다. 그러나, @thetaiz 님께서 말씀하신것 처럼 어플리케이션으로 연결되는 URL Scheme 은 공개가 어려운점 양해 부탁드립니다.

**Comment by damdaepark** [comment]
map.logoControl.getElement()를 이용하는 방법에 대해 상세 코드를 알려주실 수 있나요?
예제에는 컨트롤러 위치 옮기는 것만 나와있어서 어떻게할지 가늠이 오질 않네요 ^^;

2016년 8월 16일 오후 5:58, Kyoungtaek Koo <notifications@github.com>님이 작성:
