### ISSUE TITLE
다중마커 처리관련 문의

### ISSUE THREAD

**Issue by joshuayun** [navermaps/maps.js#161]
sMarker = new naver.maps.Marker({
	    map: oMap,
	    position: sPoint,
            ... 중략
})

위와 같은 마커를 for문으로 다중마커를 생성한 후에

setMap()을 특정마커만 지울순 없나요?

**Comment by thetaiz** [comment]
생성한 마커를 배열 등으로 가지고 있다가 해당 마커를 찾아 setMap 하면 됩니다. 특정 마커를 표시하고 싶으시면 마커 생성 시 옵션에 플래그를 넣으면 마커 객체를 통해 해당 플래그를 볼 수 있습니다.
