### ISSUE TITLE
네이버 그리기 관련 문의 입니다.

### ISSUE THREAD

**Issue by happyboi** [navermaps/maps.js#164]
![default](https://user-images.githubusercontent.com/29361848/27413663-c006b818-5737-11e7-8314-e4632fa36f95.JPG)

그리기 영역안에 마커 표시가 되어 있는데,

그 마커표시의 정보를 알 수 있는 방법이 있는지 궁금합니다.

**Comment by junthus** [comment]
@happyboi 님 안녕하세요.

마커 표시의 정보... 가 무엇일까요. 
마커 인스턴스를 얻으려면 아래 두 방법 중에 적절한 것으로 선택하시면 됩니다. 

> drawing 모듈을 통해 그려지는 마커는 API의 마커와 동일하기 때문에 마커 인스턴스에서의 조작은 [Marker Class](https://navermaps.github.io/maps.js/docs/naver.maps.Marker.html) 문서를 참고해 주세요.

1. 그려지는 시점에 이벤트 리스너를 통해 얻기
```js
// map 생성

let drawingManager = new naver.maps.drawing.DrawingManager({map: map}); // drawing 매니저 생성
let markers = [];

drawingManager.addListener('markerAdded', (marker) => {
    markers.push(marker);
});

// 마커(들) 생성
```
2. 마커가 그려진 후 `getDrawings()`메서드로 얻은 객체에서 필터링
```js
// map 생성

let drawingManager = new naver.maps.drawing.DrawingManager({map: map}); // drawing 매니저 생성

// 마커(들) 생성

let markers = Object.values(drawingManager.getDrawings())
                        .filter(itm => itm instanceof N.Marker);
```

도움이 되시길 바랍니다.

**Comment by happyboi** [comment]
![default](https://user-images.githubusercontent.com/29361848/27421408-364fb114-5765-11e7-8bb3-4f689114f316.JPG)

마커가 찍힌 곳 중에  그리기도구를 이용해서  빨간 네모안에 있는 마커 정보만를 알수 있는 지 궁금합니다.

**Comment by junthus** [comment]
@happyboi 
아하 넵넵

`rectangle`의 `bounds` 안에 속해있는 마커를 찾도록 구현해야 합니다.
[bounds.hasLatLng](https://navermaps.github.io/maps.js/docs/naver.maps.LatLngBounds.html#hasLatLng__anchor) 메서드를 아래처럼 이용하시면 되고요.

```js
// let redRect;
// let markers = [...];
// 선택영역 사각형과 마커 배열을 미리 구합니다. 

let bounds = redRect.getBounds();
let inBoundsMarker = markers.filter((marker) => { 
    return bounds.hasLatLng(marker.getPosition());
});
```

단 이 경우 마커의 `position`을 가지고 판별하기 때문에 마커 아이콘 일부는 선택 영역 바깥에 위치할 수 있습니다.
