### ISSUE TITLE
교통정보가 안나와요 

### ISSUE THREAD

**Issue by theppww** [navermaps/maps.js#165]
1. 아래는 지금 코드 입니다 
![test1](https://user-images.githubusercontent.com/29647592/27465989-213103a2-5812-11e7-8e0d-efde8ed8ff36.PNG)

<!DOCTYPE html>

<html>

<head>

    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, 

minimum-scale=1.0, user-scalable=no">

  
  <title>간단한 지도 표시하기</title>

  

  <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=키값 

정확합"></script>

</head>

<body>

<div id="map" style="width:100%;height:400px;"></div>

<script>

var map = new naver.maps.Map('map', {

    center: new naver.maps.LatLng(37.3595704, 127.105399),

  
  mapTypeControl: true,

    mapTypeControlOptions: {

        style: naver.maps.MapTypeControlStyle.DROPDOWN

    }
});

var trafficLayer = new naver.maps.TrafficLayer({
    interval: 2000 // 2초마다 새로고침
});

var btn = $('#traffic');

naver.maps.Event.addListener(map, 'trafficLayer_changed', function(trafficLayer) {
    if (trafficLayer) {
        btn.addClass('control-on');
        $("#autorefresh").parent().show();
        $("#autorefresh")[0].checked = true;
    } else {
        btn.removeClass('control-on');
        $("#autorefresh").parent().hide();
    }
});

trafficLayer.setMap(map);

btn.on("click", function(e) {
    e.preventDefault();

    if (trafficLayer.getMap()) {
        trafficLayer.setMap(null);
    } else {
        trafficLayer.setMap(map);
    }
});

$("#autorefresh").on("click", function(e) {
    var btn = $(this),
        checked = btn.is(":checked");

    if (checked) {
        trafficLayer.startAutoRefresh();
    } else {
        trafficLayer.endAutoRefresh();
    }
});

</script>
![test1](https://user-images.githubusercontent.com/29647592/27465976-0abe69c0-5812-11e7-83e0-108e1b9f10e2.PNG)

이 밑 부분은 오류 입니다  부탁 드립니다   var btn = $('#traffic');가 인식이 안 되는 것 같습니다 
![test1](https://user-images.githubusercontent.com/29647592/27465993-26adcbee-5812-11e7-85e4-6298424c7976.PNG)

**Comment by thetaiz** [comment]
동일 질문으로 이 이슈는 닫겠습니다.
