### ISSUE TITLE
교통 정보 관련입니다.^^ 

### ISSUE THREAD

**Issue by theppww** [navermaps/maps.js#166]
아래 코드는 개발자 홈페이지에 있는 개발자 예제 입니다  예제 그대로 따라 했고 

![test2](https://user-images.githubusercontent.com/29647592/27467346-bcedea12-581c-11e7-96ca-cc04a2f8c6d0.PNG)

이 밑 부분은 오류 입니다    var btn = $('#traffic');가 인지가 안 되는 것 같습니다 
 
제가 어떤 부분이  잘 못 됐는지 잘모르겠습니다 

알려 주시면 감사하겠습니다 

![test1](https://user-images.githubusercontent.com/29647592/27465993-26adcbee-5812-11e7-85e4-6298424c7976.PNG)

**Comment by cs09g** [comment]
jQuery 가 없어서 발생하는 에러 같습니다.

**Comment by thetaiz** [comment]
@theppww 님, jQuery 적용 후 해보셨나요?
