### ISSUE TITLE
NAVER MAP English SDK for Developers

### ISSUE THREAD

**Issue by bruinjustin** [navermaps/maps.js#167]
안녕하세요.
iinecard의 신현석입니다.
영문(English)로 만들어 진 네이버지도의 SDK/API 개발자 링크/영문 application을 받고 싶습니다.
지금 https://developers.naver.com로 들어가서 아무리 찾아봐도 영어로 된것이 없네요.
이부분을 제가 못찾는것인지 아니면 영어로 존재하지 않는것인지 궁금합니다.
이내용을 받으시면 010-9803-9915로 연락이나 justin@iinecard.co.jp로 이메일 부탁 드립니다.
감사합니다.

**Comment by thetaiz** [comment]
@bruinjustin 님, 현재 영문 가이드는 없습니다.
