### ISSUE TITLE
지적도 레이어가 도로보다 우선되어야 하는 것 아닌가요?

### ISSUE THREAD

**Issue by lsw3210** [navermaps/maps.js#168]
지적도 레이어 표시하기를 보고 하나 만들어 봤는데, 도로와 겹치는 부분은 도로가 지적선보다 위에 나타나 지적선을 알 수가 없습니다. 그래서 뭐가 잘못 됐나 하고, 예제를 봐도 도로가 있는 경우는 도로가 우선되어 지적선을 확인할 수 없습니다. ![default](https://user-images.githubusercontent.com/8040714/27563405-677e6320-5b0c-11e7-9c57-1d6471acb8ba.png)
'지적도 레이어 표시하기'라면 모든 레이어보다 우선해서 나타나야 하는 것 아닌가요? 지적도 레이어가 최상으로 표시될 수 있도록 바꿔주실 수 있나요? 참고로 국토정보 앱이나 VWorld 
사이트를 보면 지적선이 위성사진보다 위에 표시되어 어떤 상황에서도 지적선을 확인할 수 있습니다.

**Comment by thetaiz** [comment]
@lsw3210 님, 현재 지적도는 도로와 지적 정보가 하나로 합쳐져 타일로 내려오기 때문에 분리할 수 없습니다. 더불어 지도 API에서도 위성 사진 위에 지적도 레이어가 올라가고 있습니다.
