### ISSUE TITLE
타일 로드 완료 이벤트 처리

### ISSUE THREAD

**Issue by Kjwon15** [navermaps/maps.js#169]
[API 문서](https://navermaps.github.io/maps.js/docs/naver.maps.Tile.html#event:loaded__anchor)를 보면 타일 로드 완료시 `loaded`라는 이벤트가 발생한다고 하는데 아래와 같이 코드를 작성했지만 이벤트 처리가 전혀 되지 않습니다. 제가 잘못 사용하고 있는 것인지 아니면 버그인지 알 방법이 없어 이슈 남깁니다.

```js
      let startTime = Date.now();
      naver.maps.Event.addListener(this.map, 'loaded', () => {
          let elapsedTime = Date.now() - startTime;
          this.updateInitTime(elapsedTime);
          // naver.maps.event.removeListener(this.map, 'loaded', handler);
      })
```

이와 별개로 `click` 등의 UI 이벤트처럼 이런 이벤트에 대해서도 예제가 있었으면 좋겠습니다. 문서만 보고는 이벤트를 어떻게 잡아야 하는지 전혀 감이 오지 않습니다.

**Comment by boxersb** [comment]
@Kjwon15 `tilesloaded` 이벤트 입니다..  
아래 문서 참조 바랍니다.
> https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#event:tilesloaded__anchor

그리고, `tilesloaded` 이벤트는 지도를 이동하여 타일을 새롭게 로드하였을 경우 마다 발생합니다.  
혹시 최초 지도 로딩 완료 시점을 위해 `tilesloaded` 이벤트를 사용하시는거라면, 이벤트 발생 이후에는 이벤트 리스너를 해제 하시거나, `naver.maps.Event.once` 를 사용하시는게 좋을것 같습니다.  

감사합니다.

**Comment by boxersb** [comment]
@Kjwon15 기본적인 이벤트 방식에 대한 예제는 

> https://navermaps.github.io/maps.js/docs/tutorial-1-event-simple.example.html 

에 준비되어 있습니다.. 그러나, 모든 이벤트들에 대한 예제를 준비하기 어려운점 양해 부탁드립니다 ^^

감사합니다~

**Comment by Kjwon15** [comment]
빠른 답변 감사합니다 :+1:

**Comment by Kjwon15** [comment]
이벤트 예제 코드 페이지에 해당 [문서](https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#toc36__anchor) 링크를 넣어주시는 방법도 좋을 것 같습니다.

**Comment by boxersb** [comment]
@Kjwon15 넵.. 의견 감사합니다.  

말씀하신 내용 검토해보겠습니다~~ :)
