### ISSUE TITLE
네이버 지도로 가능한지 문의드립니다

### ISSUE THREAD

**Issue by smg1020** [navermaps/maps.js#17]
http://gisutd.tistory.com/6

위 사이트에서 나온 내용을 따라하려고 했는데

작년 글이라 그런지 바뀐게 많더라구요

위 블로그에서 나온 것 처럼 하는 것은 이제 불가능한가요?

**Comment by thetaiz** [comment]
@smg1020 님, 안녕하세요. 문의 주신 블로그의 내용을 보니 검색 API 내용으로 보입니다.
아래 링크에서 `오픈 API 이용 신청`과 `개발 가이드 보기`를 참고하세요~ ^^

* 검색 API: https://developers.naver.com/products/search

**Comment by smg1020** [comment]
@thetaiz  답변 감사드립니다. 위에 것도 참고하였지만 잘 모르겠습니다 ㅠ.ㅠ

https://openapi.naver.com/search?key=Client ID&query=검색키워드&taget=local&start=1&display=100

위 처럼 하면

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error>
전송된 요청을 수행하는 동안 다음과 같은 에러가 발생하였습니다.
<message>
<![CDATA[ Incorrect query request (잘못된 쿼리요청입니다.) ]]>
</message>
<error_code>
<![CDATA[ 011 ]]>
</error_code>
</error>

라고만 나오네요 ㅠ.ㅠ

**Comment by boxersb** [comment]
@smg1020 이 Github 은 네이버 지도 API JS v3 에 관한 이슈를 처리하는 곳입니다.
말씀하신 API는 검색 API이며, 올해 1월 개발자센터 개편 후 ClientId 와 Secret 으로 서버측 인증을 하는 방식으로 바뀌었습니다. 따라서, 해당 팁을 사용하기 위해서는 별도의 작업이 필요합니다.

자세한것은 네이버 개발자 센터의 개발자 포럼으로 질문해주시면 감사하겠습니다. ( http://forum.developers.naver.com/c/api )

감사합니다~~ :)

**Comment by smg1020** [comment]
@boxersb 감사합니다.
