### ISSUE TITLE
pinchZoom 이벤트 동기화 관련 질문드려요

### ISSUE THREAD

**Issue by ggagun** [navermaps/maps.js#170]
OpenLayers를 이용해 네이버 맵(javascript3 api)을 mashup 해 개발하는 중입니다.

map개체를 2개 생성해( 'div'도 2개)
기준맵(별도 gis엔진을 이용한..)에 event(moveend 등..)를 개치해 네이버맵의 위치를 맞춰주는 식인데...

모바일에서 핀치줌을 이용해 확대나 축소를 하면 (손을 떼지 않아 moveend가 발생하지 않은 상태...)
기준맵이 확대되거나 축소되는 동안 네이버지도도 기준맵에 맞춰 확대/축소 되어야 하는데..
기존의 축척이나 서비스영역이 그대로 유지되고 손을 화면에서 떼면...그때서야..action이 일어나는 문제가 있습니다.

이 부분에 대한 해결방법이 따로 있는건가요?

궁금합니다..
답변 부탁드려요~~

**Comment by junthus** [comment]
@ggagun 님 

(기준맵<- 이것도 네이버 지도 API 를 사용하고 계신거죠?)

확대되거나 축소되는 동안에 두 지도의 싱크를 완벽하게 맞추는건 구현상 불가능 하고요
핀치 시 연속적으로 일어나는 이벤트를 이용하시는게 최선일 듯 합니다. 
이 경우 물론 업데이트가 잦아지니 성능이 저하될 수 있습니다. 

모바일의 경우 [pinch]
(https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#event:pinch__anchor) 이벤트를, pc 의 경우 `drag`, `zooming` + `bounds_changed` 조합등으로 구현하시면 될 듯 합니다. 
열거한 이벤트들은 모두 [Map.Event](https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#toc36__anchor) 에서 확인하실 수 있습니다. map 의 다른 이벤트들도 한번 살펴보시고 적합한 것을 찾으시길 바랍니다. 

감사합니다.

**Comment by cs09g** [comment]
Openlayers 의 경우 fractional zoom(레벨이 정수로 고정되지 않음)인 반면 네이버는 정수형이라 완전히 맞추는게 힘들수 있을거 같아요. (혹시 네이버 맵도 레벨을 소수점으로 설정 가능한가요?)

**Comment by ggagun** [comment]
@junthus 님.
기준맵은 네이버 지도 API를 사용하지 않았습니다.
아래처럼... map개체를 생성하고 eventlistener에 move 이벤트를 등록해 위치를 동기화 처리한 상태입니다.

Openlayers3.x 로 하면 딱히 신경안써도 되던건데..
OpenLayers2.x 로 변경하니 저렇게 따로 노네요~ 훔....

그리고 cs09g님...말씀처럼 소수점 레벨은 지원하지 않는 걸로 알고 있습니다.
지원하는 해상도에 따라 미리 생성해둔 이미지만 서비스가 되는 방식이라..


**1. 맵개체 생성.**

map = new OpenLayers.Map('olmap', {
		maxExtent :  oExtent,
		maxResolution: nMaxResolution,
		minResolution: aResolution[aResolution.length-1],
		resolutions: aResolution,
        projection: new OpenLayers.Projection("EPSG:5186"),
        units: "m",
        numZoomLevels: nZoomLevels,
        autoUpdateSize : false,
        fractionalZoom : false,
        zoomMethod: null,
        eventListeners: {
            "move": **fn_sync_map**,
            "moveend": fn_event_moveend,
            // <-- 여기에 핀치 이벤트를 등록하고 처리하면 되지 않을까 싶은데...아직 해보진 않았고요.
        }
	});


**2. 지도위치 동기화 처리**
var **fn_sync_map** = function (e) {
	if(oNaverMap) {
		var center = map.getCenter();
		
		var newCenter = new Proj4js.Point(center.lon, center.lat);
		Proj4js.transform(sourceCoord, targetCoord, newCenter);
		
		oNaverMap.setCenter(new naver.maps.LatLng( newCenter.y, newCenter.x ));
		oNaverMap.setZoom( map.getZoom());
	}

    return false;
};

**Comment by thetaiz** [comment]
@ggagun 님, 올려주신 코드와 초기 질문을 봤을 때... OpenLayer에서 `move` 이벤트를 받아 핸들러에서 네이버 지도의 중심점과 줌 레벨을 설정하는 것... 질문에서 핀치 제스처 시 `move` 이벤트가 지속적으로 발생해 핸들러가 수행하는 구조인거고... OpenLayer 3.x 버전에서는 잘 되었으나... OpenLayer 2.x 버전에서는 핀치 제스처를 완료하고 터치를 해제해야 핸들러가 동작한가는 말씀이죠? 음... 우선 `fn_sync_map` 핸들러는 지속적으로 호출이 되나요?

**Comment by thetaiz** [comment]
@cs09g 님, 현재는 소수점 레벨은 안됩니다. ^^

**Comment by ggagun** [comment]
@thetaiz 님..우선 답변 감사합니다.

fn_sync_map은 지속적을 호출이 되고 있어서 패닝은 잘 되고 있습니다.
핀치 제스처 완료 후 터치가 해제된 후에야 기준맵과 네이버맵의 해상도도 맞춰지고 있구요.

그리고 OpenLayers3.x에서는 아래와 같이 기준 맵개체를 만들고
oMapMain = new ol.Map({
			    target : _sTarget,
			    renderer : 'canvas',
			    view : oViewMain,
			    pixelRatio: 1, 
			    interactions: ol.interaction.defaults({
			            altShiftDragRotate: false, 
			            pinchRotate: false,
			            dragPan: false, 
			            mouseWheelZoom: false,
			            pinchZoom:false
			          }).extend([
			            new ol.interaction.DragPan({kinetic: false}),
			            new ol.interaction.MouseWheelZoom({duration: 0}),
			            new ol.interaction.PinchZoom({constrainResolution: true}) //fractionalZoom false 효과
			          ]),
			    control: ol.control.defaults({
			          zoom: false,
			          attribution: false,
			          rotate: false
			        }),
			    layers : layerArr
			});

네이버 맵은 아래처럼.. 생성했구요.
var oNaverMap = new naver.maps.Map('naverMap', {
			    center: new naver.maps.LatLng(126.8935318, 37.4825079),
			    zoom: 14,
		        zoomControlOptions: { //줌 컨트롤의 옵션
		            position: naver.maps.Position.TOP_RIGHT
		        } 
			});
			
		   oNaverMap.setOptions({ //지도 인터랙션 켜기
	            draggable: true,
	            pinchZoom: true,
	            scrollWheel: true,
	            keyboardShortcuts: true,
	            disableDoubleTapZoom: false,
	            disableDoubleClickZoom: false,
	            disableTwoFingerTapZoom: false
	        });


두 지도를 싱크하기 위한 이벤트는 아래처럼 한거고... 
내부 처리는 중심점과 레벨 조정하는 걸로 동일합니다. 근데..핀치줌이 잘 적용되고 있었거든요.
네이버 지도 옵션 중 pinchZoom : true로 설정했기때문에...
적용이 되어야 하는 거 아닌 가 싶은데 안되네요.
물론 지금 방식도 저 옵션은 적용을 한 상태입니다.

oViewMain.on('change:center', function() {
			fn_sync_baseMap();
});

**Comment by thetaiz** [comment]
@ggagun 님, OpenLayer 버전과 상관없이 기준맵에서 핀치 제스처 시 네이버 지도 역시 핀치 줌이 되었는데... 지금은 안된다는 말씀이죠? 제가 이해한게 맞나요? ^^ OpenLayer 버전과 상관없이 발생해야 하거든요... 만약 그렇다면 v3.0.4에서 모바일 제스처는 지도 영역 내에서만 동작하도록 변경이 되어서 그렇게 동작하는 것 같아요. 초기엔 `document`에서 이벤트를 받아 처리했기에 기준맵에서 핀치 제스처를 해도 네이버 지도 API에서 핀치 제스처로 판단하고 동작을 시켰을 거에요. 지금은 지도 영역 내에서 핀치 제스처가 발생한 것이 아니기 때문에 네이버 지도는 줌 동작을 수행하지 않는 것으로 판단되네요~

- https://github.com/navermaps/maps.js/releases/tag/v3.0.4

**Comment by ggagun** [comment]
@thetaiz님...
OpenLayers2.x에서는 정상 작동한적이 없었어요.
네이버 API버전을 따로 올리거나 하지도 않았구요.

그리고 
"지금은 지도 영역 내에서 핀치 제스처가 발생한 것이 아니기 때문에 네이버 지도는 줌 동작을 수행하지 않는 것으로 판단되네요" <-- 요 말이 잘 이해가 안가네요.
지도 영역내가 아니라는...게..지도 영역 위에서 제스쳐를 취하고 있는데.
다른 이야기를 하신건지..ㅎ
암튼 빠른 답변 감사합니다.

**Comment by thetaiz** [comment]
@ggagun 아~ 헷갈리게 썼네요. 죄송합니다. 네이버 지도 영역 내에서 핀치 제스처가 발생한 것이 아니기 때문에 네이버 지도는 줌 동작을 수행하지 않는... 네이버 API 버전은 따로 올리시지 않아도 저희쪽에서 정기 배포를 진행하면 버전이 변경된(최신 버전)으로 사용하게 됩니다.

주 요지는... 

* 기존: 기준맵(OpenLayer)에서 핀치 제스처 시 네이버 지도가 함께 핀치 동작을 수행했다.
* 현재: 기준맵(OpenLayer)에서 핀치 제스처 시 네이버 지도가 핀치 동작을 수행하지 않는다. 옵션을 설정했음에도...

위와 같을 때...

* 원인(답변): v3.0.4에서 이벤트를 받는 영역이 지도 영역(네이버) 내로 변경되었기 때문에 지도 영역 밖에서 발생하는 이벤트는 처리하지 못해 기준맵에서 발생해도 네이버 지도는 핀치 제스처를 수행하지 않는다.

**Comment by thetaiz** [comment]
아~ 버전은 v3이며 하위 버전이 갱신된 것입니다.
