### ISSUE TITLE
오버레이데이터 추출및복원

### ISSUE THREAD

**Issue by seilmap** [navermaps/maps.js#171]
네이버 지도 v3 예제에서

오버레이테이터 추출및 복원이 있는데요

구현하고자 하는건
셔틀버스노선에서 각 정류장을 마크로 표시하고 설명 코멘트를 넣을려고 합니다.

1. 이때 설명 코멘트를 사용자로부터 입력을 받고 싶은데요
   구현 가능한지 궁금합니다.

2. 1번과는 별도로 infowindow 에서 표시되는 내용을 사용자로부터 입력을 받을 수 있는
    방법이 있는지 궁금합니다.

3. 1,2 번과는 별도로 
    사용자로부터 데이터를 입력받을 수 있는 방법이 있는지 궁금합니다.

**Comment by thetaiz** [comment]
@seilmap 님, 사용자로부터 입력받는 부분(1, 2, 3번 문의 모두)은 직접 구현해 이용해야 합니다. ^^
