### ISSUE TITLE
지도 검색시 중간지점 찾기는 어떻게 하나요?

### ISSUE THREAD

**Issue by goodzzong** [navermaps/maps.js#173]
예를 들어 지도를 이용을 하여 검색을 했을때 서로 다른 위치에 있는  좌표의 평균 위치를 구해서 지도영역안에 한번에 보일수 있는 평균 좌표는 어떻게 구할수잇나요?

**Comment by cs09g** [comment]
[fitBounds](https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#fitBounds__anchor) 함수를 쓰시면 될 것 같아요.

**Comment by thetaiz** [comment]
@goodzzong 님, 두 개의 좌표가 있다고 가정하고 아래와 같이 구할 수 있습니다.

var a = naver.maps.LatLngBounds.bounds(첫 번째 좌표, 두 번째 좌표)

각 좌표는 new naver.maps.LatLng 로~

그럼 두 좌표를 가지는 좌표 경계를 구할 수 있습니다. a.getCenter() 하면 중심 좌표를 구할 수 있으며, @cs09g 님 설명대로 fitBounds(a)하면 해당 좌표 경계가 보이도록 이동 및 줌 레벨 변경이 됩니다.
