### ISSUE TITLE
지오코드 주소 타입별 좌표계 변환 값이 조금씩 다르네요.

### ISSUE THREAD

**Issue by jb7959** [navermaps/maps.js#174]
안녕하세요.
궁금한게 있어서요.

REST API나 CDN 자바스크립트 호출 방식의 지오코드기능 사용시에, 
매개변수로 지번 형식의 주소와 도로명 형식의 주소를 넣었을 때 왜 값이 조금씩 다른건가요?

**Comment by thetaiz** [comment]
@jb7959 님, 문의 내용이 지번 형식의 주소와 도로명 형식의 주소를 넣었을 때 반환하는 좌표가 다른건가죠? REST API와 지도 API v3의 Geocoder 서브모듈 간의 좌표가 다른게 아니구요. ^^ 

혹시 사용하신 주소를 알려주시겠어요? 내부적으로 확인 후 알려드리겠습니다.

**Comment by jb7959** [comment]
@thetaiz 님, 네이버본사 주소를 테스트 값으로 넣고 동작한 결과입니다. 

> Argument : "경기도 성남시 분당구 불정로 6"     / retrun value = x: 127.1052133, y: 37.3595316
> Argument : "경기도 성남시 분당구 정자동 178-1" / return value = x: 127.1052208, y: 37.3595122

(REST API와 API v3 모듈 모두 동일한 결과를 보입니다.)

`https://openapi.naver.com/v1/map/geocode?query=주소`

APIv3
`naver.maps.Service.geocode({ address: '주소' }, function(status, response) {
            if (status === naver.maps.Service.Status.ERROR) {
                return alert('Something wrong!');
            }
            console.log(response.result.items[0].point);
        });
    }`

**Comment by thetaiz** [comment]
@jb7959 님, 서버측 확인 후 공유드리겠습니다.

**Comment by boxersb** [comment]
@jb7959 안녕하세요?
도로명 주소와 지번 주소의 좌표 값이 약간 차이가 날 수 있는 현상은 정상입니다.  
지번 주소는 있으나, 도로명 주소가 없는 지역도 있고, 모든 지번 주소가 도로명 주소와 1:1 매칭되는것도 아닙니다.  

따라서, 주소 체계에 따른 영역별 대표 좌표 선정에서 약간의 차이가 발생할 수 있습니다.

감사합니다~

**Comment by thetaiz** [comment]
@jb7959 님, 서버측 답변을 공유드려요. @boxersb 님이 언급해 주신 것과 같이 기준이 달라서 그렇습니다. 지번의 경우 지적(땅) 기준으로 지적 영역의 중심좌표로 서비스를 하고 있고, 도로명의 경우 건물기준으로 건물 영역의 중심 좌표로 서비스를 하고 있습니다.

**Comment by jb7959** [comment]
감사합니다. :)
