### ISSUE TITLE
polyline 관련 문의입니다.

### ISSUE THREAD

**Issue by happyboi** [navermaps/maps.js#176]
polyline도 마커 처럼 정보 표시를 할 수 있는지 궁금 합니다.

**Comment by junthus** [comment]
@happyboi 
정보창 말씀하시는거겠죠 ? 넵 가능합니다^^. 

정보창은 지정된 컨텐츠를 입력받은 위치에 표시하는 역할을 합니다. 마커를 인자로 사용하는건 마커 내의 위치값을 참조하기 위해서일 뿐이고 정보창은 사실 지도상 어디에나 표시할 수 있습니다.

[이 예제](https://navermaps.github.io/maps.js/docs/tutorial-1-infowindow-simple.example.html)를 참고하셔서 마커 대신 폴리라인을 생성하시고,`infowindow.open` 메서드 호출 시 두 번째 인자로 좌표(클릭한 지점이라던지)를 넣어주시면 될 듯 합니다. 

도움이 되시길 바랍니다.
