### ISSUE TITLE
naver.maps. InfoWindow 정보창 여는 위치 문제

### ISSUE THREAD

**Issue by crusien** [navermaps/maps.js#178]
v2에서 setPosition({bottom: -40,right :25}); 처럼 마커에서 상대적 위치에 정보창 위치를 설정하는 예제를 부탁드립니다. 설명에는 open()에 파라미터로 maps.Point좌표로 하라는 것처럼 되어 있는데 좌표위치로 
상대적 위치를 정한다는게 TM128좌표의 경우는 1만 더하거나 빼도 엄청나게 이동을 하네요.

**Comment by thetaiz** [comment]
@crusien 님, v3에서는 상대적인 좌표로 위치를 설정하는 것은 지원하지 않습니다. TM128 좌표계를 사용하고 있다면 Geocoder 서브모듈을 이용해 해당 좌표를 그대로 사용할 수 있습니다.

- https://navermaps.github.io/maps.js/docs/tutorial-2-geocoder-tm128coord.example.html
