### ISSUE TITLE
여러 개의 좌표 표시

### ISSUE THREAD

**Issue by eunwoo** [navermaps/maps.js#179]
안녕하세요? 
여행시 관심지를 지도에 표시하여 동선을 결정하기 위한 용도로 사용하고 싶습니다.

아래 스크립트는 한 개의 위치를 표시해 줍니다.

<pre><code>
<html>
  < head>
      < meta charset="UTF-8">
      <title>네이버 지도 API - 주소로 지도 표시하기</title>
      <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=oujrXZbguSLsbYVjW0iP&submodules=geocoder"></script>
  </ head>
  < body>
    < div id="map" style="width:100%;height:400px;"></div>
    <script>
      var map = new naver.maps.Map(document.getElementById('map'), {
		zoom: 11,
		mapTypeId: 'normal'
		});
      var myaddress = '강원도 인제군 남면 수산리 714';// 도로명 주소나 지번 주소만 가능 (건물명 불가!!!!)
      naver.maps.Service.geocode({address: myaddress}, function(status, response) {
          if (status !== naver.maps.Service.Status.OK) {
              return alert(myaddress + '의 검색 결과가 없거나 기타 네트워크 에러');
          }
          var result = response.result;
          // 검색 결과 갯수: result.total
          // 첫번째 결과 결과 주소: result.items[0].address
          // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x
          var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);
          map.setCenter(myaddr); // 검색된 좌표로 지도 이동
          // 마커 표시
          var marker = new naver.maps.Marker({
            position: myaddr,
            map: map
          });
          // 마커 클릭 이벤트 처리
          naver.maps.Event.addListener(marker, "click", function(e) {
            if (infowindow.getMap()) {
                infowindow.close();
            } else {
                infowindow.open(map, marker);
            }
          });
          // 마크 클릭시 인포윈도우 오픈
          var infowindow = new naver.maps.InfoWindow({
              content: '&lth4> 자작나무 오토캠핑장 &lt /h4>&lt a href="http://cafe.daum.net/jajakcamp" target="_blank">홈페이지&lt /a> &ltbr> &lta href="http://r5.camperstory.com/?141">실시간예약 &lt /a>
          });
      });
      < /script>
  </ body>
</html>
</code></pre>

만약 두 개이상의 위치를 표현하고 싶은 경우,

      var myaddress = '강원도 인제군 남면 수산리 714';// 도로명 주소나 지번 주소만 가능 (건물명 불가!!!!)
      naver.maps.Service.geocode({address: myaddress}, function(status, response) {
          if (status !== naver.maps.Service.Status.OK) {
              return alert(myaddress + '의 검색 결과가 없거나 기타 네트워크 에러');
          }
          var result = response.result;
          // 검색 결과 갯수: result.total
          // 첫번째 결과 결과 주소: result.items[0].address
          // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x
          var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);
          map.setCenter(myaddr); // 검색된 좌표로 지도 이동
          // 마커 표시
          var marker = new naver.maps.Marker({
            position: myaddr,
            map: map
          });
          // 마커 클릭 이벤트 처리
          naver.maps.Event.addListener(marker, "click", function(e) {
            if (infowindow.getMap()) {
                infowindow.close();
            } else {
                infowindow.open(map, marker);
            }
          });
          // 마크 클릭시 인포윈도우 오픈
          var infowindow = new naver.maps.InfoWindow({
              content: '<h4> 자작나무 오토캠핑장</h4><a href="http://cafe.daum.net/jajakcamp" target="_blank">홈페이지</a><br><a href="http://r5.camperstory.com/?141">실시간예약</a>'
          });
      });
부분을 여러번 사용하면 가능한 것을 확인했습니다.

하지만, 소스의 가독성이 떨어지고 소스가 커집니다.
myaddress를 배열로 변경하여 여러 개의 위치를 표시하고 싶은 경우에는 어떻게 해야 하는지요?
아래와 같이 했을 때 잘 동작하지 않습니다.
<pre><code>
var myaddress = [
["강원도 인제군 남면 수산리 714", "자작나무 오토캠핑장"]
,["강원도 홍천군 서면 팔봉리 1290-14", "오션월드"]
,{"강원도 평창군 봉평면 태기로 174 피닉스평창"}
,{"강원 홍천군 내촌면 답풍리 1번지"}
,{"강원도 춘천시 남산면 산수리 458"}
,{"경기 가평군 설악면 가마소길 18-16"}
,{"강원도 홍천군 서석면 검산길 263"}
,{"강원도 홍천군 화촌면 구룡령로 1016-29"}
,{"강원도 양구군 남면 도촌리 96-5"}
];

for (var i=0; i < myaddress.length; i++) {

	naver.maps.Service.geocode({address: myaddress[i][0]}, function(status, response) {
	  if (status !== naver.maps.Service.Status.OK) {
		  return alert(myaddress[i][0]+ '의 검색 결과가 없거나 기타 네트워크 에러');
	  }
	  result[i] = response.result;
	  // 검색 결과 갯수: result.total
	  // 첫번째 결과 결과 주소: result.items[0].address
	  // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x
	  myaddr[i] = new naver.maps.Point(result[i].items[0].point.x, result[i].items[0].point.y);
	  map.setCenter(myaddr[i]); // 검색된 좌표로 지도 이동
	  // 마커 표시
	  marker[i] = new naver.maps.Marker({
		position: myaddr[i],
		map: map
	  });
	  // 마커 클릭 이벤트 처리
	  naver.maps.Event.addListener(marker[i], "click", function(e) {
		if (infowindow.getMap()) {
			infowindow.close();
		} else {
			infowindow.open(map, marker[i]);
		}
	  });
	  // 마크 클릭시 인포윈도우 오픈
	  infowindow[i] = new naver.maps.InfoWindow({
		  content: '&lt h4>' + myaddress[i][1] + '&lt /h4>&lt a href="http://cafe.daum.net/jajakcamp" target="_blank">홈페이지&lt /a>&lt br>&lt a href="http://r5.camperstory.com/?141">실시간예약&lt /a>'
	  });
  });
</code></pre>

**Comment by thetaiz** [comment]
@eunwoo 님, 잘 동작하지 않는다는 것이 구체적으로 어떤 것이 동작하지 않는지 설명해 주시면 좋겠습니다.

**Comment by eunwoo** [comment]
여러개의 주소를 지도에 한 번에 표현하기 위해서 myaddress를 배열로 만들고,
주소와 상호를 추가했습니다.
첫번 째 그림처럼 장소가 등록은 됩니다. 하지만 html파일을 실행하면 두번 째 그림처럼 서울시청이 표시가 되는데, map.setCenter()가 동작하지 않는 것 처럼 보입니다.
관련 내용을 검색해보면 동기식, 비동기식 호출이라는 용어가 나오는데, callback함수를 사용하는 방식이 비동기식인가요? function(status, response) 함수를 사용하는 방식이 비동기식인 것 처럼 보이는데, 함수안에 사용하는 변수가 local변수라서 일단은 Array 전역변수로 초기화를 해주기는 했는데요.
![multiple place](https://user-images.githubusercontent.com/8966503/28143186-5cbb3d9c-679f-11e7-99c0-74f75a8535d0.PNG)
![multiple place wrong](https://user-images.githubusercontent.com/8966503/28143251-9186d6f8-679f-11e7-945d-c4b53d07ca03.PNG)

<pre><code>
		var myaddress = [
		["강원도 인제군 남면 수산리 714", "자작나무 오토캠핑장"]
		,["강원도 홍천군 서면 팔봉리 1290-14", "오션월드"]
		,["강원도 평창군 봉평면 태기로 174 피닉스평창", "오션월드"]
		,["강원 홍천군 내촌면 답풍리 1번지", "오션월드"]
		,["강원도 춘천시 남산면 산수리 458", "오션월드"]
		,["경기 가평군 설악면 가마소길 18-16", "오션월드"]
		,["강원도 홍천군 서석면 검산길 263", "오션월드"]
		,["강원도 홍천군 화촌면 구룡령로 1016-29", "오션월드"]
		,["강원도 양구군 남면 도촌리 96-5", "오션월드"]
		];
		var result = new Array();
		var myaddr = new Array();
		var marker = new Array();
		var infowindow = new Array();
		for (var i=0; i < myaddress.length; i++) {
//			alert(myaddress[i][0]);
			naver.maps.Service.geocode({address: myaddress[i][0]}, function(status, response) {
				if (status !== naver.maps.Service.Status.OK) {
					return alert(myaddress[i][0]+ '의 검색 결과가 없거나 기타 네트워크 에러');
				}
				result[i] = response.result;
				  //alert(JSON.stringify(result[i]));
				myaddr[i] = new naver.maps.Point(result[i].items[0].point.x, result[i].items[0].point.y);
				if(i == 0) {
					map.setCenter(myaddr[i]); // 검색된 좌표로 지도 이동
				}
				// 마커 표시
				marker[i] = new naver.maps.Marker({
					position: myaddr[i],
					map: map
				});
				// 마크 클릭시 인포윈도우 오픈
				infowindow[i] = new naver.maps.InfoWindow({
					content: '&lth4> 자작나무 오토캠핑장&lt/h4>&lta href="http://cafe.daum.net/jajakcamp" target="_blank">홈페이지</a><br>&lta href="http://r5.camperstory.com/?141">실시간예약</a>'
				});
				// 마커 클릭 이벤트 처리
				naver.maps.Event.addListener(marker[i], "click", function(e) {
					if (infowindow[i].getMap()) {
						infowindow[i].close();
					} else {
						infowindow[i].open(map, marker[i]);
					}
				});
			});
		}
</code></pre>
네이버 예제를 그대로 실행하면(myaddress가 배열이 아닌 경우), 아래 그림과 같이 center가 표시됩니다.
![single place](https://user-images.githubusercontent.com/8966503/28143191-61382fb0-679f-11e7-8074-a7b085aedbda.PNG)

**Comment by eunwoo** [comment]
원하는 기능을 완성하였습니다. 아래 코드를 참고하시기 바랍니다.
한 개의 콜백 함수로 여러 개의 주소에 대해서 처리하려다 보니, sleep 함수가 없으면 순서가 안 맞는 경우가 있습니다. myaddress 배열에 있는 순서대로 응답을 받으려면 sleep가 필요합니다. 또한 marker 클릭 이벤트 콜백함수의 경우 어떤 marker를 클릭했는지 판단하기 위해서 클릭한 좌표와 가장 가까운 marker를 찾는 부분이 추가되어야 했습니다.

<pre>
function sleep(num){	//[1/1000초]
	 var now = new Date();
	   var stop = now.getTime() + num;
	   while(true){
		 now = new Date();
		 if(now.getTime() > stop)return;
	   }
}
    var map = new naver.maps.Map(document.getElementById('map'), {
		zoom: 4,
		mapTypeId: 'normal'
		});
		
		// 도로명 주소나 지번 주소만 가능 (건물명 불가!!!!)
//		var myaddress = ["강원도 인제군 남면 수산리 714"];
		var myaddress = [
		["강원도 인제군 남면 수산리 714", "자작나무 오토캠핑장", "http://cafe.daum.net/jajakcamp"]
		,["강원도 홍천군 서면 팔봉리 1290-14", "오션월드", "about:blank"]
		,["강원도 평창군 봉평면 태기로 174 피닉스평창", "피닉스파크", "about:blank"]
		,["강원 홍천군 내촌면 답풍리 1번지", "수캠프", "about:blank"]
		,["강원도 춘천시 남산면 산수리 458", "황금박쥐캠핑장 춘천점", "about:blank"]
		,["경기 가평군 설악면 가마소길 18-16", "맑은물소리캠핑장", "about:blank"]
		,["강원도 홍천군 서석면 검산길 263", "?", "about:blank"]
		,["강원도 홍천군 화촌면 구룡령로 1016-29", "알프스밸리", "about:blank"]
		,["강원도 양구군 남면 도촌리 96-5", "국토정중앙천문대", "about:blank"]
		];
		var result = new Array();
		var myaddr = new Array();
		var marker = new Array();
		var infowindow = new Array();
		var response_state = 0;
		var j=0;
		for (var i=0; i < myaddress.length; i++) {
//			alert(myaddress[i][0]);
			naver.maps.Service.geocode({address: myaddress[i][0]}, function(status, response) {
				if (status !== naver.maps.Service.Status.OK) {
					return alert(myaddress[i][0]+ '의 검색 결과가 없거나 기타 네트워크 에러');
				}
				result[j] = response.result;
				//alert(JSON.stringify(result[j]));
				myaddr[j] = new naver.maps.Point(result[j].items[0].point.x, result[j].items[0].point.y);
				//alert(myaddr[j].toString());
				console.log(j+":"+myaddr[j].toString());
//				console.log(j);
				if(j == myaddress.length-1) {
					map.setCenter(myaddr[j]); // 검색된 좌표로 지도 이동
				}
				// 마커 표시
				marker[j] = new naver.maps.Marker({
					position: myaddr[j],
					map: map
				});
				// 마크 클릭시 인포윈도우 오픈
				infowindow[j] = new naver.maps.InfoWindow({
					content: '&lth4>'+myaddress[j][1]+'</h4>&lta href="'+ myaddress[j][2] +'" target="_blank">홈페이지</a><br>&lta href="http://r5.camperstory.com/?141">실시간예약</a>'
				});
				// 마커 클릭 이벤트 처리
				naver.maps.Event.addListener(marker[j], "click", function(e) {
				//alert(e.coord.toString());
				//alert(e.coord.x+","+e.coord.y);
					var x,y;
					x = e.coord.x;
					y = e.coord.y;
					var sel = 0;
					var dist_min = Math.sqrt((marker[0].position.x-x)*(marker[0].position.x-x)+(marker[0].position.y-y)*(marker[0].position.y-y));
//					alert(dist);
					var dist_new = 0;
					for(var k=1; k<j; k++) {
						//alert(marker[k].position.x);
						dist_new = Math.sqrt((marker[k].position.x-x)*(marker[k].position.x-x)+(marker[k].position.y-y)*(marker[k].position.y-y));
						//alert(dist_new);
						if(dist_new < dist_min) {
							dist_min = dist_new;
							sel = k;
						}
					}
					if (infowindow[sel].getMap()) {
						infowindow[sel].close();
					} else {
						infowindow[sel].open(map, marker[sel]);
					}
				});
				response_state = i;
				j++;
			});
			sleep(40);

		}
</pre>

**Comment by davidshimjs** [comment]
@eunwoo 클로저 문제로 보입니다. for 문의 블럭 안에서는 자유 변수가 생기지 않기 때문에 naver API의 응답이 오기 전에 이미 for 문은 끝까지 동작한 상태가 됩니다. Promise를 사용하시거나 클로저를 효과적으로 사용해보세요.

**Comment by eunwoo** [comment]
아래와 같이 naver.maps.Service.geocode를 함수안에 두어서 객체화하면 각각의 주소가 객체가되어 구현이 간단해 집니다.
<pre>
function register_address(myaddress, name) {
      naver.maps.Service.geocode({address: myaddress}, function(status, response) {
          if (status !== naver.maps.Service.Status.OK) {
              return alert(myaddress + '의 검색 결과가 없거나 기타 네트워크 에러');
          }
          var result = response.result;
//		  alert(JSON.stringify(result));
          // 검색 결과 갯수: result.total
          // 첫번째 결과 결과 주소: result.items[0].address
          // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x
          var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);
          map.setCenter(myaddr); // 검색된 좌표로 지도 이동
          // 마커 표시
          var marker = new naver.maps.Marker({
            position: myaddr,
            map: map
          });
          // 마커 클릭 이벤트 처리
          naver.maps.Event.addListener(marker, "click", function(e) {
            if (infowindow.getMap()) {
                infowindow.close();
            } else {
                infowindow.open(map, marker);
            }
          });
          // 마크 클릭시 인포윈도우 오픈
          var infowindow = new naver.maps.InfoWindow({
              content: '&lth4>'+name+'&lt/h4>&lta href="http://cafe.daum.net/jajakcamp" target="_blank">홈페이지&lt/a>&ltbr>&lta href="http://r5.camperstory.com/?141">실시간예약&lt/a>'
          });
      });
}

      var map = new naver.maps.Map(document.getElementById('map'), {
		zoom: 4,
		mapTypeId: 'normal'
		});
		
		// 도로명 주소나 지번 주소만 가능 (건물명 불가!!!!)
//		var myaddress = ["강원도 인제군 남면 수산리 714"];
		var myaddress = [
		["강원도 인제군 남면 수산리 714", "자작나무 오토캠핑장", "http://cafe.daum.net/jajakcamp"]
		,["강원도 홍천군 서면 팔봉리 1290-14", "오션월드", "about:blank"]
		,["강원도 평창군 봉평면 태기로 174 피닉스평창", "피닉스파크", "about:blank"]
		,["강원 홍천군 내촌면 답풍리 1번지", "수캠프", "about:blank"]
		,["강원도 춘천시 남산면 산수리 458", "황금박쥐캠핑장 춘천점", "about:blank"]
		,["경기 가평군 설악면 가마소길 18-16", "맑은물소리캠핑장", "about:blank"]
		,["강원도 홍천군 서석면 검산길 263", "?", "about:blank"]
		,["강원도 홍천군 화촌면 구룡령로 1016-29", "알프스밸리", "about:blank"]
		,["강원도 양구군 남면 도촌리 96-5", "국토정중앙천문대", "about:blank"]
		];
		for (var i=0; i < myaddress.length; i++) {
			register_address(myaddress[i][0], myaddress[i][1]);
		}
</pre>

**Comment by eunmokKim** [comment]
도움 정말 많이 되었습니다.
감사합니다.
