### ISSUE TITLE
안녕하세요, Naver Map API를 처음 접하는데 실내지도 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by HeeJung-Sohn** [navermaps/maps.js#18]
안녕하세요,

Naver Map에서 제공하는 실내지도와 Map API를 이용해서 그 지점에서 실내지도 정보를 이용하고, 추가적인 디스플레이 및 사용자 인터페이스 기능이 부가된 길 안내 App을 제작할 수 있을지 궁금합니다. 실내지도 관련한 예제가 있는지, 실내지도 네비게이션 관련한 예제가 혹시 있는지 궁금합니다.

감사합니다.

**Comment by thetaiz** [comment]
@HeeJung-Sohns 님, 안녕하세요. 

아쉽지만 실내지도, 내비게이션 관련 API는 없습니다.

감사합니다.
