### ISSUE TITLE
폴리라인, 폴리곤 문의

### ISSUE THREAD

**Issue by anhanho** [navermaps/maps.js#180]
안녕하세요 

몇가지 궁금한게 있어서 문의 드립니다.

1.폴리라인에 라인에 대한 간단한 정보를 텍스트로 보여줄수 있는지?

2.폴라리인을 마우스 오버하면 infowindow  같은 부가 정보 표시 이벤트를 발생할 수 있는지?

3. 폴리곤 클릭하면 이벤트를 발생할 수 있는지 ? 

4. 화면에 버텍스 정보를 8천개정도 뿌려주고 폴라라인을 그렸는데, 화면이 버벅거리는데.. 가동성 좋은 코드 가이드라인을 주실수 있는지 ?

궁금합니다.

수고하십시요.

**Comment by thetaiz** [comment]
@anhanho 님, 

* 1 - 폴리라인에 정보를 텍스트로 보여주려면 사용자 정의 오버레이를 만들어 사용해야 할 것 같아요.
* 2, 3 - 폴리라인(오버레이)의 이벤트는 아래 예제를 참고해 주시구요. 정보 창을 예로 들면 이벤트 핸들러에서 `infowindow.open()` 메서드를 사용하면 정보 창을 열 수 있습니다. 자세한 건 해당 API 레퍼런스를 참고해 주세요.
* 4 - 다량의 폴리라인을 모두 올리면 성능에 이슈가 있을 수 있습니다. 몇 가지 팁은 보이는 영역에 한정해서 폴리라인을 그리는 것과, 줌 레벨에 따라 폴리라인의 좌표 개수를 simplify해 성능을 가져가면서 폴리라인을 그리는 방법이 있습니다.
