### ISSUE TITLE
지도위 모든 마커 또는 모든 오버레이객체 지우기

### ISSUE THREAD

**Issue by rladmdrl77** [navermaps/maps.js#181]
안녕하세요.

1400개 정도의 마커 객체를 배열에 저장한 후 배열만큼 루프를 돌면서 
marker.setMap(null);  로 지웠습니다.

모두 지워지긴 하나 4초 정도의 시간이 걸립니다.(물론 마커에 걸려있는 이벤트가 있다면 삭제하는 로직 추가 되어있음).

map에 올라가있는 모든 오버레이객체를 빠르게 지울수 있는 방법이 없나요?

**Comment by davidshimjs** [comment]
@rladmdrl77 커스텀 오버레이를 하나의 가상 레이어로 쓰시고, 지울 때 해당 레이어를 제거하시면 한 번에 지우실 수 있습니다.

**Comment by thetaiz** [comment]
@davidshimjs 커스텀 오버레이를 그렇게 활용할 수 있네요~ ^^ 감사합니다.
