### ISSUE TITLE
Naver 지도 API 사용에 관해 질문 드립니다.

### ISSUE THREAD

**Issue by saturn75** [navermaps/maps.js#183]
Naver 지도 API를 사용하여 웹화면을 구현하려고 합니다.
몇가지 질문이 있어 문의 드립니다.
1.  Naver 지도 API는 일 20만회 사용이 가능하다고 알고 있습니다.
     일 사용횟수 산정 방법 및 Client에서 사용횟수를 알수 있을까요?
     (가령 지도 로드시 사용횟수가 카운트 된다던지 아님 지도내에서 위치 검색시 마다 사용횟수가 카운트
      된다던지...)
2. 일 사용횟수를 초과시 별도의 제휴를 신청 해야 한다고 하는데 제휴시 기간 제한이 있나요?
    그리고 제휴시에는 일 사용횟수가 어떻게 되나요?

꼭 답변 부탁 드립니다.
메일로 주셔도 됩니다. saturn7575@naver.com

**Comment by thetaiz** [comment]
@saturn75 님, 초기 지도 스크립트 로드 시 1회 차감입니다. 제휴와 관련해서는 네이버 개발자 센터의 제휴 문의를 이용해 주세요~ ^^
