### ISSUE TITLE
GeoJson 데이터 레이어 표시하기 후 맵 클릭

### ISSUE THREAD

**Issue by csterry12** [navermaps/maps.js#185]
국가공간정보포털에 지적도를 불러와서 지도에 GeoJson 데이터 레이어를 표시하고 있는데요.
데이터 레이어로 표시한 부분이 맵 클릭하면 좌표를 알아야 하는데 이벤트가 발생하지 않습니다. ㅠ.ㅠ
데이터 레이어를 표시한 후에도 맵을 클릭해서 좌표를 뽑을 수 있는 방법이 없을까요?

**Comment by thetaiz** [comment]
@csterry12 님, 아래 튜토리얼을 확인해 주세요~ ^^ 데이터 레이어에서 이벤트를 사용하는 방법이 있습니다.

- https://navermaps.github.io/maps.js/docs/tutorial-DataLayer.html

**Comment by csterry12** [comment]
네이버지도에서 제공하는 지적편집도와 동일하게 표현되도록 국가공간정보포털에서 연속지적도를 다운받아 postgresql로 지도 영역 안에 있는 모든 지적을 geojson으로 지도에 뿌려주고 있는데요.
검색 기능을 이용하면 해당 필지에 좌표를 뽑을 수는 있지만 geojson으로 뿌려진 맵[데이터레이어]를 클릭하면 좌표를 얻지 못합니다.
국가공간정포털에서 wms를 이용해서 groundoverlay로 지도에 뿌려주면 맵이 클릭이 되어 좌표를 추출할 수 있거든요. ㅠ.ㅠ
위 예제에서는 어떻게 구현해야 하는지 막연한데요. 힌트 좀 주실 수 없나요? ㅠ.ㅠ

**Comment by thetaiz** [comment]
@csterry12 님, 데이터 레이어를 이용하신거죠? 그리고 데이터 레이어의 이벤트 연동을 이용하신거죠? 그래도 클릭 시 이벤트가 발생하지 않는다는 말씀으로 보이는데 구현한 코드가 어떻게 되나요?

**Comment by csterry12** [comment]
제가 받은 데이터는 국가공간정보포털에 용도지역지구정보 중 산지관리/보전준보전산지의 shp파일입니다.
이 shp파일을 postgresql 테이블에 넣었습니다. 테이블은 gid, a0, a1, a2, a3, geom으로 컬럼이 구성되어 있습니다.
제가 스프링으로 개발하고 있는데요. 맵퍼 파일은 이렇습니다.
<select id="d054" resultType="MapVO">
		<![CDATA[
		SELECT row_to_json(fc) as feature
 			FROM ( 
				SELECT 'FeatureCollection' As type, 
     				array_to_json(array_agg(f)) As features
 					FROM (SELECT 'Feature' As type
    				, ST_AsGeoJSON(geom)::json As geometry
    				, row_to_json((a1, a2, a3)) As properties
					FROM al_00_d054 where geom && ST_MakeEnvelope(#{left}, #{bottom}, #{right}, #{top}, 4326)) 
     			As f )  
		As fc;
		]]>
	</select>
웹에 체크박스를 두고 이벤트를 걸어 함수를 호출하도록 구성하였습니다.
function san() {
		if($("#san").is(':checked')){
			
			if(zoom > 11) {
				$.ajax({
					type:"get",
					url: "/test/test/d054?left="+left+"&bottom="+bottom+"&right="+right+"&top="+top2,
					async: false,
					success: function(result) {
						//console.log(result);
						map.data.setStyle(function(feature) {
					    	//console.log(feature.property_f1);
					    	if(feature.property_f1.indexOf('UFM200') != -1) {
					    		var styleOptions = {
						                fillColor: '#008000',
						                fillOpacity: 0.5,
						                strokeColor: '#008000',
						                strokeWeight: 1,
						                strokeOpacity: 1
								};
					    	} else if(feature.property_f1.indexOf('UFM120') != -1) {
					    		var styleOptions = {
						                fillColor: '#ff0000',
						                fillOpacity: 0.5,
						                strokeColor: '#ff0000',
						                strokeWeight: 1,
						                strokeOpacity: 1
								};
					    	} else {
					    		var styleOptions = {
						                fillColor: '#0000FF',
						                fillOpacity: 0.5,
						                strokeColor: '#0000FF',
						                strokeWeight: 1,
						                strokeOpacity: 1
								};
					    	}
							

					        return styleOptions;
					    });
						var san = JSON.parse(result[0].feature);

						for(i=0; i<san.features.length; i++) {
							var san2 = san.features[i];
							map.data.addGeoJson(san2);
						}
					}
				});
			} else {
				alert("현재 스케일에서 지원하지 않습니다.");
				$("#san").prop('checked', false) ;
			}

		} else {
		     
		     var features2 = map.data.getAllFeature();
		     
		     for(i=0; i<features2.length; i++) {
		    	 
		    	 map.data.removeFeature(features2[i]); //일부분만 삭제됨
		     }
		     
		}
	}
geojson으로 받은 데이터를 맵에 잘 뿌려지고 있는데요.
하나에 피쳐가 여러 필지(지번)에 걸쳐져서 표시되거든요. 
여기까지는 마음 먹은 대로 구현이 되는데 문제는 geojson으로 뿌려진 데이터레이어 위 맵을 클릭했을 때
해당 위치에 좌표를 뽑고 싶거든요. geojson의 피처 중심좌표 혹은 경계좌표가 아니구요.<--- 이거 뽑으려면 맵퍼에서 불러올 때부터 피처의 property로 구현되기 때문에 불필요하거든요.
해당 좌표를 뽑아야 다시 postgresql에 있는 연속지적도 테이블을 이용해서 pnu를 뽑고 국가공간정포털에서 api로 연계해서 토지이용계획을 아래와 같이 웹에 표시해주려는 거에요.
//토지이용계획
	function use(pnu) {
		var html0 = "<table class='table table-bordered'>";
		html0 += "<tr class='success'>";
		html0 += "<td colspan='2'>토지이용계획</td>";
		//토지이용계획
		html0 += "<tr class='active'><td>용도지역</td><td>저촉여부</td></tr>";
		$.ajax({
			type:"get",
			url: 'http://openapi.nsdi.go.kr/nsdi/LandUseService/attr/getLandUseAttr?format=json&authkey=mykey&pnu='+pnu,
			async: false,
			//dataType: "json",
			success: function(result) {
				
				for(i=0; i < result.landUses.field.length; i++) {
					html0 += "<tr>";
					html0 += "<td>"+result.landUses.field[i].prposAreaDstrcCodeNm;
					html0 += "</td>";
					html0 += "<td>"+result.landUses.field[i].cnflcAtNm;
        			html0 += "</td>";
					html0 += "</tr>";
				}
			}
		});
		document.getElementById("use").innerHTML = html0;
	}
1. geojson  데이터레이어가 뿌려진 맵을 클릭했을 때 마우스가 클릭된 좌표를 뽑고 싶어요. ㅠ.ㅠ
2. 이렇게 하다보니 removefeature로 피처를 삭제하려는데 일부분만 삭제되고 전부 삭제는 안되네요. ㅠ.ㅠ. 혹시 이것도 아시나요?

**Comment by thetaiz** [comment]
@csterry12 님, 클릭 이벤트를 바인딩해서 사용하는 부분의 코드는 어떻게 되나요? map.data.addListener 요걸 이용해야 합니다. 자세한 것은 데이터 레이어 이벤트 활용하기 부분을 참고해 주세요.

- https://navermaps.github.io/maps.js/docs/tutorial-DataLayer.html

그리고 2번의 경우 저희가 테스트를 해보겠습니다.

**Comment by csterry12** [comment]
map.data.addListener를 적용하니까 좌표를 뽑을 수 있네요. 감사합니다. ㅠ.ㅠ 
여전히 removefeature는 적용이 안되네요. ㅠ.ㅠ

**Comment by thetaiz** [comment]
@csterry12 님, removeFeature 동작을 확인해 보셨나요?

**Comment by thetaiz** [comment]
@csterry12 님, 이슈를 종료합니다. 혹여 동일한 현상이 나타나면 이슈를 다시 열어주세요~
