### ISSUE TITLE
화면에 표시된 마커를 어떻게 선택하나요?

### ISSUE THREAD

**Issue by fromkt** [navermaps/maps.js#186]
마커를 50개정도 표시하고있는데요 줌인시 마커를 ajax로 리로딩하면서
기존 마커를 지우고 새로운 마커를 표시하고있습니다.
문제는 기존마커중에 남겨둬야되는 경우(선택된 마커들)가 생기는데  마커에 클래스를 줄수도 없고
어떤식으로 남겨둬야될마커를 구분할수있을지 알고싶습니다.

**Comment by thetaiz** [comment]
@fromkt 님, 마커를 클릭했을 때 마커에 커스텀으로 프로퍼티를 설정하셔도 될 것 같아요. 제거 시 해당 프로퍼티가 있으면 지우지 않는 것으로...

**Comment by davidshimjs** [comment]
@fromkt 화면에 표시된 마커 목록을 내부 변수로 관리하는 것이 좋습니다. 여기에 데이터를 두셔도 좋고, 마커의 멤버변수로 데이터를 두셔도 되지만, 네이버 API의 프로퍼티명과 겹칠 수도 있으니 `__name` 등의 잘 쓰지 않는 prefix를 활용해 주시면 더 좋습니다.
