### ISSUE TITLE
마커 클러스터링 관련 문의

### ISSUE THREAD

**Issue by Jiyong-C-Lee** [navermaps/maps.js#187]
마커 클러스터링 api를 이용중인데, clustering._clearCluster() 를 호출하고 다시 마커를 생성하면 생성한 직후에는 이전 클러스터와 마커들이 사라지는데 지도를 움직이면 다시 생성됩니다. 어떻게 해결하면 좋을까요.
_redraw, _clear, _update 중 어떤 함수를 사용해야 좋을지..?

**Comment by cs09g** [comment]
해당 메소드는 언더바(_)가 있는 것으로 봐서 private이므로 사용하지 않는 것이 좋구요, `clustering.setMap()`을 사용하시는 것을 추천드립니다.

**Comment by Jiyong-C-Lee** [comment]
아 해결되었습니다. 감사해요!
