### ISSUE TITLE
맵드래그시 내부 Offset 위치 안바뀌는 이슈 

### ISSUE THREAD

**Issue by truegrave** [navermaps/maps.js#188]
fromCoordToOffset 메서드등을 이용 특정 위경도의 위치를 현재 화면상의 좌표로

가져오려할때 같은 위경도임에도 불구하고 지도상에 가르키는 위치가 

처음 시도 한 결과와 맵을 드래그 하고 난 이후의 결과가 다릅니다.

fromOffsetToCoord 등의 반대로 사용하는 메서드 역시 마찬가지이며

맵에 Zoom등의 이벤트가 발생해야만 내부 Projection이 제대로 변경되는듯 보입니다.

**Comment by boxersb** [comment]
@truegrave 안녕하세요?

`fromCoordToOffset` 시 가져온 Offset 데이터는 지도의 이동, 줌 변경등에 따라 달라집니다.
즉, `Offset`은 유니크한 지점을 가리키는 데이터로 사용할 수 없습니다. 그러나,
`fromCoordToPoint` 는 유니크한 지점을 가리킵니다.. `Coord`와 `Point`는 같은 좌표를 가리키지만 `Offset`은 화면상의 좌표로 사용하려는 용도로... 지도 이동/줌 변경등에 따라 변화하는 좌표입니다.

감사합니다.
