### ISSUE TITLE
IE9, IE10에서 지도가 정상적으로 로드가 안되는 현상

### ISSUE THREAD

**Issue by crusien** [navermaps/maps.js#189]
IE11, 크롬, 파이어폭스에서는 정상적으로 로드되지만

IE9, 10브라우져를 직접 사용하거나  IE11의 개발자도구에서 IE9, 10으로 에뮬레이션 시 지도가 로드되지 

않고 있습니다.

스크립트 오류는 발생하지 않으며 디버거로 추적해도 특이점을 발견할 수 없었습니다.

JS파일들도 정상적으로 로드되어 있습니다.

![2017-07-26 10 22 08_0](https://user-images.githubusercontent.com/29968976/28600367-7c93c934-71ec-11e7-8e04-c8ec638af956.png)

this.oMap = new naver.maps.Map(document.getElementById(this.mapconf.mapid), { 
						center : oStartPoint,
						zoom : this.mapconf.zoom,
						zoomControl : true,
						zoomControlOptions: {position: naver.maps.Position.TOP_RIGHT},
						mapTypeControl: true,
						zoom:10,
						minZoom : 10,
						maxZoom : 14,
						logoControl:false,
						scrollWheel : true,
						draggable : true,
						disableDoubleClickZoom : true,
						scaleControl:true,
						scaleControlOptions:{position: naver.maps.Position.BOTTOM_RIGHT},
						size : oSize, 
						mapTypeId: 'normal',
						mapTypeControl:true,
					    mapTypes: new naver.maps.MapTypeRegistry({
					        'normal': naver.maps.NaverMapTypeOption.getNormalMap({
					            projection: naver.maps.TM128Coord
					        }),
					        'terrain': naver.maps.NaverMapTypeOption.getTerrainMap({
					            projection: naver.maps.TM128Coord
					        }),
					        'satellite': naver.maps.NaverMapTypeOption.getSatelliteMap({
					            projection: naver.maps.TM128Coord
					        }),
					        'hybrid': naver.maps.NaverMapTypeOption.getHybridMap({
					            projection: naver.maps.TM128Coord
					        })
					    })
	
		});

기본 옵션은 이렇게 했지만 옵션을 전부 제거해도 마찬가지로 로딩이 안됩니다. 에뮬레이션을 기본값으로 돌리면 정상적으로 지도가 출력됩니다.

**Comment by thetaiz** [comment]
@crusien 님, 혹시 호환성 보기가 켜져있는지 확인을 부탁드립니다.

**Comment by crusien** [comment]
호환성 보기는 켜져있지 않습니다.

**Comment by crusien** [comment]
![2017-07-26 10 51 31_0](https://user-images.githubusercontent.com/29968976/28600968-6f5e7ce2-71f0-11e7-8fe2-099b50c5c9c3.png)

지도 옵션버튼이나 컨트롤은 로드 되지만 타일및 좌표 로드가 안되는거 같습니다.

**Comment by thetaiz** [comment]
@crusien 님, 저희쪽에서 볼 수 있는 URL 공유가 가능할까요? 공개가 힘들면 메일로 공유를 부탁드립니다. 

* mapsopenapi@naver.com

**Comment by crusien** [comment]
www.golfzon.com/shop/branch 에서 보실 수 있습니다. IE9, 10에서 새로고침 시 로드가 될때도 있지만 대부분
안됩니다.
그 외 브라우저에서는 정상 작동을 하는군요.

2017-07-26 11:09 GMT+09:00 Yonghwan Lee <notifications@github.com>:

**Comment by thetaiz** [comment]
@crusien 님, 아래 저희 예제 페이지 역시 동일한지 확인을 부탁드려요. 저희가 IE9, 10에서 확인 시 주신 링크에서만 타일을 불러오지 못하고 있는 현상이 있어서요. 그리고 등록한 URL에서 'www'를 제거하면 www.golfzon.com, golfzon.com 모두 인증을 성공합니다. 지금은 등록한 URL에 www가 있어서 golfzon.com과 같이 들어가면 인증 오류가 발생하네요.

* https://navermaps.github.io/maps.js/docs/tutorial-2-geocoder-tm128coord.example.html

**Comment by crusien** [comment]
예제로 주신 페이지에서는 IE9, 10 에뮬레이션 상태에서도 정상으로 지도가 뜹니다.  www을 제거해야 하는 건가요?

**Comment by thetaiz** [comment]
@crusien 님, www는 사용자가 www를 입력하지 않고, golfzon.com으로 접근해 지도가 있는 곳으로 갈 경우 API 인증 오류로 지도 자체를 사용할 수 없게 되는 것을 방지하고자 알려드린 것이에요~ ^^

해당 페이지에서 IE의 개발자 도구 디버깅을 시작해 놓고 보면 태그 관련 몇 가지 알림이 있는데, 그 부분을 우선 확인해 주시겠어요? 저희 예제 페이지가 정상적으로 동작하는 것을 봐서는 API 이슈는 아니고 해당 페이지의 HTML 문제일 수 있어 보여서요.

**Comment by crusien** [comment]
js를 제거하고 해당 페이지 html에서만 지도를 띄우는건 문제없이 뜹니다.
다각도로 테스트한 결과를 말씀드리면 
문제1. 지도가 로드될 div의 스타일의 width height를 픽셀로 지정하면 지도가 정상적으로 뜨지만 100%식으로 줬을때는 지도가 뜨질 않습니다. 
문제2.
만들어진 js의 클래스안에서 this.oMap = new naver.maps.Map(document.getElementById(this.mapconf.mapid)) 이런 형식으로 무옵션으로 지도를 호출하면 지도가 잘 뜹니다. 하지만 옵션을 단 한개라도 주면 타일이 로드되지 않습니다.

**Comment by crusien** [comment]
문제점을 확인하여 다른 이슈로 다시 열겠습니다.
