### ISSUE TITLE
타 지도 웹의 장소의 명칭 및 좌표를 이용, 네이버지도 웹 경로안내 방법문의

### ISSUE THREAD

**Issue by eussi1026** [navermaps/maps.js#19]
안녕하세요.!
저희는..
타 지도 API(올레맵)이용하여 경로안내 기능을 구현하여 서비스를 하고 있는데요..
저희 서비스에서 출발지/목적지/경유지를 입력하여 검색된 경로정보(최적/무료 등등..) 호출하는데
네이버지도의 경로안내정보를 저희 시스템에서 미리 입력된 정보(출발지/목적지/경유지)의 값을 넘겨서
바로 네이버지도를 호출하고 싶습니다.
다시 말해, 저희 시스템에서 버튼 하나 클릭하면 바로 해당 정보를 가지고 네이버지도를 새창으로 띄워서 바로 경로안내정보를 확인하려고 하는데요.
혹시 가능한지요? 별도의 권한이 필요한지, 또 어떻게 구현하면 되는지 문의드립니다.

**Comment by thetaiz** [comment]
@eussi1026 님, 안녕하세요. 아래와 같이 이해를 하고 답변을 드립니다. 더 궁금하신 것이 있다면 추가로 문의를 부탁드립니다.

**출발지/목적지/경유지 위치를 표시할 때**

아래 예제와 같이 마커를 올리면 됩니다.
- https://navermaps.github.io/maps.js/docs/tutorial-1-marker-simple.example.html
- https://navermaps.github.io/maps.js/docs/tutorial-3-marker-image-icon.example.html

**경로안내정보를 표시할 때**

올레맵의 API에서 어떻게 경로정보를 주는 지 모르겠지만 폴리라인을 그릴 수 있는 좌표 정보가 있다면 아래 예제와 같이 폴리라인을 올리면 됩니다.
- https://navermaps.github.io/maps.js/docs/tutorial-6-polyline-options.example.html

**별도의 권한이 필요한지**

만약에 네이버 지도 JavaScript API v3를 사용하실려고 한다면 별도의 권한은 필요없으며, API를 사용하기 위한 클라이언트 키가 필요합니다.

아래 튜토리얼에 따라 클라이언트 키를 받아 이용하시면 됩니다.
- https://navermaps.github.io/maps.js/docs/tutorial-Getting-Started-Register-Application.html
