### ISSUE TITLE
IE9, IE10에서 지도 생성 시 TM128좌표 오류

### ISSUE THREAD

**Issue by crusien** [navermaps/maps.js#190]
맵생성 옵션에서 center: new naver.maps.Point(309944, 552085) --시청좌표

형식으로 TM128로 했을경우 IE9, IE10에서  시청위치가 맞는 좌표임에도 불구하고 타일이 존재하지 않는 영

역으로 CENTER가 잡히는 현상을 발견했습니다.  

IE11이상과 크롬, 파이어폭스에서는 정상적으로 동작합니다.

맵 생성시 center를 TM128 POINT형식으로 주면 이후는  TM128으로 동작하는 걸로 알고 있는

데 이 옵션이 하위 브라우져에서 정상적으로 동작하지 않는거 같습니다.

즉 맵 인스턴스 생성시 TM128 로 센터를 줬지만 LATLNG로 인식하는거 같습니다. 

map인스턴스 생성시  TM128 로 하위브라우져에서 인식 할수 있는 방법이 따로 있는건지요?

**Comment by junthus** [comment]
안녕하세요 @crusien 님 ~ 빨리 도움을 드리지 못해 죄송합니다 (저도 디버깅 해보느라 ㅠㅠ)

확인해보니 map 초기화 시점에 tm128 projection (geocoder 모듈 내에 있는)이 로드가 완료되지 않는 경우가 있는 듯 합니다. 그래서 프로젝션을 제대로 계산하지 못해 타일 인덱스가 엉망이 되고 있네요.

https://navermaps.github.io/maps.js/docs/tutorial-4-Submodules.html 페이지를 참고하셔서,
`naver.maps.onJSContentLoaded` 를 사용하여 모듈이 모두 로드된 후에 지도를 생성해봐 주세요. 

혹시 문제가 계속된다면 다시 알려주세요.
감사합니다.

**Comment by crusien** [comment]
저희쪽 JS모듈 인스턴스 생성할때 naver.maps.onJSContentLoaded로 감싸니 해결되는군요. api문서에 해당 사항이 필수로 기재되야 할거 같습니다.  감사합니다.
