### ISSUE TITLE
geocode 주소를 위도 경도로 불러올때!!!

### ISSUE THREAD

**Issue by rim0621** [navermaps/maps.js#192]
구글 같은 경우는 10개 이상이면 10개 이후에는 1개당 1초 걸리는데 네이버 지도도 그러나요??
 혹시 그럴경우  20개/100/500/1000 개정도 맵에 띄우려고 하는데 비용하고 걸리는 시간좀 알수 있을까요!??!

**Comment by NaverMantle** [comment]
테스트 하실 주소와 이슈 등록해주시면 저도 같이 테스트 해보겠습니다.
우선 이슈 닫도록 하겠습니다.
