### ISSUE TITLE
초보개발자입니다. api 지도에서 네이버 검색결과를 같이 띄울 수는 없나요? 

### ISSUE THREAD

**Issue by chlwovlf** [navermaps/maps.js#193]
초보 개발자입니다. 웹사이트를 만들어서 네이버 지도 v3 api를 불러오고, 거기에 네이버 검색결과를 같이 띄우고싶은데 ("현 지도에서 장소검색" 옵션을 켜고 검색하는 것 처럼) 이렇게 하는 방법이 없을까요? 

예를 들어 네이버 지도에서 '헬스장' 을 검색한 결과를 제 웹사이트 지도에서도 그대로 띄우고싶습니다. 

가능할까요? Examples 들을 살펴봤는데 이거랑 관련된 예제는 없는 것 같아서요.... 

개발 플랫폼은 루비온레일즈를 쓰고있습니다.

**Comment by thetaiz** [comment]
@chlwovlf 님, 두 가지 API를 사용해야 합니다.

* 네이버 지도 v3 API: 데이터를 이용해 지도 위에 그리는...
* 지역 검색 API: 검색어를 넣어 업체 및 상호 검색 결과를 받는... (https://developers.naver.com/docs/search/local/)

그러나 지역 검색 API 경우 검색어를 전달할 뿐 위치 정보를 전달하지는 않습니다. 즉, 현 지도에서 장소 검색과 같이 검색을 하는 지역을 특정할 수 없는... ㅠㅠ

만약 현재 보이는 영역으로 검색 결과를 필터링해서 보여주려면... 지역 검색 API를 이용해 얻은 데이터에서 현재 좌표 경계 영역(바운더리, boundary) 내에 있는 결과만 뽑아서 그려야할 것 같아요.
