### ISSUE TITLE
 파노라마에 폴리라인을 표시할수 있나요?

### ISSUE THREAD

**Issue by jeeny1978** [navermaps/maps.js#194]
안녕하세요. 

파노라마에 마커를 표시할수 있는 API가 제공되던데

혹시 폴리라인도 표시할 수 있나요?

답변 부탁드립니다. 감사합니다.

**Comment by myounggun-chae** [comment]
안녕하세요. 

파노라마에서 Marker와 InfoWindow는 올릴 수 있지만,
요청하신 Polyline 표시를 지원하지 않습니다.

감사합니다.
