### ISSUE TITLE
보이는 지도 영역의 마커만 표시하기 setMap이 아니라 getMap 아닌가요?

### ISSUE THREAD

**Issue by leesh312** [navermaps/maps.js#195]
https://navermaps.github.io/maps.js/docs/tutorial-marker-viewport.example.html

위 예제에

```javascript
function showMarker(map, marker) {

    if (marker.setMap()) return;
    marker.setMap(map);
}

function hideMarker(map, marker) {

    if (!marker.setMap()) return;
    marker.setMap(null);
}
```
위 함수들
if(marker.**set**Map()) 대신 if(marker.**get**Map())
아닌가요?

추가적인 질문으로
naver map 소스들을 npm에 공개할 계획은 없으신지요?
ES6 import가 안되어 불편함이 많습니다.

**Comment by cs09g** [comment]
마커를 표시할 지도를 설정해서 지도상에 나타내는 것이기 때문에 setMap이 맞는 것 같아요. getMap은 단순히 마커가 어느 지도에 설정되었는가를 반환합니다.

**Comment by leesh312** [comment]
setMap()이 무엇을 리턴하는지 소스가 비공개라 알 수 없지만
getMap()으로 검사하면 redraw가 없는거 같아서 이슈 달아봤습니다. 

getMap() === null 이면 어느 지도에도 표시되지 않은것으로 파라미터로 온 map에 표시하라.
아닌가요?

**Comment by cs09g** [comment]
아! 조건 안에 함수를 말씀하시는거였군요. 지금 보니 저도 @leesh312 님이랑 같은 생각입니다. getMap이 맞는것 같은데, 실제 예제 코드를 열어보니 진짜 setMap으로 구현이되어있네요. 개발자분들 답변을 기다려봐야할 것 같아요 ㅎㅎ

**Comment by boxersb** [comment]
@leesh312 @cs09g 아.. `getMap()` 이 맞습니다.. ㅠㅠ
해당 부분은 빠르게 수정될 수 있도록 조치하겠습니다.

그리고, npm 에 공개를 문의주셨는데.. npm으로 공개하려면 기본적으로 네이버 지도 API가 Open Source 여야 가능한것인데요.. 개발자센터 인증 문제도 있기때문에 현재는 Open Source로 공개할 계획이 없을을 양해 부탁드립니다.

감사합니다.

**Comment by leesh312** [comment]
오픈소스화 문제는 아쉽네요. ㅎㅎ
내부에 비공개적인 소스는 빼고 겉 함수만 오픈소스화 해주시면 더욱더 좋을것 같습니다.

그외엔 네이버 맵 api 잘 이용하고있습니다. 감사합니다.

**Comment by boxersb** [comment]
@leesh312 감사합니다~~ 👍

**Comment by junthus** [comment]
@leesh312 수정되었습니다 ~ 제보 감사드립니다.
