### ISSUE TITLE
타 GIS시스템에 Naver Map API를 Addon하여 사용해도 되나요?

### ISSUE THREAD

**Issue by jeeny1978** [navermaps/maps.js#196]
안녕하세요.

저희회사에서 타 GIS솔루션을 도입하여 사용하고 있습니다.

그런데 사용자 요구사항중에 Naver 거리뷰 파노라마뷰 기능을 넣어달라는 요청이 많은데

Naver API를 타GIS시스템에 붙여서 함께 사용해도 되나요?

답변 부탁드립니다. 감사합니다.

**Comment by thetaiz** [comment]
@jeeny1978 님, 타 GIS 시스템이 무엇인지 구체적으로 말씀해 주시면 확인하는데 도움이 될 것 같아요~ ^^ 우선 참고하시라고 약관을 링크합니다.

- https://developers.naver.com/products/terms/

**Comment by jeeny1978** [comment]
답변 감사드립니다.

ArcGIS를 사용하고 있구요.

사용하고자하는 API는  사용중인 GIS화면 위에 거리뷰 레이어를 올리고

해당 지점클릭시 파노라마뷰를 표시하는 기능을 사용하고자 합니다.

당연히 거리뷰와 파노라마뷰 사용시에는 네이버에서 제공하는 기능임을 표시하려고 하구요.

약관을 읽어 보았는데 가부여부를 확인할 수 있는 항목을 잘 못찾겠더구요.

번거로우시겠지만 다시한번 확인 부탁드립니다.

감사합니다.
