### ISSUE TITLE
heatmap redraw관련 문의드립니다

### ISSUE THREAD

**Issue by kihoon76** [navermaps/maps.js#198]
map의 dragend시 heatmap에 setdata() 로 데이터를 추가하고 
heatmap redraw를 하면 data가 있는대도 불구하고 하나도 그려지지 않습니다.
제가 뭔가 잘못한 부분이 있는지 문의드립니다

_heatMapLayer = new naver.maps.visualization.HeatMap({
				    map: map,
				    data: [],
				    opacity:1,
				    radius: 32,
				    colorMap: naver.maps.visualization.SpectrumStyle.HOT //YIOrRd//HSV//JET //OXYGEN //YIOrRd //HOT 
				});
				
_heatMapLayer.setData(_heatMapDatas);
_heatMapLayer.redraw();

이렇게하면 전혀 그려지지 않네요

**Comment by kihoon76** [comment]
_heatMapLayer = new _vender.visualization.HeatMap({
				    map: map,
				    data: [],
				    opacity:1,
				    radius: 32,
				    colorMap: _vender.visualization.SpectrumStyle.HOT //YIOrRd//HSV//JET //OXYGEN //YIOrRd //HOT 
				});
				
				_heatMapLayer.setData(_heatMapDatas);
				_heatMapLayer.redraw();

이렇게하면 전혀 그려지지 않네요

**Comment by thetaiz** [comment]
@kihoon76 님, 초기 `data`는 필수 옵션입니다. 초기 데이터가 없어서 JS 오류가 발생하고, 그 후 동작을 하지 않고 있습니다. 초기 데이터가 있을 때 추가하는 메서드로 `setData`를 제공하고 있습니다. 초기 데이터 없이 히트맵을 생성해야 하나요? 내부적으로 해당 부분을 검토해 보겠습니다.

**Comment by thetaiz** [comment]
#201
