### ISSUE TITLE
좌표와 줌을 동시에 변경할 경우 생기는 문제

### ISSUE THREAD

**Issue by davidshimjs** [navermaps/maps.js#2]
Map#setZoom(), Map#setCenter(), Map#panTo() 등을 동시에 사용할 경우 애니메이션 때문인지 zoom과 좌표 변환 중 한 가지가 안되는 문제가 있습니다.

그래서 Map#updateBy()라는 메서드가 있길래 사용해 봤는데, 여기에 몇 가지 문제가 있습니다.

1. 데스크탑에서 updateBy를 쓰게 되면 항상 줌 아웃되는 애니메이션이 발생합니다. (모바일 발생 안함)
2. 데스크탑에서 간헐적으로 updateBy 호출 후에 타일이 로딩되지 않는 문제가 있습니다. 이 때, 마우스를 잡고 움직이면 다시 타일이 보입니다. (포지션 문제일 듯)

동시 호출 시 문제 재현은 https://jsfiddle.net/8r7tmqyz/1/ 여기에서 두 번째 버튼 `setZoom_and_setCenter`를 눌러보시면 됩니다.

**Comment by boxersb** [comment]
@davidshimjs `setZoom` -> `setCenter` 를 연달아 호출했을때 발생되는 이슈 확인했습니다. 이 부분 확인 후 수정하겠습니다.
그런데, [updateBy](https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#updateBy__anchor)는 본래 애니메이션이 없는 메서드인데요.. 혹시 `morph`와 착각 하신건지요..

그리고, setZoom 의 두번째 인자는 TransitionOptions 가 아닌 effect 사용 여부를 결정하는 true or false 입니다 :)

**Comment by cs09g** [comment]
버튼 막 누르다보니까 지도 @Naver Corp. 옆에 /OpenStreetMap 도 뜨던데, 왜그런가요??

**Comment by boxersb** [comment]
@cs09g 지도 데이터 저작권 표기입니다. 네이버 지도는 북한지역 데이터로 OpenStreetMap 의 것을 사용하고 있습니다.

**Comment by cs09g** [comment]
아하, 감사합니다.

**Comment by boxersb** [comment]
@davidshimjs 일단 setZoom effect 사용 직후 setCenter 호출시 타일이 보이지 않을 수 있는 문제는 수정 배포 했습니다. 다만, effect 가 시작되고 난 후 setCenter 등으로 중심 좌표 변경시에는 해당 문제가 발생할 수 있으므로, effect 가 들어가 있는 메서드는 마지막에 호출하는 방식으로 개발 부탁드립니다 :)

**Comment by davidshimjs** [comment]
@boxersb 빠른 수정 감사드려요~! updateBy 이슈는 저희쪽 코드 문제였던 것 같습니다.

**Comment by davidshimjs** [comment]
https://jsfiddle.net/8r7tmqyz/2/ 아직 재현됩니다~! 두 번째 버튼을 빠르게 3번정도 연타하면
1) 화면이 안보이거나
2) 다른 좌표로 이동해 있습니다.

**Comment by boxersb** [comment]
@davidshimjs 아 넵.. 재현되는군요.. 수정 방향을 잡고 개선해보도록 하겠습니다.

**Comment by boxersb** [comment]
@davidshimjs 해당 현상 수정했습니다. 화면이 안보이거나 마지막에 실행했던 좌표로 지도가 정확히 이동하도록 수정했는데, 확인 한번 부탁드립니다~

**Comment by davidshimjs** [comment]
@boxersb 예전에는 화면이 안보이는 문제였는데, 지금은 화면이 안보이지는 않는데 좌표가 이동하지 않는 문제가 있습니다. (줌만 변경됨) 그리고 그렇게 된 이후에 다시 그 좌표로 이동을 해도 이동이 안되네요. (이미 현재 화면을 그 좌표로 인지하는 것 같아요)

**Comment by boxersb** [comment]
@davidshimjs https://jsfiddle.net/8r7tmqyz/4/ defer 를 제거해도 그런가요?
defer 에 의해 마지막 호출이 큐에 쌓이지 않는것 같은데.. 확인 좀 부탁드려요~

**Comment by boxersb** [comment]
@davidshimjs  
아래 jsfiddle 에 마커와 UI로 현재 표시되고 있는 position 의 인덱스를 표시해봤습니다. 위치는 제대로 나오는것 같은데 확인 부탁드립니다.

**Comment by boxersb** [comment]
close 하겠습니다.
