### ISSUE TITLE
map.data.removeGeoJson가 한번밖에 실행되지 않습니다.

### ISSUE THREAD

**Issue by Jiyong-C-Lee** [navermaps/maps.js#200]
레이어를 초기화하고 geojson 데이터를 불러와서 레이어를 생성하려 하는데 기존의 레이어를 어떻게 지워야 할지 모르겠네요. 크롬 개발자도구에서 map.data.removeGeoJson이 두 번 이상 실행되지 않는 것을 발견했는데요, 대안이 있을까요?

**Comment by thetaiz** [comment]
@Jiyong-C-Lee 님, 확인 후 공유를 드리겠습니다.

**Comment by thetaiz** [comment]
@Jiyong-C-Lee 님, 해당 로직에 오류가 있어 내일 오전 11시(예상)에 긴급배포할 예정입니다.

**Comment by thetaiz** [comment]
@Jiyong-C-Lee 님, 리얼 배포가 끝났습니다. 확인을 부탁드립니다. removeGeoJson 메서드 사용 시 정상적으로 동작해야 합니다.

**Comment by thetaiz** [comment]
@Jiyong-C-Lee 님, 확인해 보셨나요?

**Comment by thetaiz** [comment]
@Jiyong-C-Lee 님, 이슈를 종료합니다. 혹여 동일한 현상이 나타나면 이슈를 다시 열어주세요~
