### ISSUE TITLE
heatmap redraw관련 다시 문의 드립니다

### ISSUE THREAD

**Issue by kihoon76** [navermaps/maps.js#201]
답변감사합니다.
제가 정확히 하려는 것을 말씀드리겠습니다
위에서 예를 든것과 동일하다고 생각이 듭니다(초기 data옵션이 null이면 스크립트 오류가 발생하고 빈 배열을 넣어주면 오류 발생하지 않습니다)
처음에 로딩될때 화면에 보이눈 bounds안에만 heatmap을 그리고 마우스 dragend 이벤트 발생시 새로보이는 부분을 그리려고 합니다
heatmap에 뿌릴 데이터를 배열에 담아놓고 추가되는 부분을 쌓은후 heatmap에 setdata후 redraw를 호출하면 화면에서 다 사라집니다.
또 이상현상은 사라진 화면에서 마우스로 드래그한 상태로 화면 밖으로 나갔다가 들어오면 사라졌던 화면이 보이는데 마우스를 놓으면 또 사라집니다

그래서 어쩔수 없이 heatmap을 다시 생성해서 그리는데 깜빡임이 발생할 수 밖에 없네요
API문서는 너무 간단하게 나오는데 제가 원하는대로 구현이 안되네요
검토부탁 드리겠습니다
감사합니다

**Comment by thetaiz** [comment]
@kihoon76 님~ 저희쪽에서 확인할 수 있는 URL 또는 코드를 알려주실 수 있으세요? 코드 공개가 어려우면 저희 메일로 보내주셔도 됩니다. mapsopenapi@naver.com 입니다.

그리고 참고로~ redraw 시 기존의 것을 지우고 새로 그리기 때문에 깜빡임이 있을거 같아요. 새로 보이는 부분만 그린다면 기존과 겹치는 부분은 히트맵이 제대로 생성되지 않을거구요.

**Comment by kihoon76** [comment]
네 감사합니다 
메일로 URL 보내드리겠습니다

**Comment by thetaiz** [comment]
@kihoon76  님, 새 데이터를 갱신해 타일을 그리면서 오류가 있었습니다. 내일 오전 11시(예상)에 긴급배포할 예정입니다. 다만, 앞서 언급했듯이 기존의 것을 지우고 새로 그리기 때문에 깜빡임이 있습니다. ㅠㅠ

**Comment by thetaiz** [comment]
@kihoon76 님, 리얼 배포가 끝났습니다. 확인을 부탁드립니다.

**Comment by kihoon76** [comment]
확인해보았습니다.
마우스 드래그시 사라지는 문제는 여전히 해결되지 않았습니다.
그리고 제가 줌을 바꾸면 heatmap은 제거하고 데이터는 캐쉬로 가지고 있다가 다시 뿌리는데 배포전에는 오류가 안 났었는데 새롭게 오류가 납니다.
오류내용
maps.js?clientId=SgnlyXnzstmDsYDhele7&submodules=visualization:10 Uncaught TypeError: Cannot read property 'refresh' of undefined
    at n.Layer.refresh (maps.js?clientId=SgnlyXnzstmDsYDhele7&submodules=visualization:10)
    at e.redraw (maps-visualization.js:14)
    at _createHeatmap (map-core.js:430)
    at _createViewRangeData (map-core.js:420)
    at _showCellsLayer (map-core.js:521)
    at Object.maps.showCellsLayer (map-core.js:712)
    at zoom_changed (main2.js:121)
    at map-core.js:559
    at maps.js?clientId=SgnlyXnzstmDsYDhele7&submodules=visualization:7
    at Object.forEach (maps.js?clientId=SgnlyXnzstmDsYDhele7&submodules=visualization:6)

**Comment by thetaiz** [comment]
@kihoon76 님, 사용하는 브라우저가 어떤것인가요? 크롬에서 확인 시 드래그 시 정상적으로 그려지고 있습니다. createHeatmap()에서 if(false)로 둔 것은 redraw 시 오류 때문이죠?

**Comment by thetaiz** [comment]
@kihoon76 님, 해당 오류가 난 것은 줌 변경 후 initHeatmap을 통해 _removeHeatmapLayer를 실행하는데 열지도를 제거(`setMap(null)`) 후 `delete`를 수행하나 실제 객체를 제거할 수 없기에 naver.maps.visualization.HeatMap 객체를 그대로 유지하기 때문입니다. 해당 부분을 `delete`가 아닌 `null`을 이용해 주세요.

**Comment by thetaiz** [comment]
@kihoon76 드래그입니다.


![8 -08-2017 14-50-29](https://user-images.githubusercontent.com/1366046/29058002-034b36e0-7c49-11e7-8947-e18ae21fd18c.gif)

**Comment by kihoon76** [comment]
빠른 대응의 노력에 감사합니다죄송하지만 배포후에도 제가 가장 원하는 부분이 반영이 안되어서 질문을 다르게 하겠습니다예를 들어서 화면에 보이는 부분에 좌표가 한점 있고 화면에 안보이는 부분에 좌표가 하나 있다고 가정하고화면 로딩시 new naver.maps.visualization.HeatMap 으로 data 속성에 [화면에 보이는 한점 좌표]를 넣고 heatmap을 그렸습니다여기서 드래그를 하여 이번에는 이전화면에는 숨어있던 좌표 한점도 화면에 보이게 되었습니다dragend이벤트에다가 기존것에 새로 데이터를 추가 하고 싶습니다물론 heatmap을 다시 생성하면 깜빡임이 있겠죠?맵을 새로 생성하지말고 redraw를 하는 샘플소스를  보내주시면 감사하겠습니다



내 삼성 디바이스에서 보냈습니다

-------- 원본 메시지 --------
발신: Yonghwan Lee <notifications@github.com> 
날짜: 17/8/8  오후 2:52  (GMT+09:00) 
받은 사람: "navermaps/maps.js" <maps.js@noreply.github.com> 
참조: kihoon76 <lovedeer118@gmail.com>, Mention <mention@noreply.github.com> 
제목: Re: [navermaps/maps.js] heatmap redraw관련 다시 문의 드립니다 (#201) 

@kihoon76 드래그입니다.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/navermaps/maps.js","title":"navermaps/maps.js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/navermaps/maps.js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thetaiz in #201: @kihoon76 드래그입니다.\r\n\r\n\r\n![8 -08-2017 14-50-29](https://user-images.githubusercontent.com/1366046/29058002-034b36e0-7c49-11e7-8947-e18ae21fd18c.gif)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/navermaps/maps.js/issues/201#issuecomment-320857428"}}}

**Comment by thetaiz** [comment]
차주 월요일에 관련 예제를 구현해보고 공유를 드리도록 하겠습니다.

**Comment by kihoon76** [comment]
하나 또 빼먹은게 있어서요

heatmap의 setColorMap메서드의 두번째 파라미터에 inReverse옵션이 있는데 맵생성시 heatmapoptions 에서
설정하는 방법이 궁금합니다

2017-08-11 9:19 GMT+09:00 Yonghwan Lee <notifications@github.com>:

**Comment by kihoon76** [comment]
감사합니다

2017년 8월 11일 오전 9:23, 남기훈 <lovedeer118@gmail.com>님이 작성:

**Comment by thetaiz** [comment]
@kihoon76 님, 좌표 경계 내에 있는 좌표에 대해 히트맵을 그리는 예제입니다. 그리고 현재는 옵션에서 `inReverse`를 설정할 수 없습니다.

```
var heatmap = new naver.maps.visualization.HeatMap({
  data: [],
  map: map
});

var drawHeatMap = function() {
  var zoom = map.getZoom(),
      dataWithinBounds = [];

  if (zoom >= 5) {
    var bounds = map.getBounds(),
        data = heatmapPosition.filter(function(v) {
          return bounds.hasLatLng(v);
        });


    if (data && data.length > 0) {
      dataWithinBounds = data;
    }
  }

  heatmap.setData(dataWithinBounds);
  heatmap.redraw();
};

drawHeatMap();

naver.maps.Event.addListener(map, 'idle', function() {
  drawHeatMap();
});
```

**Comment by kihoon76** [comment]
감사합니다


내 삼성 디바이스에서 보냈습니다

-------- 원본 메시지 --------
발신: Yonghwan Lee <notifications@github.com> 
날짜: 17/8/14  오전 11:49  (GMT+09:00) 
받은 사람: "navermaps/maps.js" <maps.js@noreply.github.com> 
참조: kihoon76 <lovedeer118@gmail.com>, Mention <mention@noreply.github.com> 
제목: Re: [navermaps/maps.js] heatmap redraw관련 다시 문의 드립니다 (#201) 

@kihoon76 님, 좌표 경계 내에 있는 좌표에 대해 히트맵을 그리는 예제입니다. 그리고 현재는 옵션에서 inReverse를 설정할 수 없습니다.
var heatmap = new naver.maps.visualization.HeatMap({
  data: [],
  map: map
});

var drawHeatMap = function() {
  var zoom = map.getZoom(),
      dataWithinBounds = [];

  if (zoom >= 5) {
    var bounds = map.getBounds(),
        data = heatmapPosition.filter(function(v) {
          return bounds.hasLatLng(v);
        });


    if (data && data.length > 0) {
      dataWithinBounds = data;
    }
  }

  heatmap.setData(dataWithinBounds);
  heatmap.redraw();
};

drawHeatMap();

naver.maps.Event.addListener(map, 'idle', function() {
  drawHeatMap();
});


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/navermaps/maps.js","title":"navermaps/maps.js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/navermaps/maps.js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thetaiz in #201: @kihoon76 님, 좌표 경계 내에 있는 좌표에 대해 히트맵을 그리는 예제입니다. 그리고 현재는 옵션에서 `inReverse`를 설정할 수 없습니다.\r\n\r\n```\r\nvar heatmap = new naver.maps.visualization.HeatMap({\r\n  data: [],\r\n  map: map\r\n});\r\n\r\nvar drawHeatMap = function() {\r\n  var zoom = map.getZoom(),\r\n      dataWithinBounds = [];\r\n\r\n  if (zoom \u003e= 5) {\r\n    var bounds = map.getBounds(),\r\n        data = heatmapPosition.filter(function(v) {\r\n          return bounds.hasLatLng(v);\r\n        });\r\n\r\n\r\n    if (data \u0026\u0026 data.length \u003e 0) {\r\n      dataWithinBounds = data;\r\n    }\r\n  }\r\n\r\n  heatmap.setData(dataWithinBounds);\r\n  heatmap.redraw();\r\n};\r\n\r\ndrawHeatMap();\r\n\r\nnaver.maps.Event.addListener(map, 'idle', function() {\r\n  drawHeatMap();\r\n});\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/navermaps/maps.js/issues/201#issuecomment-322088693"}}}
