### ISSUE TITLE
사내용 GIS시스템에 Naver Map API를 Addon하여 사용해도 되나요?

### ISSUE THREAD

**Issue by jeeny1978** [navermaps/maps.js#203]
안녕하세요. 며칠전에 문의글 올렸는데 추가정보가 필요하다고 하셔서 다시 올립니다.

사내에서 업무용으로 ArcGIS를 사용한 GIS시스템을 사용하고 있습니다.

해당 시스템에 Naver의 거리뷰와 파노라마뷰를 추가하여 사용하여도 되는지 문의드립니다.

업무용 GIS시스템에 거리뷰 레이어를 올리고 해당 지점클릭시 파노라마뷰를 표시하려고 합니다.

Naver API를 사용시에는 네이버에서 제공하는 기능임을 명시하려고 하구요.

Naver API 약관을 읽어 보았는데 가능여부를 확인할 수 있는 항목을 잘 못찾겠더구요.

번거로우시겠지만 다시한번 확인 부탁드립니다.

감사합니다.

**Comment by thetaiz** [comment]
@jeeny1978 넵~ 내부에서 현재 확인 중에 있습니다. 조금만 더 기다려 주세요~ 죄송합니다. ㅠㅠ

**Comment by thetaiz** [comment]
@jeeny1978 님, 지도 API 스크립트를 정상적으로 로드해 사용하시면 괜찮습니다.
