### ISSUE TITLE
정보창 내용 줄바뀜으로 인한 정보창 이탈 문제

### ISSUE THREAD

**Issue by jw980707** [navermaps/maps.js#205]
new naver.maps.InfoWindow을 사용해 정보창을 띄우는데
특정정보만 줄바뀜이 생기면서 정보창을 넘어가 밖에 표출이 됩니다.

해결방법이 있는지 확인 부탁드립니다.

![abababababababab](https://user-images.githubusercontent.com/30857802/29152160-cc81b020-7dc0-11e7-8cbb-0dca2403a10e.png)

**Comment by junthus** [comment]
@jw980707 님 안녕하세요,

내용의 너비가 인포윈도우에 지정해두신 너비보다 커지면서 줄바꿈이 되는 현상 같은데요,
인포윈도우의 너비를 늘리거나 css 를 이용하셔서 처리하시면 될 듯 합니다. 

도움이 되시길 바랍니다. ^^
