### ISSUE TITLE
IE9에서 maps.js 가 로딩이 안되는 현상.

### ISSUE THREAD

**Issue by crusien** [navermaps/maps.js#206]
이전에 IE9에서 서브모듈이 로딩되기 전에 map 인스턴스를 생성해서 TM128에 대한 지도 타일이 로드 되지 않는 현상을 아래의 onJSContentLoaded 를 사용하여 해결 했으나 IE11의 개발자도구의 IE9에뮬레이션에선
이상없이 동작하지만 IE9오리지널 브라우저에서는 처음 로딩은 되지만 새로고침후엔 map.js와 서브모듈 로딩이 완료 되었을때 실행되는 onJSContentLoaded 가 실행되지 않아 저희쪽 js가 실행되지 않는 현상이
발생되고 있습니다.
$(document).ready(function() {
naver.maps.onJSContentLoaded = function() {
gz3sm = new clsShopMapSearch();
gz3sm.init({
....
	});	
});

**Comment by junthus** [comment]
@crusien 님 안녕하세요.
혹시 다른 에러 메세지는 전혀 뜨지 않나요 ? `naver` 변수가 없다던지...
확인 부탁드리겠습니다.

**Comment by crusien** [comment]
네 별다른 에러 메세지는 뜨지 않습니다.

**Comment by junthus** [comment]
@crusien 님,
테스트 해 봤는데 제 PC에선 재현이 되지 않네요 ㅠㅠ 

재현되는 PC 에서 이 [예제](https://navermaps.github.io/maps.js/docs/tutorial-2-geocoder-tm128coord.example.html) 페이지가 정상적으로 동작하는지 확인해 주시겠어요 ? (동일하게 `onJSContentLoaded`를 사용하여 geocoder를 활용하는 예제입니다.)

**Comment by crusien** [comment]
https://navermaps.github.io/maps.js/docs/tutorial-2-geocoder-tm128coord.example.html
해당 예제 페이지는 ie9에서 그냥 새로고침시에는 잘뜨지만 ctrl+f5로 새로고침하면 백지가 뜹니다.

**Comment by boxersb** [comment]
@crusien 안녕하세요? 제가 별도로 확인해봤습니다.

`document.readyState` 가 `interactive` 상태일 경우 지도 API에서 `onJSContentLoaded` 호출을 10ms 이후에 하고 있습니다.  
고객님의 페이지에서는 `$(document).ready` 에서 `onJSContentLoaded`를 설정함에 따라 시점 차이로 인해 지도가 로드되지 않을 수 있느 현상을 발견했습니다.

저희쪽 패치는 금일 오후 중으로 하도록 하겠습니다.  
그전에 `$(document).ready` 사용 하는 부분을 `$(window).on('load', ..)` 이벤트로 변경해서 테스트 한번 부탁드립니다.

감사합니다.

**Comment by boxersb** [comment]
@crusien 님.. 패치가 완료되었습니다. 테스트 부탁드릴께요~

**Comment by crusien** [comment]
$(document).ready  제거하고 즉시 호출로 변경 시에는 아예 서브모듈이 로딩되지 않는 상태로 tm128 이 먹히지 않아 지도 타일이 로딩되지 않아 다시 ready안으로 집어 넣었구요. 패치후에 테스트 결과는
5번중 1번정도가 로드가 안되는 현상정도로 상태는 더 나아지긴 했습니다.

**Comment by boxersb** [comment]
@crusien http://www.golfzon.com/shop/branch 요 페이지 맞으신가요..?
페이지 구조상.. 레이지 로딩이 아닌 head 에서 지도 API를 import 하고 하부에서 사용을 시도했기 때문에 서브모듈이 모두 불려진상태여야 하는데.. 좀 이상하네요 ^^;

패치 이후 확인하셨을때 로드가 안되는 시점에선 지도 영역이 하얗게 뜨나요? 아니면 회색 페턴 이미지가 보이나요..?

**Comment by crusien** [comment]
아 패치후에는 회색 패턴이미지로 뜨는걸보아 서브모듈로드 실패로 tm128좌표 변환이 안된거 같습니다.

**Comment by boxersb** [comment]
@crusien 넵.. 그 이슈는 저희가 별도로 원인 파악을 해보도록 하겠습니다.

현상을 보면 mapTypes 지정한 부분에서 TM128Coord 프로젝션이 적용이 안되어 있네요.. 서브모듈로드 실패 이슈가 맞는것으로 보입니다.  

차주에 확인 해보겠습니다.  
감사합니다~

**Comment by junthus** [comment]
@crusien 님 안녕하세요, 해당 이슈 수정하여 배포되었습니다. 확인 부탁드립니다.

**Comment by crusien** [comment]
IE8,9,10,11 모두 정상적으로 로딩됨을 확인했습니다. 감사합니다.
