### ISSUE TITLE
투영법 예제 이슈

### ISSUE THREAD

**Issue by cs09g** [navermaps/maps.js#207]
https://navermaps.github.io/maps.js/docs/tutorial-4-maptypes-dynamic.example.html

타일 크기 변경 시, 일반/OSM 지도는 유사한데 거리막대에 나오는 값이 많이 차이납니다.

**Comment by boxersb** [comment]
@cs09g 일반 지도와 OSM 지도의 Projection 에 따라 이미지 Tile의 형상도 다르며, 거리 계산 방식도 달라집니다.
OSM 지도일때는 ScaleControl(거리막대) 의 길이와 값이 극지방으로 향할 수록 커집니다.

**Comment by cs09g** [comment]
타일크기 변경 시 OSM 은 거리가 어느정도 맞는거같은데, 일반에서는 조금 잘못나오는 것 같습니다..
(64x64일때)
![image](https://user-images.githubusercontent.com/7428017/29500295-77651814-865a-11e7-814f-23ccc6c6fe23.png)
![image](https://user-images.githubusercontent.com/7428017/29500309-9fcaaae4-865a-11e7-9280-962eb03dc55b.png)

**Comment by boxersb** [comment]
@cs09g 64x64 일때 같은 지역의 직선거리 재기에 오차가 있다는 말씀이신가요?

**Comment by boxersb** [comment]
@cs09g 아.. 타일 크기에 따라 일반지도의 ScaleControl 바 width 가 변경되지 않는군요.. 이 이슈는 수정하도록 하겠습니다.

감사합니다!

**Comment by junthus** [comment]
@cs09g 님 수정배포 되었습니다, 확인 부탁드려요 ~

**Comment by cs09g** [comment]
다른 문제도 하나 있는거 같은데요,
지도를 확대한 다음에 타입 변경 시 지도 중심이랑 줌이 유지되지가 않습니다.
OSM 지도 확대 -> 일반클릭 -> OSM클릭 하면 현상이 나옵니다.

**Comment by boxersb** [comment]
@cs09g 님.. OSM 지도는 0 ~ 22 줌레벨 까지의 범위를 갖고 있고, 네이버 지도는 -1 ~ 14 레벨입니다.

대략적으로 네이버 지도의 줌 레벨 + 5가 OSM 지도의 줌레벨이라 mapType 변경시 그렇게 이동되게 되어있는데요..  
말씀하신 줌레벨 유지 안되는 현상은 OSM 지도의 줌 레벨이 19레벨 이상이었을때 발생할것으로 보이며..  

변경되는 mapType의 maxZoom 레벨로 자동 이동하도록 되어 있는 동작은 정상 동작입니다.

**Comment by thetaiz** [comment]
@cs09g 님, 수정된 예제가 배포되었습니다.

**Comment by cs09g** [comment]
@boxersb @thetaiz 거리막대하고 센터/줌 유지 정상 확인하였습니다~~ :+1:
