### ISSUE TITLE
지적도가 동작을 안합니다

### ISSUE THREAD

**Issue by kihoon76** [navermaps/maps.js#208]
안녕하세요 
_venderMap = new _vender.Map(_container, {
				 	center: new _vender.LatLng(mapOptions.Y, mapOptions.X), 
			        zoom: mapOptions.level, 
			        mapTypes: registry,
			        mapTypeControl: true,
			        mapTypeControlOptions: {
			        	style: _vender.MapTypeControlStyle.DROPDOWN
			        },
			        minZoom: mapOptions.minZoom || 3 
				});
				
_venderMap.mapTypes.set(naver.maps.MapTypeId.NORMAL, naver.maps.NaverMapTypeOption.getNormalMap());
_venderMap.mapTypes.set(naver.maps.MapTypeId.CADASTRAL, naver.maps.NaverMapTypeOption.getCadastralLayer());
_venderMap.mapTypes.set(naver.maps.MapTypeId.HYBRID, naver.maps.NaverMapTypeOption.getHybridMap());

dropdown에 지적도를 추가했습니다
리스트에는 나오나 선택시 동작을 안하네요 확인부탁 드립니다

**Comment by junthus** [comment]
@kihoon76 님 안녕하세요,
지적도는 맵 타입 위에 올라가는 '레이어'이기 때문에 맵 타입으로는 동작할 수 있습니다.
[지적도 레이어 표시하기 예제](https://navermaps.github.io/maps.js/docs/tutorial-2-cadastral.example.html)를 참고하셔서 레이어 형태로 구현하시면 될 듯 합니다.

도움이 되시길 바랍니다.
