### ISSUE TITLE
 [긴급] map.js로딩이슈

### ISSUE THREAD

**Issue by joshuayun** [navermaps/maps.js#209]
금일(8/24 09:30분까지) 잘 정상적으로 동작하던 map.js 가 
갑자기 10:00 경부터 로딩시 스크립트 오류가 발생하여 운영중에 장애가 발생하고 있습니다.
(소스변경 한것 없음)

조속히 확인부탁드립니다.

에러는 아래와 같이 발생하고 있습니다.

![default](https://user-images.githubusercontent.com/18458524/29645146-869c60a4-88b6-11e7-96eb-027bd72bc9f9.PNG)

**Comment by thetaiz** [comment]
넵, 확인 후 공유드리겠습니다.

**Comment by joshuayun** [comment]
도메인은 있는데. 도메인노출은 내부사정상 불가능하여 개인적으로 드릴방법은 없을까요?

**Comment by boxersb** [comment]
@joshuayun mapsopenapi@naver.com 으로 부탁드립니다~

**Comment by joshuayun** [comment]
@boxersb 메일드렸습니다. 확인부탁드립니다.

**Comment by joshuayun** [comment]
@thetaiz @boxersb  
추가로 저희쪽에서도 확인하고 있는데 marker에 infowindow 를  .open 할때 에러가 발생하는거 같습니다.
해당 쪽만 주석처리하니 오류가 발생하지 않는것을 확인하였습니다.

**Comment by boxersb** [comment]
@joshuayun 
먼저, 제보 감사드립니다. (_ _)
현재, 원인을 파악했고.. 조치중에 있습니다.
금일 v3.1.0 업데이트를 실시했는데, icon과 anchor 계산에 오류가 발견되었습니다.  

일단 v3.0.6 으로 롤백을 진행중이며 원인이 해결되면 다시 업데이트 하도록 하겠습니다.

**Comment by thetaiz** [comment]
@joshuayun 긴급배포 완료했습니다. 확인 부탁드립니다.

**Comment by joshuayun** [comment]
네 감사합니다. 현재 정상작동 되는 것을 확인하였습니다.

**Comment by thetaiz** [comment]
넵, 이슈는 닫습니다. 참고로 오후 4시 경에 v3.1.0 재배포 예정입니다. 그때 다시 한번 확인을 부탁드립니다.

**Comment by thetaiz** [comment]
@joshuayun 님, 지금 v3.1.0이 배포되었습니다. 확인을 부탁드립니다.

**Comment by joshuayun** [comment]
확인결과 정상적으로 구동되고 있습니다.
빠른 대응 감사합니다.
