### ISSUE TITLE
다중 infoWindow 창 열기

### ISSUE THREAD

**Issue by seeno81** [navermaps/maps.js#21]
API v3 에서 다중으로 infoWindow 을 열려고 합니다. 
어떻게 진행해야 하나요?!

For 문에서 new naver.maps.InfoWindow 객체를 만들어서 Open 했는데 마지막 infoWindow 만 뜨고 그전꺼는 뜨지 않아서요.

**Comment by thetaiz** [comment]
@seeno81 님, 안녕하세요.

인포윈도우(정보 창)은 스펙이 하나만 열리는 것입니다. 따라서 말씀하신 것과 같이 마지막 인포윈도우만 열립니다.
인포윈도우와 유사한 것을 여러 개 지도위에 올리려면 **사용자 정의 오버레이**를 이용하셔야 합니다.

아래는 예제입니다.

- https://navermaps.github.io/maps.js/docs/tutorial-custom-overlay.example.html
