### ISSUE TITLE
특정 주소 조회 시 지도 API 오류 발생 건

### ISSUE THREAD

**Issue by minimap7** [navermaps/maps.js#210]
#### 내용 (Description)

[오류 상황]
1. 네이버 지도 API 사용시 특정주소 조회 시 오류 발생
https://navermaps.github.io/maps.js/docs/tutorial-3-geocoder-geocoding.example.html

2. 네이버 지도에서는 해당 주소로 조회가 가능

[오류 발생 주소]
서울특별시 용산구 한강대로21나길 17

#### 추가 정보 (Additional Info)

지도API 개발 중 해당 주소검색이 오류가 나서
API 샘플 페이지에서 조회했으나 동일 오류가 발생합니다.

**Comment by boxersb** [comment]
@minimap7 안녕하세요? 현재 담당자 확인중에 있습니다.  
확인 후 다시 공유드리겠습니다~

**Comment by boxersb** [comment]
@minimap7 안녕하세요?

해당 주소에는 보안시설이 존재하고 있어서, 주소 DB에 등록이 되어 있지 않았다고 하는데요..  등록될 수 있도록 조치하겠습니다.

빠르면 내일 오후 부터 정상 검색이 가능해질것 같습니다.

**Comment by thetaiz** [comment]
정상적으로 검색이 되므로 이슈를 닫습니다.
