### ISSUE TITLE
타일레이어 및 라벨레이어 관련

### ISSUE THREAD

**Issue by monanhip** [navermaps/maps.js#211]
안녕하세요 
금일 http://openapi.map.naver.com/openapi/v3/maps.js
스크립트가 업데이트가 된것을 확인했는데
업데이트가 되면서 타일레이어 및 라벨레이어 위로 Polyline 및 마커들을 생성하고 있었습니다만
업데이트 이후 Polyline 및 Marker가 타일 레이어 및 라벨레이어 및으로 숨는 현상이 발생 하였습니다..
특별한 조치가 필요한 걸까요? 잘되던 내용들이 되지 않네요
확인 부탁드립니다.

**Comment by thetaiz** [comment]
@monanhip 불편을 드려 죄송합니다. 저희쪽에서도 이슈를 파악하고 현재 이전 버전으로 롤백을 했습니다. 정상적으로 이용이 가능할거에요. 확인 부탁드려요.

**Comment by monanhip** [comment]
@thetaiz 정상적으로 확인

**Comment by thetaiz** [comment]
@monanhip 님, 차주에 새 버전이 배포될 예정입니다. 이슈 사항이 저희가 파악하고 있는 것과 다르기에 저희쪽에서 확인할 수 있는 URL 또는 소스 코드가 필요해요~ ^^ 그렇지 않으면 차주 배포 후 동일한 현상이 발생할 거에요~ 요 댓글 확인하시면 연락을 부탁드려요~

**Comment by monanhip** [comment]
@thetaiz 답변감사드립니다.
해당 URL은 메일로 첨부드렸습니다.

**Comment by thetaiz** [comment]
@monanhip 님, v3.1.0 리얼 배포가 완료되었습니다. 이상이 없는지 확인을 부탁드립니다.

**Comment by thetaiz** [comment]
@monanhip 님, 그리고 해당 페이지를 보니 지도 API 스크립트가 두 개 들어가 있네요. 하나는 서브모듈이 있고, 다른 하나는 없구요... 그 부분 수정 부탁드려요~

**Comment by monanhip** [comment]
안녕하세요
문제없이 나오는것 확인하였습니다.

감사합니다.

2017. 8. 29. 오전 11:11에 "Yonghwan Lee" <notifications@github.com>님이 작성:
