### ISSUE TITLE
다중 마커 생성 후 바우스 후 사라짐 

### ISSUE THREAD

**Issue by joshiekim** [navermaps/maps.js#212]
#### 내용 (Description)
오전까지 잘되었으나 오후부터 비정상 작동 하네요 ㅠㅠ
제목 작성했듯이 지도 오픈과 동시에 다중마커 생성 -> 바운스 와 함께 지도 표시 -> 바로 사라짐 (1개 또는 2개만 남음) 
이후 줌인 or 줌 아웃 하면 정상적으로 나타남 
![image](https://user-images.githubusercontent.com/10149840/29818428-4557a7a8-8cf7-11e7-9dd3-f79ca0071d9a.png)
캡처 1 - 지도생성후 57개의 마커가 있어야하지만 하나만 생성된 화면 

![image](https://user-images.githubusercontent.com/10149840/29818474-730cb1ac-8cf7-11e7-8d3c-103a75f4e824.png)
캡처 2- 이후 줌아웃 화면 사라졌던 마커들이 나타남 

#### 환경 (Environment)
윈도 10 Pro /  version : 1703 / chrome 버전 60.0.3112.113(공식 빌드) (64비트) and  IE 11 11.540 / LG gram ...
* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)
아직 개발중이라 로컬 접속만 구축 되어있네요 ;; 
위의 정보 만으로 해결이 안되신다면 공유 여부 확인 후 아래 메일로 소스 전달 드리겠습니다. 

* Site URL, Source Code

**Comment by thetaiz** [comment]
@joshiekim 금일 v3.1.0 배포가 있었습니다. 로컬에서 개발 중이시라면... 저희쪽에서 재현해 볼 수 있게 지도 생성부, 마커 생성 부 등이 있는 코드 공유를 부탁드립니다. 만약 별도의 CSS를 사용하신다면 해당 CSS도 함께 부탁드립니다.

**Comment by joshiekim** [comment]
@thetaiz 늦은 시간까지 고생하시네요 ;; 메일로 공유 드렸습니다. 확인 부탁 드려요 ㅠㅠ

**Comment by thetaiz** [comment]
@joshiekim 님, 마커가 사라지는 부분은 곧 핫픽스로 배포될 예정입니다. 인포윈도우가 겹쳐서 보이는 부분은 저희쪽에서 재현이 안되고 있습니다. 인포윈도우 부분의 엘리먼트 구조를 스샷으로 올려주실 수 있나요? 더불어 CSS를 제거하고 테스트를 부탁드립니다.

**Comment by thetaiz** [comment]
@joshiekim  님, 핫픽스 배포되었습니다. 확인을 부탁드립니다.

**Comment by junthus** [comment]
@joshiekim 님 안녕하세요, 제보 주신 이슈 패치되었습니다. 한 번 확인 부탁드려요 !

**Comment by joshiekim** [comment]
@thetaiz @junthus 수정 반영 되었네요 ^^ 감사합니다. 인포윈도우도 정상 작동 됩니다~ 빠른 대응 최고네요 ㅎㅎ ^^
