### ISSUE TITLE
네이버 맵 V3 관련 질문

### ISSUE THREAD

**Issue by jw980707** [navermaps/maps.js#214]
질문1. 맵 생성 후 마우스 스크롤에 따라 확대, 축소가 안됩니다.
맵이 있는 화면 진입 후 지도에 마우스를 옮기거나, 클릭을 한 후 마우스 스크롤을 해도 확대, 축소가 안됩니다. zoomControl 바를 한번 클릭 한 후에는 정상 작동됩니다.

var oLevel = 7;
var oPoint = new naver.maps.LatLng(lat, lng);
var oMap = new naver.maps.Map(document.getElementById('NaverMap'), { 
				center : oPoint,
				zoom : oLevel,
				zoomControl : true,
				mapTypeControl : true,
				size : new naver.maps.Size(600, 400)		
});

질문2. 마커에 마우스커서를 가져갔을때 title이 작동안됩니다.
var oMarker = null;
var oSize = new naver.maps.Size(20, 27);
var oOffset = new naver.maps.Point(10, 10);
var markerOptions = {
	position : new naver.maps.LatLng(lat, lng),
        title : 'TITLE TEST',
	icon : {
		url : '/images/map/img_location.png',
		size : oSize,
		anchor : oOffset
	};
};
oMarker = new naver.maps.Marker(markerOptions);
oMarker.setMap(oMap);

확인 부탁드립니다.

**Comment by thetaiz** [comment]
@jw980707  님, 사용하고 있는 브라우저 정보도 부탁드립니다. 더불어 저희쪽에서 접근해 볼 수 있는 URL이 있으면 공유 부탁드려요~

**Comment by junthus** [comment]
타이틀이 작동 안 된다는 말씀은 무슨 얘기신지 설명좀 부탁드려요 ㅠㅠ
(참고로 브라우저에서 `title`은 마우스오버 상태로 잠시 기다리셔야 노출됩니다.)

**Comment by jw980707** [comment]
explorer 11입니다.
그리고 직접확인은 힘들것 같습니다.

**Comment by jw980707** [comment]
타이틀이 작동 안된다는건
말씀하신대로 마우스오버 상태로 있어도 타이틀 노출이 안됩니다.

**Comment by junthus** [comment]
넵 확인해보겠습니다 ~

**Comment by thetaiz** [comment]
@jw980707 님, 마크업 구조(HTML)와 사용하고 있는 CSS, 그리고 소스 코드를 저희쪽 메일로 보내주시면 재현이 되는지 확인해 보겠습니다.

**Comment by junthus** [comment]
@jw980707 님, 저희쪽에서는 어떤 pc에서도 재현이 안 되어서요 ;;

아래 예제에서도 동일 현상이 반복되는지 확인이 필요할 듯 합니다.(마커 타이틀은 녹색, 핑크색 마커에만 있네요)
https://navermaps.github.io/maps.js/docs/tutorial-5-marker-html-icon.example.html 

콘솔창에 에러 메세지나 다른 정보가 떠 있진 않은지 / 캐시를 여러번 지운 후에도 동일하게 재현이 되는지 등등
조금 더 꼼꼼하게 확인 부탁드립니다. ㅠㅠ

**Comment by jw980707** [comment]
예전에 위의 예제를 확인했는데 예제에서는 title이 잘 나오는데 제가 구현한데는 나오지 않아서 문의드린겁니다.

**Comment by jw980707** [comment]
마우스 스크롤에 확대 축소도 마찬가지입니다. 예제에 있는 어떤 지도를 가도 마우스 스크롤은 잘 작동됩니다.

**Comment by thetaiz** [comment]
@jw980707 님, 예제가 정상적으로 동작한다면 @jw980707 님의 환경적인 이슈로 보입니다. 작성된 마크업과 CSS, 소스 코드를 가지고 저희쪽에서 재현을 해봐야 이유를 알 수 있습니다. 첨부된 메일 주소로 공유해 주시면 확인해 보겠습니다.

**Comment by thetaiz** [comment]
@jw980707 님, 사용하고 있는 HTML 파일 헤더 영역에 `<meta http-equiv="X-UA-Compatible" content="IE=edge">` 추가가 되어 있는지 궁금합니다.

**Comment by jw980707** [comment]
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
추가해주니 title이 잘 작동되네요. 감사합니다.

**Comment by jw980707** [comment]
그리고 한가지 더 궁금한게 있는데
이전 버전 V2에선 마커가 겹쳤을때 처리하는 기능을 자동으로 해주었나요?
제가 가지고 있는 기존 소스에 해당기능을 처리하는 부분을 찾을수가 없어서요.

**Comment by thetaiz** [comment]
@jw980707 님, 다행이네요~ ^^ 줌 동작도 잘 동작하는거죠? 그럼 이 이슈는 닫아주시면~ ^^

그리고 v3에서는 겹침마커 처리를 제공하지 않습니다. 아래 링크는 저희가 겹침마커 처리를 예제로 소스 코드를 공개한 것입니다. 참고해 사용하시면 됩니다~

- https://github.com/navermaps/marker-tools.js/tree/master/marker-overlapping-recognizer
