### ISSUE TITLE
네이버 지도Api V3 문의 드립니다.

### ISSUE THREAD

**Issue by gksaltjs308** [navermaps/maps.js#215]
네이버 지도api 사용시 발생 오류 문의드립니다. 
1. 지도 구현시 스크립트 오류 발생 
  스크립트 오류 내용 
  메시지: Script error
         줄: 0
     문자: 0
     코드: 0
     URI: https://openapi.map.naver.com/openapi/v3/maps-drawing.js
2. 지도 맵 생성 후 마우스를 이용한 줌아웃 처리가 안되며, 줌아웃 컨트롤 버튼을 클릭 후에는 
   마우스를 이요하여 줌아웃이 되는 현상 .

위와 같은 2가지의 현상이 발생합니다. 
익스플로어의 환경설정이 영향을 미치는지 확인 부탁드립니다. 
익스플로어 : 익스플로어 10 버전. / os : windows 7
혹시 브라우저모드나 문서모드도 지도맵을 사용하는데 영향을 주나요?

**Comment by thetaiz** [comment]
@gksaltjs308 님, 혹시 저희쪽에서 접근해 확인이 가능한가요? URL이 있는지 궁금합니다.

**Comment by junthus** [comment]
Script error 메세지 부분 캡쳐라도...

**Comment by gksaltjs308** [comment]
![_2](https://user-images.githubusercontent.com/31469786/29865115-a67cb236-8daf-11e7-94f5-0b84c1788b5c.png)
로컬이라 확인은 불가능 할것 같습니다~! 
그리고 지도 하단에 네이버 마크는 기본적으로 뜨는 건가요 ?

**Comment by thetaiz** [comment]
@gksaltjs308 님, 저희쪽에서 재현이 안되서요. 이슈 작성 시 첨부된 메일로 HTML 마크업 구조, CSS, 소스 코드를 보내주실 수 있으세요? 그리고 네이버 로고 말씀이죠? 지도 옵션 `logoControl `을 `false`로 두면 됩니다.

**Comment by junthus** [comment]
혹시 동일한 환경에서 이 예제 페이지에서도 같은 이슈가 있는지 확인 부탁드립니다.
캐시를 여러번 지워가며 테스트 해 주시면 더욱... 감사할 듯 합니다. ㅜㅜ

https://navermaps.github.io/maps.js/docs/tutorial-2-drawing-options.example.html

**Comment by thetaiz** [comment]
@gksaltjs308 님, 지도 API는 해당 문서 모드를 지원하지 않습니다. 더불어 호환성 보기 역시 지원하지 않구요. HTML 파일의 헤더 영역에 `<meta http-equiv="X-UA-Compatible" content="IE=edge">` 추가를 부탁드리며, 추가 후 동작이 동일하게 오류가 나는지 확인을 부탁드립니다.

**Comment by gksaltjs308** [comment]
이미 추가해봤는데 .. ^^;; 해당 메타태그 추가하면 ... 
기존의 화면이 전부 틀어져서 문의드렸던 거였습니다 ㅠㅠ ^^;;; 
해당 메타태그 추가하면 화면이 전부 깨지다보니 .. 지도 이미지가 안나와서요

**Comment by gksaltjs308** [comment]
아 ... ^^:; 그리고 하나 더 궁금한점이 있는데 
호환성 보기를 지원하지 않는다는 말씀은 
지도를 사용할 시스템이 호환성 보기 설정이 되어 있으면 안된다는 말씀이신가요 ?

**Comment by thetaiz** [comment]
@gksaltjs308 넵 맞습니다. 호환성 보기가 켜져 있으면 오동작이 발생할 수 있습니다. ^^ 그리고 해당 메타태그를 추가하면 지도가 안나온다는 것이지요? @junthus 님이 공유드린 지도 API 예제는 모두 해당 메타태그를 가지고 있습니다.

**Comment by gksaltjs308** [comment]
네 ~! 해당 메타태그를 추가하면 화면이 전부 깨져서 지도가 안나오는것 같습니다 .
그리고 지도를 적요하고 싶은 시스템은 호환성보기가 꼭 필요해서요 .. 
처음 화면 접속할때만 스크립트에러 한번 뜨는것 같고 .. 그외에 마커 표시나, 
인포윈도우 표시는 정상적으로 되는것 같으니 .. 스크립트 에러 표시하지 않고 사용해봐야 할것 같습니다. 
감사합니다 ~!  또 문의사항 있으면 등록하겠습니다 ~! 좋은 하루 보내세요 ~!

**Comment by thetaiz** [comment]
@gksaltjs308 넵~ 그럼 이 이슈는 닫겠습니다. 감사합니다.
