### ISSUE TITLE
NAVER MAP 폴리라인 화살표 지도 줌기능 오류

### ISSUE THREAD

**Issue by rladmdrl77** [navermaps/maps.js#217]
안녕하세요.
네이버 맵 V3.0 가이드 예제를 확인 중에 아래와 같은 현상을 발견했습니다.

NAVER MAP 폴리라인 화살표 표시 예제 페이지(https://navermaps.github.io/maps.js/docs/tutorial-pointing-icon.example.html)를 크롬 브라우져를 통해 확인하면 지도 확대시에도 이상없이 화살표 위치가 폴리라인에 위치하지만 IE10 브라우져에서 동일하게 테스트 하면 지도 확대, 축소시 화살표 위치가 랜덤하게 이동합니다.
 
내용 확인 부탁드립니다.

**Comment by thetaiz** [comment]
@rladmdrl77 넵, 확인해 보겠습니다. 감사합니다.

**Comment by thetaiz** [comment]
@rladmdrl77 님, 방금(11시 경) v3.1.1 버전을 배포했습니다. 확인을 부탁드립니다.

**Comment by MyNameKimTaeSeong** [comment]
안녕하세요.
네이버 panorama 가이드 예제를 사용중에 chrome 에서는 구현이 되는데 ie11 브라우저에서는
panorama가 구현이 안되서 문의 드려요 ㅜㅜ 에러는 안뜨는데 roadview가 안나와요 

(http://localhost/gimje16/naver_panorama.aspx) 예제 페이지
