### ISSUE TITLE
마커 겹침 처리시 문의 드립니다.

### ISSUE THREAD

**Issue by jw980707** [navermaps/maps.js#218]
마커 겹침 처리 예제를 보면 동일한 위/경도가 아닌데 조금만 인접해도 겹침으로 처리가 되는데,
완전 동일한 위/경도일 경우만 겹침 처리가 되도록 하는 방법은 없나요?

**Comment by jw980707** [comment]
그리고 추가로 겹침 마커 리스트 보여줄때 순서가 역으로 나오는데 마커 순서대로 나오는 방법도 있으면 알려주세요.
![aettteaaaaa](https://user-images.githubusercontent.com/30857802/30019848-ddd9abee-919c-11e7-9e68-10d5914a79b6.png)

**Comment by jw980707** [comment]
해결책이 없는건가요?

**Comment by thetaiz** [comment]
@jw980707 님, 아래의 옵션 값을 0으로 설정하면 정확하게 동일한 값에 대해서 처리합니다.

- https://github.com/navermaps/marker-tools.js/blob/master/marker-overlapping-recognizer/src/MarkerOverlappingRecognizer.js#L19

그리고 마커 순서는 아래 메서드에서 소팅을 직접 하셔야 합니다.

- https://github.com/navermaps/marker-tools.js/blob/master/marker-overlapping-recognizer/src/MarkerOverlappingRecognizer.js#L154
