### ISSUE TITLE
Zoom 개별 지정 문의

### ISSUE THREAD

**Issue by hamclove** [navermaps/maps.js#219]
현재 v2 > v3로 변경 작업을 하고 있습니다.

기존 v2로 작업을 했을때는 zoom을 개별로 설정할 수 있어서 디자인을 별도록 수정 했었는데요.

v3로 변경하려고 보니 zoom 스타일을 변경할 수 있는 가이드가 없어 현재 난항을 격고 있습니다.

zoom 만 별개로 디자인 변경이 가능한 방법은 없을까요?

**Comment by junthus** [comment]
@hamclove 님 안녕하세요, 

v3에서는 [CustomControl](https://navermaps.github.io/maps.js/docs/naver.maps.CustomControl.html)를 이용하여 직접 줌 컨트롤을 구현해야 합니다. [사용자 정의 컨트롤 Tutorial](https://navermaps.github.io/maps.js/docs/tutorial-Custom-Control.html), [zoom_changed](https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#event:zoom_changed__anchor) 문서 등을 참고하시면 될 듯 합니다. 

도움이 되시길 바랍니다.
