### ISSUE TITLE
특정 주소의 지도가 안나오는데 원인을 잘 몰라서 문의드립니다. 

### ISSUE THREAD

**Issue by irenehh** [navermaps/maps.js#22]
지도가 안나오는 주소
http://sanggatoday.com/business_info/bs_view.php?s_pd_code=4818&where_from=search_sangga

지도가 정상적으로 나오는 주소
http://sanggatoday.com/business_info/bs_view.php?s_pd_code=4835&where_from=search_sangga

- 질문내용 : 등록한 업체의 주소를 불러와서 지도를 띠워주는 방식입니다. 모든 업체 지도가
나오지 않는건 아니구요. 특정 주소 몇 군데만 주소가 나오지 않고 있습니다. 좌표값을 불러오지
못하는것 같은데 원인을 찾지 못해 질문드립니다.

**Comment by cs09g** [comment]
소스를 보니까 좌표가 0, 0으로 되어있던데 확인해보셔야 할거같아요.
정상:
![image](https://cloud.githubusercontent.com/assets/7428017/18261167/be6bcc32-742f-11e6-8e90-884e2e447fac.png)
비정상:
![image](https://cloud.githubusercontent.com/assets/7428017/18261173/c94eb894-742f-11e6-97af-eb7b6371baca.png)

**Comment by thetaiz** [comment]
@irenehh 님, 안녕하세요.

@cs09g 님이 말씀해 주신 것과 같이 좌표 값으로 `0`이 들어가 지도가 나오지 않고 있습니다. 주소를 이용해 좌표를 가져와 사용하는 것으로 보이는데, 좌표를 가져오는 부분에 대해 구체적으로 설명을 부탁드립니다.

**Comment by thetaiz** [comment]
@irenehh 님, 주소에서 '와리'가 빠져서 좌표를 얻어올 수 없었던 것으로 추정됩니다. 확인을 부탁드릴께요.

전북익산시함열읍198-5 -> 전북익산시함열읍와리198-5

**Comment by irenehh** [comment]
@thetaiz 님, @cs09g 님 안녕하세요,
두 분 덕분에 해결했습니다.
주소 검색할 때 주소가 누락됐을꺼라곤 생각도 못했어요,ㅜ
주소검색 부분이 좀 오래전에 구현된 부분이라 얘기해서 바꾸던가 해야겠네요,

정말 감사합니다!

**Comment by thetaiz** [comment]
@irenehh 님, 이슈를 닫겠습니다.
@cs09g 님, 감사합니다. ^^

**Comment by thetaiz** [comment]
@irenehh 님, 추가로 지금 사용하시는 API 버전이 1.0으로 보입니다. 해당 버전은 종료될 예정입니다(2017년 1월 1일). 따라서 이번에 새로 나온 3.0 버전을 사용해 주세요. 

관련 기술문서 링크입니다.

- https://navermaps.github.io/maps.js/
- https://navermaps.github.io/maps.js/docs/tutorial-Migrate-From-v1.html
