### ISSUE TITLE
동으로 검색 후 지도에 폴리라인이 표시되게 하기

### ISSUE THREAD

**Issue by danielkimhy** [navermaps/maps.js#221]
#### 내용 (Description)

동명으로 검색하면 검색된 동 리스트(동이름, 해당 동 고유 코드값 등) 를 리턴받아서

리스트중 특정 동을 클릭하면 지도에 영역이 폴리라인으로 표시되게 하고싶습니다.

어떻게 하는건가요?

고수분들의 조언 부탁드립니다. 도와주세요!!

#### 환경 (Environment)
html 웹기반. javascript, ajax, json
Server: php(linux)
* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by junthus** [comment]
@danielkimhy 님 안녕하세요.

단순 주소 검색이라면 [이 예제](https://navermaps.github.io/maps.js/docs/tutorial-3-geocoder-geocoding.example.html)처럼 사용할 순 있지만, 현재 지역 폴리곤 데이터/매핑은 API로 지원하지 않습니다.

지역 폴리곤 데이터를 vworld 등을 통해 구하시고 주소 검색을 호환할 수 있는지.. 혹은 사용할 수 있는 공공 데이터가 있는지 찾아보셔야 할 듯 합니다.

도움이 되시길 바랍니다. ^^
