### ISSUE TITLE
줌컨트롤러와 포지션

### ISSUE THREAD

**Issue by hahahahohoho1** [navermaps/maps.js#222]
#### 내용 (Description)
1. 기존 v2에서 zoomControl 를 이용중에 
v3로 마이그레이션 작업중 줌컨트롤러 모양을보면 
눈끔이 빠져있는데..  눈끔을 따로 스타일 적용할수 있는 방법이 있는지.. 

2. 지금 개발중인 시스템이 map Area영역을 동적인 크기로 resize를 하고 있구요
기존에 있던 css와 충돌이 나는지 resize 버그인지는 모르겟지만 
scaleControl 를 position: naver.maps.Position.BOTTOM_RIGHT 으로 배치하게 되면
resize가 된 map area 영역을 벗어나서 scaleControl  생성되어 ( 아래로 ) map에는 보이지 않게 되네요..
Position 으로  scaleControl  의 위치를 조정할수 있는것이 좀 한계가 있는거같습니다.
이부분 다이나믹하게 조정 할수 없을까요? 

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by thetaiz** [comment]
@hahahahohoho1 님, 아래와 같이 답변을 드립니다.

1. 기본적으로 제공하는 컨트롤의 스타일을 변경할 수는 없습니다.
2. 코드와 마크업, 스타일을 봐야 정확하게 파악할 수 있겠지만, @hahahahohoho1 님의 CSS와 간섭이 발생하는 것으로 보입니다.

위 두 가지를 모두 해결할 수 있게 사용자 정의 컨트롤을 권해드려요. 아래 튜토리얼을 참고해 직접 줌 컨트롤을 구현할 수 있습니다.

- https://navermaps.github.io/maps.js/docs/tutorial-Custom-Control.html
