### ISSUE TITLE
infowindow 문의

### ISSUE THREAD

**Issue by elementaryschool** [navermaps/maps.js#223]
#### 내용 (Description)

for 문
marker.setMap(map);
infowindow.open(map, marker);

이런식으로 저장된 좌표값을 가져와 맵위에  마커와 인포창을 띄우는 작업입니다.
그런데 마커는 모두 찍히는데 인포창만 마지막 좌표 마커위에 1개만 띄워져 있습니다.
그래서 단계별로 보니 인포창이 도출됐다가 다음 인포창에 의해서 없어지는 것이었습니다.
이경우 모든 인포창을 띄울려면 어떻게 해야 될까요?

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by thetaiz** [comment]
@elementaryschool 님, 인포윈도우는 스펙상 하나만 지도 위에 노출됩니다. 여러 개의 인포윈도우를 노출하려면 사용자 정의 오버레이를 직접 구현해야 합니다. 관련 내용은 아래 글의 '사용자 정의 오버레이'를 참고해 주세요.

- http://d2.naver.com/helloworld/3380225
