### ISSUE TITLE
폴리라인 특정 기기에서 제대로 그려지지 않습니다.

### ISSUE THREAD

**Issue by ppakko1** [navermaps/maps.js#224]
#### 내용 (Description)
폴리라인을 25m 축적에서 직선으로 그렸을때 특정 스마트폰 단말기에서만 직선이 아닌 삼각형 형태로 퍼져나가면서 그려지다가 일정부분 이상 가면 그때부터 직선으로 그려집니다.

다른 축적에선 정상적으로 그려지며 통신사만 다른 같은 모델 같은 OS버전의 디바이스에선 정상적으로 그려집니다.

#### 환경 (Environment)
API v3 사용

* 해당증상이 나타나는 디바이스 user agent
Mozilla/5.0 (Linux; Android 7.0; **SM-G930L** Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.116 Mobile Safari/537.36

* 정상적인 디바이스 user agent
Mozilla/5.0 (Linux; Android 7.0; **SM-G930K** Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.116 Mobile Safari/537.36

#### 추가 정보 (Additional Info)
```
var polyline = new naver.maps.Polyline({
    map: map,
    path: [
        N.LatLng(destLat, destLng),
        N.LatLng(originLat, originLng),
    ],
    strokeColor: '#5347AA',
    strokeOpacity: 0.5,
    strokeStyle: 'solid',
});
```

**Comment by thetaiz** [comment]
@ppakko1 님, 해당 단말기를 저희가 보유하고 있지 않아 빠르게 확인하지 못하는 점 양해를 부탁드립니다. 혹시 "직선이 아닌 삼각형 형태로 퍼져나가면서 그려지다가 일정부분 이상 가면 그때부터 직선으로 그려집니다." 부분을 gif 나 영상으로 볼 수 있을까요?

**Comment by thetaiz** [comment]
@ppakko1 그리고, 브라우저는 기본 브라우저인거죠?

**Comment by ppakko1** [comment]
@thetaiz 안녕하세요. 우선 앱내에서 기본 webview를 사용중입니다.
증상이 있는 화면은 다음 이미지를 참고부탁드립니다.
![mao](https://user-images.githubusercontent.com/16592116/30470557-32dea19e-9a30-11e7-9c2c-ea114b8c2847.jpeg)
![map2](https://user-images.githubusercontent.com/16592116/30470638-7309fa2a-9a30-11e7-8f8c-3a2f29c053b1.jpeg)

**Comment by thetaiz** [comment]
@ppakko1 님, 혹시 저희 예제에서도 동일한 현상이 나타나나요? 확인을 부탁드릴께요.

- https://navermaps.github.io/maps.js/docs/tutorial-3-polygon-simple.example.html

**Comment by ppakko1** [comment]
@thetaiz 님, 예제코드 그대로 확인했을때는 문제가 없어서 다음과 같은 과정을 거쳐 확인하다 보니 똑같은 증상을 보였습니다.
1. 예제코드에서 폴리라인만 그리도록 나머지 코드 제거
2. 폴리라인도 직선 1개만 표시되도록 path에 두개의 좌표만 넣음
3. zoom을 13(25m)로 변경
4. 두 지점 좌표의 경도(lng)의 정수부가 같을때는 문제가 없음(127.11482048 / 127.11473464)
5. 두 지점 좌표의 경도(lng)의 정수부가 다를때 문제 발생(126.93694967 / 127.04196242)

아래는 문제가 재현된 테스트 코드입니다.
```
var map = new naver.maps.Map('map', {
    center: new naver.maps.LatLng(37.48471809, 126.93694967),
    zoom: 13
});

var polyline = new naver.maps.Polyline({
    map: map,
    path: [
        new naver.maps.LatLng(37.48471809, 126.93694967),
        new naver.maps.LatLng(37.46982768, 127.04196242)
    ]
});
```

**Comment by thetaiz** [comment]
@ppakko1 님, 해당 단말기를 찾아 위에 말씀해 주신 코드를 이용해 테스트를 해봤으나... 삼성 기본 브라우저, 크롬 브라우저, 네이버 앱의 웹뷰에서 정상적으로 폴리라인이 그려지고 있었습니다. "우선 앱내에서 기본 webview를 사용중입니다." 이렇게 말씀해 주셨는데 혹시 지금 개발하고 계시는 앱 내에서 사용하는 웹뷰를 말씀하시는건가요?

**Comment by ppakko1** [comment]
@thetaiz 네 맞습니다. 앱내의 웹뷰를 통해 띄웠을때 발생하고있습니다.
위에도 얘기드렸듯 모든 단말에서 그러는건 아니고 제가 보유한 기기중엔 SM-G930L 모델에서만 증나이 나타납니다.

**Comment by thetaiz** [comment]
@ppakko1 님, 테스트는 말씀해주신 단말기(Galaxy S7 (LG U+), OS 버전 동일)를 찾아 진행했습니다. 혹시나 싶어 네이버 앱의 웹뷰로도 테스트를 진행하였습니다. 혹시 네이버 앱의 웹뷰로도 동일하게 나타나나요?

일반적인 기본 브라우저, 크롬이 아닌 웹뷰인 경우 저희쪽에서 디버깅이 어렵습니다. ㅠㅠ
