### ISSUE TITLE
데이터 재조회시마다 지도 새로 그리기 방법 문의

### ISSUE THREAD

**Issue by eungsik** [navermaps/maps.js#226]
아래처럼 최초 로딩시 전체 주소값을 조회하여 아래와 같이 작업을 하고 있습니다.
1. 서버에서 주소 리스트를 받아와서
2. 지도 그리고 
3. 각 주소에 맞는 좌표에 마커+건물(폴리라인)+토지(폴리곤)을 그린다.

데이터를 전체 조회한 이후 
특정의 그룹의 주소만 선택해서 재조회해서 가져오려고
아래 지도 그리는 부분과 폴리라인, 마커 그리는 부분등 전체를 함수로 만들어서
적용해보니 기존 지도위에 다시 그리고 있어서 지도를 확대/축소할 경우 이전 지도가 노출되는
경우가 발생합니다.
재조회할 경우 기존 지도를 지우고 다시그릴수 있는 방법이 있는지 도움 부탁드립니다.

// 최초 로딩시 작업 진행 시작
$(document).ready(function() 
{
        // 주소리스트 조회
	fnBtnClick("Search");

//지도 그리기
    var map = new naver.maps.Map("map", {
        zoom: 3,
        center: new naver.maps.LatLng(36.2253017, 127.6460516),
        zoomControl: true,
        zoomControlOptions: {
            position: naver.maps.Position.TOP_LEFT,
            style: naver.maps.ZoomControlStyle.SMALL
        },
        // 일반/지형도/위성/겹쳐보기
        mapTypeControl: true,
        mapTypeControlOptions: {
            style: naver.maps.MapTypeControlStyle.DROPDOWN
        }
    });
폴리곤/폴리라인 그리기 등등

}
// 최초 로딩시 작업 종료

**Comment by thetaiz** [comment]
@eungsik 님, 개발자 센터에 댓글을 달았습니다.
