### ISSUE TITLE
safari 브라우져에서 마커 이벤트가 정상적으로 동작하지 않습니다.

### ISSUE THREAD

**Issue by crusien** [navermaps/maps.js#227]
Safari 5.1.7 버전에서 테스트 했으며 네이버 샘플페이지에서도 정상적으로 동작 되지 않는게 확인됩니다.

https://navermaps.github.io/maps.js/docs/tutorial-5-marker-html-icon.example.html

마커에 대한 이벤트가 제대로 동작하지 않습니다.

**Comment by boxersb** [comment]
@crusien 님.. Safari 5.1.7 이라면.. Windows 버전 말씀이신가요..?

**Comment by crusien** [comment]
네 윈도우 버젼입니다.

**Comment by thetaiz** [comment]
@crusien 님, 해당 현상을 확인했으며, 수정하였습니다. 배포는 10월 정기배포(10월 말)에 릴리스할 예정입니다. 해당 일자보다 빠른 배포를 원하시면 다시 말씀해 주세요~

**Comment by thetaiz** [comment]
@crusien 님, 금일 v3.1.3 버전이 배포되었습니다. 확인을 부탁드려요.

**Comment by crusien** [comment]
패치 감사합니다. 사파리에서도 마커 이벤트가 정상 작동 합니다.
