### ISSUE TITLE
겹침 마크 클릭시 나오는 리스트 화면 이벤트

### ISSUE THREAD

**Issue by sportsst** [navermaps/maps.js#228]
#### 내용 (Description)
#153 이슈 답변은 잘 받았습니다.
겹침마크 클릭시 보여지는 리스트 박스가 보여질때 이벤트와, 리스트가 사라질때 혹은 리스트 밖의 화면을 클릭 했을때 시점의 이벤트를 찾을 수가 없어서  다시 질문드립니다.

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by thetaiz** [comment]
@sportsst 님, 리스트 박스가 보여질 때, 사라질 때의 이벤트는 지도 API에서 제공하지 않습니다. 겹침마커 기능 자체가 지도 API에서 제공하는 것이 아닙니다. 직접 구현해 사용하실 수 있도록 예제 형식으로 소스 코드를 공개한 것입니다. ^^ 따라서 해당 이벤트는 직접 커스텀 이벤트로 구현하시면 됩니다. 

화면이라면 지도를 말씀하시는건가요? 그렇다면 naver.maps.Event.addListener(map, 'click', function(){}); 과 같이 지도 이벤트를 사용할 수 있습니다.
