### ISSUE TITLE
기존 지도 서비스 화면에 경고창 제거 방법

### ISSUE THREAD

**Issue by sportsst** [navermaps/maps.js#229]
#### 내용 (Description)
v2에서 v3으로 수정중에 있습니다만,  기존 화면에서 계속 경고창이 보이는데요 이게 서비스중에는 안보여야 할거 같은데요 어떻게 해야 할까요

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by boxersb** [comment]
@sportsst 경고창이 보여서 많이 불편하시겠지만, v2 -> v3 전환률이 현재 높지 않은 상태여서, 배너 노출을 결정했습니다.  
이용자분들의 불편을 고려하여 내부에서 다시 검토해보겠습니다.

감사합니다~

**Comment by thetaiz** [comment]
배너를 제거하였으므로 이 이슈는 닫습니다.
