### ISSUE TITLE
클러스터링 마커

### ISSUE THREAD

**Issue by monkeychoi** [navermaps/maps.js#23]
네이버 지도는 마커 클러스터링은 지원하지 않나요 ? 항공뷰 마커는 관련 기능이 적용된 것 같은데 일반 마커에는 그렇지 않은 것 같아서요
향후 계획은 혹시 있으신가요??

**Comment by monkeychoi** [comment]
답변이 있었네요 지원 계획이 없으시군요

**Comment by boxersb** [comment]
@monkeychoi 안녕하세요? 클러스터링 마커는 지도 API v3에 기본 탑재하지 않을 계획이구요..
오픈 소스 형태로 클러스터링을 지원할 수 있는 모듈을 제공할 계획에 있습니다.

감사합니다.
