### ISSUE TITLE
오픈레이어스에서 배경지도 사용 가능여부

### ISSUE THREAD

**Issue by smzziu** [navermaps/maps.js#230]
안녕하세요. 오픈레이어스에서 네이버 배경지도를 사용해도 문제가 없을까요?

저작권이나 약관에 위배되지않는지 궁굼합니다.

다음지도 같은경우는 사용 불가 ( https://devtalk.kakao.com/t/topic/38470)
라고되어있어서요.

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by boxersb** [comment]
@smzziu 안녕하세요?

네이버지도도 다음지도와 같은 이유로 오픈레이어스상에서 지도 타일 사용은 저작권 및 약관에 위배됨을 알려드립니다.

감사합니다~
