### ISSUE TITLE
map.getBounds () 값이????

### ISSUE THREAD

**Issue by happykony** [navermaps/maps.js#234]
#### 내용 (Description)

map.getBounds () 를 통해 얻는 값이 이상합니다.
SW, NE 에 대한 값이 아닌
map 의 center 좌표만 나옵니다.
원래 이런 건가요?? 지도 경계 좌표 값을 구하는 방법이 따로 있나요?

#### 환경 (Environment)

윈도우즈7, IE11

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by thetaiz** [comment]
@happykony 님, 저희쪽에서 확인할 수 있는 URL이 있나요? 예제 페이지에서 확인해 보니 정상적으로 동작하고 있습니다.

**Comment by happykony** [comment]
소스코드의 다른 부분에 문제가 있었나보네요....
다른 기능 빼고 지도만 띄운 상태에서 테스트 해보니까 제대로 값이 나옵니다....
답변 감사합니다.
