### ISSUE TITLE
사용자 정의 오버레이 문의

### ISSUE THREAD

**Issue by happycgi** [navermaps/maps.js#235]
https://navermaps.github.io/maps.js/docs/tutorial-custom-overlay.example.html
위에 있는 링크의 예제를 참고해서 작업중입니다

하고싶은것은 여러개의 사용자 오버레이를 지도에 뿌려주고 싶은데요
(샘플이페이지나 소스가 있다면 감사하겠습니다..)

위의 샘플은 클릭을 하였을때 사용자 오버레이가 추가되지만 전 클릭하지 않고
반목문안에 샘플소스를 넣어 실행하도록 하였습니다(position 좌표만 변경하여 바로 나올수 있도록)

그런데 좌표에 오버레이가 위치하지 않고 일렬로 그냥 추가가되어 버리는데요
무엇을 수정해줘야 할까요..?

**Comment by thetaiz** [comment]
@happycgi 님, 여러 개의 사용자 정의 오버레이를 올리는 예제는 없으나, 링크의 예제를 통해서 쉽게 만들 수 있습니다. 사용자 정의 오버레이 클래스를 만들어 놓고, 아래와 같이 필요한 만큼 사용자 정의 오버레이를 생성하면 됩니다.

```
var overlay = new CustomOverlay({
        position: e.coord
    });

overlay.setMap(map);
```

일렬로 그냥 추가가 된다는 것은 어떤 설명인지 궁금하네요.

**Comment by happycgi** [comment]
아...  html 디자인이 잘못되어져서 문제가 생겼던 거네요
디버깅을 좀 더 해볼걸 하는 생각이 드네요
빠른 답변 고맙습니다

**Comment by thetaiz** [comment]
@happycgi 궁금하신 것이 있으면 언제든지 문의를 주세요~ ^^ 이 이슈는 닫겠습니다.
