### ISSUE TITLE
행정구역의 GeoJson데이터를 얻어 지도상에 표시하고 싶습니다.

### ISSUE THREAD

**Issue by udkw93274** [navermaps/maps.js#236]
#### 내용 (Description)
행정구역의 GeoJson데이터를 얻어 지도상에 표시하고 싶습니다.
광역시, 도 / 시군구 / 읍면동 에 관련된 좌표 정보를 얻고 싶은데 얻을 수 있는 API가 있을까요?
또한 얻을 때 네이버에서 사용하는 지역코드를 받을 수 있을까요?

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
행정구역 GeoJson 데이터를 제공하는 API는 없습니다.
