### ISSUE TITLE
How to send from address and to address parameters to Naver Map

### ISSUE THREAD

**Issue by dkchittimilla** [navermaps/maps.js#24]
Hi Team,

In our application, we have a link to naver maps. When user click on that link we should open a new window which points to map.naver.com. In the map we need to show the directions.

We are trying to send the source address and destination address using the parameters **saddr** and **daddr** (like the one used for google maps). But this is not working. 

http://map.naver.com/?saddr=My+Location&daddr=xxx

Please help me on this.

**Comment by boxersb** [comment]
@dkchittimilla 

We can't share target url that landing to Naver maps service. There are several technical & security reasons. Sorry~

**Comment by dkchittimilla** [comment]
@boxersb  

We are not sharing the target URL, in our anchor tag, we are keeping href as "http://map.naver.com". This is loading fine in new window, but with this we also want to share the source and destination address so that in the map we can see the directions line. 

Please check the highlighted section in below screen.

![image](https://cloud.githubusercontent.com/assets/11506930/18378683/004d018a-768c-11e6-8268-c9c7c1d5a132.png)

**Comment by cs09g** [comment]
It sounds like you need to use Routing API or Static map API. but I'm not sure Naver Map API supports them.

**Comment by boxersb** [comment]
@dkchittimilla It can't.

Again. We can't share target url `rules`. Sorry for omit word `rules`.

I can tell you one point.

Naver maps don't support directions restore url by departure and destination address. But, it provide url by coordinate of departure and destination, text of departure and destination.

The other rules are officially not notice. And.. we have a plan for encrypt whole coordinate. It's our national security issue. That's why we can't share rules.

Thanks.

**Comment by dkchittimilla** [comment]
@boxersb  

As mentioned by you in the comments **"But, it provide url by coordinate of departure and destination, text of departure and destination."**

Can you guide me how to frame naver map url with co-ordinates?

**Comment by cs09g** [comment]
What about to use like
![image](https://cloud.githubusercontent.com/assets/7428017/18380014/5b31100e-76b0-11e6-8582-bb8663e69147.png)

It's example [서울시청 to 을지로입구]

http://map.naver.com/?menu=route&mapMode=0&lat=37.5671975&lng=126.979976&dlevel=13&slng=126.9783882&slat=37.5666103&eslng=126.9787115&eslat=37.5669187&sdid=11556036&sType=SITE&elng=126.9826381&elat=37.56606&pathType=0&dtPathType=2&sText=7ISc7Jq47Yq567OE7Iuc7LKt&eText=7J2E7KeA66Gc7J6F6rWs7Jet&enc=b64

**Comment by boxersb** [comment]
@dkchittimilla 
I said. 
> We have a plan for encrypt whole coordinate. It's our national security issue.

Sorry~
