### ISSUE TITLE
API 좌표변환 문의 드립니다.

### ISSUE THREAD

**Issue by ls8653** [navermaps/maps.js#248]
주소 -> 좌표 변환을 해서 좌표 값을 가져오는데 실패가 되는 경우가 있습니다.
해당 주소로 맵검색을 하면 결과가 출력 되는데 어떤 문제가 있을까요?

**Comment by NaverMantle** [comment]
실패하는 주소를 알려주시면 확인해 보도록 하겠습니다.

**Comment by NaverMantle** [comment]
이슈 재동록 해주시면 같이 확인해 보겠습니다.
