### ISSUE TITLE
추가 기능 문의

### ISSUE THREAD

**Issue by dlengmlek** [navermaps/maps.js#249]
구글 map api에서 google 대신 naver 네임 변경 만으로도 사용할수 있어서 기존 구글맵 사용에서 네이버맵으로 편리하게 넘어왔습니다.

다만 구글맵을 선택했던 이유중에 하나가 지도 모드변경 즉 나이트모드 혹은 사용자지정으로 지도 색갈을 변경 할수있어서 였습니다. 막상 테스트하니 구글맵이 지도 반출 어쩌고하는 이유로 경로 탐색이나 나이트 모드 등 사용조차 안되고 더불어 국내맵은 sk 맵을 혼용사용하는것으로 보여집니다.

네이버지도의 경로 탐색이나 지도모드변경 그리고 지도 회전 기능을 추가해 주실 계획은 없으신지요.

**Comment by NaverMantle** [comment]
네. 추가되면 좋은 기능들이나 바로 제공은 어려운 기능들입니다.
내부 이슈로 등록하고 검토해보도록 하겠습니다.
좋은 의견 감사합니다.

**Comment by NaverMantle** [comment]
@dlengmlek 님
경로 탐색은 이제 지원이 가능합니다.
다만 지도 모드와 지도 회전은 웹 다이나믹 지도에서는 지원이 불가능하고 모바일 지도에서는 모두 지원이 가능합니다.
참고 부탁 드립니다.

관련 링크
- http://docs.ncloud.com/ko/naveropenapi_v3/maps/direction/driving.html
- https://navermaps.github.io/ios-map-sdk/guide/0.html
- https://navermaps.github.io/android-map-sdk/guide/0.html

**Comment by dlengmlek** [comment]
잊고 있었는데 이렇게 경로 탐색이라도 적용되어지니 너무 좋네요.
좋은 기능과 개선에 감사합니다. ㅎㅎ
