### ISSUE TITLE
개발자님에게 질문드립니다. 네트워크 느린 환경

### ISSUE THREAD

**Issue by eunmokKim** [navermaps/maps.js#250]
안녕하십니까 개발자님에게 문의드리려고 합니다.
네트워크가 느린환경에서 개발진행을 하고 있는데 
네이버지도 기본모듈에서 마커를 추가해서 쓰고있습니다.
마커로 지점은 잘 찍어주는거 같으나 크롬 콘솔에서 아래와 같은 에러가 떨어지면서
네이버지도 UI가 회색화면으로 깨져서 나옵니다.
혹시다른방법으로 개선할 점이 있을지 문의드리고 싶습니다.

A parser-blocking, cross site (i.e. different eTLD+1) script, https://openapi.map.naver.com/openapi/v3/maps-geocoder.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by NaverMantle** [comment]
맨 하단 See more details 페이지 가보시면 2G 사용자 (느린 네트워크 사용자)의 경우
document.write를 통해 스크립트 삽입하는 것을 차단하고 있다고 합니다.

해당 페이지에 가보시면 관련 문서가 있으니 참고 부탁드립니다.
https://www.chromestatus.com/feature/5718547946799104
