### ISSUE TITLE
Marker 삭제가 안됩니다.

### ISSUE THREAD

**Issue by chunsoo59** [navermaps/maps.js#251]
#### 내용 (Description)

Zoom 에 따라 마커를 올린 후 Zoom이 변경되면 마커를 삭제해야 하는 기능을 구현하고 있습니다.
https://github.com/navermaps/maps.js/issues/31 에 나온데로 marker.setMap(null); 로 삭제하려는데 삭제가 안됩니다.
Marker를 샘플로 3개까지 올렸는데, 문제없이 올라가는데, 삭제를 하려면, 멈취 버립니다. 개발자도구에서 보니. addrMarker.setup(null);  에서 Uncaught ReferenceError: addrMarker is not defined 라는 메시지가 나옵니다.

#### 환경 (Environment)

Linux, apache, php, wordpress
* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

function myAddrMarker (myAddr, myStr, myTitle) {
	var items;
	
	naver.maps.Service.geocode({
			address: myAddr
		}, function(status, response) {
			if (status !== naver.maps.Service.Status.OK) {
				return alert('Something wrong!');
			} 

			var result = response.result; // 검색 결과의 컨테이너
			items = result.items; // 검색 결과의 배열
		}
	);
		
	var addrMarker = new naver.maps.Marker({
		position: new naver.maps.LatLng(items[0].point.x, items[0].point.y),
		map: map,
		icon: {
			content: [ myStr ].join(''),
			size: new naver.maps.Size(38, 58),
			anchor: new naver.maps.Point(19, 58),
		}
	});
		
	addrMarker.setTitle(myTitle);
}

naver.maps.Event.addListener(map, 'zoom_changed', function(zoom, marker) {
	cZoom = map.getOptions("zoom");

	switch (cZoom) {
		case 5 :
		case 6 :
			var tmpStr = '<div  style="background-color:blue; color:white"> <div  align="center">서울특별시</div> 
			myAddrMarker ('서울특별시', tmpStr, '서울특별시');
			break;

		default :
			addrMarker.setup(null); // 
			break;
	}
});

* Site URL, Source Code

**Comment by chunsoo59** [comment]
marrker 삭제를 위해 이런 저런 시도를 하다, 현재 소스에서는 marker 생성마저 안되고 있네요.

**Comment by chunsoo59** [comment]
동작하는 소스 다시 올립니다. 그냥 marker가 표시만 되는 소스입니다.
이를 Zoom에 따라 보였다 안 보였다 해야 합니다.

function myAddrMarker (myAddr, myStr, myTitle) {
	var items;
	
	naver.maps.Service.geocode({
			address: myAddr
		}, function(status, response) {
			if (status !== naver.maps.Service.Status.OK) {
				return alert('Something wrong!');
			} 

			var result = response.result; // 검색 결과의 컨테이너
			items = result.items; // 검색 결과의 배열
			
			var addrMarker = new naver.maps.Marker({
				position: new naver.maps.LatLng(items[0].point.y, items[0].point.x),
				map: map,
				icon: {
					content: [ myStr ].join(''),
					size: new naver.maps.Size(38, 58),
					anchor: new naver.maps.Point(19, 58),
				}
			});
			addrMarker.setTitle(myTitle);
		}
	);
}

var tmpStr = '<div  style="background-color:blue; color:white"> <div  align="center">서울특별시</div> <p /> 매매 1,000 전세 1,000 <br /> 인구 800만 가구 250만 </div>';
myAddrMarker ('서울특별시', tmpStr, '서울특별시');

**Comment by chunsoo59** [comment]
function myAddrMarker (myAddr, myStr, myTitle) {
	var items;
	
	naver.maps.Service.geocode({
			address: myAddr
		}, function(status, response) {
			if (status !== naver.maps.Service.Status.OK) {
				return alert('Something wrong!');
			} 

			var result = response.result; // 검색 결과의 컨테이너
			items = result.items; // 검색 결과의 배열
			
			var addrMarker = new naver.maps.Marker({
				position: new naver.maps.LatLng(items[0].point.y, items[0].point.x),
				map: map,
				icon: {
					content: [ myStr ].join(''),
					size: new naver.maps.Size(38, 58),
					anchor: new naver.maps.Point(19, 58),
				}
			});
			addrMarker.setTitle(myTitle);
		}
	);
}

var tmpStr = '<div  style="background-color:blue; color:white"> <div  align="center">서울특별시</div>  </div>';
myAddrMarker ('서울특별시', tmpStr, '서울특별시');

**Comment by chunsoo59** [comment]
http://forum.developers.naver.com/t/topic/9667
이 내용을 보았는데, 그래도 어느 부분이 잘 못되었는지 모르겠네요.

**Comment by NaverMantle** [comment]
올려주신 내용만 봤을 때는 문제 없어보입니다.
전체코드나 확인 가능한 URL이 있을까요?

**Comment by NaverMantle** [comment]
작성하시는 코드 URL을 올려주시거나 테스트 할 수 있는 코드를 새로운 이슈에 등록해주시면 같이 확인해보겠습니다.
우선 이슈 닫을께요.
