### ISSUE TITLE
Subresource Integrity 웹 보안 취약점 관련 사항

### ISSUE THREAD

**Issue by greatBK81** [navermaps/maps.js#252]
#### 내용 (Description)
안녕하세요. 사이트 구축 후 웹 보안 취약점 점검을 진행했는데 네이버지도API용 자바스크립트를 
추가한 부분에서 Subresource Integrity 웹 보안취약점이 발견 되었다고 회신을 받았습니다.
해당 이슈 관련하여 integrity 정보를 배포하실 계획은 없으신가요?

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
지도 JS 배포 방식이 nodejs 나 bootstrap 와는 달리 내부적으로 버전을 업데이트하여 사용자가 항상 최신 버전을 내려 받도록 되어 있습니다. 해당 배포 방식으로 SRI 보안 처리가 어렵습니다. 참고 부탁 드립니다.
