### ISSUE TITLE
네이버 지도 도형에 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by leesangu** [navermaps/maps.js#255]
네이버 지도(JavaScript v3)를 사용하여 개발 중에 있습니다.
네이버 지도에서 user가 도형(원(타원), 사각형, 폴리곤등)을 그렸을 때, 그 도형안에 있는 모든 marker의 좌표(x좌표, y좌표)를 구할 수가 있나요?(도형범위 밖에 있는 maker는 제외)

**Comment by leesangu** [comment]
죄송하지만 leesangu@koreacb.com으로 메일 부탁드립니다.

**Comment by NaverMantle** [comment]
안녕하세요.
도형을 그리시고 도형의 getBounds() 를 통해 Bounds를 얻으시고 
마커가 hasLatLng 또는 hasBounds 에 포함되는지 체크하시면 됩니다.

#### 문서
[Marker](https://navermaps.github.io/maps.js/docs/naver.maps.Marker.html)
[Polygon](https://navermaps.github.io/maps.js/docs/naver.maps.Polygon.html)
[LatLngBounds](https://navermaps.github.io/maps.js/docs/naver.maps.LatLngBounds.html)

**Comment by NaverMantle** [comment]
메일로 전달 드렸습니다.
