### ISSUE TITLE
Ground overlay 구현 중 이미지가 삽입되지 않습니다.

### ISSUE THREAD

**Issue by jongho105** [navermaps/maps.js#257]
#### 내용 (Description)

   드론으로 촬영한사진을 네이버 지도상에 겹쳐서 Overlay 시켜 놓고 싶은데, 좌표평면 경계까지는 생성되는데 사진이 올라와있지를 않네요. 경로가 틀려서 확인을해봐도 이미지만 html에 올렸을때 올라가는걸로보아 경로문제는없는데, 경계선만 표시되고 이미지가 업로드되지않습니다.

질문1. zoom level 당 이미지 크기 ?
질문2. geotiff 이미지를 넣을려고 하는데, HTML 에서도 아이콘형식으로만 올라오던데 네이버 지도 올릴수있는 이미지 포맷형식을 알고싶습니다.

#### 환경 (Environment)

   HTML , JAVAscript 
OS: window
Browser : Chrome

#### 추가 정보 (Additional Info)

소스는 메일로보냈습니다.

**Comment by NaverMantle** [comment]
GeoTIFF 포멧은 브라우저에서 지원하지 않는 이미지 포멧이라 화면에 표시되지 않습니다.
사용가능한 이미지 포멧은 JPG, PNG, GIF, BMP 등 일반적으로 브라우저에서 지원하는 이미지 포멧입니다.

#### 참고 예제
[지상 오버레이 표시하기](https://navermaps.github.io/maps.js/docs/tutorial-ground-overlay.example.html)
