### ISSUE TITLE
docs/tutorial-marker-viewport.example.html 예제 실행 시 에러

### ISSUE THREAD

**Issue by parkjinyong12** [navermaps/maps.js#258]
#### 내용 (Description)

비로그인 오픈 API 서비스 환경
WEB 설정으로 해당 URL을 등록하였고,
file:///C:/Users/JD/AppData/Local/Temp/nonD5DC.htm

샘플 예제에서 maker의 icon 옵션 중 url옵션을 주석 처리하였음.  아래와 같은 에러 코드 확인.

maps.js:6 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.capitalize (maps.js:6)
    at n.Marker._icon_changed (maps.js:13)
    at n.Marker.__notifyChanged (maps.js:12)
    at n.Marker.set (maps.js:7)
    at n.Marker.setIcon (maps.js:13)
    at n.Marker.setOptions (maps.js:13)
    at maps.js:13
    at Object.forEach (maps.js:6)
    at n.Marker.setOptions (maps.js:13)
    at new n.Marker (maps.js:13)

#### 환경 (Environment)

Chrome 버전 64.0.3282.119(공식 빌드) (64비트)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>샘플 코드</title>
</head>
<body>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=********************"></script>
<div id="map" style="width:1920px;height:1024px;"></div>

<script type="text/javascript">
	/*
    //지도 생성시에 옵션을 지정할 수 있습니다.
	var map = new naver.maps.Map('map', {
		// 지도 초기 중심 위치
        center: new naver.maps.LatLng(37.541, 126.986),

		// 지도 확대/축소 설정
        zoom: 10, 
        minZoom: 7, 
        zoomControl: true, 
        zoomControlOptions: {
            position: naver.maps.Position.TOP_RIGHT
        }
    });

	var marker = new naver.maps.Marker({
		position: new naver.maps.LatLng(37.541, 126.986),
	    map: map
	});
	*/
	
	//var HOME_PATH = window.HOME_PATH || '.';
	var MARKER_SPRITE_X_OFFSET = 29,
		MARKER_SPRITE_Y_OFFSET = 50,
		MARKER_SPRITE_POSITION = {
			"A0": [0, 0],
			"B0": [MARKER_SPRITE_X_OFFSET, 0],
			"C0": [MARKER_SPRITE_X_OFFSET*2, 0],
			"D0": [MARKER_SPRITE_X_OFFSET*3, 0],
			"E0": [MARKER_SPRITE_X_OFFSET*4, 0],
			"F0": [MARKER_SPRITE_X_OFFSET*5, 0],
			"G0": [MARKER_SPRITE_X_OFFSET*6, 0],
			"H0": [MARKER_SPRITE_X_OFFSET*7, 0],
			"I0": [MARKER_SPRITE_X_OFFSET*8, 0],

			"A1": [0, MARKER_SPRITE_Y_OFFSET],
			"B1": [MARKER_SPRITE_X_OFFSET, MARKER_SPRITE_Y_OFFSET],
			"C1": [MARKER_SPRITE_X_OFFSET*2, MARKER_SPRITE_Y_OFFSET],
			"D1": [MARKER_SPRITE_X_OFFSET*3, MARKER_SPRITE_Y_OFFSET],
			"E1": [MARKER_SPRITE_X_OFFSET*4, MARKER_SPRITE_Y_OFFSET],
			"F1": [MARKER_SPRITE_X_OFFSET*5, MARKER_SPRITE_Y_OFFSET],
			"G1": [MARKER_SPRITE_X_OFFSET*6, MARKER_SPRITE_Y_OFFSET],
			"H1": [MARKER_SPRITE_X_OFFSET*7, MARKER_SPRITE_Y_OFFSET],
			"I1": [MARKER_SPRITE_X_OFFSET*8, MARKER_SPRITE_Y_OFFSET],

			"A2": [0, MARKER_SPRITE_Y_OFFSET*2],
			"B2": [MARKER_SPRITE_X_OFFSET, MARKER_SPRITE_Y_OFFSET*2],
			"C2": [MARKER_SPRITE_X_OFFSET*2, MARKER_SPRITE_Y_OFFSET*2],
			"D2": [MARKER_SPRITE_X_OFFSET*3, MARKER_SPRITE_Y_OFFSET*2],
			"E2": [MARKER_SPRITE_X_OFFSET*4, MARKER_SPRITE_Y_OFFSET*2],
			"F2": [MARKER_SPRITE_X_OFFSET*5, MARKER_SPRITE_Y_OFFSET*2],
			"G2": [MARKER_SPRITE_X_OFFSET*6, MARKER_SPRITE_Y_OFFSET*2],
			"H2": [MARKER_SPRITE_X_OFFSET*7, MARKER_SPRITE_Y_OFFSET*2],
			"I2": [MARKER_SPRITE_X_OFFSET*8, MARKER_SPRITE_Y_OFFSET*2]
		};

	var map = new naver.maps.Map('map', {
		center: new naver.maps.LatLng(37.3595704, 127.105399),
		zoom: 10
	});

	var bounds = map.getBounds(),
		southWest = bounds.getSW(),
		northEast = bounds.getNE(),
		lngSpan = northEast.lng() - southWest.lng(),
		latSpan = northEast.lat() - southWest.lat();

	var markers = [];

	for (var key in MARKER_SPRITE_POSITION) {

		var position = new naver.maps.LatLng(
			southWest.lat() + latSpan * Math.random(),
			southWest.lng() + lngSpan * Math.random());

		var marker = new naver.maps.Marker({
			map: map,
			position: position,
			title: key,
			icon: {
				//url: HOME_PATH +'/img/example/sp_pins_spot_v3.png',
				size: new naver.maps.Size(24, 37),
				anchor: new naver.maps.Point(12, 37),
				origin: new naver.maps.Point(MARKER_SPRITE_POSITION[key][0], MARKER_SPRITE_POSITION[key][1])
			},
			zIndex: 100
		});

		markers.push(marker);
	};

	naver.maps.Event.addListener(map, 'idle', function() {
		updateMarkers(map, markers);
	});

	function updateMarkers(map, markers) {

		var mapBounds = map.getBounds();
		var marker, position;

		for (var i = 0; i < markers.length; i++) {

			marker = markers[i]
			position = marker.getPosition();

			if (mapBounds.hasLatLng(position)) {
				showMarker(map, marker);
			} else {
				hideMarker(map, marker);
			}
		}
	}

	function showMarker(map, marker) {

		if (marker.getMap()) return;
		marker.setMap(map);
	}

	function hideMarker(map, marker) {

		if (!marker.getMap()) return;
		marker.setMap(null);
	}

</script>
</body>
</html>

* Site URL, Source Code

https://navermaps.github.io/maps.js/docs/tutorial-marker-viewport.example.html

**Comment by NaverMantle** [comment]
서비스 URL은 file:/// 만 등록해주세요.
서비스 URL을 변경해 보시고 오류가 나신다면 다시 이슈 등록해 주세요.
