### ISSUE TITLE
지도API 키워드(예:치과) 검색방법은?

### ISSUE THREAD

**Issue by JeongJunKyo** [navermaps/maps.js#26]
지도API 키워드(예:치과) 검색을 하려면
검색API 를 같이 이용해야 하나요?
그리고 검색 데이터의 최종수정일자를 가져올수 있나요?

**Comment by cs09g** [comment]
검색API 에 문의를 해주셔야 할 것 같아요..

**Comment by boxersb** [comment]
@JeongJunKyo 안녕하세요? 검색 API 중 지역 검색 API를 사용하셔야 하며 가이드 페이지는 아래와 같습니다.
> https://developers.naver.com/docs/search/local

검색 API에 대한 질문은 개발자 센터의 포럼 ( http://forum.developers.naver.com/c/api ) 을 이용해주시면 감사하겠습니다.

감사합니다~
