### ISSUE TITLE
폴리곤 삭제 Event

### ISSUE THREAD

**Issue by asknmap** [navermaps/maps.js#262]
#### 내용 (Description)
폴리곤을 DrawingManager를 이용해서 그리면
Default로 map click & polygon click event가 동작하는 것 같습니다.
polygon 클릭시 ( editable:true ) / map 클릭시 ( polygon editable:false)

그런데 정적으로 Polygon 객체를 생성하여 setMap할 경우에는
해당 기능을 따로 구현해줘야 하는 것입니까?
editable은 click후에 간단하게 할 수 있지만,
rightclick은 삭제버튼을 스스로 구현해야 하는겁니까?

#### 환경 (Environment)
윈10 / javascript 
* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
네. 해당 기능은 DrawingModule에서 제공하는 기능입니다.
도형을 직접 생성하셨다면 별도로 구현하셔야 합니다.
