### ISSUE TITLE
지도 API의 HeatMap 관련

### ISSUE THREAD

**Issue by aprolight** [navermaps/maps.js#265]
HeatMap 표출 관련하여 문의 드립니다.

mapOptions 에서 minZoom 선언 유무가 HeatMap 표시와 관련 있는 듯 합니다.

**mapOptions 에서 minZoom을 설정 하면 HeatMap이 표출되지 않고, 
mapOptions 에서 minZoom을 설정 하지 않으면 HeatMap이 표출됩니다.**

스크립트 코드는 아래와 같으며, 확인 부탁합니다.

	<script>
		//HeatMap 표출되지 않음
		var mapOptions = {
			center: new naver.maps.LatLng(37.3595704, 127.105399),
			zoom: 14,
			minZoom: 1,
			maxZoom: 14
		};
		
		//HeatMap 표출됨
		/*var mapOptions = {
			center: new naver.maps.LatLng(37.3595704, 127.105399),
			zoom: 14,
			maxZoom: 14
		};*/

		var map = new naver.maps.Map('map', mapOptions);
			
		var data = new Array();
			data[0] = new naver.maps.LatLng(37.3595704, 127.105399);
			data[1] = new naver.maps.LatLng(37.3585704, 127.104399);

		var heatmap = new naver.maps.visualization.HeatMap({
			map: map,
			data: data
		});
	
	</script>

**Comment by NaverMantle** [comment]
오류 확인하였습니다.
가급적 빠르 시일 수정하도록 하겠습니다.

**Comment by twipixel** [comment]
2019년 12월 19일에 수정된 버전 배포 예정입니다.
