### ISSUE TITLE
Polyline 퍼포먼스 문제

### ISSUE THREAD

**Issue by davidshimjs** [navermaps/maps.js#27]
어느 순간부터 Polyline을 한 path 그리는데 100ms 이상씩 걸리고 있습니다.
https://jsfiddle.net/p0jnuj7b/2/

참고로 구글 지도는 2~3ms 정도씩 걸리네요. 원래는 안그랬었는데, 어떤 변경에 의해 생긴 사이드 이펙트인 것 같아요.

그래서
https://navermaps.github.io/maps.js/docs/tutorial-2-datalayer-region.example.html
이런 예제 코드가 굉장히 느리게 그려집니다. (저희도 polyline을 200개 이상씩 쓰거든요.)

**Comment by cs09g** [comment]
Polyline 한 번 호출 하는 것 자체가 좀 딜레이가 있는건가요??
루프 안돌고 그냥 한번에 배열 자체를 넣어도 시간이비슷하게 나오는거 같네요.
https://jsfiddle.net/p0jnuj7b/4/

**Comment by thetaiz** [comment]
@davidshimjs 님, 해당 현상에 대한 패치가 진행될 예정입니다. 죄송합니다.

**Comment by davidshimjs** [comment]
@cs09g 네 새로운 인스턴스를 생성하는 액션 자체에 딜레이가 있는 것 같아요. 원래 polyline을 그리는 작업은 딜레이가 별로 없거든요. @thetaiz 죄..죄송할 것 까지야;; 항상 고맙게 사용하고 있습니다 :) 감사합니다~!

**Comment by thetaiz** [comment]
@davidshimjs 님, 패치가 끝났습니다. 확인을 부탁드립니다. ^^

**Comment by davidshimjs** [comment]
네 문제 없습니다~! 감사합니다 👍

**Comment by thetaiz** [comment]
넵, 그럼 이슈를 닫겠습니다. 감사합니다. ^^
