### ISSUE TITLE
익스플로러에서는 잘 적용되는데 크롬에서는 인증 실패가 되네요. 크롬은 지원 안되는건가요.

### ISSUE THREAD

**Issue by commelboy777** [navermaps/maps.js#271]
안녕 하세요 

익스플로러에서 아래 사진과 같이 잘 적용 됩니다. 

![image](https://user-images.githubusercontent.com/37855714/38004987-b2bde834-3279-11e8-883e-57b5d903dacd.png)

하지만 크롬에서는 아래 그럼과 같이 인증 실패가 나고 있습니다. 
크롬은 적용 안되는 건가요?

![image](https://user-images.githubusercontent.com/37855714/38005010-c7690a48-3279-11e8-9bc4-e5e20cfc087c.png)

파이어폭스도 실행하니 크롬과 같은 인증 실패가 되네요. 

제가 처음 적용때는 크롬과 파이어폭스도 동작한걸 확인한것 같은데 

오늘 확인 결과 인증 실패가 나오고 있습니다.

버젼은 V2 버젼입니다.

**Comment by cs09g** [comment]
제 생각에는 도메인이 동일하다면 인증이 성공해야 정상일 것 같습니다. 또는 브라우저 캐시 삭제를 한 후에 다시 시도해보시면 될 것 같습니다.

**Comment by NaverMantle** [comment]
안녕하세요.
V2는 서비스 종료 되었습니다.

아래 관련 링크와 마이그레이션 가이드 첨부 드립니다.

- [네이버 지도 JS api v2 종료 안내 [2017년 12월 11일]](https://developers.naver.com/notice/article/10000000000030654987)
- [(구) 네이버 오픈 API 호출 종료에 따른 마이그레이션 안내](https://developers.naver.com/notice/article/10000000000030640929)
- [마이그레이션: v2에서 v3로 전환하기](https://navermaps.github.io/maps.js/docs/tutorial-Migrate-From-v2.html)
- [API 이용 안내 FAQ](https://developers.naver.com/products/intro/faq/)

**Comment by cs09g** [comment]
@NaverMantle 조금 이상한점은, v2 서비스 종료가 되었는데 IE에서 동작했다는 것은 무슨 현상일까요? 일시적인것으로 봐야하는것인지...

**Comment by NaverMantle** [comment]
실제로 테스트 해보시면 같은 동작하지 않습니다. 캐쉬 문제라 생각합니다.
