### ISSUE TITLE
ie11 에서는 panorama가 구현이 안되요!!

### ISSUE THREAD

**Issue by MyNameKimTaeSeong** [navermaps/maps.js#272]
#### 내용 (Description)
   크롬에서는 파노라마가 구현이 되는데 ie11 에서는 구현이 안됩니다.
   원인을 알 수 가 없네요.

#### 환경 (Environment)

    visual studio 2008 에서 개발중입니다.

* window Ultimate K, ie11 , 11.0.9600.18952, Device Information, etc:

#### 추가 정보 (Additional Info)

    http://localhost/gimje16/naver_panorama.aspx

   소스는 네이버 api panorama 기본 예제 소스입니다.
   

* Site URL, Source Code

**Comment by cs09g** [comment]
브라우저 에러 메시지를 첨부해주셔야 할 것 같습니다.(개발팀에서 이제 더 이상 게시글을 확인하지 않는 것 같아.. [네이버 개발자 센터](https://developers.naver.com/forum/list)에 업로드하시는 것을 권장합니다)

**Comment by NaverMantle** [comment]
안되시면 다시 이슈 등록 부탁드릴께요.
