### ISSUE TITLE
사용자 정의 지도를 만들고 있습니다.(그린팩토리 에디터)

### ISSUE THREAD

**Issue by Johnjoo** [navermaps/maps.js#273]
지도 테스트 해보고 있습니다.
네이버 지도 API v3가 정상적으로 동작합니다.

#### 내용 (Description)
그린팩토리 에디터해서 회사의 설계도를 만들고 있습니다.

#### 환경 (Environment)
윈10, 인터넷익스플러어10
* OS, OS Version, Browser, Browser Version, Device Information, etc:

궁금한점
1.
그린팩토리에서 글자로 "안방", "작은방", "거실"

이렇게 표시를 할려고 하면 어떻게 해야 하나요?

2. 
그린팩토리에서 좌표를 알수 있을까요?
마우스 휠을 돌리면 중심이 안잡히고, 이래저래 확대되고 축소되고...

**Comment by NaverMantle** [comment]
답변 드립니다.

1. 표시 방법은 타일 이미지에 직접 글자를 입력하시거나 사용자 Layer 생성해서 Label만 올리실 수 있습니다.
2. 좌표는 아래 좌표 이해 가이드를 참고하셔서 사용자 지도에 따른 거리 계산을 직접 하셔야 합니다.

#### 사용자 Layer 샘플 코드
사용자 Layer 샘플 코드는 [이미지 타일 지도 유형](https://navermaps.github.io/maps.js/docs/tutorial-2-maptypes-imagemaptype.example.html) 예제 하단에 labelLayer 만 생성해서 추가하였습니다.
```
var map = new naver.maps.Map('map', {
    center: new naver.maps.LatLng(37.3595704, 127.105399),
    zoom: 10,
    mapTypeControl: true,
    mapTypeControlOptions: {
        style: naver.maps.MapTypeControlStyle.DROPDOWN
    }
});

var openStreetMapType = new naver.maps.ImageMapType({
    name: 'OSM',
    minZoom: 0,
    maxZoom: 19,
    tileSize: new naver.maps.Size(256, 256),
    projection: naver.maps.EPSG3857,
    repeatX: true,
    tileSet: "https://c.tile.openstreetmap.org/{z}/{x}/{y}.png",
    provider: [{
        title: " /OpenStreetMap", // 출처 표기는 이미지 제공처의 정첵을 따라야 합니다.
        link: "http://www.openstreetmap.org/copyright"
    }]
});

map.mapTypes.set('osm', openStreetMapType);
map.setMapTypeId('osm');

var labelMapTypeOptions = {
    name: '라벨 지도',
    minZoom: 0,
    maxZoom: 19,
    projection: naver.maps.EPSG3857,
    tileSize: new naver.maps.Size(256, 256),
    repeatX: true,
    vendor: 'MyCorp.',
    tileSet: [
        'https://mts1.googleapis.com/vt?lyrs=m@234000000&src=apiv3&hl=ko-KR+&x={x}&y={y}&z={z}&style=50,37%7Csmartmaps',
    ]
};

var labelMapType = new naver.maps.ImageMapType(labelMapTypeOptions);

var labelMapTypeRegistry = new naver.maps.MapTypeRegistry({
    'labelLayer': labelMapType
});

var labelLayer = new naver.maps.Layer('labelLayer', labelMapTypeRegistry);
labelLayer.setMap(map);

$('#labelLayer').on('click', function(e) {
    e.preventDefault();

    var btn = $(this);

    if (labelLayer.getMap()) {
        labelLayer.setMap(null);
        btn.removeClass('control-on').val('POI 켜기');
    } else {
        labelLayer.setMap(map);
        btn.addClass('control-on').val('POI 끄기');
    }
});


```

#### 좌표 이해 가이드
- [지도 서비스는 어떻게 만드는 것일까? ](https://d2.naver.com/helloworld/1174)
- [네이버 지도 JavaScript API 완벽 가이드 - 투영, 지도 유형 편(https://d2.naver.com/helloworld/9121395)

**Comment by Johnjoo** [comment]
예시 소스에서 다음 부분에 대한 설명을 
https://mts1.googleapis.com/vt?lyrs=m@234000000&src=apiv3&hl=ko-KR+&x={x}&y={y}&z={z}&style=50,37%7Csmartmaps
알아 볼수 있는 곳은 없을까요? 저 부분을 이해 하기가 어렵습니다.

**Comment by NaverMantle** [comment]
@Johnjoo 님

관련 문서를 찾아보려고 해도 안나오네요.

구글 타일 서버 관련해서는 외부에 제공하는 API가 아니라서 없는거 같은데요.

유사한 구글 mapType 설정하는 예제가 있어서 해당 링크만 첨부 드립니다.

아래 링크에 달 지도 타입 예제가 있습니다. 타일 요청시 인자별 설명은 없지만 타일을 요청하는 규약 정도로 생각하시면 될 듯 합니다.

https://developers.google.com/maps/documentation/javascript/examples/maptype-image
