### ISSUE TITLE
geojson 예제 문의

### ISSUE THREAD

**Issue by keepbang** [navermaps/maps.js#277]
geojson 예제를 보고 geoserver를 이용해서 맵에 행정구역 표시를 하고있습니다.
url로 json데이터를 가져오는거 까지는 했는데 예제중에

    success: function(idx) {
            return function(geojson) {
                regionGeoJson[idx] = geojson;

                loadCount++;

                if (loadCount === 17) {
                    startDataLayer();
                }
            }

여기서 idx는 무엇을 뜻하나요??

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
regionGeoJson 의 index 를 의미합니다. 
<img width="673" alt="2018-05-08 2 13 03" src="https://user-images.githubusercontent.com/32921533/39739082-f36e58b2-52c9-11e8-96d8-bb6ea01baaca.png">
