### ISSUE TITLE
초기지도 생성시 중점좌표 utmk로 생성가능한가요?

### ISSUE THREAD

**Issue by youdo80** [navermaps/maps.js#279]
utmk좌표계로 지도를 생성하고  싶은데 생성이 안되서 질의 드립니다.
이것저것 다해보는데 안되서 질문드립니다.

center: new naver.maps.LatLng(35.161112, 126.807099) ==> 가능
center: new naver.maps.Point(<?echo "$x_lat,$y_lng";?>) ==> 불가능
center: new naver.maps.UTMK(<?echo "$x_lat,$y_lng";?>) ==> 불가능

var map = new naver.maps.Map('map', {
        //center: new naver.maps.LatLng(LatLng), //지도의 초기 중심 좌표
        center: new naver.maps.Point(<?echo "$x_lat,$y_lng";?>), //지도의 초기 중심 좌표
        //center: new naver.maps.LatLng(35.161112, 126.807099), //지도의 초기 중심 좌표
        zoom: 10, //지도의 초기 줌 레벨
        minZoom: 1, //지도의 최소 줌 레벨
        zoomControl: true, //줌 컨트롤의 표시 여부
        zoomControlOptions: { //줌 컨트롤의 옵션
            position: naver.maps.Position.TOP_RIGHT
        }
    });

**Comment by twipixel** [comment]
네이버 지도 서비스는 기본적으로 UTMK를 변조한 UTMK_NAVER 좌표계를 사용하고 있습니다.
UTMK와 거의 비슷하여 그대로 사용할 수는 있지만 정확하게 UTMK를 사용하시려면 지도 타일이 있어야 합니다.

EPSG3857 좌표계를 사용한 예제는 아래와 같습니다.
- [이미지 타일 지도 유형](https://navermaps.github.io/maps.js/docs/tutorial-2-maptypes-imagemaptype.example.html)

위 예제를 보시면 투영을 EPSG3857 으로 변경하고 그에 맞는 지도 타일을 설정하고 있습니다.
타일과 좌표계는 세트라 생각하시면 됩니다.

아래는 투영과 지도에 관한 가이드 첨부 드립니다.
- [네이버 지도 JavaScript API 완벽 가이드 - 투영, 지도 유형 편](https://d2.naver.com/helloworld/9121395)

**Comment by NaverMantle** [comment]
네이버 지도 서비스는 기본적으로 UTMK를 변조한 UTMK_NAVER 좌표계를 사용하고 있습니다.
UTMK와 거의 비슷하여 그대로 사용할 수는 있지만 정확하게 UTMK를 사용하시려면 지도 타일이 있어야 합니다.

EPSG3857 좌표계를 사용한 예제는 아래와 같습니다.
- [이미지 타일 지도 유형](https://navermaps.github.io/maps.js/docs/tutorial-2-maptypes-imagemaptype.example.html)

위 예제를 보시면 투영을 EPSG3857 으로 변경하고 그에 맞는 지도 타일을 설정하고 있습니다.
타일과 좌표계는 세트라 생각하시면 됩니다.

아래는 투영과 지도에 관한 가이드 첨부 드립니다.
- [네이버 지도 JavaScript API 완벽 가이드 - 투영, 지도 유형 편](https://d2.naver.com/helloworld/9121395)
