### ISSUE TITLE
예제 에러

### ISSUE THREAD

**Issue by cs09g** [navermaps/maps.js#28]
두 가지의 지도 유형을 함께 사용하기[https://navermaps.github.io/maps.js/docs/tutorial-5-maptypes-naver_osm.example.html] 에서 

지도 모드 버튼을 '위성' -> 'OSM' -> '위성' 또는 '일반' 순서로 누르면 브라우저가 멈추고 다음 에러가 발생합니다.
Uncaught RangeError: Maximum call stack size exceeded

브라우저는 최신 크롬/ IE11 입니다.

**Comment by boxersb** [comment]
@cs09g 안녕하세요? 해당 예제에 문제가 있네요.. 수정하도록 하겠습니다~~ :)

**Comment by boxersb** [comment]
@cs09g 안녕하세요? 예제에서 발생하는 오류를 수정했습니다. 확인 부탁드려요~~

**Comment by cs09g** [comment]
@boxersb 네, 확인했습니다~ 잘되네요ㅎ
