### ISSUE TITLE
장소명 검색시 장소 id 값은  따로없나요?

### ISSUE THREAD

**Issue by KimHeaJi** [navermaps/maps.js#281]
장소명 검색한다음 장소 id 값을 별도로 저장해서 장소조회할때 id 값 사용해서 하려고 id 값 어디서 가져오나요?

**Comment by NaverMantle** [comment]
아래는 지도에서 제공하는 API 오버뷰입니다.
어떤 API 기능을 이야기 하시는걸까요?

**Comment by NaverMantle** [comment]
우선 이슈 닫도록 하겠습니다. 다시 이슈 등록 부탁드릴께요.
