### ISSUE TITLE
네이버 지도 경계 확장이 안되요!

### ISSUE THREAD

**Issue by modoodoc** [navermaps/maps.js#282]
#### 내용 (Description)
네이버 지도에서 마커를 올린 후에 이 마커가 모두 보이도록 네이버 지도의 경계를 확장하고자 합니다. 
하지만, 이러한 확장이 전혀 되지 않고 있습니다. 확장기능은 LagLngBounds 객체의
extend 를 통해 좌표를 확장 후에 Map 객체에 확장된 bound 객체를 인자로 하여 fitBounds() 를 호출하고
네이버 지도를 최종적으로 확장하는 것입니다.

#### 환경 (Environment)
OS 10.13.4

#### 추가 정보 (Additional Info)
```
        map = new naver.maps.Map('map_canvas', {
            center: new naver.maps.LatLng(37.536189, 126.979559),
            zoom: 10,
            zoomControl: true,
            zoomControlOptions: {
                style: naver.maps.ZoomControlStyle.SMALL,
                position: naver.maps.Position.TOP_LEFT
            },
        });

        // 마커 그룹의 중심을 지도의 중심으로 하기.
        var bounds = map.getBounds();
        for(var i=0;i<markers.length;i++) {
            bounds.extend({
                 latlng: markers[i].getPosition()
            });
         }

         map.fitBounds(bounds);
```

위는 제가 구현한 코드입니다. 어떻게 하면 네이버 지도를 마커를 모두 보이도록 확장할 수 있을까요?

답문 기다리겠습니다 감사합니다 :)

**Comment by NaverMantle** [comment]
안녕하세요.

아래 처럼 수정해 보세요.

```
for(var i=0;i<markers.length;i++) {
            bounds.extend(markers[i].getPosition());
         }
```

**Comment by modoodoc** [comment]
적어주신 코드로 수정했는데 지도가 마커를 포괄하여 확장하지 않는군요.. 

다른 문제가 있을까요?

**Comment by NaverMantle** [comment]
동작하는 코드를 첨부해주시거나 URL을 주시면 해당 코드를 테스트 해보겠습니다.

**Comment by NaverMantle** [comment]
다시 이슈 등록해 주시면 확인해보겠습니다.

**Comment by tlseoxhdfud** [comment]
안녕하세요 NaverMantle 님, 

거의 5개월 만에 다시 답글을 쓰는군요 결국 저희는 구글지도에서 네이버 지도로

옮기기로 결정하면서 이 문제를 해결해야 할 상황이 되어 다시 여쭙니다

동작하는 url은 아래와 같습니다 

http://mdd-bean-test.ap-northeast-2.elasticbeanstalk.com/search/ 

혹시 어떤 문제일지요?

답문 기다리겠습니다 감사합니다! :)
