### ISSUE TITLE
네이버지도 api키를 R에 연동시키고 싶습니다.

### ISSUE THREAD

**Issue by mrsensible** [navermaps/maps.js#284]
제목 그대로 네이버지도를 R에 연동시키고 싶습니다. python이랑 같은 방식으로 연동하면 될지 몰라서 이렇게 글을 남깁니다.

**Comment by NaverMantle** [comment]
안녕하세요. 
ggmap 패키지에 네이버 지도가 포함되어 있다고 합니다.
아래 링크 참고 부탁드립니다.

ggmap 으로 네이버지도 기반 시각화
- http://freesearch.pe.kr/archives/4247
- http://blog.naver.com/PostView.nhn?blogId=hwan0447&logNo=220690610749&parentCategoryNo=15&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView
