### ISSUE TITLE
네이버 지도 로드뷰 관련 문의 

### ISSUE THREAD

**Issue by moon-yc** [navermaps/maps.js#287]
네이버 지도 담당자님께, 

안녕하세요
서울특별시 서울시설공단 도로시설처 문영철차장입니다. 

귀 사에서 제공하고 있는 네이버 지도 로드뷰와 관련하여, 
우리 공단에서 유지관리중인 서울시 자동차 전용도로(강변북로, 올림픽대로, 내부순환로 등)의 
유지관리시 귀 사의 로드뷰 정보를 이용하여 상시 점검을  가능하도록 하고 싶습니다. 

이와관련하여,  네이버와 서울시설공단이 MOU를 체결하여 자동차전용도로에 대한 정보를 공유하고 싶습니다. 

구체적으로는,  초기단계에서 생각하는 내용은 다음과 같습니다.
 귀 사에서 제공하는 로드뷰 업데이트를 서울시 자동차 전용도로에 한정하여 
 2개월(가정)에 한번씩  네이버 지도에 업데이트 방안(소요 비용에 대해서는 용역계약 체결)

우리 공단에서는 24시간 관리하고 있는 자동차 전용도로상 실시간 CCTV 상황 및 비상상황에 대한 
정보를 네이버 화면에 제공하는 방안  

이러한 사항이 가능하시다면 정보 공유 및 회의를 하고 싶으니 회신을 바랍니다. 

감사합니다.

**Comment by twipixel** [comment]
안녕하세요.

제휴 관련 채널 알려드립니다.

아래 링크들에서 문의가 가능하시고 NCLOUD PLATFORM에서 유료 문의도 가능할 듯 합니다.

참고로 NCLOUD 에서는 유료화 버전은 9월중으로 준비할 예정입니다.

- [제휴 제안](https://www.navercorp.com/ko/company/proposalRegister.nhn)
- [제휴 신청](https://developers.naver.com/apps/#/cooperation)
- [제휴 문의](https://developers.naver.com/forum/list?cat=0a70f848-618d-1da5-8161-8dfdae5b0023&page=1)
- [NCLOUD 문의](https://www.ncloud.com/support/question)

**Comment by NaverMantle** [comment]
안녕하세요.

제휴 관련 채널 알려드립니다.

아래 링크들에서도 문의가 가능하시고 NCLOUD PLATFORM 기업 유료 문의도 가능할 듯 합니다.

참고로 NCLOUD 에서는 기업 유료화 버전은 9월중으로 준비 예정입니다.

- [제휴 제안](https://www.navercorp.com/ko/company/proposalRegister.nhn)
- [제휴 신청](https://developers.naver.com/apps/#/cooperation)
- [제휴 문의](https://developers.naver.com/forum/list?cat=0a70f848-618d-1da5-8161-8dfdae5b0023&page=1)
- [NCLOUD 문의](https://www.ncloud.com/support/question)
