### ISSUE TITLE
네이버지도앱 네비게이션 연동 지원 안되나요

### ISSUE THREAD

**Issue by rhrh82** [navermaps/maps.js#288]
안녕하세요
네이버 지도 API로 주소 목록을 가지고 네이버 지도 앱 내의 네비게이션과 연동할수 잇는 방법이 있는지요..

출발지 경유지 경유지 경유지 도착지..
이런식으로 말이죵..

앱을 별도로 개발한다면 네비게이션 쪽 네이버 API가 있을까요.. 안보여서 ㅋ

**Comment by NaverMantle** [comment]
안녕하세요.

URL 스키마 관련해서 [공식 문서](https://developers.naver.com/docs/utils/mobileapp/)를 찾아봤지만 외부로 제공되고 있지는 않아보입니다. 

아래 링크를 보시면 URL 스키마로 네이버 지도앱을 OS 별로 띄우는 예제를 보실 수 있는데요.
Android 예제를 실행해보니 네이버 지도앱까지는 띄울 수 있었습니다.
실제 내비게이션으로 바로 실행은 안되는 듯 합니다.

참고 부탁드립니다.

[네이티브 지도앱 링크 달기](https://blog.itanoss.kr/ko/%EB%84%A4%EC%9D%B4%ED%8B%B0%EB%B8%8C-%EC%A7%80%EB%8F%84%EC%95%B1-%EB%A7%81%ED%81%AC-%EB%8B%AC%EA%B8%B0/)

**Comment by rhrh82** [comment]
친절하고 상세한 답변 매우 감사드립니다 ^^ 일부러 자료까지 찾아 링크 달아주시다니 ㅠ.ㅠ
감격 입니다!
