### ISSUE TITLE
예제 모아보기 페이지

### ISSUE THREAD

**Issue by cs09g** [navermaps/maps.js#29]
예제 모아보기 페이지[https://navermaps.github.io/maps.js/docs/tutorial-digest.example.html] 에서 

해시 태그로 되어 있는 부분이 클릭했을 때 스스로를 링크해 스크롤 이동하도록 되어 있는데, navigation bar 때문에 위치가 맞지 않습니다. 특히 '#마커', '#정보창', '#도형' 등 작은 상자에 있는 항목은 id가 div 가 아닌 a 에 걸려있어 더 많이 위로 올라가다보니 한 줄 자체가 올라가 안보입니다.

**Comment by junthus** [comment]
@cs09g 엇 그런 문제가 있었군요. 수정하겠습니다. ^^

**Comment by junthus** [comment]
@cs09g 해당 a 태그는 페이지 내에서 클릭을 의도한 부분이 아니였기 때문에 클릭되지 않도록 수정하였습니다. 제보 감사드립니다 ^^
