### ISSUE TITLE
네이버 지도 무반응 관련

### ISSUE THREAD

**Issue by LeeJaeng** [navermaps/maps.js#290]
안녕하세요. 

다름이 아니라, 평소에도 네이버 지도를 아무 문제 없이 개발에 계속 사용해 왔었는데, 갑자기 이상한 문제가 생겨서 문의 드립니다. 

지도를 div 에 셋팅을 했는데, 아무 반응이 없습니다. zoom 컨트롤도 먹지 않고 드래그에도 아무 반응 없습니다. 
제대로 작동하는 지도에서 오른쪽 마우스 클릭을 하면 아무 것도 나타나지 않는데, 
지금 창에서는 오른쪽 클릭하면 이미지 저장하는 그런 것들이 생깁니다. 

혹시 놓친 것이 있는지 궁금합니다.

**Comment by twipixel** [comment]
안녕하세요.

우선 개발자 도구에서 Console 창에 나오는 오류 부터 확인해 주시고요.

콜솔에 별다른 오류가 없으면 보통은 div 의 width, height 가 
정의 되지 않았거나 다른 css 속성으로 인해 안보이는 경우가 있습니다.

가장 좋은 방법은 body 에 div 생성해서 거기에 지도를 붙혀보시면 나올거라 예상됩니다.

그래도 안되면 개발하시는 주소를 알려주시면 확인해 보겠습니다.

**Comment by NaverMantle** [comment]
위 조치대로 안되면 다시 이슈 등록 부탁드릴께요.
