### ISSUE TITLE
좌표->주소변환 

### ISSUE THREAD

**Issue by sksep627** [navermaps/maps.js#291]
좌표를 주소로 변화하는 API를 사용하고 있습니다.
https://openapi.naver.com/v1/map/reversegeocode

잘 사용하고 있었는데,, 갑자기 어제 오후 부터 MP03 오류를 내고 있습니다.

혹시.. 뭐가 변경된게 있나요???
지금 사용중이 사이트라,, 확인 부탁 드립니다.

ex) 아래 좌표를 검색해야 하는데,, 못하고 있어요..
130.4017155,33.5903547

**Comment by NaverMantle** [comment]
안녕하세요
MP03 오류는 API의 검색결과가 없다는 오류입니다.
openapi로 제공되는 좌표를 주소로 변환하는 API(reversegeocode)는 국내좌표를 주소로 변환하는 기능을 제공하고 있는데요
말씀주신 좌표(130.4017155,33.5903547)는 확인결과 일본 후쿠오카쪽 좌표로 보입니다.
따라서 해당 좌표에 API 결과가 없는게 맞습니다.

감사합니다.
