### ISSUE TITLE
지도 API 기능 문의드립니다..

### ISSUE THREAD

**Issue by choseonghyeon** [navermaps/maps.js#292]
#### 내용 (Description)

네이버 지도 API 중 구글 맵 API 기능의 지도 전체화면 [컨트롤기능](https://developers.google.com/maps/documentation/javascript/controls?hl=ko)이 존재하는지 문의드립니다. 
ex)
function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 4,
    center: {lat: -33, lng: 151},
    zoomControl: false,
    scaleControl: true,
    fullscreenControl: true
  });
}

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요.

네이버 지도는 MapOptions 의 size 를 생략하면 지도 DOM 요소의 HTML 랜더링 크기로 자동 리사이즈 됩니다.

아래 예제를 참고해 주세요.

[전체화면과 미니맵 예제](https://navermaps.github.io/maps.js/docs/tutorial-7-map-fullsize-minimap.example.html)
