### ISSUE TITLE
지도 API 문의

### ISSUE THREAD

**Issue by Kwansic** [navermaps/maps.js#293]
#### 내용 (Description)
 
1) 작년초에 네이버 지도 open API를 인증을 받았습니다. 허나 올해부터 인증이 해제되었습니다.
2) 또한 확인결과 익스플로러에서는 제대로 정상 출력을합니다. 그러나 크롬에서는 지도가 제대로 출력되지 않습니다.

#### 환경 (Environment)
 html

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)
 웹사이트 http://saeon.co.kr
소스코드 
<div module="mall_company">
   
    <div class="c_info">
		<img src="/dsm/img/sub/p_company3.png">

			
			<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=aA8VptB9Ml1mokyOsLI6&submodules=geocoder"></script>
			<script src="http://openapi.map.naver.com/openapi/v2/maps.js?clientId=aA8VptB9Ml1mokyOsLI6"></script>
			
			<div id = "testMap" style="border:1px solid #ff8f2e; margin:0 auto; margin-bottom:20px;">

			<script type="text/javascript">
                
                
				var oPoint = new nhn.api.map.LatLng(36.4200221, 127.4069893);
				nhn.api.map.setDefaultPoint('LatLng');
				oMap = new nhn.api.map.Map('testMap' ,{
							point : oPoint, 
							zoom : 12,
							enableWheelZoom : true,
							enableDragPan : true,
							enableDblClickZoom : false,
							mapMode : 0,	// - 일반모드0, 위성보기1
							activateTrafficMap : false,
							activateBicycleMap : false,
							minMaxLevel : [ 1, 14 ],
							size : new nhn.api.map.Size(750, 450)
						});
				
				var mapZoom = new nhn.api.map.ZoomControl(); // - 줌 컨트롤 선언
				themeMapButton = new nhn.api.map.ThemeMapBtn(); // - 자전거지도 버튼 선언
				mapTypeChangeButton = new nhn.api.map.MapTypeBtn(); // - 지도 타입 버튼 선언
				var trafficButton = new nhn.api.map.TrafficMapBtn(); // - 실시간 교통지도 버튼 선언
				trafficButton.setPosition({top:10, right:80}); // - 실시간 교통지도 버튼 위치 지정
				mapTypeChangeButton.setPosition({top:10, left:50}); // - 지도 타입 버튼 위치 지정
				themeMapButton.setPosition({top:10, right:10}); // - 자전거지도 버튼 위치 지정
				mapZoom.setPosition({left:10, top:10}); // - 줌 컨트롤 위치 지정.

				oMap.addControl(themeMapButton);
				oMap.addControl(trafficButton);

				var oSize = new nhn.api.map.Size(28, 37); //아이콘 사이즈
				var oOffset = new nhn.api.map.Size(14, 37); //아이콘 사이즈에 따른 위치 보정
				var oIcon = new nhn.api.map.Icon('http://static.naver.com/maps2/icons/pin_spot2.png', oSize, oOffset);

				var oIcon = new nhn.api.map.Icon('http://static.naver.com/maps2/icons/pin_spot2.png', oSize, oOffset);
				oMarker = new nhn.api.map.Marker(oIcon, { title : '|주|새온 042)933-3369' }); //마커 제목 생성
				oMarker.setPoint(oMap.getCenter()); // 마커 표시할 좌표 선택
				oMap.addOverlay(oMarker); //마커를 지도위에 표시

				//마커 라벨 출력
				 
				oLabel = new nhn.api.map.MarkerLabel(); //마커 라벨 선언
				oMap.addOverlay(oLabel); //마커 라벨 지도에 추가, 기본은 보이지 않는 상태로 추가됨
				oLabel.setVisible(true, oMarker); //마커 라벨 보이기

			</script>
			</div>
			<div style="font-size:14px; font-weight:bold; padding-bottom:150px; border-top:1px solid #cccccc; margin-left:220px; margin-right:220px; padding-top:10px;">(314072) 대전광역시 유성구 테크노9로 35 지능로봇산업화센터 512호</div>
	</div>

    <div class="{$map_display|display}">
        <h3>위치</h3>
        <p>{$map_image}</p>
    </div>
</div>

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요.

지도 OpenAPI V2 는 서비스 종료 되었습니다.

아래 링크 참고하셔서 V3로 교체 하셔야 합니다.


- [(구) 네이버 오픈 API 호출 종료에 따른 마이그레이션 안내](https://developers.naver.com/notice/article/10000000000030640929)
- [마이그레이션: v2에서 v3로 전환하기](https://navermaps.github.io/maps.js/docs/tutorial-Migrate-From-v2.html)
- [네이버 지도 API 명세](https://developers.naver.com/docs/map/overview/)
- [JavaScript API V3](https://navermaps.github.io/maps.js/docs/naver.maps.Map.html)
