### ISSUE TITLE
지도상의 거리를 수치화 할 방법이 있을까요 ?

### ISSUE THREAD

**Issue by jicu12** [navermaps/maps.js#294]
#### 내용 (Description)

데이터베이스에 여러 장소들에 대한 정보를 입력해둔 상태이고
지도상에 한 기준 장소를 두고 그로부터 일정 범위 내에 위치하는 장소만 데이터베이스에서 뽑아와서 마커로 표시하고싶은데요.
범위 내의 장소표기 같은 예제가 없어서 질문드립니다.
#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요.
아래 2가지 방법이 있을 듯 합니다.

- getDistance 함수 이용 하는 방법
- 바운즈에 좌표가 포함되었는지 체크하는 방법

getDistance 이용방법은
[MapSystemProjection](https://navermaps.github.io/maps.js/docs/naver.maps.MapSystemProjection.html) 의 getDistance 함수나 getDestinationCoord 을 활용하시는 방법입니다.

바운즈내에 확인은
[LatLngBounds](https://navermaps.github.io/maps.js/docs/naver.maps.LatLngBounds.html) 클래스에 hasLatLng(latlng) 을 이용하는 방법입니다.

**Comment by jicu12** [comment]
감사합니다 getDistance 함수 사용해보도록 하겠습니다 ^^

**Comment by NaverMantle** [comment]
필요하시면 재이슈 등록 부탁드립니다. 이슈 닫도록 하겠습니다~
