### ISSUE TITLE
지도 API를 사용할때 자바스크립트에서 스크립틀릿 변수사용시 지도가 안나와요

### ISSUE THREAD

**Issue by jicu12** [navermaps/maps.js#295]
#### 내용 (Description)

제목 그대로입니다.
네이버지도 API를 사용하는데 자바스크립트에서 스크립틀릿 변수를 가져와서 사용하려하는데
이렇게 코드를 짜면 지도가 웹상에 표시가 전혀 안되더라구요.
변수를 가져오지 않고 위에 0,1,2 번째 배열값처럼 절대경로를 넣었을때는 이상없이 작동이 됩니다.
아래 코드의 위에서 5번째 줄입니다. 
            	var addArr=new Array();
            	addArr[0]='인하로77번길 29';
            	addArr[1]='인하로67번길 24-20';
            	addArr[2]='인천 남구 경인남길 90';
            	addArr[3]=<%=add%>;  ################지도 표기오류
            	            	
            	
            	urlArr= new Array();
            	urlArr[0]='https://store.naver.com/restaurants/detail?id=37483560&query=%EB%AF%B8%EB%A1%9C%EA%B3%B1%EC%B0%BD';
            	urlArr[1]='https://store.naver.com/restaurants/detail?id=35337901&query=%EC%9A%B0%EC%84%A0%EC%86%8C%EA%B3%B1%EC%B0%BD';
            	urlArr[2]='https://store.naver.com/restaurants/detail?id=33078284&query=%EB%82%A8%EB%8F%84%EB%BD%80%EA%B8%80%EC%9D%B4';
            	urlArr[3]='https://www.inhatc.ac.kr';
            	nameArr=new Array();
            	nameArr[0]='<a href="https://store.naver.com/restaurants/detail?id=37483560&query=%EB%AF%B8%EB%A1%9C%EA%B3%B1%EC%B0%BD" target="_blank">미로곱창</a>';
            	nameArr[1]='<a href="https://store.naver.com/restaurants/detail?id=35337901&query=%EC%9A%B0%EC%84%A0%EC%86%8C%EA%B3%B1%EC%B0%BD" target="_blank">우선소곱창</a>';
            	nameArr[2]='<a href="https://store.naver.com/restaurants/detail?id=33078284&query=%EB%82%A8%EB%8F%84%EB%BD%80%EA%B8%80%EC%9D%B4" target="_blank">남도뽀글이</a>';
            	nameArr[3]='<a href="http://www.inhatc.ac.kr" target="_blank">인하대학교</a>';
   				var map = new naver.maps.Map('map');				// ###################맵 변수 설정
   				var myaddress = '인하로100'; 							//################<.%=_address%> 자바 변수값 받아오기가 정상실행이 안됌
   				for(var i=0;i<addArr.length;i++){
					naver.maps.Service.geocode({address: addArr[i]}, function(status, response) {
		         		   if (status !== naver.maps.Service.Status.OK) {
		           		     return alert(addArr[i] + '의 검색 결과가 없거나 기타 네트워크 에러');
		        		    }
		        		    var result = response.result;
		        		    // 검색 결과 갯수: result.total
		         		   // 첫번째 결과 결과 주소: result.items[0].address
		         		   // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x
		         		   var myaddr = new naver.maps.Point(result.items[0].point.x, result.items[0].point.y);
		        		    map.setCenter(myaddr); // 검색된 좌표로 지도 이동
		         		   // 마커 표시
		           		 var marker = new naver.maps.Marker({
		          		    position: myaddr,
		           		   map: map
		          		  });
		          		  // 마크 클릭시 인포윈도우 오픈
		          		  var infowindow = new naver.maps.InfoWindow({
		          		      content:nameArr[i]
		          		  });
		           		 // 마커 클릭 이벤트 처리
		           		 naver.maps.Event.addListener(marker, "click", function(e) {
		           		   if (infowindow.getMap()) {
		           		       infowindow.close();
		          		    } else {
		           		       infowindow.open(map, marker);
		           		   }
		          		  });

		      		  });
				}
   				
#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code
데이터베이스에 여러 장소들에 대한 정보를 입력해둔 상태이고
지도상에 한 기준 장소를 두고 그로부터 일정 범위 내에 위치하는 장소만 데이터베이스에서 뽑아와서 마커로 표시하고싶은데요.
범위 내의 장소표기 같은 예제가 없어서 질문드립니다.

**Comment by jicu12** [comment]
추가사항입니다.
add라는 스크립트릿 변수가 
로그인 한 계정의 데이터베이스에서 주소를 불러오는 것인데
로그인이 안되어있을때는 지도가 정상적으로 뜨네요
로그인 한 후에 데이터베이스에서 add에 정상적인 값이 저장되는것까지는 확인을 했습니다.
add 값이 addArr배열에 들어갈때 문제가 생긴것 같습니다.

**Comment by NaverMantle** [comment]
해결하셨다니 다행입니다. 이슈 닫도록 하겠습니다!
