### ISSUE TITLE
Zoom에 따른 마커 이동 다시 문의드립니다.

### ISSUE THREAD

**Issue by cocoman1** [navermaps/maps.js#297]
이전에 답변 남겨주신 샘플 예제로 해서 처리는 가능 한듯 하나
여전히 마커가 줌 할때마다 움직이는게 이상한듯하여
다시 문의드립니다.
줌 값이 낮아질수록 마커가 지도상에서 옳바른 위치가 아니라
이동하는듯 하는데요.
확인 부탁드립니다.

확인 URL 첨부합니다.

http://www.makeus.co.kr/school/test_map.asp

**Comment by NaverMantle** [comment]
안녕하세요.

[HTML 마커 예제](https://navermaps.github.io/maps.js/docs/tutorial-5-marker-html-icon.example.html)에 휘문 고등학교를 올려 보았더니 정상으로 나옵니다.

그래서 작성하신 페이지 페이지에 CSS 없는 HTML 마커를 올려보니 위치 변경없이 잘 동작하는데요.

작성 하신 코드에 아래 마커 코드를 넣어보시면 위치 변경없이 잘 동작하시는걸 확인할 수 있습니다.

아마 CSS 를 확인해 보시면 좋을 듯 합니다.

```
var redMarder = new naver.maps.Marker({
    position: new naver.maps.LatLng(37.505109,127.061420),
    map: map,
    title: 'Green',
    icon: {
        content: ['<div style="width: 30px; height: 30px; border: 1px solid red">', '</div>'].join(''),
        size: new naver.maps.Size(30, 30),
        anchor: new naver.maps.Point(15, 15),
    },
    draggable: true
});
```

**Comment by cs09g** [comment]
코드를 보니까 `anchor`가 0,0으로 설정되어있네요. 이 경우 마커의 위치가 왼쪽 상단을 기준으로 동작합니다. `anchor`를 `new naver.maps.Point(30, 20)`으로 설정하고 테스트해보세요.(왼쪽 상단을 기준으로하고, 원하는 기준점은 중앙 하단이므로 (높이, 너비/2))
