### ISSUE TITLE
cross site 경고문에 대한 문의입니다.

### ISSUE THREAD

**Issue by Mellonia** [navermaps/maps.js#298]
#### 내용 (Description)

크롬 브라우저에서 웹 로드 시 콘솔창에

`
cross site (i.e. different eTLD+1) script, https://openapi.map.naver.com/openapi/v3/maps-geocoder.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
`

라는 워닝이 자꾸 뜹니다. 알아본 결과로 느린 네트워크에서는 다른 방식으로 서브모듈을 로딩한다고 하던데
그렇다면 **저 워닝이 뜨는 것은 지금 네트워크의 속도가 느리다는 의미인가요??**

그리고 map api를 임포트한 아래의 스크립트 문에서
  <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=~~~&submodules=geocoder"></script>

&submodules=geocoder 부분을 제거했더니 콘솔에서 워닝이 뜨지 않습니다.
**해당 부분을 제거하는 것으로 다른 기능적인 문제(맵, 마커 로드)가 발생하지 않나요?**
그리고 **해당 부분을 제거하면 느린 네트워크에서의 서브모듈이 로딩되지 않는건가요?**

저는 크롬 브라우저에서 상기에 표시한 워닝을 없애고 싶습니다. &submodules=geocoder를 없애는 것이
정답이 아니라면 어떤 방법이 없을까요?

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

Mac OS, Chrome Browser

#### 추가 정보 (Additional Info)

* Site URL, Source Code

URL : https://koreatech.in

**Comment by NaverMantle** [comment]
안녕하세요.
문제의 원인은 서브모듈(geocoder)을 로딩할 때 document.write 를 사용합니다.
이때 로딩이 완료되기 전까지 정지 상태가 되는데요. 
네트워크 느린 환경에서 document.write 를 사용하면 장애 서비스 처럼 보인다고 크롬에서 경고 메시지를 보내고 있습니다.

이에 따른 몇 가지 해결 방법 중에 쉬운 2가지를 알려드리겠습니다.

첫번째는 
submodules=geocoder 를 지우는 것입니다.
geocoder로 인해 발생하는 문제라 geocoder를 지우시면 문제 해결이 되며
geocoder는 지도나 마커 생성에는 영향이 없습니다.
geocoder의 역활은 아래 링크를 참고하세요.

두번째는
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=~~~&submodules=geocoder"></script>
스크립트 로드를 </body> 태그 바로 앞에 넣으시면 해결 됩니다.

더 자세한 해결 방법이나 원인에 대해서 궁금하시면 관련 링크 맨 하단을 참고 하세요.

관련 링크 
- [geocoder](https://navermaps.github.io/maps.js/docs/module-geocoder.html) 
- [크롬 경고 안내](https://www.chromestatus.com/feature/5718547946799104)
