### ISSUE TITLE
지도상에 시작점, 종료점으로 길찾기를 API를 통해서 사용 할 수는 없나요?

### ISSUE THREAD

**Issue by JONGHWALEE** [navermaps/maps.js#299]
지도상에 시작점, 종료점으로 길찾기를 API를 통해서 사용 할 수는 없나요?
레이어 표출을 포함해서 질의 드립니다

**Comment by NaverMantle** [comment]
안녕하세요.
안타깝게도 네이버 지도 OpenAPI 에는 길찾기 API가 없습니다.
