### ISSUE TITLE
naver.maps.Event.addListener  가 작동이 안되는 문제

### ISSUE THREAD

**Issue by stonepol** [navermaps/maps.js#3]
naver.maps.Event.addListener(marker, 'click', function() {
	alert("here");
});

마커의 클릭시 이벤트 처리를 위해 리스너를 등록하였습니다.
PC 브라우져에서 테스트시는 정상적으로 작동합니다..

다만 해당 페이지를 안드로이드 모바일 WebView 에서 호출하였습니다.
해당 마커를 클릭하였을 경우 해당 function 이 호출되지 않습니다..

그러나, WebView에서 marker가  아닌 map 이벤트 Listener는 정상적으로 호출됩니다.
here2와 here alert 창이 호출됩니다.. 

naver.maps.Event.addListener(map, 'click', function(e) {
        alert("here2");	
	naver.maps.Event.trigger( marker , 'click' , null );
});

안드로이드  WebView를 통해서는 마커의 클릭시 이벤트 전달 또는 InfoWindow 처리가 안되는듯 
싶습니다..

확인 바랍니다.

**Comment by boxersb** [comment]
@stonepol 안녕하세요.. 불편을 드려서 죄송합니다.. 해당 건 확인해보겠습니다~~

**Comment by boxersb** [comment]
@stonepol 혹시.. 해당 WebView 에서 https://navermaps.github.io/maps.js/docs/tutorial-1-infowindow-simple.example.html 이 예제도 동작하지 않는지요..?

Galaxy S5 의 안드로이드 브라우저에서 테스트 결과 이상이 없습니다. 혹시 재현되는 기기의 환경을 알려주실 수 있으신가요?

참고로, `naver.maps.Event.trigger` 로 이벤트를 강제 트리거할 경우 DOM 이벤트의 경우에는 정상동작하지 않을 수 있습니다. 모바일 기기에서의 click 은 실제로는 `touchend` 와 매핑되어 있습니다.

**Comment by boxersb** [comment]
@stonepol 이슈를 올리신지 7일이 경과하여, close 하도록 하겠습니다.
혹시 재현경로를 확인하셨다면 이슈 `Reopen` 부탁드립니다.

**Comment by jeongjaehong** [comment]
marker에 draggable 속성을 지정하는 경우에 발생하는 문제 같습니다.
