### ISSUE TITLE
예제 페이지 앵커 에러

### ISSUE THREAD

**Issue by cs09g** [navermaps/maps.js#30]
https://navermaps.github.io/maps.js/docs/naver.maps.Map.html#fitBounds__anchor

가이드 사이트에서 Fires 항목의 링크를 누르면 페이지가 해당 항목으로 올바르게 이동하지 않습니다.
약간 더 밑으로 스크롤이 이동합니다.

**Comment by boxersb** [comment]
@junthus 이 부분 전반적으로 검토 부탁드립니다~

**Comment by junthus** [comment]
@cs09g 제보 감사합니다. 다음 배포에 포함되도록 조치하겠습니다 ~~

**Comment by junthus** [comment]
@cs09g님, 안녕하세요~
해당 이슈 수정되었습니다. 제보해주셔서 감사합니다 ^^

**Comment by cs09g** [comment]
@junthus 네, 알겠습니다~~
