### ISSUE TITLE
안녕하세요 네이버 지도 API 이용 문의 드립니다

### ISSUE THREAD

**Issue by LeeHoontae** [navermaps/maps.js#303]
#### 내용 (Description)
안녕하세요 친구들이랑 웹 개발 프로젝트를 하는데 네이버 지도 api 를 사용하는데 예를 들어 지도를 사용할 때 지도 위에 블록을 올려서 강남구 위에 마우스를 올리면 강남구 위에 빨간색 블록이 올라오게 역삼1동 위에 마우스를 올리면 역삼1동이 파란색 블록으로 표시되게 그런식으로 꾸미고 싶은데  범위를 설정할때 일일이 범위를 저희가 알아서 위도 경도를 파악해서 입력값으로 넣어서 만들어야 되는지 아니면 네이버에서 제공해주는 범위에 대한 자료가 따로 있는지 궁금해서 문의 드립니다.

#### 환경 (Environment)

* OS - Window 10, Internet Explorer 또는 Chrome 또는 eclipse 실행시 나오는 Web browser , 
  Spring framework, Jsp & Servlet

#### 추가 정보 (Additional Info)

참고할만한 사이트 : https://www.nemoapp.kr/  에서 위에 메뉴에 사무실을 누르시고 지도를 확대해서 동 위에 마우스를 올리시면 블록이 나옵니다.

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요.
네이버 API 에서는 제공하고 있지는 않습니다.
아래 포럼에 관련 내용이 있으니 참고 부탁드립니다.

https://developers.naver.com/forum/posts/25711
