### ISSUE TITLE
로딩시 맵 전체가 안보입니다.

### ISSUE THREAD

**Issue by jungjaekim1** [navermaps/maps.js#305]
#### 내용 (Description)

최초 로딩시 맵 전체가 다 안보이고 반 정도만 보입니다.
그러다가 F12 버튼을 누르면 전체가 다 보입니다.

무슨 문제인지 알 수가 없어서 문의 드립니다.

#### 환경 (Environment)

* OS, Windows, chome/IE 둘다

#### 추가 정보 (Additional Info)

http://www.khcu.ac.kr/ad/sub/content.do?MENU_SEQ=200003533

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요.
IE / Chrome 둘 다 재현이 안됩니다.
예상되는 문제는 map 엘리먼트의 width와 height 가 제대로 적용이 안되었을거라 생각됩니다.

지도만 따로 떼어서 정상적으로 노출되는지 확인해보시고
보내 주신 페이지에 삽입하는 방식을 추천 드립니다.
