### ISSUE TITLE
네이버 오픈 API 지도 열지도 시각화 기능 관련 문의드립니다.

### ISSUE THREAD

**Issue by wjdwl201** [navermaps/maps.js#306]
#### 내용 (Description)
 열지도 시각화 기능을 알아보기위해 열지도 시각화 예제를 확인해봤는데 데이터 분포 그리드 간격이 약 800 m였습니다. 반경 1~2 km내의 좁은 구역에서 열지도 시각화처럼 데이터 분포를 시각적으로 나타내고 싶은데, 1~2 m 정도의 촘촘한 그리드 간격을 갖도록 수정 할 수 있는 부분인가요? 아니면 좁은 범위에서의 contour를 그릴수 있는 다른 기능이 있다면 소개해주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/41771585/43302869-0d175206-91a8-11e8-9ee0-7f1bb2976b24.png)

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요. 답변이 늦어 죄송합니다.
제가 이해한게 맞다면 1~2m  단위로 데이터를 추가하시면 원하시는 데로 표현하실 수 있습니다.
옵션으로는 그리드 간격을 조절하실 수 없습니다.
