### ISSUE TITLE
사용자 정의 InfoWindow 위치

### ISSUE THREAD

**Issue by jumini3** [navermaps/maps.js#308]
안녕하세요. 
네이버 지도 V3 예제 페이지들을 참고하여 사용자 정의 InfoWindow, 사용자 정의 마커 이미지를 사용해서 마커 이미지 클릭 시 InfoWindow를 표시하고 있습니다.
마커 이미지와 InfoWindow간에 간격이 많이 존재하여 pixelOffset로 조정해보고자 하는데
값을 넣어주는 기준이 어떻게 되는지가 궁금합니다. 즉 계산식이 있어서 나온 결과값으로 해야하는건지.. 궁금합니다.  혹시 다른 속성으로 조정해야하는 거면 알려주시기 바랍니다.

**Comment by NaverMantle** [comment]
안녕하세요.
정보창의 말꼬리 offset 값입니다. 단위는 pixel 입니다.
아래 이미지는 아래 예제 링크에서 pixelOffset 을 
{x:100, y:-100} 을 주었을 때와 {x:0, y:25} 를 주었을 때 이미지 입니다.
y를 25 이동했는데 말꼬리가 안보이는 이유는 말꼬리 길이가 25pixel 입니다.

<img width="457" alt="2018-08-06 4 57 57" src="https://user-images.githubusercontent.com/32921533/43704212-75a364ce-994e-11e8-9d32-9bdfab1f8b5d.png">

<img width="453" alt="2018-08-06 4 57 22" src="https://user-images.githubusercontent.com/32921533/43704171-5db2825a-994e-11e8-989f-cebbd8467463.png">


[정보창 예제 링크](https://navermaps.github.io/maps.js/docs/tutorial-1-infowindow-simple.example.html)

```
var opt = infowindow.getOptions();
opt.pixelOffset = {x:100, y:-100};
infowindow.setOptions(opt);
```
