### ISSUE TITLE
GeoJSON 데이터 레이어 표시하기 문의

### ISSUE THREAD

**Issue by MightyTedKim** [navermaps/maps.js#309]
#### 내용 (Description)
1. 안녕하세요 geojson 예시 파일(홈페이지에 있는 예시)들 링크나 파일을 얻을 수잇을까요?

2. Vworld에서 UTM-K로 좌표를 얻었는데, json 파일로 저장후 geojson으로 뿌리려고 합니다.
받고보니 geojson이어서 바로 지도에 표시하면 되겠다 싶어서 공부하는데 ajax에서 막히고 있어요

연습하려하는데 naver 표시가 된 geojson 파일 링크나 파일 받을 수 있을까요?

*API 링크*
http://api.vworld.kr/req/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&MAXFEATURES=40&SRSNAME=EPSG:5179&OUTPUT=application/json&EXCEPTIONS=text/xml&KEY=52386B84-DABA-3345-ABB9-9D3393D256A8&DOMAIN=localhost:8800&TYPENAME=LT_C_AISPRHC&PROPERTYNAME=prohibited,prh_lbl_1,prh_lbl_2,prh_lbl_3,prh_typ,ag_geom,prh_lbl_4

`<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>간단한 지도 표시하기</title>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=VZh2P8e3BanI8L1zMwyD&amp;submodules=panorama,geocoder,drawing,visualization"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>  
</head>
<body>
<article>

<div id="wrap" class="section">
    <h2>GeoJSON 데이터 레이어 표시하기</h2>
    <p>GeoJSON 데이터를 지도에 표시하는 예제입니다. 이 예제는 jQuery 구문을 포함하고 있습니다.</p>
    <div id="map" style="width:100%;height:600px;"></div>
    <code id="snippet" class="snippet"></code>
</div>
<script id="code">
var map = new naver.maps.Map(document.getElementById('map'), {
    zoom: 5,
    mapTypeId: 'normal',
    center: new naver.maps.LatLng(37.3586524, 127.1060678)
});

var HOME_PATH = window.HOME_PATH || '.';

$.ajax({
    url: '0.json',
    dataType: 'json',
    success: startDataLayer
});

function startDataLayer(geojson) {
    map.data.addGeoJson(geojson);

    map.data.setStyle(function(feature) {
        var color = 'red';

        if (feature.getProperty('isColorful')) {
            color = feature.getProperty('color');
        }

        return {
            fillColor: color,
            strokeColor: color,
            strokeWeight: 2,
            icon: null
        };
    });

    map.data.addListener('click', function(e) {
        e.feature.setProperty('isColorful', true);
    });

    map.data.addListener('dblclick', function(e) {
        var bounds = e.feature.getBounds();

        if (bounds) {
            map.panToBounds(bounds);
        }
    });

    map.data.addListener('mouseover', function(e) {
        map.data.overrideStyle(e.feature, {
            strokeWeight: 8,
            icon: HOME_PATH +'/img/example/pin_spot.png'
        });
    });

    map.data.addListener('mouseout', function(e) {
        map.data.revertStyle();
    });
}
</script>

    
</article>

</body>

</html>
`

0.json 한국 행정구역도를 나타내는 것은 되는데
api로 가져온 파일을 넣으면 빨간 X 표시가 뜨네요 
ㅜ
파일은 https://github.com/DroneEncore/drone3/tree/master/naverAPI 에 있습니다

**Comment by NaverMantle** [comment]
안녕하세요.
[행정구역 GeoJSON 데이터 레이어 표시하기](https://navermaps.github.io/maps.js/docs/tutorial-2-datalayer-region.example.html) 예제에서 
디버그툴 > Network 탭 > 을 보시면 이미지 처럼 데이터가 보입니다. 
데이터를 더블 클릭하시면 웹 브라우저 새창으로 데이터가 보이실텐데요.
마우스 우클릭으로 저장하셔서 사용하시면 됩니다.

<img width="752" alt="2018-08-06 5 30 50" src="https://user-images.githubusercontent.com/32921533/43705782-16ae9164-9953-11e8-9f9b-0c496c14835a.png">

**Comment by MightyTedKim** [comment]
감사해요 ㅋㅋ 덕분에 지도 가지고 재밌는 공부 했네요 ㅎㅎ
Vworld서 공역정보 가져와서, 드론 날릴 수 있는 항공 공역 표시해봣어요 ㅋㅋㅋㅋ
어플만 있고 웹상으로는 없어가지고.. 지도 재밌네요 ㅎㅎ 파노라마 등등등

좋은 하루 되세요 :)

<img width="542" alt="drone_picnic_practice" src="https://user-images.githubusercontent.com/38391144/45434079-8122a780-b6e8-11e8-9cc4-d11f22e032e4.png">

**Comment by NaverMantle** [comment]
@MightyTedKim 
👍👍👍
