### ISSUE TITLE
marker 삭제 방법

### ISSUE THREAD

**Issue by seeno81** [navermaps/maps.js#31]
네이버지도에서 marker 이동을 구현하려고 합니다.
위치를 Update 하는 방향으로 개발 중인데 기존의 marker 를 어떻게 삭제해야하나요?

function navermapmarkerupdate() {
            objectMap.forEach(function (oMap, key, mapObj) {
                var position = new naver.maps.LatLng(sw_lat, sw_lng);
                var marker = new naver.maps.Marker({
                    map: naverMap,
                    position: position,
                    title: oMap.patientKey,
                    icon: {
                        content: oMap.marker,
                        size: new naver.maps.Size(38, 58),
                        anchor: new naver.maps.Point(19, 58),
                    },
                    draggable: false
                });
                naver.maps.Event.addListener(marker, 'click', getClickHandler(marker));
            });
        }

이런 식으로 marker 만 업데이트 하고 있습니다.

**Comment by boxersb** [comment]
@seeno81 
아래의 가이드대로 `marker.setMap(null);` 을 실행하면 마커가 지도에서 삭제 됩니다
> https://navermaps.github.io/maps.js/docs/naver.maps.Marker.html#setMap__anchor

마커를 지도에 올리고 끝내는것이 아니라, 마커의 리스트를 따로 관리하고 계셔야, 추후 삭제가 가능합니다.
