### ISSUE TITLE
현재 위치 이동 버튼

### ISSUE THREAD

**Issue by kimeasyn** [navermaps/maps.js#312]
#### 환경 (Environment)

네이버 포털 사이트에서 지도 메뉴 들어갔을때 줌버튼과 함께 있는 현재위치로 이동 버튼은 쾌적하게 잘 되는데요

지도 api에는 줌, 로고 등 컨트롤러는 있는데 현재위치 컨트롤러는 없어서
제가 customControler 객체를 이용해서

```
if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function (position) {
        var location = new naver.maps.LatLng(
            position.coords.latitude,
            position.coords.longitude
        );
    map.setCenter(location);
    }, function (error) {
        console.error(error);
    })
}
```
같은 소스로 작성했더니 현위치로 이동은 되는데 속도가 4~5초정도 지연이 있네요
현위치 좌표 이동 동작은 어떻게 하는지 알려주실수 있나요?

**Comment by twipixel** [comment]
안녕하세요.
map.naver.com 은 사용자 위치를 클릭 시 구하는 게 아니라 서비스 시작 시 미리 구해 놓고 클릭 시 이동하여 지연이 없습니다.
