### ISSUE TITLE
검색 API와 네이버 지도 API 연결을 위한 질문

### ISSUE THREAD

**Issue by jpdstyle** [navermaps/maps.js#318]
#### 내용 (Description)
검색 API에서 결과 값으로 mapx 와 mapy 값을 받습니다.
그것들을 네이버 지도 API를 사용하여 위도 경도 값으로 변환하길 원합니다.
naver.maps. TransCoord
에서
fromEPSG3857ToLatLng(coord)
fromNaverToLatLng(n)
fromTM128ToLatLng(tm128)
fromUTMKToLatLng(utmk)

모두 시도했지만 아무런 답을 찾지 못했습니다.

카텍좌표값이라고 하여 
fromTM128ToLatLng(tm128)
이것을 이용하였지만 모두 같은 결과값만 반환합니다.

빠른 답 부탁드립니다.

테스트는
372811, 481779
311550, 395527
로 하시면 됩니다.

                    var spot = data[i],
                        latlng = new naver.maps.TransCoord.fromTM128ToLatLng(data[i].mapx,data[i].mapy),
                        marker = new naver.maps.Marker({
                        position: latlng,
                        draggable: false
                    });

                    var contentString = [
                        '<div class="iw_inner">',
                        '   <h3>'+spot.title+'</h3>',
                        '</div>'
                    ].join('');

                    var infoWindow = new naver.maps.InfoWindow({
                        content: contentString
                    });

                    markers.push(marker);
                    infoWindows.push(infoWindow);
이런 비슷한 형식으로 진행했는데 제가 어느 부분을 잘못했는지요.

빠른 답변 부탁드립니다.

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
안녕하세요.
fromTM128ToLatLng 인자를 잘못 넣으셨네요.
아래 처럼 시도해 보세요.
```
latlng = new naver.maps.TransCoord.fromTM128ToLatLng({x:data[i].mapx, y:data[i].mapy}),
```
https://navermaps.github.io/maps.js/docs/naver.maps.TM128Coord.html
