### ISSUE TITLE
WPF의 WebBrowser에서 네이버 지도 OpenAPI 인증 실패

### ISSUE THREAD

**Issue by Chickenchaser-Kwak** [navermaps/maps.js#319]
현재 WPF 어플리케이션을 제작중인데, WPF의 WebBrowser컨트롤에서 로컬에 저장된 HTML 파일을 불러와서 네이버 지도를 띄우려고 합니다.

윈도우창이 로딩되면 C#단에서 HTML파일 내용을 읽어와 WebBrowser에 전달해서 띄우고 있는데요,
처음 HTML 파일이 WebBrowser에서 로딩되면 네이버 지도가 잠깐 표시되었다가(정상적으로 작동된 것처럼 보이네요) 지도가 사라지면서 "네이버 지도 Open API 인증이 실패했습니다." 라고 표시됩니다.

IE Edge 브라우져에서 로컬HTML파일을 바로 열었을 때는 문제가 없이 잘 작동합니다.

혹시 API 인증에 클라이언트 ID입력 외에 추가로 설정이나 환경 설정이 필요한건가요?

**Comment by hyeyoung0112** [comment]
혹시 어떻게 해결하셨나요?
