### ISSUE TITLE
geocode API를 사용하려고 합니다. SSL 관련 에러.

### ISSUE THREAD

**Issue by wodls1980** [navermaps/maps.js#32]
http://openapi.naver.com/v1/map/geocode  로 호출시 

{"errorMessage":"HTTPS only allowed : Unsupported protocol (지원하지 않는 프로토콜입니다.)","errorCode":"072"}

라는 메시지를 받고 있습니다.

혹시 저 메시지에 관해 어떻게 처리하는 방법이던가, 문의할 곳이나, 도움이 될만한 부분이 있으면
알려주시면 감사하겠습니다.

wodls1980@naver.com

**Comment by boxersb** [comment]
@wodls1980 안녕하세요
아래와 같이 터미널에서 curl GET 방식으로 날려본결과 정상 동작을 하고 있습니다.
> curl -XGET "https://openapi.naver.com/v1/map/geocode?query=%EB%B6%88%EC%A0%95%EB%A1%9C6" -H "Content-Type: application/json" -H "X-Naver-Client-Id: orK7_YeBAdN64OJ8HUVz" -H "X-Naver-Client-Secret: G7gfzmIRCR"

혹시 HttpClient 사용시 Post 방식으로 날리신것 아닌지요?
