### ISSUE TITLE
네이버지도를 사용중...특정 URL에서는 로딩이 되지 않는데요.

### ISSUE THREAD

**Issue by 619blog** [navermaps/maps.js#323]
네이버지도 v1 을 잘사용하던중 ...
*.abc.com 으로 사용중입니다.
a1.abc.com
a2.abc.com 은 잘 사용하고 있습니다.

신규 서비스로 
b1.abc.com에 네이버 지도 좌표를 넣었더니.. 지도를 불러오지를 못하는데요...

b1.abc.com은 현재 내부에서만 동작하고 외부에서 는 접속이 안되는 상태인데요..

이경우는 지도를 불러오지를 못하나요?

#### 환경 (Environment)

v1 사용중이니다.
* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
@619blog 님 

안녕하세요.

v2도 서비스 종료 되었는데요. v1을 사용하실 수 있나요?

[내 어플리케이션 바로 가기](https://developers.naver.com/apps/#/list) 에서  웹 서비스 URL 을 한번 체크해주시기 바랍니다.

> 텍스트 폼 우측 끝의 '+' 버튼을 누르면 행이 추가되며, '-' 버튼을 누르면 행이 삭제됩니다.
http와 https는 구분하지 않습니다.
www는 빼고 입력해 주세요. 예) http://naver.com
서브 도메인이 있으면 대표 도메인명만 입력해 주세요. (예: http://naver.com)
하이브리드 앱은 location.href 객체 출력 값을 입력하면 됩니다. (예: file://로컬URI)

**Comment by NaverMantle** [comment]
@619blog 님

폐쇄망 이야기셨군요. 
사용이 불가능한건 아니지만 제한적입니다.

아래 관련 링크 첨부 드립니다.
* [네이버지도 api 사용시 방화벽 허용을 해야하는 url 정보](https://developers.naver.com/forum/posts/8547)
* [Openapi.naver.com의 IP주소 대역을 알고싶어요](https://developers.naver.com/forum/posts/10369)
* [단축 url 사용을 위한 방화벽 ip허용리스트](https://developers.naver.com/forum/posts/22286)
