### ISSUE TITLE
지도내 고속도로 표시 제거가 가능한가요?

### ISSUE THREAD

**Issue by chchorok** [navermaps/maps.js#324]
#### 내용 (Description)
지도내 표시되는 고속도로 표시를 제거하고 싶습니다.
가능한지요?

#### 환경 (Environment)
Web, Windows, IE, Chrome

**Comment by twipixel** [comment]
@chchorok 
안녕하세요. 현재는 POI 만 제거 가능합니다.
https://navermaps.github.io/maps.js/docs/tutorial-5-custom.example.html

**Comment by NaverMantle** [comment]
@chchorok 
안녕하세요. 현재는 POI 만 제거 가능합니다.
https://navermaps.github.io/maps.js/docs/tutorial-5-custom.example.html
