### ISSUE TITLE
실시간 교통 레이어를 특정 구간만 보여줄 수 있나요?

### ISSUE THREAD

**Issue by fdisk** [navermaps/maps.js#325]
안녕하세요?

제목 그대로의 문의 사항입니다. 
예제 (https://navermaps.github.io/maps.js/docs/tutorial-3-traffic.example.html )에 나온 실시간 교통 레이어를 사용해보고 싶습니다.

다만 예제처럼 좌표 주변의 모든 도로의 실시간 교통정보가 아닌 특정 구간(노드 좌표와 노드 좌표사이)만 교통정보를 표시할 수 있는 방법이 있을까요?

감사합니다.

**Comment by NaverMantle** [comment]
@fdisk 님 안녕하세요. 

교통 정보 데이터가 없으시면 
API 를 활용할 경우 [교통지도 레이어를 켜고 끄는](https://navermaps.github.io/maps.js/docs/tutorial-5-custom.example.html) 정도만 가능합니다.

[Layer](https://navermaps.github.io/maps.js/docs/tutorial-Layers.html) 는 타일 이미지를 받아 표시하는 방식이고
[DataLayer](https://navermaps.github.io/maps.js/docs/tutorial-DataLayer.html) 는 데이터를 직접 지도에 그리는 방식인데요.

특정 구역의 데이터가 있으실 경우 아래 예제처럼 DataLayer 를 활용하실 수 있습니다.

- [GeoJSON데이터 레이어 표시하기](https://navermaps.github.io/maps.js/docs/tutorial-1-datalayer.example.html)
- [GPX 데이터 레이어 표시하기](https://navermaps.github.io/maps.js/docs/tutorial-4-datalayer-gpx.example.html)
- [KML 데이터 레이어 표시하기](https://navermaps.github.io/maps.js/docs/tutorial-3-datalayer-kml.example.html)
