### ISSUE TITLE
401 에러

### ISSUE THREAD

**Issue by Miyoung-Lim** [navermaps/maps.js#327]
https://openapi.naver.com/v1/map/geocode?query=%EB%B6%88%EC%A0%95%EB%A1%9C+6
로 request를 보냈을 때,

401 GET 
{"errorMessage":"Not Exist Client URL information : Authentication failed. (인증에 실패했습니다.)","errorCode":"024"}
라고 에러가 리턴되었는데요,
어떤 에러인지 알 수 있을까요?

**Comment by Miyoung-Lim** [comment]
https://openapi.naver.com/v1/map/geocode?clientId=BS1db0PaEGmwo4vqjH4V&query=%EB%B6%88%EC%A0%95%EB%A1%9C+6
로 request를 보내면 
{"errorMessage":"Not Exist Client ID : Authentication failed. (인증에 실패했습니다.)","errorCode":"024"}
라고 에러가 리턴되었습니다. 
Client ID는 맞는데 왜 에러가 발생하는 걸까요?

**Comment by NaverMantle** [comment]
@Miyoung-Lim 님 

안녕하세요.
geocode 요청 시 해더에 
X-Naver-Client-Id 와 X-Naver-Client-Secret 을 넣어 주셔야 하는데요.
아래 링크에서 애플리케이션 정보에 있는 ClientID 와 Client Secret 를 확인하셔서 다시 시도해 주세요.

#### 관련 링크 
- [내 어플리케이션 바로 가기](https://developers.naver.com/apps/#/list)
- [네이버 지도 API 명세](https://developers.naver.com/docs/map/overview/)

**Comment by Miyoung-Lim** [comment]
감사합니다
