### ISSUE TITLE
이벤트 종료시점 알기

### ISSUE THREAD

**Issue by ct0052** [navermaps/maps.js#33]
지도레벨변경 또는 지도영역이동 시 해당 좌표 내에 존재하는 지점들을
구하는 지도를 만들었습니다.
다만, 이벤트 발생시 DB 쿼리를 하게 했더니..
맵이동을 할경우.. 이동하는 내내 계속 쿼리를 수행하게 되어 화면이 많이 느리게 됩니다.
따라서.. 지도이동을 하거나.. 휠마우스 등으로 지도 레벨을 변경할때..
해당 이벤트가 끝나는 시점을 알고 싶습니다..
그래서 해당시점에서만 DB 쿼리를 하도록 하고 싶은데..
방법이 없을까요?

현재는..

    naver.maps.Event.addListener(map, 'bounds_changed', function(bounds) {
        //처리코드
    });		

를 이용하여 변화를 감지합니다.

즉.. 사용자가.. 지도를 클릭해서.. 영역을 쭉 이동할 경우.. 해당 이벤트가 끝나는 시점을
알고 싶습니다.

또한 아랫분께서도 질문하셨는데요..

지도에 표현된 마커와 오버레이등을 한번애 없애는 방법도 있을까요?

답변 부탁드리겠습니다.

**Comment by boxersb** [comment]
@ct0052 `idle` 이벤트를 사용해보시기 바랍니다.
줌 변경시에는 `bounds`가 여러번 변경되기 때문에 `idle` 이벤트를 사용하시면, 지도 이동 액션 완료 후의 처리를 하실 수 있습니다.
  
그러나, 지도 줌 변경 없이 마우스로 패닝을 연속으로 수행할 경우에는 `idle` 이벤트 역시 여러번 발생할 수 있습니다.  
이럴 경우에는 `idle` 이벤트 핸들러에서 적절한 timeout 을 부여해서 처리하는것도 방법입니다.

```js
var idleTimer = null;
naver.maps.Event.addListener(map, 'idle', function() {
   if (idleTimer) {
       window.clearTimerout(idleTimer);
       idleTimer = null;
   }

   idleTimer = window.setTimeout(function() {
       // do some thing
    }, 500);
});
```

**Comment by boxersb** [comment]
마커와 오버레이를 한번에 없애는 방법은 별도로 제공하지 않습니다.
모든 오버레이는 해당 오버레이의 `setMap` 메서드를 통해 지도에 추가되면, 지도 인스턴스에서 별도 관리하지 않습니다.  
따라서, 마커나 오버레이를 지도에 올리고 나서도, 해당 객체의 목록을 보관해두셨다가, for 루프등을 통해 순회하면서 일괄적으로 `setMap(null)` 메서드를 사용해서 지도에서 제거하셔야 합니다.  

감사합니다~
