### ISSUE TITLE
고도값을 알아낼수 있는 API가 제공되는지요?

### ISSUE THREAD

**Issue by yellowin** [navermaps/maps.js#331]
안녕하세요. 등산관련 서비스제작시 네이버지도API를 사용하려고 합니다.
사용자 이동경로에 따른 위치정보를 기준으로 해발고도값을 기록하고 표시해주려고 하는데~
이 고도값을 알아낼수 있는 방법이 있을지요?

**Comment by NaverMantle** [comment]
고도 정보 API 는 11월 중에 [Naver Cloud Platform](https://www.ncloud.com/) 에서 제공될 예정입니다.
