### ISSUE TITLE
ReverseGeocode 관련 질문입니다. (왕초보 버전)

### ISSUE THREAD

**Issue by BBODRI84** [navermaps/maps.js#332]
#### 내용 (Description)
안녕하세요. 
기존에 javascript v3 에서 제공하는 예제대로 정상적으로 사용중이였는데
신규 api키 발급 받고 난 이후로는 401에러가 떨어져서 문의 드립니다. 
(지도나 마커는 정상적으로 표시되고 있습니다. )

혹시 예제들을 볼 수 있는 방법이 있을까여? 

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by NaverMantle** [comment]
@BBODRI84 님

401 에러는 인증 에러입니다.
아래 문서 참고 하셔서 확인 부탁 드립니다.

[주요 오류 코드 링크](https://developers.naver.com/docs/common/openapiguide/errorcode.md#%EC%A3%BC%EC%9A%94-%EC%98%A4%EB%A5%98-%EC%BD%94%EB%93%9C)
