### ISSUE TITLE
React Native 관련 질문

### ISSUE THREAD

**Issue by devonnuri** [navermaps/maps.js#335]
#### 내용 (Description)
React Native에서 지도 뷰나 Panorama 기능을 사용할 수 있나요?

#### 환경 (Environment)
* expo 30.0.1, react 16.3.1, react-native 30.0.0

#### 추가 정보 (Additional Info)
React Native에서 지도 뷰나 거리뷰 같은 기능을 사용할 수 있나요? 가능하다면 React Native 안에서 어떻게 로드하는지 알 수 있을까요?

**Comment by NaverMantle** [comment]
@devonnuri 님
지원이 불가합니다. 추후에 가능하게되면 예제로 찾아뵙겠습니다.
감사합니다.
