### ISSUE TITLE
네이버지도 다운로드 기능 문의드립니다.

### ISSUE THREAD

**Issue by yellowin** [navermaps/maps.js#336]
모바일앱에서 네이버지도 다운로드 기능의 서비스를 개발하려고 합니다.
등산정보안내 서비스인데요. 사용자들이 오프라인에서 다운로드된 지도를 사용하게 하려고 합니다.
상업적으로 이용되는 기능은 아닙니다. 모든 사용자가 무료로 사용되게 할겁니다.

전에 개발자포럼을 통해 문의드린 질문의 답변으론....
네이버지도 다운로드가(타일맵 이미지) 정책상 안되는것은 알겠는데요. 혹시 가능한 방법이 있을지요? 유료라도요~
이미 네이버지도 다운로드 기능을 제공하고 있는 앱이 있는데...
이곳은 어떻게 다운로드 기능을 사용하고 있는것인지 궁금하네요.
아마도 가능한 방법이 있어서겠지요? 네이버 정책상으로 지도 다운로드 기능이 가능한 방법을 알려주시면 감사하겠습니다. ^^

**Comment by NaverMantle** [comment]
@yellowin 님
네이버지도 다운로드 기능을 제공하는 앱은 불법입니다.
해당 앱을 알려주신다면 조치하도록 하겠습니다.
감사합니다.

아래는 이용 약관 링크와 관련 내용 발췌한 부분 입니다.
https://developers.naver.com/products/terms/

## 이용 약관
⑧	이용자는 회사의 사전 동의 없이 API서비스의 결과 데이터(네이버 서비스 회원의 계정 관련 정보, 네이버 서비스의 컨텐츠 내용 등 일체의 데이터를 포함한다)를 본 약관에서 허용한 범위를 넘어서서 무단으로 복제, 저장, 가공, 배포하거나 제3자에게 제공해서는 안됩니다.

⑨	이용자는 API 허용량을 늘이거나, 데이터를 추출 저장하는 등의 목적으로 동일한 애플리케이션이나 동일한 목적으로 서비스 되는 애플리케이션 등에서 여러 개의 클라이언트 아이디를 사용하여 API를 호출하여 사용해서는 안됩니다
