### ISSUE TITLE
리액트에서 네이버지도 사용방법 문의

### ISSUE THREAD

**Issue by leencoln** [navermaps/maps.js#338]
#### 내용 (Description)
create-react-app v2 로 홈페이지 만들고 있는데 script 파일 컴포넌트에서 불러오는 예시같은게 있나요
api key 노출 되는데 숨기는 방법도 알려주세요

#### 환경 (Environment)
mac, vscode, create-react-app v2, node.js -v 10.1

* OS, OS Version, Browser, Browser Version, Device Information, etc:

#### 추가 정보 (Additional Info)

* Site URL, Source Code

**Comment by iamdenny** [comment]
https://www.npmjs.com/package/react-naver-maps
이런 외부 모듈이 있는데요. 활용해 보시는건 어떨까요?
