### ISSUE TITLE
limit이 모두 찰 경우 Response가 어떻게 떨어지나요 ? 

### ISSUE THREAD

**Issue by kkak10** [navermaps/maps.js#34]
###안녕하세요 :) 

개발중에 해당 API가 limit이 초과할 경우 대응해야하는 케이스가 생겨서 문의 드립니다.

naver Map API Script를 스크립트 단에서 동적으로 로딩해서 처리하려합니다.

혹시 limit이 차면 어떤식으로 Response가 오나요 ? 그리고 해당 부분을 Script에서 예외 처리할때 그냥 Http Status 코드만 보고 처리해도 문제가 되지 않을지 문의 드립니다 :)

**Comment by boxersb** [comment]
@kkak10 안녕하세요?
Quota Limit 이 발생하여도, 지도 API js의 컨텐츠는 로드가 됩니다.  
단, 지도 API를 사용하여 지도를 초기화시 인증을 수행하고, Quota Limit 발생시 js 오류를 반환하도록 되어 있습니다.   
따라서, 인증 오류 발생시의 뱔도 예외 처리는 어려운점 양해 부탁드립니다.  

감사합니다.
