### ISSUE TITLE
사용 API 설정에 지도가 없습니다.

### ISSUE THREAD

**Issue by leejinseok** [navermaps/maps.js#342]
#### 내용 (Description)
![image](https://user-images.githubusercontent.com/7136340/48614031-9eb60b00-e9d0-11e8-8362-55f7861a47dd.png)

**Comment by qkrtkddn456** [comment]
저도 안떠서 api를 못쓰고있네요 ㅠㅠ 빠른수정 부탁드립니다

**Comment by alswh5202** [comment]
그거때문에 저도 시간낭비 엄청많이했는데
보니깐 11월 13이후부터는 플랫폼이 바꼈더라구요
네이버 클라우드 콘솔 플랫폼에서 신청하면 가능해요!

**Comment by leejinseok** [comment]
@alswh5202 대단히 감사합니다. 구글도 구글 클라우드 플랫폼으로 가더니 마찬가지이군요
