### ISSUE TITLE
naver.maps.Ellipse.html 오타 수정 요청

### ISSUE THREAD

**Issue by Shin-JaeHeon** [navermaps/maps.js#344]
#### 내용 (Description)
 https://navermaps.github.io/maps.js/docs/naver.maps.Ellipse.html 의 setBounds(bounds)항목의

> Bounds | BoudnsLiteral

부분에 오타가 있습니다. (아래는 올바른 철자)

> Bounds | BoundsLiteral

**Comment by NaverMantle** [comment]
안녕하세요.
이슈 감사합니다. 수정하여 반영하였습니다. 👍
