### ISSUE TITLE
앱에서 지도가 표시되지 않고 있습니다.

### ISSUE THREAD

**Issue by root69gh** [navermaps/maps.js#345]
지도 API를 이용해서 만든 지도 웹페이지를 안드로이드 앱에서도 서비스 하고 있었는데

웹브라우저에서는 잘 나오지만 앱에서는 지도가 표시되지 않고 있습니다.

갑자기 이런 상황이 되었는데 어떤 이유가 있을까요?

**Comment by ncrash** [comment]
저희도 동일한 이슈로 고생중입니다 ㅜㅜ 
SSL 인증서 오류 원인은 아래와 같습니다.

![image](https://user-images.githubusercontent.com/153414/49282719-35a3bc80-f4d3-11e8-81a6-ac9d2253df0f.png)

```The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. You can fix this by following DigiCert's Certificate Installation Instructions for your server platform. Pay attention to the parts about Intermediate certificates.```

위 메시지를 보시면 네이버 지도 SSL 인증서는 모든 브라우저를 대응하지 못한다고 명시 되어 있고
안드로이드 주로 구형 단말에서 인증서 호환 안되는 케이스가 발생하고 있습니다.

https://www.sslshopper.com/ssl-checker.html#hostname=https://openapi.map.naver.com

**Comment by twipixel** [comment]
@root69gh 님 안녕하세요. 
보안 인증서 문제로 장애가 있었습니다.
이용에 불편을 드려 죄송합니다.
감사합니다.

**Comment by NaverMantle** [comment]
@root69gh 님 안녕하세요.
보안 인증서 문제로 장애가 있었습니다.
이용에 불편을 드려 죄송합니다.
감사합니다.
