### ISSUE TITLE
네이버지도 고정 레이어 띄우기

### ISSUE THREAD

**Issue by dyaus1** [navermaps/maps.js#349]
네이버 지도를 구현중입니다.

네이버 부동산을 보시면 지도 우측 상단에 전국지도 레이어가 고정으로 떠 있는것을 볼수 가 있습니다.

이와 비슷한 기능을 구현하려는 건데요.

제가 임의로 만든 HTML DIV 태그로 만든 레이어를 

제가 구현한 네이버 지도 위에 고정으로 띄우려 합니다.

줌을 하든 드래그로 지도 이동을 하든 

우측 상단에 고정으로 떠있는 HTML 레이어 입니다.

구현이 가능 한건가요?

가능하다면 샘플 소스 부탁드립니다.

제발요~

**Comment by Jinkwon** [comment]
안녕하세요.
혹시 도움이 되지 않을까 하여 남겨봅니다.^^
- 동작 페이지
https://navermaps.github.io/maps.js/examples/map/7-map-fullsize-minimap-opened.html
- 예제 코드
https://navermaps.github.io/maps.js/docs/tutorial-7-map-fullsize-minimap.example.html
