### ISSUE TITLE
API v3 적용 후 맵이 나오지 않는 문제

### ISSUE THREAD

**Issue by jinjillian** [navermaps/maps.js#35]
여기에 문의 드리는 것이 맞는지 모르겠습니다만... ^^;;

가이드에 따라 HTML 코드에 기존에 key=******** 이던 을 clientId =********* 로 변경하니,
맵이 전혀 보여지지 않습니다.

현재 다시 V2로 바꿔놓기는 했는데,  
현재 v3가 서비스가 되지 않아서인것인지
제가 가이드대로 한 것 중에 문제가 있는지 확인하려면 어떻게 해야 할까요?

답변 부탁드립니다.  감사합니다.

**Comment by boxersb** [comment]
@jinjillian 안녕하세요?
key 를 clientId 로 변경하신것 이외에 버전도 v1 또는 v2에서 v3로 변경하신건가요?
지도 API의 버전도 변경하셨다면, 아래의 마이그레이션 가이드에 따라 코드를 수정해주셔야합니다.

* [v2 -> v3](https://navermaps.github.io/maps.js/docs/tutorial-Migrate-From-v2.html)
* [v1 -> v3](https://navermaps.github.io/maps.js/docs/tutorial-Migrate-From-v1.html)

v1은 올해 말 서비스 종료가 예정되어 있으니, 기존 v1 사용자이실 경우 v3로 마이그레이션 부탁드립니다.

**Comment by jinjillian** [comment]
답변감사합니다. 
말씀하신대로 아래 2번과 같이 ver도  추가해보았으나 현상은 동일합니다.

현재구현된것
http://openapi.map.naver.com/openapi/naverMap.naver?ver=2.0&key=할당받은키값   --- 정상출력됨.

마이그레이션한것
1. http://openapi.map.naver.com/openapi/v3/maps.js?clientId=할당받은클라이언트아이디값  -- 빈화면
2. http://openapi.map.naver.com/openapi/v3/maps.js?ver=3.0&clientId=할당받은클라이언트아이디값 --빈화면

제가 무엇을 빠트린걸까요?

답변 다시한번 부탁드립니다.

감사합니다.

**Comment by boxersb** [comment]
현재 구현된것이 v2 버전인것으로 보이는데요..

> http://openapi.map.naver.com/openapi/v2/maps.js?clientId=할당받은클라이언트아이디값 

위 url로 하시면 정상 출력되나요? 그렇다면, v3로 마이그레이션 하지 않으신것에 해당됩니다 :)
v3로 마이그레이션은 구현된 코드까지, v3에 맞게 전환하시는것이구요..  

현재 구현된것에서 인증 체계만 `클라이언트아이디`로 변경하시려면 위 공유드린대로 url상에서 v3를 v2로 고쳐서 시도해보시기 바랍니다.

**Comment by jinjillian** [comment]
덕분에 잘해결했습니다. 각각의 페이지에도 속성값이 모두 바뀐것을 적용하지 않았었네요. 

감사합니다.
