### ISSUE TITLE
주소 -> 좌표 변환 문의 입니다.

### ISSUE THREAD

**Issue by LcYellows** [navermaps/maps.js#36]
JavaScript API V3 사이트 에는 Geocode 가이드가 없는거 같습니다.

v1 방식대로 사용하니 문제가 발생하고 있는데

V3 사이트에도 가이드 문서 부탁드립니다.

**Comment by boxersb** [comment]
안녕하세요? 
지도 API Javascript API v3 사이트는 본래 js API만을 위한 문서 사이트입니다.  
따라서, 주소<->좌표 변환 서버 API에 대한 가이드가 존재하지 않는데요..

일단은, 현재 네이버 개발자센터의 문서를 참조 부탁드립니다.
> https://developers.naver.com/docs/map/overview
위 페이지의 주소-좌표 변환 API 부분을 참조부탁드리구요..

> https://developers.naver.com/docs/common/apicall
위 페이지의 서버측 개발 가이드 참조 하시어 GET 방식으로 호출 부탁드립니다.'

감사합니다.
