### ISSUE TITLE
현재 마커가 목적지 사이의 경로에 벗어났는지 알 수 있는 API가 있나요?

### ISSUE THREAD

**Issue by hahaha1277** [navermaps/maps.js#362]
마커가 실시간으로 위치를 받으면서 목적지 까지의 경로로 이동하다가 그 경로를 이탈하면 다시 목적지 까지의 경로를 찾는 어플리케이션(ex. 차량용 네비게이션)을 개발하려고 하는데요.

혹시 네이버에서 '현재 마커가 사용자가 설정한 어떠한 경로를 벗어나는지' 알 수 있는 API를 제공하는지 궁금합니다.

**Comment by twipixel** [comment]
안녕하세요.
OpenAPI 내부에서는 제공하는 기능이 없습니다.
아래 turfjs 에서 제공하는 booleanWithin 을 사용하시면 경로에서 포인트가 벗어났는지 확인 가능합니다.
감사합니다.

https://turfjs.org/docs/#booleanWithin

**Comment by hahaha1277** [comment]
감사합니다. 개발에 많은 도움이 되었습니다.
