### ISSUE TITLE
음식점 주차가능 정보를 알려주는 API가 있나요?

### ISSUE THREAD

**Issue by gomjang** [navermaps/maps.js#363]
음식점 주차가능 정보를 알려주는 API가 있나요?

**Comment by twipixel** [comment]
아마 타사에서도 해당 API는 제공하지 않는것으로 알고 있습니다.

**Comment by gomjang** [comment]
네, 제가 찾아보니 제공되는 곳은 없는것 같습니다.
동료가 다리가 불편하여 "1층" & "추차가능"한 음식점을 찾으려고 보니 복합 조건의 지도검색을 제공하는 서비스도 없어 혹시 API 가 제공되면 만들어 보려고 했습니다.
네이버 지도에 복합 조건으로 검색이 되면 좋겠네요. 답변 고맙습니다.
