### ISSUE TITLE
네이버 지도 예제에서 인증 파라미터 확인 부탁드립니다.

### ISSUE THREAD

**Issue by cyberjam** [navermaps/maps.js#364]
#### 내용 (Description)

git에 있는 예제들에서 인증 파라미터가 clientId로 되어있어 네이버 인증이 제대로 이루어 지지 않아 지도가 뜨지 않습니다.

ncpClientId로 바꿔주셔야 합니다.

무슨 이유에서 인지는 모르겠으나 더 좋은 방법이 있다면 누구든지 말씀 부탁합니다.

#### 환경 (Environment)

* OS, OS Version, Browser, Browser Version, Device Information, etc:
Windows 10 64bit
Chrome 78.0.3904.97
네이버지도 v3
Local 에서 예제 html 실행

##### 수정 이전
 <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js? clientId=클라이언트 id"></script>

##### 수정 이후
 <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=클라이언트 id"></script>

* Site URL, Source Code

고맙습니다.

**Comment by twipixel** [comment]
안녕하세요. 
현재 보시는 저장소는 `개발자센터용`으로 지원이 종료되었습니다.
현재 저장소의 예제를 돌려보시려면 말씀하신것처럼 `ncpClientId` 로 수정하셔서 확인하셔야 하며 변경된 저장소는 아래에 있습니다. 참고 부탁드립니다.
감사합니다.

`NaverCloudPlatform`용 저장소입니다.
https://github.com/navermaps/maps.js.ncp

**Comment by cyberjam** [comment]
> 안녕하세요.
> 현재 보시는 저장소는 `개발자센터용`으로 지원이 종료되었습니다.
> 현재 저장소의 예제를 돌려보시려면 말씀하신것처럼 `ncpClientId` 로 수정하셔서 확인하셔야 하며 변경된 저장소는 아래에 있습니다. 참고 부탁드립니다.
> 감사합니다.
> 
> `NaverCloudPlatform`용 저장소입니다.
> https://github.com/navermaps/maps.js.ncp

정말 감사합니다!
