### ISSUE TITLE
웹사이트 Open API 신청 링크 누르면 그런 페이지 없다고 나옵니다. 

### ISSUE THREAD

**Issue by hjk** [navermaps/maps.js#365]
#### 내용 (Description)
Client ID 신청하기 위해 Open API 신청 눌렀는데 글쎄.. 저런 오류가 뜨다니요
#### 환경 (Environment)
Chrom browser

#### 추가 정보 (Additional Info)
황당했습니다.

* Site URL, Source Code
https://developers.naver.com/register

**Comment by twipixel** [comment]
안녕하세요.
개발자 센터는 서비스가 종료되었습니다.
Naver Cloud Platform 에서 발급 가능합니다.
아래 링크 참고 부탁 드립니다.
감사합니다.

https://console.ncloud.com/mc/solution/naverService/application
https://navermaps.github.io/maps.js.ncp/docs/tutorial-1-Getting-Client-ID.html
