### ISSUE TITLE
정보창을 여러 개 동시에 뛰우려면 어떻게 하나요?

### ISSUE THREAD

**Issue by lsw3210** [navermaps/maps.js#37]
정보창을 여러 개 띄우려고 해도 마지막 것만 표시됩니다.
marker와 contentstring은 배열로 선언해서 사용이 가능한데,
infowindow는 배열로 안됩니다.

	infowindows[j] = new naver.maps.InfoWindow({
		maxWidth:200,
		content: contentString[j]
	});

	infowindows[j].open(map, markers[j]);
--------------------------------------------------------------------------
그리고, V2에서는 nhn.api.map.MarkerLabel()함수가 있었는데, 없어졌나요?
getTitle함수가 있기는 한데, 몰라서 그런지는 모르지만 
PC화면에서는 마우스를 갖다대면 타이틀이 보이는데, 모바일에서는 작동을 안합니다.

V2하고 V3가 너무 달라져서 어렵습니다.
V2에서 쓰던 함수 등을 그냥 쓸 수 있어야 하는 것 아닌가요?

**Comment by junthus** [comment]
안녕하세요 @lsw3210 님

InfoWindow는 화면상에 한 개만 존재하는 것이 원칙이라 인포윈도우 여러개를 동시에 표시하시려면 `OverlayView`를 상속받아 사용자 정의 오버레이를 생성해야 합니다. [이 글](https://navermaps.github.io/maps.js/docs/tutorial-CustomOverlay.html)과 [예제](https://navermaps.github.io/maps.js/docs/tutorial-custom-overlay.example.html)를 참고해서 구현할 수 있습니다.

v3에서는 마커 생성시 [옵션](https://navermaps.github.io/maps.js/docs/naver.maps.Marker.html#toc35__anchor)으로 `title`을 지정하면 `mouseover`이벤트 시에 툴팁을 노출합니다. 모바일에서는 해당 이벤트가 없기 때문에 툴팁을 표시하려면 위와 동일하게 사용자 정의 오버레이를 생성해서 사용하셔야 합니다. 

안타깝게도 v2와 v3의 구현이 크게 달라서 호환이 쉽지 않은점 양해 부탁드립니다. [마이그레이션: v2에서 v3로 전환하기](https://navermaps.github.io/maps.js/docs/tutorial-Migrate-From-v2.html)문서를 참고하시면 조금 도움이 될 듯합니다. 또 궁금한 부분이 있으시면 글 남겨주세요. ^^
