### ISSUE TITLE
Naver event controll

### ISSUE THREAD

**Issue by mrs-jinsu** [navermaps/maps.js#374]
C#을 이용한 프로그램 개발 중 Naver 지도 api를 사용하게 되었습니다.

지도에 마우스 우클릭으로 별도의  A~E에 대한 항목을 만들어서 클릭이벤트처리를 하려고 하는데 가능한지 질문드립니다.

**Comment by mrs-jinsu** [comment]
자체적으로 마커에 대한 콜백을 받아서 C# 내에서 처리하기로 했습니다.

**Comment by twipixel** [comment]
안녕하세요.
UI 이벤트 rightclick을 받아 보실 수 있습니다.
아래 튜토리얼 참고하세요.
https://navermaps.github.io/maps.js.ncp/docs/tutorial-UI-Event.html

**Comment by mrs-jinsu** [comment]
감사합니다 ^^
