### ISSUE TITLE
오프라인 기능 문의

### ISSUE THREAD

**Issue by cinnamon** [navermaps/maps.js#38]
안녕하세요, 현재 지도 관련 앱 개발중인데 전화가 안 잡히는 곳에서도 동작해야 하는 상황입니다.
혹시 원하는 지역을 로컬에 저장해서 (영구 저장일 필요는 없음. 캐시 정도 개념) 
인터넷에 연결되어 있지 않아도 사용할 수 있도록 구현 가능한가요?

**Comment by thetaiz** [comment]
@cinnamon 님, 안녕하세요. 

아쉽지만 인터넷이 연결되지 않은 상태에서는 지도를 사용할 수 없습니다. 
관련해 로컬에 저장해 사용할 수 있도록 하는 기능은 없습니다.

만족스러운 답변을 드리지 못해 죄송합니다.
감사합니다.
