### ISSUE TITLE
혹시 영어 매뉴얼이 존재 하나요?

### ISSUE THREAD

**Issue by didemf** [navermaps/maps.js#39]
해외에서 개발 시 필요한대 영어 매뉴얼이 존재 하나요?

**Comment by thetaiz** [comment]
@didemf 님, 안녕하세요.

현재는 영문 매뉴얼은 없습니다. 내부적으로 검토는 해보겠지만 언제쯤 제공할 수 있다고 확답을 못드리는 점 양해를 부탁드려요.

감사합니다.
