### ISSUE TITLE
circle 클래스의  getDrawingRect() 문의

### ISSUE THREAD

**Issue by chahwon** [navermaps/maps.js#4]
원 도형을 특정 위치에 표시 이후 해당 도형의 영역 경계 좌표를 구하여
지도상 도형 경계 위경도 좌표를 확인 하기 위하여 getDrawingRect() 함수를 사용하였습니다. 
해당 함수로 부터 얻은 Point 좌표를 지도 좌표인 위경도 좌표로 변환해서 사용하려합니다.
*리턴 받은 Bounds 의 _max 와 _min 값의 의미도 자세히 알려주시면 감사하겠습니다.

그러나 Projection관련 좌표 변환 함수들을 이용하였을때 기존 원 도형이 그려진 위치와는 상관이 없는 
전혀 다른 위치가 나와서 혹 해당 함수의 간단한 사용법 및 아님 해당 함수로 부터 나온 Point 데이터로
위경도 좌표를 구할수 없는지 궁금하여 문의 드립니다.

**Comment by thetaiz** [comment]
안녕하세요. 불편을 드려 죄송합니다.

원의 경계 좌표를 구하실 땐 circle.getBounds() 메서드를 이용해 주세요. 문서상 표기가 안되었습니다. 이 부분은 수정해 반영하겠습니다.

circle.getBounds() 메서드를 사용하시면 위경도의 [경계 좌표](https://navermaps.github.io/maps.js/docs/naver.maps.LatLngBounds.html)를 구할 수 있습니다. 이때 sw(min), ne(max) 값을 이용할 수 있습니다. 오브젝트를 기준으로 좌하단, 우상단의 좌표입니다.

감사합니다.

**Comment by chahwon** [comment]
감사합니다.

**Comment by thetaiz** [comment]
금일 문서가 수정되었습니다. 이슈를 닫습니다.
