### ISSUE TITLE
Static Map은 사용할 수 없나요?

### ISSUE THREAD

**Issue by kkak10** [navermaps/maps.js#40]
Documentation을 보니깐 StaticMap에 대한 부분이 없는것 같은데 현재 지원하지 않는 상태인가요 ?

지원하지 않는다면 향후 지원 기획이나 일정은 어떻게 되시나요 ?

**Comment by thetaiz** [comment]
@kkak10 님, 안녕하세요.

이곳은 JavaScript API v3 관련 문서와 예제를 제공하는 곳입니다. ^^

Static Map API는 네이버 개발자 센터의 명세를 확인해 주세요.
- https://developers.naver.com/docs/map/overview

감사합니다.
