### ISSUE TITLE
openlayers2

### ISSUE THREAD

**Issue by gangsterrapper** [navermaps/maps.js#41]
openlayers2의 맵으로 naver map v3를 사용가능한가요?

**Comment by cs09g** [comment]
> openlayers2의 맵 

이라는 것이 무엇을 말하는 것인지 알려주셔야 할 것 같아요.

**Comment by boxersb** [comment]
@gangsterrapper 안녕하세요?
openlayers2 로 지도 API v3를 사용하신다는 말씀은 타일을 가져다 쓰시겠다는건지요..?
오픈 API 인증을 거치지 않고, 데이터를 사용하는것은 오픈 API 약관에 위배됩니다..
도움을 드리지 못해 죄송합니다.
