### ISSUE TITLE
맥에서 스크롤 과민감..

### ISSUE THREAD

**Issue by cs09g** [navermaps/maps.js#42]
맥에서 트랙패드로 휠 할 때, 과도하게 줌이 되는데 수정 예정이신지 궁금합니다.

**Comment by boxersb** [comment]
@cs09g 안녕하세요?
저희팀 모두 맥에서 개발하고 있는데요.. 특별히 과하게 줌이 동작한다고 보진 않습니다..  
`과도하게 줌`이 된다는 정도가 어느 정도인지 동영상을 캡춰해서 공유해주시면 좋겠습니다.

**Comment by cs09g** [comment]
트랙패드로 휠을 어느정도 했을 때 줌이 과도한것인지 캡쳐하기가 힘들어서 ㅠㅠ.. 설명드리자면
한 번 스크롤에 줌동작이 여러번 들어가서, 트랙패드 중간에서 제일 아래까지 슥 끌어보니 100m 거리막대가 표시되는 정도로 확대가 되더라고요. 확대가 진행중일 때 트랙패드를 터치하면 연속 확대 이벤트가 끊기고 터치한 레벨에서 확대가 멈추는데, 그냥 스크롤 되도록 두면 연속 줌 이벤트가.....

**Comment by boxersb** [comment]
@cs09g QuickTimer Player 등을 사용하여, 동영상 캡춰를 해서 보여주시면 좋겠습니다.  
트래패드나 매직마우스류의 마우스는 특성상 관성 스크롤 및 빠른 스크롤을 지원할 수 있고, 지도 줌 레벨 조정도 같은 의도로 사용할 수 있다고 판단하여, 따로 제한을 두지는 않았습니다.

**Comment by cs09g** [comment]
livecoding 에 naver, daum, google 지도에서 비슷한 속도/정도로 스크롤 한 결과 업로드하였습니다.
https://www.livecoding.tv/cs09g/videos/QqBp5-map-zooming-by-trackpad-scrolling

**Comment by boxersb** [comment]
공유해주신것 봤는데.. 저희 팀에서도 문제가 없다는 의견입니다.  
그렇게 과도하게 줌이 되는것 같아 보이지는 않는데요~~ ^^  
이정도는 서비스별 특성 차이라고 봐주시면 감사하겠습니다.

감사합니다~

**Comment by cs09g** [comment]
@boxersb 네ㅎㅎ 알겠습니다~ 수고하세용
