### ISSUE TITLE
이벤트 순서가 궁금합니다.

### ISSUE THREAD

**Issue by LandPriceInfo** [navermaps/maps.js#43]
지도에서 zoom_changed 와 bounds_changed를 이용해서 이벤트에 따라 처리를 하고 있습니다.
그런데 데스크톱의 마우스휠 줌일땐 bounds가 먼저 발생하고 줌이 처리되는데,
모바일의 핀치줌일땐 줌이 먼저 발생하고 바운즈가 바뀝니다.

제가 필요한 정보는 현재 줌 이전에 보던 지도의 줌 정보인데, 순서 이슈가 있어서 항상 동일한 결과를 위해선 어떻게 처리해야할지 고민이 생깁니다.
고견을 기다리겠습니다.

**Comment by boxersb** [comment]
@LandPriceInfo 안녕하세요?
이 부분도 `idle` 이벤트를 통해 우선 구현 부탁드립니다.  
`idle` 이벤트는 지도의 줌 이펙트나 지도 이동이 끝났을때 호출됩니다.  
따라서, `idle` 이벤트 발생전 기존의 zoom 정보를 가지고 있다가, 발생 후 변경된 `zoom`정보를 가지고 처리하셔야 할것 같습니다.  
  
모바일 핀치줌일때와 데스크탑 마우스 휠 줌일때의 순서 이슈는 저희 쪽에서도 추가적으로 확인해보겠습니다.  
일관된 순서로 노출될 수 있도록 해보겠습니다.  

큰 도움이 못되어 드려 죄송합니다~

**Comment by LandPriceInfo** [comment]
감사합니다. 이슈가 없는게 더 이상한거죠. 도움 말씀 주셔서 잘 해결할 수 있으리라 기대됩니다. 참고로 모바일 테스트는 iOS 기기 입니다.

**Comment by boxersb** [comment]
@LandPriceInfo  이슈 관리 차원에서 다시 오픈하겠습니다 :)

**Comment by LandPriceInfo** [comment]
네!

**Comment by boxersb** [comment]
@LandPriceInfo 내부 회의 결과, 데스크탑 환경에서도 줌 이펙트 발생중에 `bounds_changed` 가 발생하지 않으며, 이펙트 완료후에 `zoom_changed` 이후에 `bounds_changed`가 발생하도록 수정하기로 했습니다.  
이 로직은 모바일웹 환경에서와 동일하게 변경되는 내용입니다.  
적용은 다음주 목요일인 `10월 27일` 오전중에 진행할 예정입니다.  
참고 부탁드립니다~

감사합니다~

**Comment by LandPriceInfo** [comment]
넵 신속한 처리에 감사드립니다.

**Comment by boxersb** [comment]
@LandPriceInfo 안녕하세요? 위 로직 금일 업데이트 완료하였습니다.
감사합니다.

**Comment by LandPriceInfo** [comment]
감사합니다! b!
