### ISSUE TITLE
마우스 right 버튼 클릭시 지도 Drag 되는 증상 문의 드립니다.

### ISSUE THREAD

**Issue by chahwon** [navermaps/maps.js#44]
단독 마우스 rightclick 으로는 지도가 Drag 되지 않지만 

마우스 left down 후 rightclick 상태로 move를 수행하면 지도가 drag 되는 증상이 있는데 

정상적인 Flow로 봐야 하는 부분인지 문의 드립니다.

해당 부분은 마커에 대한 팝업메뉴 기능을 추가하여 테스트 하던 과정중  

특정 위치에 마우스 left 버튼 클릭후 마우스 right버튼 클릭 유지 상태에서 이동하면 지도가 Drag 됩니다.

위와 같이 마커에 대한 팝업메뉴 표출시 상황에 따라 오작동의 소지가 있어 문의 드려봅니다.

실예로 다수의 마커가 있는 상태에서 위와 같은 동작으로 지도 마우스 left 클릭-> mouse right 클릭을
반복하여 right click에 대한 지연이 발생하면 특정 위치로 점프하는 증상이 있습니다.

**Comment by boxersb** [comment]
@chahwon 안녕하세요?

현재는 left down -> right down -> left up -> drag 가 가능한 현상은 의도한 동작입니다만, 말씀하신것 처럼 우클릭 메뉴등을 보여주고자 하는 경우도 있으므로, 이 부부은 검토 후 수정해볼 수 있도록 하겠습니다~~

**Comment by chahwon** [comment]
정상적인 flow 였네요. 
빠른 답변 감사하고 해당 부분에 대한 예외 처리 검토도 부탁드립니다.

**Comment by boxersb** [comment]
@chahwon 안녕하세요?
마우스 좌클릭 후 빠르게 우클릭을 하면, 더블클릭 이벤트로 인식하는 문제를 수정했습니다.
확인 부탁드려요~

확인 후 문제가 있으면 이슈 Reopen 부탁드립니다.

감사합니다~

**Comment by chahwon** [comment]
잘 되네요 감사합니다.
