### ISSUE TITLE
지도에서 마커 다 지우기

### ISSUE THREAD

**Issue by tsryu** [navermaps/maps.js#45]
안녕하세요
v2에서 v3으로 마이그레이션 중인 개발자입니다

필터를 누를때마다 지도가 리셋되고
조건에 맞는 마커들이 찍히도록 함수를 개발했는데요.

예전에는 map.clearOverlay()로 리셋을 시켰는데
이제는 marker.setMap(null)로 마커기준으로 삭제할 수 있게 되어있더군요

그럼 일괄적으로 마커를 다 지우는 함수같은 것은 없는건가요?

**Comment by boxersb** [comment]
@tsryu 안녕하세요?

넵.. v3 버전에서는 `setMap` 메서드로 오버레이에 지도를 설정하는 방식으로 동작하기 때문에, `map` 에서는 지도위에 올라가있는 오버레이들을 관리하지 않고 있습니다.  
올라간 마커들을 돌면서, `setMap(null);`을 호출하는 식으로 작업 부탁드립니다.  
  
감사합니다~~

**Comment by tsryu** [comment]
넵 답변감사합니다!
