### ISSUE TITLE
웹서비스 URL을 확인해달라고 하는 에러 질문드립니다.

### ISSUE THREAD

**Issue by ChoiYongWook** [navermaps/maps.js#46]
키를 발급받고

localhost에서 테스트 하고 있었는데
클라이언트ID와 URL(localhost가 아닌 다른것으로 등록)을 확인해달라고 하는데

어떻게 해야하나요???

**Comment by boxersb** [comment]
@ChoiYongWook 안녕하세요? 

localhost 에서 테스트하시려면 해당 클라이언트 ID의 웹 서비스 url을 `localhost`로 등록하셔야 하며.. 별도의 포트를 사용하고 계시다면 해당 포트번호까지 등록하셔야 합니다.

![screen shot 2016-11-01 at 11 59 40 am](https://cloud.githubusercontent.com/assets/189953/19878350/c8ac7f80-a02a-11e6-93fd-f363041d7612.png)

감사합니다~

**Comment by ChoiYongWook** [comment]
아~ 그렇군요...
답변 감사합니다.

다른 질문이 있는데

![default](https://cloud.githubusercontent.com/assets/23023486/19879304/b3cee526-a034-11e6-9355-7e85c1cd9748.PNG)

화면이 위와같이 나오길래 밑에처러 옵션을 줘봤는데 없어지지 않더라구요.....

![default](https://cloud.githubusercontent.com/assets/23023486/19879344/f8b7466a-a034-11e6-9fef-08685315cb76.PNG)

div영역에 style을 빼도 똑같았습니다.

그리고 해당 지도를 클릭했을때 a링크로 새탭이 열려서 해당 위치 받을수 있게 하려고 하면 어떻게 해야할지 고민입니다....

**Comment by boxersb** [comment]
@ChoiYongWook 어떤 옵션을 줬을때 뭐가 없어져야하는지요..?

**Comment by ChoiYongWook** [comment]
@boxersb 지도 옆에 하얀색 빈공간이 나오는부분입니다.
즉 div영역에 해당 지도가 꽉차게 그려구조 싶었습니다

**Comment by boxersb** [comment]
div 에 width, height 스타일을 제거하시고, map 초기화시 size 옵션을 생략하시면 됩니다.

**Comment by boxersb** [comment]
@ChoiYongWook 참고로, map의 size  옵션을 생략하면 div가 실제 렌더링 되는 크기로 지도가 리사이즈 됩니다.
따라서, 해당 div의 상위 크기에 영향을 받습니다. 잘 안되시면, 상위 div의 width, height 를 설정하시고, 지도 div의 width, height 는 각각 100%로 지정해 보시기 바랍니다.  
자세한것은 아래 예제의 코드 참조 바랍니다.
> https://navermaps.github.io/maps.js/docs/tutorial-7-map-fullsize-minimap.example.html

감사합니다.

**Comment by ChoiYongWook** [comment]
@boxersb 현재 퍼블리싱 되어 나온 소스를 보니 
`http://map.naver.com/?menu=location&mapMode=0&lat` ~~ 이런식으로
호출을 하게 되어 검색해보니 2.0버전인것 같습니다

이것을 3.0으로 마이그레이션 해야할텐데 어떻게 해야할지 모르겠습니다.

또한 현재 size를 화면사이즈를 인식해서 size옵션을 주는것으로 해결하긴 했습니다.
size옵션 생략시 div영역이 테이블안에 감싸저 있었고 
테이블 밖으로 꺼내고 테이블을 지워도 똑같은 현상이 발생했었습니다.

**Comment by boxersb** [comment]
@ChoiYongWook 

퍼블리싱되어 나온 소스라는게 어디의 소스를 말씀하시는건가요..?
table 과 div 결합 구조에서 table 제거시 발생하는 현상은 저희쪽에선 확인이 어렵고 개발 이슈로 보여서 저희가 확인해드리기 어렵습니다.
