### ISSUE TITLE
polyline 초기화 방법 문의 드립니다.

### ISSUE THREAD

**Issue by kimyk86** [navermaps/maps.js#47]
var polyline = new naver.maps.Polyline({
	    map: popMap,
	    strokeWeight: 4,
	    strokeColor: '#114d91',
	    path: popPaths
	});
	popMap.panToBounds(polyline.getBounds(), 500);

이런식으로 폴리라인을 그리는데 새로운 내용이 출력될때는 기존 폴리라인이 사라져야 하는데
사라지는 방법을 모르겠습니다.
폴리라인 초기화 함수가 있는지 궁금합니다.

**Comment by thetaiz** [comment]
@kimyk86 님, 안녕하세요.

'새로운 내용이 출력될 때는' 말씀이 새로운 `path`를 이용한 새로운 폴리라인을 말씀하시는건가요? 아래와 같은 방법이 있습니다.

* 갱신: `polyline.setPath(newPopPaths)`와 같이 호출해 기존의 폴리라인을 갱신하는 방법. `polyline.setOptions('path', newPopPaths)`도 동일합니다.
* 기존 것을 제거하고, 새로운 폴리라인을 생성: `polyline.setMap(null)`과 같이 호출해 기존의 것을 제거하고, 새로 폴리라인을 생성하는 방법.

**Comment by kimyk86** [comment]
빠른 답변 감사합니다.
현재 아래와 같이 폴리라인을 그려주고 있습니다.
popPaths에 배열로 각각의 지점이 저장되어있고 그지점을 선으로 연결하는건데
다른정보 조회시 기존 폴리라인이 삭제가 되어야 하는데 계속 값이 지워지질 않습니다.
아래와 같이 출력 후 
그 아래에 if문으로 추가를 해주어도 초기화가 되지 않습니다.
어떤식으로 해야하는지 다시한번 답변 부탁드립니다.

var polyline = new naver.maps.Polyline({
	    map: popMap,
	    strokeWeight: 4,
	    strokeColor: '#114d91',
	    path: popPaths
	});

if(popPaths.length == 0) {
   polyline.setMap(null);
}
popMap.panToBounds(polyline.getBounds(), 500);
