### ISSUE TITLE
clearOverlay()

### ISSUE THREAD

**Issue by Stella0916** [navermaps/maps.js#48]
안녕하세요. 
좋은 지도 API 만들어주셔서 감사하게 잘 사용하고 있습니다.

저는 현재 이미지 마커 관련한 기능을 개발 하고 있습니다.
그런데 네이버 지도 API v2 에서는 clearOverlay 함수를 지원했는데요.
이번에 마이그레이션 하면서 'clearOverlay'라는 함수에서 찾을수 없는 함수라고 에러가 뜹니다.

튜토리얼 중 '마이그레이션: v2에서 v3로 전환하기' 문서에는
삭제되었다거나, 변경되었다는 안내가 없어 문의 드립니다.

답변 기다리겠습니다.

만약에 삭제된 API라면,
현재 그려진 지도의 마커를 한번에 삭제 할 수 있는 방법을 알고싶습니다. 

- 아래의 문의보고 더 상세히 적어봅니다.
```

var cityHall = new naver.maps.LatLng(37.5666805, 126.9784147);
var markerOptions = {
    position: cityHall,
    icon: {
        url: 'http://static.naver.net/maps/v3/pin_default.png',
        size: new naver.maps.Size(22, 35),
        anchor: new naver.maps.Point(11, 35)
    }
};
var marker = new naver.maps.Marker(markerOptions);

marker.setMap(map); // 추가
marker.setMap(null); // 삭제
```

--- 
위의 예제에서, marker 변수의 정보를 따로 저장하고 있지 않는 상황인데요. (스코프가 다른 상황)
따라서 기존에 nhn.api.map.Map 객체 단위에서 호출하듯이,
마커의 정보 따로 없이 clearOveray() 함수와 같이 초기화 호출 함수 방법은 없는지 문의드립니다.

**Comment by boxersb** [comment]
@Stella0916 안녕하세요?
지도 API v3에서는 `setMap(map)` 과 같이 오버레이에 지도를 설정하는 방식이므로, Map 객체에서 따로 오버레이의 리스트를 관리하지 않고 있습니다.
따라서, 모든 오버레이 제거를 원하실경우, 지도에 추가한 오버레이의 목록을 배열등으로 관리하고 계시다가, 삭제를 원하는 시점에 해당 배열을 루프로돌면서 `setMap(null);` 을 호출해주시면 됩니다.  
감사합니다~

**Comment by Stella0916** [comment]
네 잘알겠습니다.
