### ISSUE TITLE
폴리라인 생성시 단순히 선이 아닌 화살표를 넣을수있나요?

### ISSUE THREAD

**Issue by kimyk86** [navermaps/maps.js#49]
a에서 b지점으로 폴리라인 생성시 단순이 선이 아닌
화살표 모양이든 방향을 A에서 B방향이라는 것을 보여줄수있는 방법이 있을까요?
화살표가 나온다거나 등등..

**Comment by boxersb** [comment]
@kimyk86 안녕하세요?
해당 기능은 현재 개발중에 있습니다. 적절한 시점이 되면 공개하도록 하겠습니다 :)
감사합니다~
