### ISSUE TITLE
panorama 뷰의 위치변경시 시점 문의 드립니다.

### ISSUE THREAD

**Issue by chahwon** [navermaps/maps.js#5]
먼저 빠른 답변 감사드립니다. 

2D 지도와 panorama 뷰와의 연동 테스트 하는 도중 특정 지역에서 setPosition 함수를 이용하여 위치를 변경시 파노라마 뷰의 시점이 변경되는 부분이 있어 문의 드립니다. 

테스트는 도로 중앙으로 시점을 맞추어 놓고 setPostion 함수를 사용시 * 도로중앙의 시점에서 대각 방향으로 이동하는 부분이 있어 문의 드립니다.

**Comment by myounggun-chae** [comment]
안녕하세요. 

`setPosition` 호출 시 파노라마 시야(`pov`)를 초기화 하는 문제가 있었네요.
파노라마 위치 변경 시 이전 `pov` 변경되지 않도록 개선하겠습니다.
배포 일정 정해지면 다시 코멘트 드릴께요.

제보 감사합니다:-)

**Comment by chahwon** [comment]
감사합니다.

**Comment by myounggun-chae** [comment]
@chahwon `setPosition` 버그 수정하여 배포하였습니다. 
확인 부탁드립니다.

**Comment by chahwon** [comment]
잘되네요. 빠른 수정 감사합니다.

**Comment by myounggun-chae** [comment]
확인 감사합니다:-)  이슈를 닫습니다.
