### ISSUE TITLE
영문으로 지역 / 건물명 노출 가능 여부 문의

### ISSUE THREAD

**Issue by redring33** [navermaps/maps.js#50]
안녕하세요.
naver map viewer 사용시 영문으로 지역 / 건물명등을 노출 할 수 있는지 여부를 문의 드립니다.

확인 부탁 드립니다.

감사합니다.

**Comment by boxersb** [comment]
@redring33 안녕하세요?
답변이 늦어져 대단히 죄송합니다 ;;
네이버 지도를 통한 영문명 지역/건물명을 지도의 타일로 노출하는 부분은 현재 제공하지 않고 있습니다.
양해 부탁드립니다.

감사합니다~
