### ISSUE TITLE
네이버 지도에서  InfoWindow  관련 질문입니다.

### ISSUE THREAD

**Issue by pong777** [navermaps/maps.js#51]
InfoWindow 는 다중으로 띄울수는 없는 부분인가요?

기존 마커 label 사용 했었는데  네이버 지도 v3.0 나오면서 클라이언트 사 네이버 지도들을 바꿔주면서 
마커 label  없어지면 InfoWindow로 사용하여 마커 정보를 띄우려고 했는데 2개 이상인데요.

InfoWindow 는 다중으로 띄울수는 없는 부분인가요?

**Comment by boxersb** [comment]
@pong777 넵.. `InfoWindow`는 제작 의도상 지도 하나당 하나만 뜨도록 되어 있습니다.
여러개의 라벨을 사용하고자 하신다면, HTML 마커나 커스텀 오버레이를 제작해서 사용하시는게 좋을것 같습니다.
만족스러운 답변을 드리지 못해 죄송합니다.

감사합니다~
