### ISSUE TITLE
v2 에서 https 로 전환되지 않는 문제

### ISSUE THREAD

**Issue by hongtae-kim** [navermaps/maps.js#52]
v2 버전을 쓰고 있습니다. 
특정pc에서 maps.js 을 첨부하는 http 가 https 로 전환되지 않는 문제가 생기고 있습니다.
maps.js 를 https 로 링크를 걸어도 스크립트 내부에서 http로 호출하는 부분이 있기 때문에 문제는 여전히 발생합니다.

윈도우7, 익스8 환경이며 크롬에서도 동일한 증상입니다.

해결책이 없을지 문의 드립니다.

**Comment by boxersb** [comment]
@hongtae-kim 안녕하세요? 지도 API v2, v3 모두 https 를 지원하며, 내부 리소스 또한 https 환경에서 동작하도록 처리가 되어 있습니다.
저희가 마련해둔 테스트 페이지에서는 이상이 없어 보이는데요.. 아래의 url 확인 부탁드립니다.

> https://openapi.map.naver.com/openapi/samples/openapi-v2.html

감사합니다~
