### ISSUE TITLE
주소를 위치로 변환하는 기능 문의 드립니다.

### ISSUE THREAD

**Issue by seokbinko** [navermaps/maps.js#53]
안녕하세요.

v2에서 아래와 같이 주소를 위치(위도, 경도)로 변환하고 있는데요

http://openapi.map.naver.com/api/geocode.php?key= 맵키&encoding=utf-8coord=LatLng&query=' + 주소

v3에서는 해당기능 사용할때 어떻게 변환할지 문의 드립니다.

감사합니다.

**Comment by boxersb** [comment]
@seokbinko 안녕하세요? 주소-좌표 변환 API는 v2, v3와는 관계 없는 별도의 서버 API입니다 ^^;
`Client ID` 와 `Client Secret`을 사용하는 방식의 인증에 대한 가이드는 아래의 문서 참조 바랍니다.

> * 지도 API 명서 - https://developers.naver.com/docs/map/overview
> * API 호출 가이드 - https://developers.naver.com/docs/common/apicall

감사합니다~
