### ISSUE TITLE
맵 인쇄방법이 궁금합니다.

### ISSUE THREAD

**Issue by lee-suwon** [navermaps/maps.js#54]
안녕하세요?

인쇄페이지에서 사각형,원,폴리곤,폴리라인, 사용자 정의 오버레이등을 표시하고 인쇄를 하면
해당 부분이 인쇄되지 않습니다.
방법이 없는지 궁금합니다.

감사합니다.

**Comment by junthus** [comment]
안녕하세요 @lee-suwon 님
사용하고 계신 브라우저가 무엇인가요 ?.?

**Comment by lee-suwon** [comment]
IE 11 사용하고 있습니다.

**Comment by lee-suwon** [comment]
InfoWindow,Marker 부분은 보이는데
사용자정의오버레이로 표시된 marker, infoWindow와 도형(원,사각형,다각형)은 인쇄가 안되네요

**Comment by junthus** [comment]
말씀하신 '인쇄페이지'는 js map v3 api를 이용해서 직접 구현하신 페이지인거죠 ?
(map.naver.com 에도 인쇄페이지가 있어서 헷갈리네요 ;;)

**Comment by lee-suwon** [comment]
지금 작업하고 있는 페이지입니다.

**Comment by junthus** [comment]
넵 이슈 확인했습니다. 
해당 현상은 IE 브라우저의 svg 태그 인식 버그로 보입니다.
검토후 빠른 시일 내에 패치하도록 하겠습니다.

**Comment by lee-suwon** [comment]
감사합니다.

**Comment by junthus** [comment]
11월 정기배포(24일)에 포함하기로 했습니다. 조금만 기다려 주세요 ~~ ^^

**Comment by lee-suwon** [comment]
수고많으시네요.
감사합니다.

**Comment by junthus** [comment]
@lee-suwon 님 안녕하세요 ^^
해당 내용 패치되었습니다. 확인 부탁드려요 ~~
