### ISSUE TITLE
문서가 약간 부실합니다.

### ISSUE THREAD

**Issue by jaymz9634** [navermaps/maps.js#55]
개인적인 느낌일 수 있으나..

회사 업무 적용을 위해.. 문서들을 검토해 보았으나..

요구하는 기능인 길찾기에 대한건 없네요..

제가 못 찾는 건지...

오른쪽 상단의 검색을 해도 아무 반응도 없고..

**Comment by thetaiz** [comment]
@jaymz9634 님, 안녕하세요. 

길찾기 기능은 제공하고 있지 않습니다.

**Comment by jaymz9634** [comment]
빠른 답변 감사합니다.

원하는 기능이 없다고 하니 아쉽네요..

수고하세요..^^
