### ISSUE TITLE
Naver Map Open API certification failed!

### ISSUE THREAD

**Issue by tparikh2** [navermaps/maps.js#56]
Hi,

I am new to naver map and trying to get simple map using naver map api js v3. I got registered and got client id and client secret value. 

Then I am using this client id like this : **<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=myclientid"></script>**

and I am getting below error:
Naver Map Open API certification failed!
Please check clientId and web service url.

Can anyone please help me to fix this issue? 

Regards,
Tushar Parikh.

**Comment by boxersb** [comment]
@tparikh2 Hi~
Did you registered `Web Service Url` in your application?
Check it out below url.
> https://developers.naver.com/appinfo

If you registerd `http://boxersb.com` as web service url for your `Client ID`.
The application should run in `*.boxersb.com` location.

**Comment by tparikh2** [comment]
Thanks Kyoungtaek Koo

Thanks & Regards,
Tushar Parikh.

+91-909-901-3316
