### ISSUE TITLE
dblclick의 기본 동작을 취소할 수 없습니다.

### ISSUE THREAD

**Issue by davidshimjs** [navermaps/maps.js#58]
`dblclick` 이벤트의 originalEvent, pointerEvent 안에 있는 `preventDefault()` 메서드를 실행해도 더블클릭시 줌인 동작을 취소할 수가 없습니다.

**Comment by boxersb** [comment]
@davidshimjs 지도의 이벤트 발생시에 같이 전달해주고 있는 `originalEvent` 등의 `preventDefault` 메서드로는 지도의 동작을 취소할 수 없습니다.  
`Map.setOptions('disableDoubleClickZoom`);` 을 사용하여 지도 확대 기본 동작을 해제하시기 바랍니다.

감사합니다~

**Comment by davidshimjs** [comment]
@boxersb 맵의 옵션을 끄는 방법만 있는거군요! 평소에는 doubleClickZoom을 사용하다가 핀을 더블클릭하거나 했을 때의 동작을 정의하고 싶었던 건데요, 취소가 가능하다면 이런 기능을 만들 수 있을 것 같아요.

**Comment by boxersb** [comment]
@davidshimjs 내부적으로 이벤트 동작을 조금 손보고 있습니다.
말씀하신것처럼, 오버레이에서 더블클릭시에는 지도가 더블클릭되어서는 안되기에 해당 이슈도 처리하겠습니다~
감사합니다~

**Comment by boxersb** [comment]
@davidshimjs 안녕하세요?
금일 업데이트 버전에서 마커위의 더블클릭시 지도가 확대되는 문제를 수정했습니다.
확인 부탁드리며, 문제가 발견되면 이슈 Reopen 부탁드립니다.

감사합니다.
