### ISSUE TITLE
map 의 click 이벤트 삭제관련하여 문의드립니다.

### ISSUE THREAD

**Issue by monanhip** [navermaps/maps.js#59]
map.addListener('click', function(e) {  
})

를 통하여 추가한 이벤트를 다시 제거 하려면 어떻게 해야될까요..

**Comment by thetaiz** [comment]
@monanhip 님, 안녕하세요.

아래와 같이 이벤트를 사용해 주시면 됩니다.

**이벤트 추가 시**
```js
var listener  = naver.maps.Event.addListener(map, 'click', function(e) {});
```

**이벤트 해제 시**
```js
naver.maps.Event.removeListener(listener);
```

**Comment by monanhip** [comment]
@thetaiz 학습중인 곳에 잘 적용했습니다 . 감사드립니다.!
