### ISSUE TITLE
How to handle the infowindow close event if we have multiple markers

### ISSUE THREAD

**Issue by dkchittimilla** [navermaps/maps.js#6]
In our application we are showing a Naver map with multiple map points and each point has a InfoWindow. In this case how can we handle the close events for these info windows.

Please share me if there is any example code.

**Comment by cs09g** [comment]
What about to use an array to add listeners. code like
```
var markers = [marker1, marker2];

for (var i = 0, len = markers.length; i < len; i++) {
  naver.maps.Event.addListener(markers[i], "click", function(e) {
    if (infowindow.getMap()) {
        infowindow.close();
    } else {
        infowindow.open(map, markers[i]);
    }
	});
}
```

** But it does not work with an error message "position or anchor should be assigned."
It's weird.

**Comment by boxersb** [comment]
@cs09g dkchittimilla
The code you written above might actually doesn't work.  
Even though you assigned event handler of `markers[i]` in for loop, value of variable `i` is always `markers.length - 1` as final value in for loop. Because, handler body refer only final value in for loop as closure..

You can use another closure to refer corresponding value `i`.  
Please see example below..
> https://navermaps.github.io/maps.js/docs/tutorial-marker-viewportevents.example.html

`getClickHandler` function. bottom of code in that example is returns curried function to capture value `i`(index) as closure value `seq` (argument). And, use it in returned curried function(event handler) to refer corresponding value.  

I hope this helps you~

**Comment by boxersb** [comment]
@dkchittimilla 

We don't have `close` or `open` event for `InfoWindow`. But, you can use `map_changed` KVO event for that.  
When `map_changed` fires, `map` argument passed to handler. If `map` is `naver.maps.Map` instance, `InfoWindow` is opened, `null` is closed.

**Comment by cs09g** [comment]
Thanks @boxersb , fixed my example as
[https://jsfiddle.net/8r7tmqyz/3/](url) 
1. but then, why it does not work for the last marker?
2. why don't you make custom infoWindow?

**Comment by boxersb** [comment]
@cs09g 
1. See https://jsfiddle.net/wxe2j20h/4/ I forked.
2. What do you mean "custom infoWindow"?

**Comment by cs09g** [comment]
@boxersb Sorry, Mistakes. that is already custom infowindow in my sight. I thought there are two infoWindow types. One is default infowindow form which includes base infoWindow structure such as header/body/'x' button. it requires only text for each section. so if users are not familiar with styles, it might be useful. 
The other is custom infowindow form that requires div element as a text form like in the Naver API.

**Comment by boxersb** [comment]
@cs09g I think you want to google style InfoWindow (header/body/x button).
NAVER style InfoWindow designed to more flexibility for it's ui. User can add Title or close button(x) to InfoWindow `content`, if user wants.

In our opinion.. google style Infowindow is more customed InfoWindow.

**Comment by cs09g** [comment]
actually, google's style is same with Naver's
https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

**Comment by boxersb** [comment]
@cs09g Naver's Infowindow don't support automatically display close button (x button).

**Comment by cs09g** [comment]
아, x도 텍스트로 넘겨서 만든줄 착각했습니다. 감사합니다 :) :+1:

**Comment by boxersb** [comment]
@dkchittimilla This issue has generated after 7 days elapsed. Therefore, to close the issue.
If you have another question about this issue, please repoen to let us know.

Thanks.
