### ISSUE TITLE
좌표변환 질문

### ISSUE THREAD

**Issue by gangsterrapper** [navermaps/maps.js#60]
EPSG:900913 좌표를 위경도로 변환 가능한가요??

**Comment by boxersb** [comment]
`EPSG:900913` 이라면 `EPSG:3857` 을 말씀하시는건가요?

**Comment by boxersb** [comment]
특정 좌표를 공유해주시면 방법을 찾아보도록 하겠습니다.

**Comment by gangsterrapper** [comment]
서울 시청 126.76620435615891,37.42829747263545
900913 : 14111549.3187;4498975.26728

http://cs2cs.mygeodata.eu/#links 에서 변환한 데이터입니다

**Comment by boxersb** [comment]
@gangsterrapper 안녕하세요?

해당 좌표는 다행히 네이버 지도 API v3의 `Geocoder` 모듈을 활용하여 변환이 가능합니다.

> Geocoder 기본 가이드 : https://navermaps.github.io/maps.js/docs/tutorial-Geocoder.html

`Geocoder`의 `EPSG3857Coord` (EPSG3857 평면 좌표계 투영) 객체를 활용하실 수 있습니다.
아래의 코드 참조바랍니다.
```js
// EPSG3857 평면 좌표
var epsg3857Point = new naver.maps.Point(14111549.3187, 4498975.26728);

// 위/경도로 변환한 좌표
var latlng = naver.maps.EPSG3857Coord.fromCoordToLatLng(epsg3857Point);

console.log(latlng); //  (37.4282975, 126.7662044)
```

위/경도 좌표는 편의상 소수점 이하 7자리까지 표기하며, 마지막 자리는 8번째 자리의 반올림 값입니다.  
도움이 되셨으면 좋겠습니다.

감사합니다~

**Comment by gangsterrapper** [comment]
해결했습니다.감사합니다.
