### ISSUE TITLE
줌컨트롤 관련

### ISSUE THREAD

**Issue by gangsterrapper** [navermaps/maps.js#61]
줌 컨트롤에 마우스가 오버될 경우
시군구, 시도 등의 문구가 노출됩니다.

최대,최소 줌 레벨을 제한하였더니 텍스트가 노출되는 위치가 이상해서

차라리 안나오게 하려고 합니다.

옵션에는 없는것으로 보이는데 방법이 있을까요?

**Comment by thetaiz** [comment]
@gangsterrapper 님, 안녕하세요.

현재 문서에는 누락되어 있지만, 아래와 같이 `legendDisabled` 옵션을 설정하면 줌 컨트롤의 범례를 노출하지 않을 수 있습니다.

참고로, 문서는 금주 정기배포에 반영될 예정입니다. 감사합니다.

```js
var map = new naver.maps.Map("map", {
    ... (생략) ...
    zoomControl: true, 
    zoomControlOptions: {
        position: naver.maps.Position.TOP_LEFT,
        style: naver.maps.ZoomControlStyle.LARGE,
        legendDisabled: true
    }
});
```
