### ISSUE TITLE
marker tooltip 관련 문의드립니다.

### ISSUE THREAD

**Issue by flyhamster** [navermaps/maps.js#62]
var marker = new naver.maps.Marker({
        map: map,
        position: position,
        title: 'test',
        icon: {
            url: HOME_PATH +'/img/example/sp_pins_spot_v3.png',
            size: new naver.maps.Size(24, 37),
            anchor: new naver.maps.Point(12, 37),
            origin: new naver.maps.Point(MARKER_SPRITE_POSITION[key][0], MARKER_SPRITE_POSITION[key][1])
        },
        zIndex: 100
    });

마커에 title 설정했을 때 툴팁 문자열이 노출된다고 나와있는데 동작을 안하는것 같습니다.

**Comment by junthus** [comment]
@flyhamster 님 안녕하세요, 툴팁은 마커에 마우스 오버시에 노출됩니다. 참고 부탁드립니다.

**Comment by flyhamster** [comment]
마우스 오버시에 노출이 안됩니다.

https://navermaps.github.io/maps.js/docs/tutorial-marker-animation.example.html

이 예제에서도 마우스 오버시에 노출이 안되네요.
크롬, 파이어폭스 둘다 테스트 해봤습니다.

**Comment by junthus** [comment]
@flyhamster 헛 저는 잘 되는 듯 한데.. 마우스 오버후 조금 기다리면 아래 그림처럼 노출되지 않나요 ?

![image](https://cloud.githubusercontent.com/assets/5088669/20554321/84bec046-b19e-11e6-9a24-38efc2a56049.png)

**Comment by flyhamster** [comment]
헉... 몇초 후에 노출되는 거군요 ㅠㅠ 
시간을 조정할 순 없을까요??

**Comment by junthus** [comment]
현재 노출되는 툴팁은 브라우저의 스펙(`title`)이라 조정이 불가능합니다 ㅠㅠ
세세한 조정을 원하시면 다른 방법으로 구현하셔야 합니다.

**Comment by flyhamster** [comment]
답변 감사합니다.

**Comment by thetaiz** [comment]
@flyhamster 님, 대안으로 HTML 마커를 이용하고(`title` 없이) 마커의 이벤트(`mouseover`, `mouseout`)에 따라 툴팁 부분을 직접 `show()`, `hide()`하는 방식도 생각해 볼 수 있겠네요.
