### ISSUE TITLE
부트스트랩 모달에서의 포지션 오류

### ISSUE THREAD

**Issue by webhacking** [navermaps/maps.js#63]
![13](https://cloud.githubusercontent.com/assets/10232178/20553699/dca4fd52-b199-11e6-8843-a10c5333c92b.png)

위와 같이 모달에서 볼 때, 반 쯤 짤려서 보여지네요.
이전에 동일한 이슈가 있는가요 ?

**Comment by junthus** [comment]
@webhacking 안녕하세요 ~ 혹시 저희가 재현해 볼 수 있는 url이 있을까요 ?

**Comment by webhacking** [comment]
@junthus 안녕하세요 ~ 피드백 감사합니다.
URL 은 하단에 따로 적어두겠습니다.
아직 개발 초기단계 서비스라.. 접속이 잘 안되거나 그럴수도있어용..(?) TT

주소 : https://develop.truckup.kr/orderlist/ (리스트 배차 정보를 눌렀을시 보이는 지도 영역)
아이디 : 01022223333
패스워드 : 1234

**Comment by junthus** [comment]
@webhacking 님 답변이 늦어 죄송합니다 ㅠㅠ

살펴보았더니 `modal()`이 실행되기 전에 지도가 초기화 되고 있어서 지도 영역의 사이즈를 계산할 수 없는 상황입니다. ㅠㅠ 지도 영역의 크기를 다시 계산할 수 있도록 아래와 같이 한 줄 추가 부탁드립니다.

```js
$('#driver-infoModal').modal();
map.trigger('resize');
```

추가로, `배차정보` 버튼을 누를때마다 지도가 계속 생성되고 있는데요, 모달창을 종료하는 시점에 `map.destroy();`를 실행해주시면 지도가 정리됩니다.

도움이 되시길 바랍니다 ^^ 감사합니다~~.

**Comment by webhacking** [comment]
@junthus 답변 감사합니다. ^^ 
도움 많이 되었습니다.

**Comment by smchae** [comment]
@junthus  안녕하세요, 위의 코멘트에서 map.destroy();를하면 지도가 정리된다고 하셨는데 아래와 같이 적용을 `map.destroy();`를 사용했음에도 불구하고 #66 의 현상이 일어납니다. 제가 `destroy();` 를 잘못 쓰고 있는건가요?
```
$('#driver-infoModal').modal().on('hidden.bs.modal', function () {
   map.destroy();
});
```

**Comment by junthus** [comment]
@smchae @webhacking 
아뇨 ^^ `map` 변수가 있는지만 확인한다면 잘못 사용하는 상황은 아닐 것 같습니다. 
혹시 모르니 캐시를 한 번 지우고 확인해 주시고, 문제가 계속 발생한다면 다시 한 번 확인할 수 있도록 url 부탁드림다.

**Comment by smchae** [comment]
@junthus 
캐시를 지우고 해봐도 같은 현상입니다. console.log 를 통해서 확인하면, map.destory(); 이후에도 map이 destory 되지 않는 현상이 발생합니다. 모달이 닫기는 event는 인식을 하는데 destory가 적용이 안되네요.

테스트아이디: 01022223333
패스워드: 1234
오더넘버 #6155의 지도가 제대로 적용이 되지 않습니다.

감사합니다.

**Comment by cs09g** [comment]
@smchae 궁금해서 들어가보니, 지도가 안나오던데.. 원래그런건가요?

**Comment by smchae** [comment]
@cs09g 원래 나와야하는데 #66에 스크린샷처럼 map객체가 제대로 생성되지 않는 것 같습니다. 하지만 console로 map객체를 찍으면 객체에 값들이 들어가있는데 제대로 표현이 안되고 있습니다.

![default](https://cloud.githubusercontent.com/assets/19833955/20656184/576586fc-b56d-11e6-9d40-1f9743c97aaf.png)

**Comment by cs09g** [comment]
@smchae 마찬가지로 콘솔에서 driver-df-map 으로 지도 생성 함수를 호출해보니 이 때는 다시 정상 표출됩니다. 코드 어딘가에서 꼬였나봅니다.

**Comment by junthus** [comment]
엇 같이 확인해주시는 분들이 있군요 ^^ 감사합니다.

@webhacking 님
![image](https://cloud.githubusercontent.com/assets/5088669/20656339/e92cb32a-b56e-11e6-8792-a3045c2d2d9b.png)

변수 선언에 오류가 있어 marker에 잘못된 `position`값이 들어갑니다. ^^ 수정해주시면 정상으로 작동할 것 같아요. 추가로 `$('#driver-infoModal').on('hide.bs.modal', ...` 이 이벤트 리스너가 계속 쌓이고 있습니다. 동작상 별 문제는 없겠지만 해제하는게 좋을 듯 합니다 ~~ 참고 부탁드려요 !

**Comment by smchae** [comment]
@junthus @cs09g  정말 감사합니다! 덕분에 잘 해결할수 있었습니다~

**Comment by junthus** [comment]
@webhacking @smchae 이슈 닫겠습니다 ^^ 혹시 또 문제사항이 있다면 언제든 제보해주세요.
즐거운 개발(;;)되세요 ~~~ 감사합니다.
