### ISSUE TITLE
marker 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by flyhamster** [navermaps/maps.js#64]
marker 에 mouseover, mouseout 이벤트를 추가하여
InfoWindow open, close 를 하고 있습니다.

그런데 지도를 움직인 직후에 marker 에 mouseover 이벤트가 발생하지 않고 있습니다.

맵 로딩 -> marker mouseover(정상작동) -> infoWindow open -> marker mouseout -> infoWindow close

맵 로딩 -> marker mouseover(정상작동) -> infoWindow open -> marker mouseout -> infoWindow close-> 지도 움직임 -> marker mouseover(동작하지 않음) -> marker mouseout(디버깅으로 호출되는 거 확인) -> marker mouseover(정상작동) -> infoWindow open

**Comment by junthus** [comment]
헛 제보 감사드립니다. 빠르게 패치하도록 하겠습니다.

**Comment by junthus** [comment]
안녕하세요 @flyhamster 님, 
제보해주신 이슈 패치하였습니다. 확인 한 번 부탁드립니다 ~~~~.

**Comment by flyhamster** [comment]
수고하셨습니다.
감사합니다. 👍
