### ISSUE TITLE
v2 -> v3 겹침 마커 표시 문의드립니다.

### ISSUE THREAD

**Issue by seokbinko** [navermaps/maps.js#65]
안녕하세요. 

현재 네이버지도 v2 를 v3로 마이그레이션 하는 중에 겹침 마커 여부에 대해 문의드리고자 합니다.

기존엔 .clickCoveredMarker 로 겹침 마커를 판별했는데, 새로운 버전에서는 현재 마커가 겹침마커인지

어떻게 판별할지 몰라 문의 드립니다.

감사합니다.

**Comment by junthus** [comment]
안녕하세요 @seokbinko 님 ^.^
v3버전은 겹침마커를 판별하는 방법을 내장하여 제공하지 않고, 별도의 툴로 제공하고 있습니다. 
아래 저장소의 내용을 참고하시면 도움이 될 듯 합니다. 
https://github.com/navermaps/marker-tools.js/tree/master/marker-overlapping-recognizer
