### ISSUE TITLE
map duplicate

### ISSUE THREAD

**Issue by webhacking** [navermaps/maps.js#66]
처음 부트스트랩 모달을 통하여 `맵` 을 생성한 후,
다음 모달에서 이전과 동일하게 맵을 생성하였을 경우 보여지는 지도영역이 제대로 표기되지않는 현상이 발생합니다.

제대로 표기되지않는 현상은 이전에 생성한 `맵`이 겹쳐저 보입니다.
`Map` 객체를 생성할 때 지정한 element 에 내용과 style을 전부 리셋하였는데도 동일하여 혹시 이와 관련되서 내부 함수가 있는지 여부또한 궁금합니다.

**Comment by webhacking** [comment]
![20161125_194100](https://cloud.githubusercontent.com/assets/10232178/20622624/213a44c8-b347-11e6-9da6-78b1d700011c.png)

참고 사진입니다.

**Comment by junthus** [comment]
@webhacking 님 안녕하세요 ~ 
`map.destroy()` 를 호출하면 될 듯 한데 뭔가 문제가 있나 보네요 ㅠㅠ
혹시 모르니 캐시를 지우고 한 번 테스트 해 주시고, 
계속 문제가 발생한다면 다시 한번 확인할 수 있는 url 부탁드립니다.

**Comment by junthus** [comment]
@webhacking 님 잘 해결되셨다니 이 이슈도 종료 처리하겠습니다 ^^

**Comment by webhacking** [comment]
@junthus 네 감사합니다.^^ 많은 도움 되었습니다.
