### ISSUE TITLE
CustomOverlay 문의

### ISSUE THREAD

**Issue by flyhamster** [navermaps/maps.js#68]
1. CustomOverlay 를 이용하여 info 창을 여러개 띄우려고 합니다.
position 값이 이상하게 나와서 확인부탁드립니다.
![2016-11-29 3 48 13](https://cloud.githubusercontent.com/assets/5085222/20699586/6b8232c8-b64b-11e6-83f5-e5ab03423883.png)

2. CustomOverlay 를 클릭 했을때 다른 처리를 하려고 하는데
click  이벤트는 지원을 하지 않는건가요??

**Comment by junthus** [comment]
안녕하세요 @flyhamster 님

v3 api에서는 `zoom` 변경시에 left top 을 갱신하고 있습니다. 때문에 화면 좌표가 음수가 나오는 것은 줌이 변경됐을 당시의 좌표보다 왼쪽, 위쪽에 있는 것을 의미할 뿐 잘못된 값은 아닙니다. (혹시 원하는 위치에 표시되지 않는다면 알려주세요.)

`OverlayView`는 추상 클래스이기 때문에 따로 이벤트를 랩핑해서 제공하지는 않습니다. [addDomEventListener](https://navermaps.github.io/maps.js/docs/naver.maps.Event.html#-static-addDOMListener__anchor)등을 이용하셔서 직접 구현하시면 될 듯 합니다.

도움이 되시길 바랍니다 ^.^

**Comment by flyhamster** [comment]
줌을 변경하진 않았고 지도를 움직였을때 위의 결과가 나왔습니다.

**Comment by junthus** [comment]
@flyhamster 넵넵
줌 변경시에 초기화 되고 패닝시에는 left top 값이 변경됩니다. 다시 줌이 변경되면 초기화 되고요.
혹시 예상한 위치에 오버레이가 표시되지 않는다면 접근할 수 있는 url을 남겨주시면 확인해보겠습니다.

**Comment by flyhamster** [comment]
naver.maps.Event.addDOMListener(this.map, 'click', function() {
                this.map.setZoom(8);
            });

![2016-11-30 8 58 12](https://cloud.githubusercontent.com/assets/5085222/20734208/495759cc-b6db-11e6-8050-cac3c7eeafe0.png)

제가 잘못 사용하고 있는걸까요....ㅠㅠ

**Comment by cs09g** [comment]
첫 번째 파라미터가 DOMElement 이므로, map.getElement() 를 사용해야 하지 않을까요? map 은 DOM 이 아니라 지도 객체를 나타내는 것 같아요.

**Comment by thetaiz** [comment]
@flyhamster 님, @cs09g 님 설명처럼 `map`은 지도 객체이므로 `naver.maps.Event.addListener` 메서드를 사용해야 합니다. 초기 질문인 커스텀 오버레이를 클릭했을 때 이벤트를 받을려면 아래와 같이 `naver.maps.Event.addDOMListener`를 이용하라는 @junthus 님의 설명이었습니다. 이때 커스텀 오버레이에서 엘리먼트는 반환하는 인터페이스('getElement') 역시 구현이 되어야 하구요. ^^

```
var customOverlay = new CustomOverlay();

naver.maps.Event.addDOMListener(customOverlay.getElement(), 'click', function(e){});
```

**Comment by flyhamster** [comment]
답변 감사합니다.
