### ISSUE TITLE
getScript로 js 로드 후, naver.maps.Service.geocode({ 호출 시 에러가 발생 합니다.

### ISSUE THREAD

**Issue by chichansong** [navermaps/maps.js#69]
테스트를 위해 샘플 코드를 작성 중인데, 에러가 발생하는 부분이 있어서 문의 드립니다.

`$.getScript("https://openapi.map.naver.com/openapi/v3/maps.js?clientId=클라이언트ID&submodules=panorama", function() {
    		searchAddressToCoordinate('정자동 178-1');
	});`

다음과 같이 구문을 동작해서 해 놓은 상태에서 searchAddressToCoordinate 함수가 실행되면

`function searchAddressToCoordinate(address) {
    naver.maps.Service.geocode({
        address: address
    }, function(status, response) {
        if (status === naver.maps.Service.Status.ERROR) {
            return alert('Something Wrong!');
        }
        var item = response.result.items[0],
            addrType = item.isRoadAddress ? '[도로명 주소]' : '[지번 주소]',
            point = new naver.maps.Point(item.point.x, item.point.y);
      //  infoWindow.setContent([
      //          '<div style="padding:10px;min-width:200px;line-height:150%;">',
      //          '<h4 style="margin-top:5px;">검색 주소 : '+ response.result.userquery +'</h4><br />',
      //          addrType +' '+ item.address +'<br />',
      //          '&nbsp&nbsp&nbsp -> '+ point.x +','+ point.y,
      //           '</div>'
      //      ].join('\n'));
        map.setCenter(point);
        infoWindow.open(map, point);
    });
}`

naver.maps.Service.geocode({ 이 부분에서 
**Uncaught TypeError: Cannot read property 'geocode' of undefined**
gecode가 선언되지 않았다는 메세지 같은데, 왜 그러는지 모르겠네요.

**Comment by boxersb** [comment]
@chichansong 안녕하세요? 

`$.getScript` 를 통해 지도 API를 비동기 로드하실 경우.. submodule 또한 비동기 로드가 되게 됩니다.
이때는 `$.getScript` 의 콜백 호출과 별개로 `geocoder` 모듈의 로드 시점이 결정됩니다.

따라서, `$.getScript` 콜백 내에서 `naver.maps.onJSContentLoaded` 를 활용하여 서브모듈까지 모두 로드가 된 상태에서 실행해주시면 되겠습니다.

```js
$.getScript('https://openapi.map.naver.com/openapi/v3/maps.js?clientId=클라이언트ID&submodules=geocoder', function() {
    naver.maps.onJSContentLoaded = function() {
        // Map 및 geocoder 처리 로직
    };
});
```

> https://navermaps.github.io/maps.js/docs/tutorial-4-Submodules.html

위 링크 하단의 `onJSContentLoaded` 사용 부분 참조부탁드립니다.

감사합니다~

**Comment by boxersb** [comment]
@chichansong 그리고, 이슈로 올려주셨던 url에 `submodules` 항목에 `geocoder` 가 빠져있고 panorama 가 들어가 있습니다.
