### ISSUE TITLE
다수의 마커좌표로 지도 센터 이동시 화면좌표 문의 드립니다.

### ISSUE THREAD

**Issue by chahwon** [navermaps/maps.js#7]
증상:
마커의 화면좌표를 구하는 테스트를 진행하는 과정에서 이상한 점이 있어 문의 드립니다.

지도상에 2개의 마커를  거리를 두고 배치후 해당 마커의 좌표로 지도 중심이동하게 되면 
첫째 마커의 화면좌표는 Projection 함수 변환시 정상이나 두번째 마커를 지도 중심이동하게 되면 
첫번째 마커의  화면좌표를 구할때 위치한 마커2의 화면좌표가 반환됩니다.

테스트: 
* Projection 화면좌표변환 함수를 통해 값을 구할시 위와 같은 방식이라면 
  동일한 픽셀좌표가 나와야 하나  같지 않아 문의 드립니다. 

아래는 제가 사용한 테스트 코드 입니다.

              
        var oDefPoint = new naver.maps.LatLng(37.3595704, 127.105399);
		var defaultLevel = 12;
		var oMap = new naver.maps.Map(document.getElementById('map'), {
		    center: oDefPoint,
						zoom : defaultLevel,						
						mapMode : 0,						
						minMaxLevel : [ 1, 14 ],
						size: new naver.maps.Size(880, 530)
		});		
		
		var markerlist = [];

		var listener = naver.maps.Event.addListener(oMap, 'click', function (e) {

		    var marker = new naver.maps.Marker({
		        position: new naver.maps.LatLng(e.coord.y, e.coord.x),
		        map: oMap
		    });

		    markerlist.push(marker);		    
		});
		
		
		function marker1() {
		    oMap.setCenter(markerlist[0].getPosition());

		    var projection = oMap.getProjection();
		    var pos = projection.fromCoordToOffset(markerlist[0].getPosition());
		    alert(pos);
		}

		function marker2() {
		    oMap.setCenter(markerlist[1].getPosition());

		    var projection = oMap.getProjection();
		    var pos = projection.fromCoordToOffset(markerlist[1].getPosition());
		    alert(pos);
		}

    <form>
        <input  type="button" value="마커1 이동" onclick="marker1()" />
        &nbsp;
        <input  type="button" value="마커2 이동" onclick="marker2()" />        
        <br />
    </form>

**Comment by myounggun-chae** [comment]
@chahwon 
안녕하세요.
지도 중심에 위치한 마커1과 마커2의 화면 좌표가 동일하게 나오지 않아서 문의를 주신것 같은데요?

화면 좌표는 지도 화면의 DOM 컨테이너 상에서의 오프셋이라서 지도의 이동이 발생하면 변동될 수 있는 값입니다.
아래 튜토리얼 하단의 '화면 좌표' 부분을 보시면 답변이 될 것 같습니다. ^^

*  지도 투영 - 화면 좌표 (Offset Coordinate)  
https://navermaps.github.io/maps.js/docs/tutorial-Projection.html

> 화면 좌표는 지도의 이동, 줌 레벨 변경 등으로 인한 DOM 컨테이너의 위치에 따라 변동될 수 있는 좌표이므로 어느 한 지점을 고유하게 가리키는 절대 좌표로 사용할 수는 없습니다.

감사합니다.

**Comment by chahwon** [comment]
제가 해당 방법에 대해서 접근을 잘못한것 같습니다. 감사합니다.

**Comment by myounggun-chae** [comment]
API 사용하면서 궁금하신 사항은 언제든 올려주세요:-)

이슈를 닫습니다.
