### ISSUE TITLE
safari 브라우저에서 마커 이동이 되지 않습니다.

### ISSUE THREAD

**Issue by amyarh92** [navermaps/maps.js#70]
안녕하세요. 
네이버 지도 화면을 개발후 사파리 브라우저에서 마커 이동 테스트를 하다 생긴 문의드릴것이 있어 이슈 남깁니다.
마커가 드래그 앤 드롭하면 지도의 마커가 고정이 되어야하는데 safari 브라우저에서만 마우스 커서에 따라 계속해서 마커가 따라 다닙니다.
`
        naver.maps.Event.addListener(this.marker, 'dragend', (e) => {
            this.marker.setPosition(e.coord);
            let position = this.marker.getPosition();
            this.searchAddress(position._lat, position._lng);
        });
`
이경우는 어떻게 처리하면 되는지 해결책을 알려주시면 감사하겠습니다. :)

**Comment by thetaiz** [comment]
@amyarh92 님, 안녕하세요.

확인차 몇 가지 문의를 드릴께요.

- 마커의 드래그 앤 드롭을 별도로 구현하신건가요? 아니면 마커의 `draggable` 옵션을 이용하신건가요?
- 마커를 생성하고, 마커에 이벤트를 걸고 사용하는 로직을 볼 수 있을까요? 테스트할 수 있는 페이지가 있다면 더욱 좋습니다.
- 위 상황이 발생하는 환경(OS, 브라우저 버전)이 어떻게 되나요?
- 마커가 따라다닌다는 것이 드롭 후에도 마우스 커서에 마커가 붙어서 움직인다는 것인가요? 아니면 놓은 위치에 제대로 마커가 놓이지 않는 것인가요?

**Comment by amyarh92** [comment]
@thetaiz 안녕하세요.

마커의 draggable 옵션은 true로 선언하였고, 위의 남긴 코드처럼 이벤트 리스너를 추가하 드롭시에 이벤트를 추가하였습니다. 
테스트 환경은 mac os, safari 버전 9.1.3(11601.7.8) 입니다. 
문제가 되는 액션은 말씀주신것과 같습니다. 
마커 관련 코드는 보안상의 이유로 다음과 같이 간략히 적어드림에 양해 부탁드립니다.
` createMarker(lat, lng, map) {
        this.marker = new naver.maps.Marker({
            position: new naver.maps.LatLng(lat, lng),
            draggable: true,
            map: map,
            icon: ' 이미지 경로'
        });

        naver.maps.Event.addListener(this.marker, 'dragend', (e) => {
            this.marker.setPosition(e.coord);
            let position = this.marker.getPosition();
            this.searchAddress(position._lat, position._lng);
            this.setState({
                markerLng: position._lng,
                markerLat: position._lat
            });
        });
    }
`

**Comment by cs09g** [comment]
직접 이벤트를 걸면 한 50% 확률로 마커의 그림자가 드래그 됐다가 마우스 업을 해도 마커를 따라다니는 문제.. 저도 사파리에서만 경험했답니다ㅠㅠ 해결 방법이 궁금하네요. (네이버 API 문제가 아니라 사파리에서 DOM 드래그 효과를 줄 때 발생하는 문제같습니다)

**Comment by thetaiz** [comment]
@amyarh92 님, 해당 현상이 파이어폭스와 사파리에서 발생하는 것을 확인했습니다. 빠르게 패치하도록 하겠습니다.

더불어 한 가지 더 궁금한 것이 `dragend` 이벤트 핸들러에서 다시 마커의 위치를 잡는 것이 해당 버그 때문에 추가하신 것 같습니다. `e.coord`가 드래그가 끝난 곳의 좌표이니 마커의 `setPosition`, `getPosition` 부분은 제거해도 괜찮습니다.

**Comment by amyarh92** [comment]
@thetaiz님, 빠른 확인 및 해결 감사드립니다 :) `setPosition`, `getPosition`은 조언 주신대로 제거해보도록 하겠습니다 👍

**Comment by thetaiz** [comment]
@amyarh92 님, 해당 패치는 긴급 또는 정기 배포로 나갈 예정이며, 정기 배포 시 12월 말로 예상됩니다. 따라서 그 전까지는 크롬을 이용해 개발을 부탁드립니다. 배포 완료 시 다시 공유드리겠습니다.

**Comment by amyarh92** [comment]
@thetaiz 확인 감사드립니다 :) 패치 완료시 다시 테스트 하도록 하겠습니다.

**Comment by thetaiz** [comment]
@amyarh92 님, 좀 전에 긴급 배포되었습니다. 확인을 부탁드립니다.
