### ISSUE TITLE
주소 -> 좌표 API 구현시 "024 인증에 실패 했습니다"라는 메세지가 발생합니다.

### ISSUE THREAD

**Issue by chichansong** [navermaps/maps.js#71]
API 명세서 상의 주소 -> 좌표 API 호출 url에 
어플리케이션에서 발급받은 클라이언트ID를 다음과 같이 입력 후,

https://openapi.naver.com/v1/map/geocode?clientId=클라이언트ID

호출시에 

{"errorMessage":"Not Exist Client ID : Authentication failed. (인증에 실패했습니다.)","errorCode":"024"}

해당 값이 리턴되어지고 있습니다.

원인 파악을 할 수가 없어서요.
답변 해주시면 감사하겠습니다.

**Comment by boxersb** [comment]
@chichansong 안녕하세요?

> https://developers.naver.com/docs/map/overview

위 페이지에 들어가 보시면, 각 API 호출에 관한 예제 코드가 간략히 있습니다.
geocode, reversegeocode API의 경우 clientId 와 clientSecret 값을 서버측에서 HTTP Header 로 넘겨서 인증을 하는 코드를 별도 작성해주셔야하며, GET 방식의 파라미터 전달등으로는 사용하실 수 없습니다.

감사합니ㅏㄷ.
