### ISSUE TITLE
지도API로 검색 반경내의 상세보기 url 접근 가능한가요?

### ISSUE THREAD

**Issue by youngjiggi** [navermaps/maps.js#72]
지도API로 좌표정보 정도등 외에도 콘탠츠적인 (예: 상세보기 http://map.naver.com/local/siteview.nhn?code=) 정보에 접근할수 있나요?

네이버 지도API나 다른 네이버 오픈API로 특정 검색 주소 반경 N개 주소들의 상세보기url들을 요청 할수 있나요?

감사합니다.

**Comment by cs09g** [comment]
지도 보다는 검색쪽 API 와 가깝운 것 같아요. http://developers.naver.com/docs/search/local

**Comment by boxersb** [comment]
@youngjiggi 안녕하세요?
아쉽게도 장소 상세정보나 반경검색등의 API는 현재 지원하지 않고 있습니다.

감사합니다.
