### ISSUE TITLE
줌 레별 변경시 오류

### ISSUE THREAD

**Issue by gangsterrapper** [navermaps/maps.js#74]
![2016-12-02 6 02 40](https://cloud.githubusercontent.com/assets/15029532/20828450/f9488154-b8ba-11e6-88f4-55d62cc4e357.png)

네이버 지도 위에 트래픽 레이어를 올려서 작업중입니다.

연속해서 여러번 줌을 변경하게되면 첨부된 이미지와 같은 현상이 발생하는데 

소스보기를 해보니 변경전 레벨의 타일이 다 삭제되지 못하고 변경 후 타일과 겹쳐서 나타나는 문제로 보입니다.

해결방법을 알고 싶습니다.

**Comment by thetaiz** [comment]
@gangsterrapper 님, 안녕하세요. 혹시 사용하는 브라우저가 어떤 것인가요? 다른 브라우저에서도 동일한가요?

**Comment by gangsterrapper** [comment]
크롬,사파리 동일합니다.

**Comment by thetaiz** [comment]
@gangsterrapper 재현 방식 설명을 부탁드립니다. 저희쪽에서 재현이 안되서요. 작성된 코드도 공유가 가능하면 부탁드립니다.

**Comment by boxersb** [comment]
@gangsterrapper 안녕하세요?
> https://navermaps.github.io/maps.js/docs/tutorial-3-traffic.example.html

위 페이지에서 재현이 되시나요?

**Comment by gangsterrapper** [comment]
@boxersb @thetaiz  네이버에서 제공하는 트래픽 레이어를 올린게 아니고요. 다른 서버에 타일을 레이어로 올렸습니다.

**Comment by boxersb** [comment]
@gangsterrapper 아 넵.. 어떤식으로 올리셨는지 저희가 확인을 할 수 있어야 하는데요..
저희가 제공하는 방식으로는 문제가 없기에, 개발 방법의 이슈로 보입니다.

혹시 저번에 공유해주신적 있으셨던가요?

**Comment by gangsterrapper** [comment]
@boxersb 
![2016-12-02 6 49 39](https://cloud.githubusercontent.com/assets/15029532/20829718/92db8744-b8c0-11e6-9142-8a586ab6ec60.png)

**Comment by boxersb** [comment]
@gangsterrapper DOM Type의 MapType 을 만들어서 넘겨서 사용중이시군요..

위 코드 참조하여 확인해보겠습니다.

번거로우시겠지만, DOM Type 의 MapType 보다는 ImageMapType 을 만들어서 사용해보시길 권합니다.

참조 예제 링크
> https://navermaps.github.io/maps.js/docs/tutorial-2-maptypes-imagemaptype.example.html

좋은 주말 되세요~

**Comment by gangsterrapper** [comment]
@boxersb 저희쪽 서버에는 트래픽 정보만 있고 네이버 지도위에다가 겹쳐서 보여줄려고 하는겁니다.
이런 예제도 있을까요?

**Comment by boxersb** [comment]
@gangsterrapper 

```js
var map = new naver.maps.Map("map", {
    center: new naver.maps.LatLng(37.3614483, 127.1114883),
    zoom: 5,
    mapTypeId: "normal",
    mapTypeControl: true,
    mapTypeControlOptions: {
        style: naver.maps.MapTypeControlStyle.DROPDOWN
    }
});

var myMapType = {
    name: 'mytraffic',
    tileSize: new naver.maps.Size(256, 256),
    getTile: function(x, y, z) {
        y = Math.pow(2, z + 1) - 1 - y;

        return $('<img src="'+ 'http://m.its.go.kr:9089/geoserver/gwc/service/tms/1.0.0/ntic:moct_view_lv3@EPSG:5179@png/'+ (z - 1) +'/'+ x +'/'+ y +'.png' +'" style="position:absolute;z-index:10" />')[0];
    }
};

var mylayer = new naver.maps.Layer('mytraffic', myMapType);

mylayer.setMap(map);
```

위, 코드와 같이 트래픽레이어를 올려봤는데 말씀하신 현상이 재현되지 않는데요.. 이런식의 사용 보다는
`ImageMapType` 으로 만들어서 사용해보시길 권해드립니다.
