### ISSUE TITLE
트래킹 기능은 사용할수 없나요?

### ISSUE THREAD

**Issue by WinterMaps** [navermaps/maps.js#75]
m.map.naver로 접속했을시 왼쪽위에 과녁모양 트래킹 버튼은 어떻게 사용해야 하나요
![image](https://cloud.githubusercontent.com/assets/24321081/20856750/69fb60c0-b95a-11e6-9f69-8e7ae9c79844.png)

**Comment by thetaiz** [comment]
@WinterMaps 님, 안녕하세요..

해당 컨트롤은 `naver.maps.CustomControl`을 이용해 직접 구현하셔야 합니다.

- API 레퍼런스: https://navermaps.github.io/maps.js/docs/naver.maps.CustomControl.html
- 튜토리얼: https://navermaps.github.io/maps.js/docs/tutorial-Custom-Control.html

내부적으로 현재 위치를 가져오는 것은 아래 링크를 보면 도움이 될 것입니다.
- https://developer.mozilla.org/ko/docs/WebAPI/Using_geolocation

감사합니다.
