### ISSUE TITLE
이런기능을 담을 어플도 제작가능한지 궁금합니다.

### ISSUE THREAD

**Issue by znzl123ro** [navermaps/maps.js#76]
네이버맵 API를 이용해서,

지도위에 경로를 직접 선을 그어가며 그리거나 임의의 경로를 저장하여 

이를 기반으로 실시간 네비게이션 혹은 드론의 웨이포인트항법 처럼 

경로를 따라가며 자율주행이가능토록 데이터를 받아올 수 있을까요?

**Comment by thetaiz** [comment]
@znzl123ro 님, 안녕하세요.

지도 API는 지도를 생성하고, 그 위에 오버레이를 올리는 것을 제공합니다. 따라서 직접 경로 선을 그리거나, 임의의 경로를 기반으로 경로 선을 그리고, 따라가는 것은 구현이 가능합니다. 마지막 질문처럼 데이터를 받아올 수는 없습니다. 데이터를 받는 부분은 직접 구현하셔야 하고, 받아온 데이터를 지도에 그리는 것은 가능합니다.
