### ISSUE TITLE
주소 api를 ajax로 호출시 사용관련 문의 입니다.

### ISSUE THREAD

**Issue by chichansong** [navermaps/maps.js#77]
기존 호출시에 제이쿼리로
──────────────────────────────────────────
		$.ajax({
		        url : url + callback,
			type : "GET",
			async : false,
			contentType : "application/json",
			dataType : "jsonp",
			jsonp : "callback",
			success : function(data, textStadtus, jqXHR){
				ajaxSuccess(data);
			}
──────────────────────────────────────────
다음과 같은 방법으로 호출해서 사용 중인데, 이번 라이센스 변경으로 지도 api 리뉴얼 페이지에서
주소 찾기 api로 바꿀려고 하는중인데요..
──────────────────────────────────────────
GET https://openapi.naver.com/v1/map/reversegeocode?encoding=utf-8&coordType=latlng&query=127.1052133,37.3595316
Host: openapi.naver.com
User-Agent: curl/7.43.0
Accept: */*
Content-Type: application/json
X-Naver-Client-Id: {애플리케이션 등록 시 발급받은 client id 값}
X-Naver-Client-Secret: {애플리케이션 등록 시 발급받은 secret값}
──────────────────────────────────────────
api에서는 이렇게 호출하라고 나와있는데, ajax 호출시 어떻게 보내야 위에 형식에 맞춰지는지 문의 드립니다.

**Comment by boxersb** [comment]
@chichansong 안녕하세요?

> https://developers.naver.com/docs/map/overview

위 페이지 상단의 `API 호출 예제`를 참조하셔서 서버 사이드에서 `reversegeocode` API 호출시 HTTP 헤더로 `Client-Id`와 `Client-Secret`을 전달해주셔야 인증이 가능합니다.  
또한, Ajax 요청은 Same-Origin-Policy 문제도 걸려있으므로, 작업하시는 사이트에서 Open API를 호출하는 기능을 추가해서 사용하시는것이 좋을것 같습니다.  

이러한 문제를 해결하기 위해서, 최근에 `Geocoder` 서브 모듈을 사용하여 js 단에서 바로 서버 API를 호출할 수 있도록 하였습니다.  
아래의 링크들 참조하시기 바랍니다.

* [개발자 센터 공지사항](https://developers.naver.com/notice/article/10000000000030647896)
* [Geocoder 서브모듈](https://navermaps.github.io/maps.js/docs/module-geocoder.html)
* [Geocoder 를 활용한 Geocoding API 튜토리얼](https://navermaps.github.io/maps.js/docs/tutorial-Geocoder-Geocoding.html)
* [Geocoder 를 활용한 주소와 좌표 검색 API 호출 예제](https://navermaps.github.io/maps.js/docs/tutorial-3-geocoder-geocoding.example.html)

감사합니다.
