### ISSUE TITLE
네이버와 openlayer3연동 관련 질문드립니다.

### ISSUE THREAD

**Issue by teamgt** [navermaps/maps.js#78]
https://github.com/Gaia3D/OL3_KoreanTmsLayer/blob/master/NaverWMS.html
위 링크에서 보시면 네이버의 맵 타일만을 이용하고, openlayers 3으로 맵을 조작하는것을 볼수있습니다.
혹시 이렇게 네이버에서 제공하는 api를 사용하지 않고 openlayers를 이용하여 맵을 제어하고
맵타일만 이용해도 되는지요??

**Comment by boxersb** [comment]
@teamgt 안녕하세요?

일단 제보해주셔서 감사합니다.
네이버 지도의 타일 이미지는 공유해주신것과 같이 `OpenLayers`등을 통하여 무단으로 서비스할 수 없습니다.

해당 프로젝트에는 저희가 따로 조치를 취하도록 하겠습니다.  
감사합니다.

**Comment by teamgt** [comment]
그렇다면 naver API와 openlayers를 같이 사용할수있는방법이 있을까요???

**Comment by boxersb** [comment]
@teamgt 
네이비 지도의 타일 이미지는 네이버에서 제공한 Open API를 통해서만 사용하실 수 있으며, OpenLayers 등에서 타일 이미지를 사용하여 지도를 만드는 형태는 허용하지 않습니다.  
개인적인 용도로 지도의 타일 이미지를 직접 가져다 OpenLayers 등을 써보시는것은 괜찮지만, 실제 서비스를 하시게 되면 타일 이미지 최신성등에 문제가 발생할 수 있습니다.

감사합니다.
