### ISSUE TITLE
지도 API 웹서비스 URL

### ISSUE THREAD

**Issue by smchae** [navermaps/maps.js#79]
안녕하세요,

Cordova를 이용하여 하이브리드 앱을 개발하고 있습니다.

안드로이드의 경우
웹서비스 URL에 file:///android_asset/www/index.html 를 사용하여 잘 이용하고 있으나

iOS의 경우
웹서비스 URL에 file://var/containers/Bundle/Application/{매번 변하는값}/{앱이름}/www/index.html#의 형태로
매번 변하는 값이 있어 URL를 설정하기가 힘든데 이러한 경우는 어떻게 설정을 해야 인증을 받을 수 있을까요?

감사합니다.

**Comment by boxersb** [comment]
@smchae 안녕하세요?

> file://var/containers/Bundle/Application/{매번 변하는값}/{앱이름}/www/index.html#

위와 같은 형태라면.. 매번 변하는 값 이전의 고정값만을 가지고 URL 등록을 해서 인증하시면 될것 같습니다.

> file:///var/containers/Bundle/Application/

감사합니다.

**Comment by smchae** [comment]
@boxersb 감사합니다! 덕분에 1초만에 문제를 해결하였습니다~

**Comment by boxersb** [comment]
넵.. 감사합니다 :)
