### ISSUE TITLE
좌표 주소변환 문의 드려요

### ISSUE THREAD

**Issue by chahwon** [navermaps/maps.js#8]
좌표 주소 변환시 기존 방식대로 호출하면 되는지요?
V3 Api 에 관련 Class 및 함수가 보이지 않아서요 

기존 방식대로 라면 client id , secret 을 헤더에 추가 했음에도 등록되지 않은 키라고 나오는 부분은 
어느 부분을 확인 해야 할지 궁금합니다.

아래는 제가 사용한 자바스크립트에서의 루틴 입니다.

https://openapi.map.naver.com/api/reversegeocode?encoding=utf-8&coord=latlng&output=json&query=127.12623,37.49165	

xmlHttp = new XMLHttpRequest();
		        xmlHttp.open("GET", theUrl, false); 
		        xmlHttp.setRequestHeader('X-Naver-Client-Id', 'xxxxx', false);
		        xmlHttp.setRequestHeader('X-Naver-Client-Secret', 'xxxxx', false);
		        xmlHttp.onreadystatechange = ProcessRequest;
		        xmlHttp.send(null);

**Comment by chahwon** [comment]
아 제가 주소를 잘못 기입했었네요. 
이 주소가 아닌 => https://openapi.map.naver.com/api/reversegeocode?
이 주소로 하니 잘되네요 https://openapi.naver.com/v1/map/reversegeocode?

**Comment by boxersb** [comment]
@chahwon 감사합니다 :)
