### ISSUE TITLE
레이어 이름 표시 방법 문의

### ISSUE THREAD

**Issue by csterry12** [navermaps/maps.js#80]
예제 중 행정구역 GeoJSON 데이터 레이어 표시하기가 있는데요.
여기서는 레이어 이름을 툴팁으로 표현하고 있는데,
그렇게 하지 않고 바로 레이어 피처 위에 표시하는 방법이 있나요?

**Comment by boxersb** [comment]
@csterry12 레이어의 이름등은 원하는 좌표를 획득하셔서 HTML 마커 또는 커스텀 오버레이를 만들어서 띄우시면 될것 같습니다.
