### ISSUE TITLE
v3 테스트 중 IE에서 유형(일반/위성) 버튼이 깨집니다.

### ISSUE THREAD

**Issue by asia7880** [navermaps/maps.js#81]
![map_test](https://cloud.githubusercontent.com/assets/24541841/21133971/d8b5cde6-c15e-11e6-921f-bf497b81615e.jpg)

IE, Chrome 두가지에서 테스트 했을 때 IE만 버튼이 깨집니다.
(현재IE11이며 F12에서 브라우저 설정을 바꿔도 동일한 현상 발생)

JSP페이지에서 테스트했으며 javascript 예제 코딩 그대로 입니다.
NAVER Maps JavaScript API v3 > Examples > 지도 컨트롤 위치 설정하기 부분

**Comment by boxersb** [comment]
@asia7880 안녕하세요?

페이지네 DocType 을 확인 부탁드립니다.
DocType 이 지정되어 있지 않은 Quirks mode 의 HTML 페이지는 지원하지 않습니다.

DocType 예시
```html
<!DOCTYPE html>
<html>
  ...

```

감사합니다.
