### ISSUE TITLE
CustomOverlay 를 사용하여 커스텀 마커를 사용시 이벤트에대한 궁금한점

### ISSUE THREAD

**Issue by asnike** [navermaps/maps.js#82]
CustomOverlay 예제를 이용해
커스텀 마커를 만들어 이용중입니다.
근데 클릭 이벤트가 발생 안하는것 같아요.
이에 대한 내용을 다 뒤져봤는데 못찾아서... 
일반 마커는 클릭 이벤트 잘 발생하는거 확인하고, 
커스텀 마커 만들어서 확인 해보면 클릭이 발생 하지않습니다.
제가 뭐 놓친게 있을까요?
이벤트는 아래와 같이 걸었습니다.
`naver.maps.Event.addListener(customMarker, 'click', clickCacllback)`

**Comment by boxersb** [comment]
@asnike 안녕하세요?
`CustomOverlay`를 만드셨을경우.. 이벤트 dispatch 는 직접 구현하셔야 합니다.
예를 들면, `onAdd` 메서드 실행 시점에 click 이벤트를 거시고, click 이벤트 발생시, 지도 API의 이벤트를 trigger 하시면 됩니다.

```js
MyOverlay.prototype.onAdd = function() {
    var overlayLayer = this.getPanes().overlayLayer,
        element = $(this._element),
        self = this;

    element.appendTo(overlayLayer);
    element.on('click', function(e) {
        // 클릭이벤트 발생
        naver.maps.Event.trigger(self, 'click');
    });
}
```

도움이 되셨으면 좋겠습니다.

**Comment by asnike** [comment]
아하 직접 디스패치 해줘야하는군요 ^^
웬지 그럴것 같았는데 문서에는 나와있지 않아서 문의드렸습니다.
감사합니다!

**Comment by boxersb** [comment]
@asnike 아 넵.. 문서 및 예제를 보강하도록 하겠습니다 ^^;
