### ISSUE TITLE
pinch to zoom 시에 줌이 반대로 되는 문제가 있습니다

### ISSUE THREAD

**Issue by davidshimjs** [navermaps/maps.js#83]
크리티컬한데 간헐적으로 일어나는 문제인데요, 안드로이드에서는 어디에서나 높은 확률로, iOS에서는 인앱에서 높은 확률로 발생되는 문제입니다. (iOS에서는 네이버앱에서 map.naver.com 을 들어가면 높은 확률로 재현할 수 있습니다. 물론 iOS safari에서도 간헐적으로 일어납니다.)

pinch-to-zoom 으로 줌인을 하려고 할 때, 줌 아웃이 되는 문제입니다. 재현 방법은 여러가지가 있는데요, 아래 두가지 방법이 그나마 확률이 높습니다.
1) 줌아웃을 하고 애니메이션이 끝나기 전에 줌인을 하면 발생합니다.
2) 한쪽을 잡고 패닝을 하다가 다른쪽 손으로 줌인을 하려고 하면 발생합니다.

재현 가능성은 아래 순으로 높습니다.
안드로이드 인앱 = 안드로이드 브라우저 > iOS 인앱 >>>>>>> iOS Safari

줌인을 하려고 할 때 줌 아웃이 자꾸 된다는 c/s 받아서 확인해본 결과 네이버 지도 서비스에서도 동일하게 발생하는 것을 확인했으며 (네이티브 지도앱은 발생하지 않음), 디바이스 문제는 아닌 것으로 보여집니다.

100% 재현 경로를 찾아서 제보 해드려야 하는데, 뭐가 문젠지 코드를 봐야 알 것 같네요 ㅠㅠ 해보시고 잘 안되면 말씀해주세요.

**Comment by boxersb** [comment]
@davidshimjs 안녕하세요?
`MapOptions` 의 `disableTwoFingerTapZoom` 을 `true` 로 설정하고 다시 한번 재현시켜 보시겠어요?

**Comment by davidshimjs** [comment]
@boxersb 근데 저희 서비스가 아니라 네이버 지도 서비스에서 재현이 돼요;

**Comment by boxersb** [comment]
@davidshimjs 호갱노노에서는 재현되지 않는 이슈인가요?
네이버 지도는 모바일웹 버전으로 확인하신거죠?

**Comment by davidshimjs** [comment]
@boxersb 호갱노노에서도 재현되는 이슈가 맞습니다~! 옵션 끄고 한 번 해볼께요

**Comment by boxersb** [comment]
@davidshimjs 넵.. 확인 한번만 부탁드릴께요~

**Comment by davidshimjs** [comment]
@boxersb 옵션 끄니깐 확실히 재현이 잘 안되네요!

**Comment by boxersb** [comment]
@davidshimjs 아.. 그럼 일단은 옵션 끄고 서비스 부탁드리구요..
옵션을 켜도 그런 오동작이 잘 발생하지 않도록 수정해보겠습니다..
제보 감사드려요!

**Comment by davidshimjs** [comment]
@boxersb 넵~! 두루뭉실하게 제보해서 죄송해요 ㅠㅠ

**Comment by boxersb** [comment]
@davidshimjs 두 손가락 탭시 줌인 되는 인터렉션시.. 두 손가락 사이의 끼인각도가 적을때만 줌인이 되도록 금일 오전 수정 배포하였습니다.

확인 부탁드립니다.
