### ISSUE TITLE
wms를 뿌릴 수 있는 방법 있을까요?

### ISSUE THREAD

**Issue by csterry12** [navermaps/maps.js#84]
국가공간정보포털이나 브이월드에서 제공하는 wms를 뿌리고 싶은데 방법이 있을까요?

**Comment by boxersb** [comment]
GeoJSON 포맷을 사용하여 Data Layer 로 올릴 수 있고..  
그외의 별도 데이터 포맷은 직접 데이터를 파싱하여 지도에 마커나 기타 오버레이로 올리시면 됩니다.

> https://navermaps.github.io/maps.js/docs/tutorial-2-datalayer-region.example.html

shp 파일 형태의 Raw 데이터 형태는 지원하지 않으며, KML, GPX 등의 데이터 포맷도 현재는 지원하지 않습니다.

KML과 GPX 데이터 포맷은 향후 지원을 추가할 예정입니다.

감사합니다.
