### ISSUE TITLE
clientID가 작동하지 않습니다. 

### ISSUE THREAD

**Issue by kohys** [navermaps/maps.js#85]
예제를 보고 작성한 코드가 작동을 하지 않아서

예제를 그대로 복사해서 서버에 올리고 해당 URL로 발급받은 clientID를 입력했는데

openAPI 인증이 실패했다고 뜹니다.

**Comment by boxersb** [comment]
@kohys 확인할 수 있는 url 을 공유해주실 수 있으신가요?

**Comment by kohys** [comment]
http://testhompage.xyz/maptest.html 
 
위 페이지는 깃헙에 올라온 예제를 복붙해서 제가 받은 clientID만 입력한 코드입니다.
 
혹시 잘못된 부분이 있다면 답장 부탁드립니다. 
 
 
clientID를 발급받은 네이버 아이디는 akrrns0609입니다.
 
 
 
 
 
 
-----Original Message-----

**Comment by boxersb** [comment]
@kohys clientId 를 입력할 자리에 `YOUR_CLIENT_ID` 가 설정된것으로 확인됩니다. 실제 클라이언트 ID를 입력해도 문제가 있나요?

![screen shot 2016-12-21 at 6 43 32 pm](https://cloud.githubusercontent.com/assets/189953/21384319/68ccf3c4-c7ad-11e6-8863-68bab3521dd7.png)
