### ISSUE TITLE
네이버 지도에 보면 음식점, 주유소 등 지도 상에 유용한 정보를 표시해주던데 API v3에는 제공하지 않나요?

### ISSUE THREAD

**Issue by vivace99** [navermaps/maps.js#86]
<img width="206" alt="2016-12-23 12 56 51" src="https://cloud.githubusercontent.com/assets/922122/21446852/0cab1e96-c90f-11e6-809d-9bd4f3671ef5.png">

네이버 지도에 보면 음식점, 주유소 등 지도 상에 유용한 정보를 표시해주던데 API v3에서 해당 메뉴를 사용 할 수 있는 방법은 없나요?

**Comment by thetaiz** [comment]
@vivace99 님, 안녕하세요. 현재 장소에 대한 정보를 내려주는 JavaScript API를 제공하고 있지 않습니다. 다만, 네이버 개발자 센터의 지역 검색을 이용해 받아온 결과를 API v3로 지도에 올릴 수는 있습니다.

- https://developers.naver.com/docs/search/local

이때 결과의 좌표 값을 그대로 이용할 수는 없고, 다음 가이드에 따라 좌표를 변환해 사용하면 됩니다.

- https://navermaps.github.io/maps.js/docs/tutorial-Geocoder.html

**Comment by vivace99** [comment]
@thetaiz 님, 검색에 지역 항목이 있었군요.
지역 검색을 보니 좌표가 아닌 string query라 지도에서 구현하기 쉽지 않겠지만 그래도 방법이 있어서 다행이네요.
빠른 답변 감사합니다.
