### ISSUE TITLE
네이버 지도 API 웹 서비스 URL에 IP 주소 입력 가능하나요?

### ISSUE THREAD

**Issue by cgj1789** [navermaps/maps.js#87]
![aaaapi](https://cloud.githubusercontent.com/assets/24665145/21481312/bb5ee7fa-cba9-11e6-9452-9c6b084f7350.png)

위에 화면처럼 IP 주소를 이용해서 등록 가능하나요?

**Comment by cs09g** [comment]
로컬에서 테스트 할때 그냥 127.0.0.1 로 등록해도 됐던거 같아요

**Comment by boxersb** [comment]
ip 주소로 입력시.. 브라우저에서도 ip 주소로 접근하시면 인증 됩니다.
