### ISSUE TITLE
네이버 지도 API 웹 서비스 URL 유효한 주소 입력

### ISSUE THREAD

**Issue by cgj1789** [navermaps/maps.js#88]
현재 프로젝트 테스트하고 있습니다.

일반 사용자들이 네이버 지도를 보기 위해 접속하는 URL이 http://www.naver.com/test/test123&AC=&nice/deep/deeper&VA=content 라고 쓴다고 가정하면 
네이버 지도 API 웹 서비스 URL에 위와 같이 그대로 써도 해당 페이지가 보이는게 맞나요?

질문의 핵심은 보안유지를 위해 일반 사용자들한테 보여주기 식으로 노출되는 URL이랑 
실제 개발 프로젝트에서 사용되는 URL이 다를 경우 어떤 URL을 입력하여야 네이버 지도 API 인증하고 출력하는데 문제가 없을까요?

그리고 만약에 URL이 http://www.naver.com/test 이 부분까지는 일반 사용자에게 보여주기식 URL이나 실제 개발 프로젝트나 동일하게 사용한다면 그냥 http://www.naver.com/test 이렇게 적어도 하위 디렉토리가 달라져도 네이버 지도를 출력하는데 문제가 없나요?

네이버 개발자센터나 잘 아시는 분께서 꼭 답변 좀 부탁드리겠습니다. 찾아봐도 명확한 답변이 없습니다.

소중한 답변 감사합니다.

**Comment by boxersb** [comment]
안녕하세요?

개발 환경의 url과 서비스 환경의 url이 다르다면, 개발용과 서비스용의 애플리케이션을 각각 생성하시어.. Client Id 도 다르게 설정하여 사용하셔야 합니다.

웹 서비스 url은 일반적으로 `http://www.naver.com/` 과 같이 도메인명만 입력하면, 해당 도메인의 하위 디렉토리가 모두 인증이 가능합니다. 그러나, `http://www.naver.com/test/` 와 같이 입력하신다면 test 디렉토리와 그 하위 디렉토리에서만 인증됩니다.

즉, `http://www.naver.com/another/` 와 같은 페이지에서는 인증이 실패하게 됩니다.

도움이 되셨으면 좋겠습니다.
