### ISSUE TITLE
네이버 지도 api연계를 사용하고 있는데요

### ISSUE THREAD

**Issue by dojo333** [navermaps/maps.js#89]
문의할 곳을 찾다가 여기에 글 올립니다.

현재 공공기관에서 네이버 지도를 서비스 하고 있습니다.

api키를 이용하여 api를 호출하는 방식이 26일 서비스가 중단되어
v3로 마이그레이션을 해야하는데 
내부 테스트를 위해 방화벽오픈을 해야하는 상황입니다.
공공기관 방화벽 정책이 url기준이 아니라 ip 주소 기준으로 오픈해야하기때문에 
대표 ip외 지도api에 사용되는 ip전체주소 리스트가  필요합니다.

빠른 답변 부탁드립니다.

**Comment by boxersb** [comment]
@dojo333 오픈 API의 ip주소는 정책상 공유해드릴 수 없는점 양해 부탁드립니다.
