### ISSUE TITLE
2-datalayer-region.html 예제파일 소스오류 문의드립니다

### ISSUE THREAD

**Issue by joon2** [navermaps/maps.js#9]
example 중에서 2-datalayer-region.html을 실행하였는데 지도화면만 보이고
geoJson으로 호출되어야할 폴리곤이 생성이 안됩니다. 디렉토리 설정도 하였고 유사 예제파일인 1-datalayer.html 도 잘 실행됩니다. 2-datalayer-region.html 소스 쪽에서 문제가 있는것 같습니다. 답변 기다리겠습니다.

**Comment by boxersb** [comment]
@joon2 안녕하세요?

> http://localhost:8000/examples/datalayer/2-datalayer-region.html 

위와 같이 path를 잡아서 실행해보니 잘 나오는데요.. 사용 브라우저가 Chrome 이라면, 개발자 도구등에서 오류 메세지 같은것이 뜨는지 확인 부탁드립니다.
