### ISSUE TITLE
이벤트의 기능에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by hmflow** [navermaps/maps.js#90]
NEvent.addListener(map,'contextmenu',functioh(){});

1버전에서 contextmenu 에 대한 기능은 어떻게 구하는지 알고싶습니다.

**Comment by boxersb** [comment]
지도 API 1 버전 (v1 또는 1.0)은 종료되었습니다.
혹시 v3 버전에 대한 문의신가요?

**Comment by hmflow** [comment]
네 3버전으로 마이그레이션 중 입니다^^;

**Comment by boxersb** [comment]
@hmflow 아 넵..

v3버전에서는 `rightclick`이라는 이벤트로 구현 가능합니다 :)

```js
naver.maps.Event.addListener(map, "rightclick", function(e) {
    // 우클릭 메뉴 처리
});
```

감사합니다~

**Comment by hmflow** [comment]
감사합니다 ^^
