### ISSUE TITLE
거리뷰 예제가 작동이 안되네요

### ISSUE THREAD

**Issue by despera21** [navermaps/maps.js#92]
Examples 페이지에 있는 네이버 거리뷰 레이어 표시하기 예제가 작동이 안되는 것 같습니다
실제 네이버 지도를 보면 오른쪽 상단에 거리뷰 이미지를 클릭하면 화면이 파란색으로 바뀌고
거리뷰 이미지가 붙은 마우스를 어느 한 거리에 찍으면 그 거리의 거리뷰가 보이는데

Examples 페이지에 있는 네이버 거리뷰 레이어 표시하기에서는 그런 작동을 할 수 없게끔 되어 있네요
단지 파란색 거리선만 보이고 있네요

**Comment by boxersb** [comment]
거리뷰 레이어는 파란색 거리뷰 타일 레이어를 의미하는거구요..

네이버 지도 서비스와 같은 형태는 별도로 구현을 하셔야 합니다 ^^;

감사합니다.

**Comment by despera21** [comment]
그렇게 구현을 하려고 하는데 찾아봐도 방법이 나와 있지 않네요
죄송한데 그런 방법을 어디에서 찾을 수 있는지 알려주셨으면 고맙겠습니다
아니면 직접 알려주시면 정말 감사하구요 ^^

**Comment by boxersb** [comment]
@despera21 그 부분은 구현에 관한거라서 답변드리기 어렵구요..
관련한 예제도 현재 공개해둔것이 없습니다..

이 부분은 마우스에 따라 다니는 이미지나 동작 방식을 개발자가 자유롭게 결정할 수 있도록 하기 위해서, panorama 구현 자체에는 포함되어 있지 않습니다.
