### ISSUE TITLE
마커 표시할 때 

### ISSUE THREAD

**Issue by yoonheeoh** [navermaps/maps.js#94]
![image](https://cloud.githubusercontent.com/assets/24819831/21633549/873f2bec-d293-11e6-89eb-7824f88bb8eb.png)

첨부한 사진처럼 마커(붉은색 옷모양) 아래에 마크에 대한 설명을 html 코드로 만들어서 붙이고 싶습니다. 방법이 있나요?

**Comment by thetaiz** [comment]
@yoonheeoh 님, 안녕하세요.

["네이버 지도 JavaScript API 완벽 가이드 - 오버레이 편"](http://d2.naver.com/helloworld/3380225)의 "사용자 정의 오버레이"를 참고해 주세요. ^^

**Comment by yoonheeoh** [comment]
네 감사합니다~
