### ISSUE TITLE
StaticMap 관련 문의

### ISSUE THREAD

**Issue by hyoseok0** [navermaps/maps.js#95]
[StaticMap 가이드](https://developers.naver.com/docs/map/tutorial#section-Tutorial_staticMap3.8)에 내용이 나오지 않아 문의드립니다.

1. StaticMap 내부 Marker에 click event handler 설정 가능 여부
지도 api 에 요청 시 이미지 파일을 return해주기 때문에 StaticMap 내부 Marker에 click event handler 등록하는 게 불가능해 보이긴 한데요. 혹시나 가능한지?

2. StaticMap 내부 Marker의 아이콘을 이미지/HTML마크업을 사용 가능 여부
naver.maps.Marker 의 아이콘 설정 방식대로 가능한지?

3. StaticMap 내부 Marker 개수가 10개 제한 여부?

4. naver.maps.Map 사용시 화면 지도 고정 가능?
scroll 이나 touch 등이 발생해도 zoom 이나 지도 이동이 되지 않도록 option 설정 가능 여부

**Comment by boxersb** [comment]
1. StaticMap 은 문자 그대로 정적 이미지 리소스이기 때문에 Marker 에 클릭 이벤트 핸들로 등록은 불가합니다.
2. StaticMap 의 마커 이미지를 사용자화 하는것은 불가합니다.
3. 알파벳으로 표기된 마커는 10개, 그외 일반 마커는 30개 까지 노출할 수 있습니다.
4. 지도 API v3 사용시 지도 화면 고정이 가능합니다.  
지도 초기화시 옵션을 설정하시거나, 초기화 후 옵션을 수정할 수 있습니다.  
```js
var map = new naver.maps.Map('map-container', {
    ...
    pinchZoom: false,   // 터치의 핀치 제스쳐 줌을 사용하지 않습니다.
    scrollWheel: false,  // 마우스의 휠 줌을 사용하지 않습니다.
    draggable: false,    // 터치 또는 마우스를 이용한 지도 드래그를 허용하지 않습니다.
    disableDoubleClickZoom: true,   // 더블 클릭 줌인 기능을 사용하지 않습니다.
    disableDoubleTapZoom: true,     // 터치 더블 탭 줌인 기능을 사용하지 않습니다.
    disableTwoFingerTapZoom: true   // 두 손가락 터치 탭 줌 아웃 기능을 사용하지 않습니다.
});
```
> MapOptions 명세 : https://navermaps.github.io/maps.js/docs/naver.maps.html#.MapOptions

감사합니다.

**Comment by hyoseok0** [comment]
touch/scroll 을 통해 article 간 이동을 해야 하는데, 지도를 포함한 article 에서는 지도에 touch/scroll event 가 적용되어 article 이동이 어려웠습니다. naver.maps.Map 의 화면 고정이 가능하므로, static map 대신 naver.maps.Map 을 사용하려고 합니다. 

상세한 답변 주셔서 감사합니다!!
