### ISSUE TITLE
10 applications limitation

### ISSUE THREAD

**Issue by ketokun** [navermaps/maps.js#96]
Hi there,

For some we are unable to register more than 10 map applications under one account. We are planning to use naver map on more than 10 domain names. Is there a workaround for this?

UPD: Also is it possible to use multiple domains under 1 application?

Cheers

**Comment by boxersb** [comment]
The reason we are limited to 10 applications per account is because of the possibility of an attack.
If you want to register more, you need to use a separate Naver account.
  
The portion of the application that registers multiple web service URLs is under review.

**Comment by ketokun** [comment]
Thanks a lot for the clarification.

Could you please answer another question:
On naver site https://developers.naver.com/notice/article/10000000000030643859 the API limited by 200000 times. What is implied by the API call? Is it when the map loaded once on a page or it's once per user?

Thanks

**Comment by boxersb** [comment]
You can think of the Naver Map API 20,000 times limit as a pageview.  
Once a map is displayed on the page, it is used once, and even if you create another map without refreshing the page, it does not consume any usage.  
However, the `geocoding` and `reversegeocoding` APIs consume usage each time they are called.  
This part is also the same when calling through the Maps Javascript API v3. (https://navermaps.github.io/maps.js/docs/tutorial-Geocoder-Geocoding.html)

Thanks

**Comment by ketokun** [comment]
Thanks a lot for your help!
