### ISSUE TITLE
웹접근성 관련 배경이미지 alt 추가 요청

### ISSUE THREAD

**Issue by cjy217** [navermaps/maps.js#97]
안녕하세요.

네이버 지도 API 사용하고 있습니다.
웹접근성 마크 획득 위해서 네이버지도API가 포함된 페이지에 자동검사기로 검사를 해보니.. 

<img src="https://ssl.pstatic.net/static/maps2/ico_pano_dir_final.png" width="900" height="400" class="png" data-newcca-inline-style="max-width:none;max-height:none;">

부분.. 다른곳은 빈값으로 alt가 설정 되어 있는데 https://ssl.pstatic.net/static/maps2/ico_pano_dir_final.png 불러오는 부분에만 alt가 설정 되어 있지 않습니다.
해당 부분에 alt 추가해주실 수있는지 궁금합니다!

감사합니다.

**Comment by boxersb** [comment]
@cjy217 사용하신 지도 API 버전이 v3인가요? v2인가요?

**Comment by cjy217** [comment]
@boxersb 2.0 버전 입니다

**Comment by boxersb** [comment]
@cjy217 다음 패치에 alt 적용하도록 하겠습니다. ^^;

다음 패치 일정은 1월 19일입니다.  

감사합니다.

**Comment by cjy217** [comment]
@boxersb 와우 감사합니다^^ 새해 복 많이 받으세요~

**Comment by boxersb** [comment]
@cjy217 제보 감사합니다. 새해 복 많이 받으세요~

**Comment by cjy217** [comment]
@boxersb 안녕하세요ㅎ alt건 금일 패치가 되어있지 않아 재문의 드립니다ㅠㅠ 따로 작업해줘야되는 부분이 있는지 궁금합니다 항상 감사합니다^^

**Comment by boxersb** [comment]
@cjy217 아.. 죄송합니다.
저희 정기배포가 다음주 목요일로 연기가 되었습니다.. 미리 공유드리지 못해 죄송합니다.

혹.. 급하신 건인가요?

**Comment by cjy217** [comment]
@boxersb 아니요ㅎㅎ 패치가 되었는데 제쪽에서 작업을 해줘야되는건가 싶어서요ㅎㅎ 알겠습니다 감사합니다 수고하세요^^

**Comment by boxersb** [comment]
네.. 죄송합니다.. 다음주 목요일 패치 후 공유 드리겠습니다 ^^;

**Comment by boxersb** [comment]
@cjy217 안녕하세요? 배포가 하루 앞당겨져서 방금 alt 추가하여 배포 완료되었습니다.

`alt=""` 로 설정했습니다. 확인 부탁드려요 ^^;

**Comment by cjy217** [comment]
@boxersb 안녕하세요ㅎ 확인했습니다 오픈소스인데 적용해주셔서 감사합니다ㅠㅠ 새해 복 많이 받으세요!!ㅎ

**Comment by boxersb** [comment]
@cjy217 확인 감사드립니다~ 새해 복 많이 받으세요~~
