### ISSUE TITLE
이곳에 질문하느거 맞나..? 클라이언트아이디 포함 등록해보았는데 지도가 안나와요 

### ISSUE THREAD

**Issue by eastpjh** [navermaps/maps.js#98]
```
<head>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=fiFNYbutY6twwUqXAOhR"></script>
</head>

<body>

<script>
		var map = new naver.maps.Map(mapDiv);
</script>


<div id="map" style="width:100%;height:400px;"></div>

</body>
```

위와같이 했는데 공백으로 나옵니다.

**Comment by boxersb** [comment]
안녕하세요?

크롬등의 브라우저에서 개발자도구를 열고 `<div id="map" style="width:100%;height:400px;"></div>` 의 HTML 엘리먼트의 크기를 확인 부탁드립니다.  
div 의 `width` 가 잘못잡혀있을 가능성이 있습니다..  

확인을 위해 해당 div의 width 를 `400px` 등의 고정값으로 설정해서 다시 확인 부탁드립니다.

**Comment by eastpjh** [comment]
http://dongdaemuntong.com/dong_main/test.php 이곳인데 px로 지정했는데 안되요 ㅜㅠ 이것도해보고 저것도 해보고 검색도하고있느데 안되네요 ㅜㅠ 힌트좀 주세요 ㅜㅠ

**Comment by boxersb** [comment]
@eastpjh 해당 페이지와 코드를 다시 보니 `mapDiv` 가 정의되어 있지 않네요..   (doctype 과 html 테그도 빠져있습니다.)
아래와 같이 변경 해보시기 바랍니다.

```html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=fiFNYbutY6twwUqXAOhR"></script>
</head>

<body>

<div id="map" style="width:100%;height:400px;"></div>

<script>
    var map = new naver.maps.Map('map');
</script>


</body>
</html>
```

**Comment by boxersb** [comment]
그런데, 저렇게 했더니 OpenAPI 인증 오류가 발생하네요..  
등록하신 웹 서비스 URL과 클라이언트 Id 가 일치하는지 확인 부탁드려요~
