### ISSUE TITLE
특정 이벤트를 삭제하는 방법

### ISSUE THREAD

**Issue by yoonheeoh** [navermaps/maps.js#99]
naver.maps.Event.addListener(map,'click',fn_moveClick); 
이렇게 이벤트를 추가하고 난 후 

이벤트를 삭제하기 위해
var listeners = [naver.maps.Event.addListener(map,'click',fn_moveClick)];
naver.maps.Event.removeListener(listeners);	
해당 구문을 실행시켰는데 계속 클릭이벤트가 실행됩니다.
특정 이벤트를 삭제하는 다른 방법이 있나요?

**Comment by boxersb** [comment]
addListener 의 반환값을 사용하시면 됩니다.  
고객님께서 `listeners = [naver.maps.Event.addListener(map,'click',fn_moveClick)];` 와 같이 한번더 addListener 를 호출하셔서 마지막것만 제거된것 같은데요.. 아래와 같이 변경 바랍니다.

```js
var listener = naver.maps.Event.addListener(map,'click',fn_moveClick);

naver.maps.Event.removeListener(listener);
```

감사합니다.

**Comment by yoonheeoh** [comment]
네 감사합니다~
